src/objects/Account_Address__c.object
<CustomObject>
    <description>Junction object to tie multiple address records to an account and multiple accounts to a single address record.</description>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Address Lookup</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Account_Addresses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Mail_To__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Mail To</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Address</label>
    <nameField>
        <displayFormat>AA-{000000000}</displayFormat>
        <label>Account Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <description>This record type if for all records created by SFDC Users.</description>
        <label>Address</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountFormsContTest.cls
@isTest
public class AccountFormsContTest {
    static Account acct;
    static Address__c addy;
    static Account_Address__c aAddy;
    static AccountFormsCont cont;

    static void setupData(){
        AVA_SFCORE__TaxNowSetting__c ts1 = new AVA_SFCORE__TaxNowSetting__c(); 
        ts1.AVA_SFCORE__Active_Setting__c = true; 
        ts1.Name='Test Account';
        insert ts1;

        acct = TestingUtils.createAccounts(1, 'TestAccount', false)[0];
        addy = TestingUtils.createAddresses(1, true)[0];
       
        cont = new AccountFormsCont();
    }

    static testMethod void constructorTest(){
        setupData();

        acct.Type = 'AccountFormsTest';
        insert acct;
         
         aAddy = TestingUtils.createAccountAddresses(1, acct.id, addy.id, false)[0];
        aAddy.Primary_Mail_To__c = true;
        insert aAddy;

        Test.startTest();
        cont.mainAccount = new Account(Id=acct.Id);
        Test.stopTest();

        System.assertEquals('AccountFormsTest', cont.mainAccount.Type);
    }

    static testMethod void saveTest_pass(){
        setupData();
        cont.redirectPage = true;

        acct.Type = 'saveTest';
        cont.mainAccount = acct;
        cont.address = addy;

        Test.startTest();
        PageReference pg = cont.save();
        PageReference pg1 = cont.selectAddress();
        
        Test.stopTest();

        System.assertNotEquals(null, pg, 'Should have returned an actual pagereference');

        Account dbAcct = [SELECT Type FROM Account WHERE Id = :acct.Id];

        System.assertEquals('saveTest', dbAcct.Type);
    }

    static testMethod void saveTest_fail(){
        setupData();
        cont.redirectPage = true;

        acct.Name = null;
        cont.mainAccount = acct;

        Test.startTest();
        PageReference pg = cont.save();
        
        Test.stopTest();

        System.assertEquals(null, pg);

        try{
            Account dbAcct = [SELECT Id FROM Account LIMIT 1];
            System.assert(false, 'There should be no contacts in the database due to failed save');
        } catch (QueryException e) {}
    }
}