src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <description>dcw_DistChannels.dc_location</description>
        <inlineHelpText>dcw_DistChannels.dc_location</inlineHelpText>
        <label>Location (DCW)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Clone_Field_Set_To_Clone__mdt.object
<CustomObject>
    <fields>
        <fullName>Field_Set_Name__c</fullName>
        <label>Field Set Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Clone Field Set To Clone</label>
    <pluralLabel>Clone Field Set To Clones</pluralLabel>
</CustomObject>

src/objects/Custom_Clone_Child_Object__mdt.object
<CustomObject>
    <fields>
        <fullName>Child_Field_on_Parent__c</fullName>
        <label>Child Field on Parent</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Child_Object_Api__c</fullName>
        <label>Child Object Api</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Copy_User_Field__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Copy User Field</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opportunity</fullName>
                    <default>true</default>
                    <label>Opportunity</label>
                </value>
                <value>
                    <fullName>Apttus_Proposal__Proposal__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Lookup_Field__c</fullName>
        <label>Parent Lookup Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Required_Fields__c</fullName>
        <label>Required Fields</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Lookup_Field__c</fullName>
        <label>User Lookup Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Custom Clone Child Object</label>
    <pluralLabel>Custom Clone Child Objects</pluralLabel>
</CustomObject>

src/objects/Custom_Clone_System_Fields__mdt.object
<CustomObject>
    <fields>
        <fullName>Copy_Clone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Copy Clone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field_Api__c</fullName>
        <label>Field Api</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Lookup__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Lookup</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>User</fullName>
                    <default>true</default>
                    <label>User</label>
                </value>
                <value>
                    <fullName>Value</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
                <value>
                    <fullName>ParentObject</fullName>
                </value>
                <value>
                    <fullName>System</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Opportunity</fullName>
                    <default>true</default>
                    <label>Opportunity</label>
                </value>
                <value>
                    <fullName>Apttus_Proposal__Proposal__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>String</fullName>
                    <default>true</default>
                    <label>String</label>
                </value>
                <value>
                    <fullName>Integer</fullName>
                </value>
                <value>
                    <fullName>Related Object</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Id</fullName>
                </value>
                <value>
                    <fullName>Decimal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Custom Clone System Field</label>
    <pluralLabel>Custom Clone System Fields</pluralLabel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>Line of Business for Leads</description>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CTK - Complex Turnkey</fullName>
                </value>
                <value>
                    <fullName>Equipment Only</fullName>
                </value>
                <value>
                    <fullName>MA - Maintenance Agreement</fullName>
                </value>
                <value>
                    <fullName>MA - Renewal</fullName>
                </value>
                <value>
                    <fullName>MCP</fullName>
                </value>
                <value>
                    <fullName>Parts Only</fullName>
                </value>
                <value>
                    <fullName>Rental Chillers</fullName>
                </value>
                <value>
                    <fullName>Retrofit/Upgrades</fullName>
                </value>
                <value>
                    <fullName>Service &amp; Repair - Quoted</fullName>
                </value>
                <value>
                    <fullName>Service &amp; Repair - T&amp;M</fullName>
                </value>
                <value>
                    <fullName>Start-Up</fullName>
                </value>
                <value>
                    <fullName>TK - Turnkey Contracting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MA_Model__c.object
<CustomObject>
    <fields>
        <fullName>Proposal__c</fullName>
        <label>Quote/Proposal</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>MA Models</relationshipLabel>
        <relationshipName>MA_Models</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>MA Model</label>
    <nameField>
        <displayFormat>MAM-{000000000}</displayFormat>
        <label>MA Model Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MA Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Billing_Terms__c</fullName>
        <label>Billing Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Billed 100% upon acceptance</fullName>
                </value>
                <value>
                    <fullName>Billed in full upon completion</fullName>
                </value>
                <value>
                    <fullName>Billed per accepted milestones</fullName>
                </value>
                <value>
                    <fullName>MA Annually</fullName>
                </value>
                <value>
                    <fullName>MA monthly</fullName>
                </value>
                <value>
                    <fullName>MA quarterly</fullName>
                </value>
                <value>
                    <fullName>MA semi-annually</fullName>
                </value>
                <value>
                    <fullName>Per accepted schedule of values (SOV)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DM_District_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be populated by Cups DM &amp;ROSM Workflow rule and is used in Cups email notification.</description>
        <inlineHelpText>Opportunity Owner DM (District Manager)</inlineHelpText>
        <label>DM (District Manager)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DMOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>Line of business</description>
        <inlineHelpText>Type of Service/Product</inlineHelpText>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>CTK - Complex Turnkey</fullName>
                    <label>Contracting</label>
                </value>
                <value>
                    <fullName>Equipment Only</fullName>
                </value>
                <value>
                    <fullName>MA - Maintenance Agreement</fullName>
                </value>
                <value>
                    <fullName>MA - Renewal</fullName>
                </value>
                <value>
                    <fullName>MCP</fullName>
                </value>
                <value>
                    <fullName>Parts Only</fullName>
                </value>
                <value>
                    <fullName>Rental Chillers</fullName>
                </value>
                <value>
                    <fullName>Retrofit/Upgrades</fullName>
                </value>
                <value>
                    <fullName>Retrofit/Upgrades/CAP</fullName>
                </value>
                <value>
                    <fullName>Service &amp; Repair - Quoted</fullName>
                </value>
                <value>
                    <fullName>Service &amp; Repair - T&amp;M</fullName>
                </value>
                <value>
                    <fullName>Start-Up</fullName>
                </value>
                <value>
                    <fullName>TK - Turnkey Contracting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vertical_Market__c</fullName>
        <description>Project Industry Types (versus account industry types).  If the Account is a Facilities Management Company the Vertical (Industry) for the opportunity could be different.</description>
        <inlineHelpText>Opportunity Industry type - may be different then Account</inlineHelpText>
        <label>Vertical Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Airports &amp; Transportation</fullName>
                </value>
                <value>
                    <fullName>Assembly, Arenas, and Recreation</fullName>
                </value>
                <value>
                    <fullName>Education K-12</fullName>
                </value>
                <value>
                    <fullName>Financial / Office Space</fullName>
                </value>
                <value>
                    <fullName>Government Buildings</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>Higher Education</fullName>
                </value>
                <value>
                    <fullName>Life Sciences, Pharm, Biotech</fullName>
                </value>
                <value>
                    <fullName>Lodging / Hotels</fullName>
                </value>
                <value>
                    <fullName>Manufacturing Facilities and Warehouses</fullName>
                </value>
                <value>
                    <fullName>Mining</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous Nonresidential Buildings</fullName>
                </value>
                <value>
                    <fullName>Multi-family Residential</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Religious Buildings</fullName>
                </value>
                <value>
                    <fullName>Stock Replenishment</fullName>
                </value>
                <value>
                    <fullName>Stores and Restaurants / Retail</fullName>
                </value>
                <value>
                    <fullName>Telecommunications and Data Centers</fullName>
                </value>
                <value>
                    <fullName>Warehouses (excl. Manufacturer Owned)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>North_America</fullName>
        <active>true</active>
        <businessProcess>North America</businessProcess>
        <description>New (Replaces all existing North America Page Layouts)</description>
        <label>North America</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>DM_District_Manager__c</fullName>
        <label>DM (District Manager)</label>
        <relationshipName>DM_District_Manager</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CloneSObjectTest.cls
@isTest
private class CloneSObjectTest {
    public static Id oppRecType = [SELECT Id, Name 
                                   
                                   FROM RecordType 
                                   WHERE DeveloperName = 'North_America' 
                                   AND SobjectType = 'Opportunity'
                                   limit 1].Id;
    public static Id quoteRecType = [SELECT Id, Name 
                                     FROM RecordType 
                                     WHERE DeveloperName = 'North_America_Proposal' 
                                     AND SobjectType = 'Apttus_Proposal__Proposal__c'
                                     limit 1].Id;
    public static Opportunity opp;
    public static Apttus_Proposal__Proposal__c quoteProp;  
    public static User testUser;
    public static Map<String, List<Custom_Clone_System_Fields__mdt>> systemFields = GroupBy.strings('Object_Name__c', [SELECT Is_Lookup__c, Field_Api__c, Location__c, Object_Name__c, Type__c, Value__c, Copy_Clone__c FROM Custom_Clone_System_Fields__mdt]);
    public static Map<String, List<Clone_Field_Set_To_Clone__mdt>> cloneFieldSets = GroupBy.strings('Object_Name__c', [SELECT Field_Set_Name__c, Object_Name__c FROM Clone_Field_Set_To_Clone__mdt]);
    public static Map<String, List<Custom_Clone_Child_Object__mdt>> cloneChildObjects = GroupBy.strings('Object_Name__c', [SELECT Required_Fields__c, User_Lookup_Field__c, Copy_User_Field__c, Child_Field_on_Parent__c, Child_Object_Api__c, Parent_Lookup_Field__c, Object_Name__c FROM Custom_Clone_Child_Object__mdt]);
    
    @testsetup public static void setUp() {
        AVA_SFCORE__TaxNowSetting__c ts1 = new AVA_SFCORE__TaxNowSetting__c(); 
        ts1.AVA_SFCORE__Active_Setting__c = true; 
        ts1.Name='Test Account';
        insert ts1;    
    }
    public static void setupOpportunity() {
        AVA_SFCORE__TaxNowSetting__c ts1 = new AVA_SFCORE__TaxNowSetting__c(); 
        ts1.AVA_SFCORE__Active_Setting__c = true; 
        ts1.Name='Test Account';
        insert ts1;   
        
        Account acc = (Account) SObjectFactory.create(Account.SobjectType);
        opp = (Opportunity) SObjectFactory.create(Opportunity.SobjectType, new Map<Schema.SobjectField, Object>{Opportunity.accountId =>acc.id, Opportunity.RecordTypeId => oppRecType, Opportunity.StageName  => 'No Bid', Opportunity.Vertical_Market__c => 'Airports & Transportation'});
        
    }
    public static void setupQuoteProposal() {
        AVA_SFCORE__TaxNowSetting__c ts1 = (AVA_SFCORE__TaxNowSetting__c) SObjectFactory.create(AVA_SFCORE__TaxNowSetting__c.SobjectType);
        
        Account acc = (Account) SObjectFactory.create(Account.SobjectType);
        opp = (Opportunity) SObjectFactory.create(Opportunity.SobjectType, new Map<Schema.SobjectField, Object>{Opportunity.accountId =>acc.id, Opportunity.RecordTypeId => oppRecType, Opportunity.StageName  => 'No Bid', Opportunity.Vertical_Market__c => 'Airports & Transportation'});
        
        Apttus_Config2__PriceList__c priceList = (Apttus_Config2__PriceList__c) 
            SObjectFactory.create(Apttus_Config2__PriceList__c.SobjectType);
        
        Map<Schema.SobjectField, Object> proposalFieldMap = new Map<Schema.SobjectField, Object>();
        proposalFieldMap.put(Apttus_Proposal__Proposal__c.Apttus_Proposal__Opportunity__c, opp.id);
        proposalFieldMap.put(Apttus_Proposal__Proposal__c.Apttus_Proposal__Account__c, acc.id);
        proposalFieldMap.put(Apttus_Proposal__Proposal__c.Apttus_QPConfig__PriceListId__c, priceList.id);
        proposalFieldMap.put(Apttus_Proposal__Proposal__c.Apttus_Proposal__Primary__c, true);
        proposalFieldMap.put(Apttus_Proposal__Proposal__c.Proposal_Valid_for_Days__c, '30');
        proposalFieldMap.put(Apttus_Proposal__Proposal__c.T_C_Country__c, 'USA');
        proposalFieldMap.put(Apttus_Proposal__Proposal__c.Emergency_Service_Level__c, 'Not included - available on T&M basis');
        proposalFieldMap.put(Apttus_Proposal__Proposal__c.RecordTypeId, quoteRecType);
        proposalFieldMap.put(Apttus_Proposal__Proposal__c.Document_Presentation_Language__c, 'English');
        proposalFieldMap.put(Apttus_Proposal__Proposal__c.Billing_Terms__c, 'Due Upon Receipt');
        proposalFieldMap.put(Apttus_Proposal__Proposal__c.Quote_Presentation_Currency__c, 'USD');
        proposalFieldMap.put(Apttus_Proposal__Proposal__c.Line_of_Business__c, 'MA - Renewal');
       
        quoteProp = (Apttus_Proposal__Proposal__c) 
            SObjectFactory.create(Apttus_Proposal__Proposal__c.SobjectType, proposalFieldMap);
       
        testUser = (User)SObjectFactory.create(User.SobjectType,  new Map<Schema.SobjectField, Object>{User.DM_District_Manager__c => UserInfo.getUserId()});
    }
    
    @isTest static void OpportunityCloneTest() {
        setupOpportunity();
        Test.startTest();
        CloneSObject clone = new CloneSObject((Sobject)opp, 'Opportunity', 'Clone_Field_Mapping', systemFields.get('Opportunity'), cloneChildObjects.get('Opportunity'));
        clone.getCurrentRunningUser(UserInfo.getUserId());
        clone.populateMasterClone();
        clone.cloneFields();
        Test.stopTest();
        System.assert(clone.cloneObject instanceof Opportunity, 'This should be an opportunity');
        System.assertEquals(UserInfo.getUserId(), clone.currentUser.Id, 'This should be the correct User');
        for(Schema.FieldSetMember field : Schema.getGlobalDescribe().get('Opportunity').getDescribe().FieldSets.getMap().get('Clone_Field_Mapping').getFields()) {
            System.assertEquals(clone.masterObject.get(field.getFieldPath()), clone.cloneObject.get(field.getFieldPath()), field.getFieldPath() + ' field should match');
        }
        System.assertEquals(UserInfo.getUserId(), (String)clone.cloneObject.get('OwnerId'), 'This should be set correctly');
        System.assertEquals('Target/Lead Verification', (String)clone.cloneObject.get('StageName'), 'This should be set correctly');
        System.assertEquals(0, (Decimal)clone.cloneObject.get('Probability'), 'This should be set correctly');
    }
    
    @isTest static void QuoteProposalCloneTest() {
        setupQuoteProposal();
        CloneSObject clone;
        System.runAs(testUser) {
            Test.startTest();
            clone = new CloneSObject((Sobject)quoteProp, 'Apttus_Proposal__Proposal__c', 'Quote_Clone_Mapping', systemFields.get('Apttus_Proposal__Proposal__c'), cloneChildObjects.get('Apttus_Proposal__Proposal__c'));
            clone.getCurrentRunningUser(UserInfo.getUserId());
            clone.cloneFields();
            Test.stopTest();
        }
        System.assert(clone.cloneObject instanceof Apttus_Proposal__Proposal__c, 'This should be an Quote/Proposal');
        System.assertEquals(testUser.Id, clone.currentUser.Id, 'This should be the correct User');
        for(Schema.FieldSetMember field : Schema.getGlobalDescribe().get('Apttus_Proposal__Proposal__c').getDescribe().FieldSets.getMap().get('Quote_Clone_Mapping').getFields()) {
            System.assertEquals(clone.masterObject.get(field.getFieldPath()), clone.cloneObject.get(field.getFieldPath()), field.getFieldPath() + ' field should Match');
            
        }
        System.assert(((String)clone.cloneObject.get('Apttus_Proposal__Proposal_Name__c')).contains('- CLONED'), 'This should have the correct name');
        System.assertEquals('Draft', (String)clone.cloneObject.get('Apttus_Proposal__Approval_Stage__c'), 'This should be set correctly');
        System.assertEquals(null, (String)clone.cloneObject.get('DM_Approval_Name__c'), 'This should be the current User Name');
        System.assertEquals(UserInfo.getUserId(), (String)clone.cloneObject.get('DM_District_Manager__c'), 'This should be set to the correct User');
    }
    
    @isTest static void QuoteProposalCloneChildrenTest() {
        setupQuoteProposal();
        List<MA_Model__c> maModels = (List<MA_Model__c>)SObjectFactory.create(10, MA_Model__c.SObjectType,  new Map<Schema.SobjectField, Object>{MA_Model__c.Proposal__c => quoteProp.Id});
        
        CloneSObject clone;
        System.runAs(testUser) {
            clone = new CloneSObject((Sobject)quoteProp, 'Apttus_Proposal__Proposal__c', 'Quote_Clone_Mapping', systemFields.get('Apttus_Proposal__Proposal__c'), cloneChildObjects.get('Apttus_Proposal__Proposal__c'));
            clone.getCurrentRunningUser(UserInfo.getUserId());
            clone.populateMasterClone();
            clone.cloneFields();
            clone.saveCloneObject();
            
            Test.startTest();
            clone.cloneAndSaveChildObjects();	
            Test.stopTest();
        }
        
        
        
        //List<Apttus_Config2__ProductConfiguration__c> productConfigs = [SELECT Id, Apttus_Config2__Status__c FROM Apttus_Config2__ProductConfiguration__c WHERE Apttus_QPConfig__Proposald__c =: clone.cloneObject.Id];
        //System.assertEquals(1, productConfigs.size(), 'This should have created only one');
        //List<Apttus_Config2__LineItem__c> lineItems = [SELECT Id FROM Apttus_Config2__LineItem__c WHERE Apttus_Config2__ConfigurationId__c =: productConfigs[0].Id];
        //System.assertEquals(5, lineItems.size(), 'This should be the same size as the master line items');
        
        
        
    }
    
    @isTest static void OpportunityCloneSaveTest() {
        setupOpportunity();
        
        CloneSObject clone = new CloneSObject((Sobject)opp, 'Opportunity', 'Clone_Field_Mapping', systemFields.get('Opportunity'), cloneChildObjects.get('Opportunity'));
        clone.getCurrentRunningUser(UserInfo.getUserId());
        clone.populateMasterClone();
        clone.cloneFields();
        
        Test.startTest();
        clone.saveCloneObject();		
        Test.stopTest();
        System.assertNotEquals(null, clone.cloneObject, 'This should have been properly inserted');
        List<Apexpages.Message> msgs =  ApexPages.getMessages();
        System.assert(msgs.isEmpty(), 'There should be no messages on the page');
    }
    
    @isTest static void OpportunityChildSaveTest() {
        setupOpportunity();
        testUser = (User)SObjectFactory.create(User.SobjectType,  new Map<Schema.SobjectField, Object>{User.DM_District_Manager__c => UserInfo.getUserId()});
        UnitTest.addData(SObjectFactory.create(10, OpportunityTeamMember.SObjectType, new Map<Schema.SobjectField, Object>{OpportunityTeamMember.OpportunityId => opp.Id, OpportunityTeamMember.UserId => testUser.Id}))
            .tag('Team Members');
        
        UnitTest.addData(SObjectFactory.create(10, Product2.SObjectType))
            .tag('Products');
        
        UnitTest.addData(SObjectFactory.build(10, PricebookEntry.SObjectType, new Map<Schema.SobjectField, Object>{PricebookEntry.isActive => true}))
            .tag('Pbe');
        UnitTest.get('Pbe').property('Product2Id').assignFrom('Products');
        UnitTest.get('Pbe').insertAll();
        
        UnitTest.addData(SObjectFactory.build(10, OpportunityLineItem.SObjectType , new Map<Schema.SobjectField, Object>{OpportunityLineItem.OpportunityId => opp.Id, OpportunityLineItem.Quantity => 1, OpportunityLineItem.TotalPrice => 0}))
            .tag('Oli');
        UnitTest.get('Oli').property('PricebookEntryId').assignFrom('Pbe');
        UnitTest.get('Oli').insertAll();
        
        CloneSObject clone = new CloneSObject((Sobject)opp, 'Opportunity', 'Clone_Field_Mapping', systemFields.get('Opportunity'), cloneChildObjects.get('Opportunity'));
        clone.getCurrentRunningUser(UserInfo.getUserId());
        clone.populateMasterClone();
        clone.cloneFields();
        clone.saveCloneObject();
        Test.startTest();
        clone.cloneAndSaveChildObjects();	
        Test.stopTest();
        
        List<OpportunityLineItem> clonedOlis = [SELECT Id, OpportunityId FROM OpportunityLineItem WHERE OpportunityId =: opp.Id];
        System.assertEquals(10, clonedOlis.size(), 'These should be the same size');
        Id userId = UserInfo.getUserId();
        List<OpportunityTeamMember> cloneTeamMembers = [SELECT Id, OpportunityId FROM OpportunityTeamMember WHERE OpportunityId =: opp.Id And UserId =: userId];
        System.assertEquals(1, cloneTeamMembers.size(), 'These should be the same size');
    }
    
}