src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>dcw_DistChannels.dc_active_flag</description>
        <inlineHelpText>dcw_DistChannels.dc_active_flag</inlineHelpText>
        <label>Active (DCW)</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account_Address__c.object
<CustomObject>
    <description>Junction object to tie multiple address records to an account and multiple accounts to a single address record.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Addresses</relationshipLabel>
        <relationshipName>Account_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Address_Name__c</fullName>
        <formula>Address__r.Address_Name__c</formula>
        <label>Address Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Address Lookup</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Account_Addresses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bill_To__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bill To</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mail_To__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mail To</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Physical__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Physical</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Bill_To__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Bill To</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Mail_To__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Mail To</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Ship_To__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Ship To</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ship To</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Address</label>
    <nameField>
        <displayFormat>AA-{000000000}</displayFormat>
        <label>Account Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <label>Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_3__c</fullName>
        <label>Address Line 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_4__c</fullName>
        <label>Address Line 4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Name__c</fullName>
        <inlineHelpText>Descriptive name for the Address.</inlineHelpText>
        <label>Address Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>United States</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Åland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia, Plurinational State of</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <label>State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Acklins</fullName>
                </value>
                <value>
                    <fullName>Acre</fullName>
                </value>
                <value>
                    <fullName>Aguascalientes</fullName>
                </value>
                <value>
                    <fullName>Ahuachapán</fullName>
                </value>
                <value>
                    <fullName>Aisén del General Carlos Ibáñez del Campo</fullName>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alagoas</fullName>
                </value>
                <value>
                    <fullName>Alajuela</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Alberta</fullName>
                </value>
                <value>
                    <fullName>Alta Verapaz</fullName>
                </value>
                <value>
                    <fullName>Alto Paraguay</fullName>
                </value>
                <value>
                    <fullName>Alto Paraná</fullName>
                </value>
                <value>
                    <fullName>Amambay</fullName>
                </value>
                <value>
                    <fullName>Amapá</fullName>
                </value>
                <value>
                    <fullName>Amazonas</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Ancash</fullName>
                </value>
                <value>
                    <fullName>Andaman and Nicobar Islands</fullName>
                </value>
                <value>
                    <fullName>Andhra Pradesh</fullName>
                </value>
                <value>
                    <fullName>Anhui</fullName>
                </value>
                <value>
                    <fullName>Anse la Raye</fullName>
                </value>
                <value>
                    <fullName>Antioquia</fullName>
                </value>
                <value>
                    <fullName>Antofagasta</fullName>
                </value>
                <value>
                    <fullName>Anzoátegui</fullName>
                </value>
                <value>
                    <fullName>Apure</fullName>
                </value>
                <value>
                    <fullName>Apurímac</fullName>
                </value>
                <value>
                    <fullName>Aragua</fullName>
                </value>
                <value>
                    <fullName>Arauca</fullName>
                </value>
                <value>
                    <fullName>Araucanía</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <description>This record type if for all records created by SFDC Users.</description>
        <label>Address</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Address_Line_1__c</fullName>
        <description>Whenever an Opportunity with the Record type of &apos;North America Apttus&apos; is created or edited, it should copy the Primary Billing Address fields from the Account over to the Opportunity.</description>
        <inlineHelpText>Whenever an Opportunity with the Record type of &apos;North America Apttus&apos; is created or edited, it should copy the Primary Billing Address fields from the Account over to the Opportunity.</inlineHelpText>
        <label>Bill To Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Address_Line_2__c</fullName>
        <description>Whenever an Opportunity with the Record type of &apos;North America Apttus&apos; is created or edited, it should copy the Primary Billing Address fields from the Account over to the Opportunity.</description>
        <inlineHelpText>Whenever an Opportunity with the Record type of &apos;North America Apttus&apos; is created or edited, it should copy the Primary Billing Address fields from the Account over to the Opportunity.</inlineHelpText>
        <label>Bill To Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Address_Line_3__c</fullName>
        <description>Whenever an Opportunity with the Record type of &apos;North America Apttus&apos; is created or edited, it should copy the Primary Billing Address fields from the Account over to the Opportunity.</description>
        <inlineHelpText>Whenever an Opportunity with the Record type of &apos;North America Apttus&apos; is created or edited, it should copy the Primary Billing Address fields from the Account over to the Opportunity.</inlineHelpText>
        <label>Bill To Address Line 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Address_Line_4__c</fullName>
        <description>Whenever an Opportunity with the Record type of &apos;North America Apttus&apos; is created or edited, it should copy the Primary Billing Address fields from the Account over to the Opportunity.</description>
        <inlineHelpText>Whenever an Opportunity with the Record type of &apos;North America Apttus&apos; is created or edited, it should copy the Primary Billing Address fields from the Account over to the Opportunity.</inlineHelpText>
        <label>Bill To Address Line 4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Address_Name__c</fullName>
        <description>Whenever an Opportunity with the Record type of &apos;North America Apttus&apos; is created or edited, it should copy the Primary Billing Address fields from the Account over to the Opportunity.</description>
        <inlineHelpText>Whenever an Opportunity with the Record type of &apos;North America Apttus&apos; is created or edited, it should copy the Primary Billing Address fields from the Account over to the Opportunity.</inlineHelpText>
        <label>Bill To Address Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_City__c</fullName>
        <description>Whenever an Opportunity with the Record type of &apos;North America Apttus&apos; is created or edited, it should copy the Primary Billing Address fields from the Account over to the Opportunity.</description>
        <inlineHelpText>Whenever an Opportunity with the Record type of &apos;North America Apttus&apos; is created or edited, it should copy the Primary Billing Address fields from the Account over to the Opportunity.</inlineHelpText>
        <label>Bill To City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Final_Credit_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Final Credit Approval</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/OpportunityTriggerHandler.cls
public class OpportunityTriggerHandler {

    //Retrieve Opportunity record types and hold in a map
    public static Map<Id, Schema.RecordTypeInfo> oppRTMap = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosById();
    public static final Set<String> SET_OPPORTUNITY_STAGES = new Set<String> {'Closed Lost' , 'Abandoned' };

    public static void handleAfterUpdate(Map<Id, Opportunity> opps, Map<Id, Opportunity> oldMap) {
        List<Opportunity> filterOpps = OpportunityTriggerServices.filterClosedWon(opps.values());
		system.debug('filterOpps ' + filterOpps);
        List<Opportunity> finalCreditApprovalOpps = new List<Opportunity>();
        for(Opportunity opp :filterOpps)
        {
            if(opp.Final_Credit_Approval__c)
            {
                finalCreditApprovalOpps.add(opp);    
            }
                
        }
        
        if(!finalCreditApprovalOpps.isEmpty()) 
        {
            List<Apttus_Proposal__Proposal__c> quoteProposals = OpportunityTriggerServices.getPrimaryQuoteProposal(filterOpps);
            system.debug('quoteProposals ' + quoteProposals);
            if(!quoteProposals.isEmpty()) {
                OpportunityTriggerServices.kickOffApprovalProcess(quoteProposals, opps);
            }
        }

        OpportunityTriggerServices.processOpportunitySplitsOnAmountChange(opps.values(),oldMap);
        OpportunityTriggerServices.processOpportunitySplits(opps.values());
    }

    public static void handleAfterUpdate(Map<Id, Opportunity> oppsp) {
    }


    public static void handleBeforeInsertUpdate(List<Opportunity> oppList) {
        /*
            Whenever an Opportunity with the Record type of 'North America Apttus' is created or edited, it should copy the Primary Billing
            Address fields over to the Opportunity. No error should be thrown if there is no Account attached to the Opportunity or if a Primary
            Bill To address is not specified on the Account.
        */

        // Check if the Record Type is 'North America Apttus'
        system.debug('oppList::'+oppList.size());
        Set<id> accID = new Set<Id>();
        for(Opportunity opp : oppList)
        {
            if(opp.RecordTypeId != null && oppRTMap.get(opp.RecordTypeId).getName().containsIgnoreCase('North America Apttus'))
            {
                if (opp.AccountId != null)
                {
                    accId.add(opp.AccountId);
                    System.debug('Account Id'+opp.AccountId);
                }
              }
        }
		
        List<Account_Address__c> acctAddrJunctionObjs = [Select Account__c, Active__c, Address_Name__c, Address__c, Bill_To__c, Mail_To__c, Name, Physical__c, Primary_Bill_To__c, Primary_Mail_To__c, Primary_Ship_To__c, Ship_To__c FROM Account_Address__c where Account__c IN:accId];
        System.debug('ACCOUNT aDDRESS ::'+acctAddrJunctionObjs);
        Map<Id,Account_Address__c> accAddrMap = new Map<Id,Account_Address__c>();
        Map<String,String> accountAddressMap = new Map<String,String>();
        for(Account_Address__c addressVar :[Select Account__c, Active__c, Address_Name__c, Address__c, Bill_To__c, Mail_To__c, Name, Physical__c, Primary_Bill_To__c, Primary_Mail_To__c, Primary_Ship_To__c, Ship_To__c FROM Account_Address__c where Account__c IN:accId and Primary_Bill_To__c = true])
        {
            accountAddressMap.put(addressVar.account__c, addressVar.Address__c);
            accAddrMap.put(addressVar.Address__c,addressVar);
        }
        Map<String,Address__c> addressMap = new Map<String,Address__c>();
        for(Address__c adrVar: [select id,Name, Address_Line_1__c, Address_Line_2__c, Address_Line_3__c, Address_Line_4__c, Address_Name__c, Postal_Code__c, City__c, Country__c, State_Province__c FROM Address__c where Id IN :accAddrMap.keySet()])
        {
            addressMap.put(adrVar.Id,adrVar);
        }
        
        for(Opportunity opp : oppList) {
            if(opp.RecordTypeId != null && oppRTMap.get(opp.RecordTypeId).getName().containsIgnoreCase('North America Apttus')) {
                if (opp.AccountId != null) {
                    System.debug('Entered here Call');
                    // Get the associated account address records from the junction object (Account_Address__c) via the account id
						
                    // Loop through the list of account address records and grab the one whose 'Primary Bill To' field is TRUE
                    // Get the Address record for the given Id and set appropriate Opportunity address fields
                            //Address__c addr = [SELECT Id, Name, Address_Line_1__c, Address_Line_2__c, Address_Line_3__c, Address_Line_4__c, Address_Name__c, Postal_Code__c, City__c, Country__c, State_Province__c FROM Address__c WHERE id = :aa.Address__c and Primary_Bill_To__c = true];
                            if(accountAddressMap.containsKey(opp.AccountId))
                            {
                    		Address__c addr = addressMap.get(accountAddressMap.get(opp.AccountId));
                                
                            opp.Bill_To_Address_Name__c = addr.Address_Name__c;
                            opp.Bill_To_Address_Line_1__c = addr.Address_Line_1__c;
                            opp.Bill_To_Address_Line_2__c = addr.Address_Line_2__c;
                            opp.Bill_To_Address_Line_3__c = addr.Address_Line_3__c;
                            opp.Bill_To_Address_Line_4__c = addr.Address_Line_4__c;
                            opp.Bill_To_City__c = addr.City__c;
                            opp.Bill_To_Country__c = addr.Country__c;
                            opp.Bill_To_State_Province__c = addr.State_Province__c;
                            opp.Bill_To_Zip_Postal_Code__c = addr.Postal_Code__c;
                            }
                }
            }
        }
    }
     public static void updateBidderDate(List<Opportunity> oppList){// Updates bidder date when opportunity Bidder date is set to future
        List<Bidder__c> bidderList = [SELECT Id, of_Follow_up_Attempts__c, Opportunity__r.Bid_Date__c FROM Bidder__c
                                     WHERE Opportunity__c IN :oppList];
        for(Bidder__c b :bidderList){
            if(b.Opportunity__r.Bid_Date__c > System.today()){
             	b.of_Follow_up_Attempts__c = 0;   
            }
        }
        if(!bidderList.isEmpty()){
            update bidderList;
        }
    }


}