src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>IE_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate the record pertains to the IE integration. This is set on import of records from Daikin IE Back Office database or IE system.</description>
        <inlineHelpText>If checked, this account has purchased Intelligent Equipment subscription(s) or a contact at this company is an IE system user.</inlineHelpText>
        <label>IE Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IE_ID__c</fullName>
        <externalId>true</externalId>
        <label>IE ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IE_Sync_Status__c</fullName>
        <label>IE Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>DW_Product_Line__c</fullName>
        <description>DW Product Line from the Product</description>
        <formula>Product2.DW_Product_Line__c</formula>
        <inlineHelpText>DW Product Line from the Product</inlineHelpText>
        <label>DW Product Line</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IE_ID__c</fullName>
        <externalId>true</externalId>
        <label>IE ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IE_Sync_Status__c</fullName>
        <description>Status that gets set when attributes on the record are updated and therefore needs to be sent to the IE system.</description>
        <inlineHelpText>Pending = Record needs to be sent to the IE system. 
Processed = Record was successfully received by IE system. 
Error = Record was not successfully received by IE system.</inlineHelpText>
        <label>IE Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Additional_Materials_Amount_Approved__c</fullName>
        <inlineHelpText>What Additional Materials Dollar Amounts were approved?</inlineHelpText>
        <label>Additional Materials Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Case_Category__c</fullName>
        <inlineHelpText>Please specify the category for this Case</inlineHelpText>
        <label>Case Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Accounts</fullName>
                </value>
                <value>
                    <fullName>Addresses</fullName>
                </value>
                <value>
                    <fullName>Approvals</fullName>
                </value>
                <value>
                    <fullName>Assets</fullName>
                </value>
                <value>
                    <fullName>Batch Jobs</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Campaigns</fullName>
                </value>
                <value>
                    <fullName>Cases</fullName>
                </value>
                <value>
                    <fullName>Change of Driver</fullName>
                </value>
                <value>
                    <fullName>Chatter</fullName>
                </value>
                <value>
                    <fullName>Claim</fullName>
                </value>
                <value>
                    <fullName>Contacts</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Credit Application</fullName>
                </value>
                <value>
                    <fullName>CRM</fullName>
                </value>
                <value>
                    <fullName>Dashboards</fullName>
                </value>
                <value>
                    <fullName>Documents</fullName>
                </value>
                <value>
                    <fullName>DST Assistance</fullName>
                </value>
                <value>
                    <fullName>Equipment Issue</fullName>
                </value>
                <value>
                    <fullName>Expedite</fullName>
                </value>
                <value>
                    <fullName>Extended</fullName>
                </value>
                <value>
                    <fullName>Fleet</fullName>
                </value>
                <value>
                    <fullName>Force.com Sites</fullName>
                </value>
                <value>
                    <fullName>FPA Special Request</fullName>
                </value>
                <value>
                    <fullName>General Questions</fullName>
                </value>
                <value>
                    <fullName>GEOTAB</fullName>
                </value>
                <value>
                    <fullName>Integration</fullName>
                </value>
                <value>
                    <fullName>Invoices</fullName>
                </value>
                <value>
                    <fullName>Known Issue (Fix on fail)</fullName>
                </value>
                <value>
                    <fullName>Leads</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Daikin_Parts_Amount_Approved__c</fullName>
        <inlineHelpText>What Daikin Parts Dollar Amounts were approved?</inlineHelpText>
        <label>Daikin Parts Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hours_Approved__c</fullName>
        <description>The hours amount of labor Daikin will reimburse for Warranty that have been approved. Compare with Hours Requested</description>
        <inlineHelpText>The labor hours that will be reimbursed and have been approved. Compare to Hours Requested on the case ticket</inlineHelpText>
        <label>Hours Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IE_ID__c</fullName>
        <description>Used by the Intelligent Equipment group to link to IE Assets.</description>
        <externalId>true</externalId>
        <label>IE ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Labor_Amount_Approved__c</fullName>
        <inlineHelpText>What Labor Dollar Amounts were approved?</inlineHelpText>
        <label>Labor Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <formula>Asset.SerialNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Serial Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X3rd_Party_Parts_Amount_Approved__c</fullName>
        <inlineHelpText>What 3rd Party Parts Dollar Amounts were approved?</inlineHelpText>
        <label>3rd-Party Parts Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>TRC</fullName>
        <active>true</active>
        <businessProcess>TRC - North America</businessProcess>
        <description>Default Record Type for TRC web cases when the TRC Group is unknown for the Product.</description>
        <label>TRC</label>
    </recordTypes>
    <recordTypes>
        <fullName>Warranty</fullName>
        <active>true</active>
        <businessProcess>Warranty</businessProcess>
        <description>Used for Warranty case claims</description>
        <label>Warranty</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Service_Code__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Materials_Amount_Approved__c</fullName>
        <label>Additional Materials Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Service Codes</relationshipLabel>
        <relationshipName>Case_Service_Codes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Daikin_Parts_Amount_Approved__c</fullName>
        <label>Daikin Parts Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hours_Approved__c</fullName>
        <label>Hours Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Labor_Amount_Approved__c</fullName>
        <label>Labor Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>WarrantyClassCode__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Warranty Class</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Case Service Codes (Warranty Class)</relationshipLabel>
        <relationshipName>Case_Service_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X3rd_Party_Parts_Amount_Approved__c</fullName>
        <label>3rd-Party Parts Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Case Service Code</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Case Service Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Service Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>IE_ID__c</fullName>
        <description>IE database unique record ID.</description>
        <externalId>true</externalId>
        <inlineHelpText>IE database unique record ID.</inlineHelpText>
        <label>IE ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IE_Sync_Status__c</fullName>
        <description>Status that gets set when attributes on the record are updated and therefore needs to be sent to the IE system.</description>
        <inlineHelpText>Pending =  Record needs to be sent to the IE system. 
Processed = Record was successfully received by IE system.
Error = Record was not successfully received by IE system.</inlineHelpText>
        <label>IE Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Apttus_Config2__ConfigurationType__c</fullName>
        <description>The product configuration type</description>
        <label>Configuration Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standalone</fullName>
                    <default>true</default>
                    <label>Standalone</label>
                </value>
                <value>
                    <fullName>Bundle</fullName>
                </value>
                <value>
                    <fullName>Option</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DW_PCL_Description__c</fullName>
        <label>DW PCL Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DW_Product_Business_Unit__c</fullName>
        <label>DW Product Business Unit</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DW_Product_Class__c</fullName>
        <label>DW Product Class</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DW_Product_Family__c</fullName>
        <label>DW Product Family</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DW_Product_Line__c</fullName>
        <label>DW Product Line</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <description>Product Category</description>
        <label>Product Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Sub_Category__c</fullName>
        <label>Product Sub-Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TRC_Group__c</fullName>
        <inlineHelpText>Identifies which TRC group is responsible for handling Cases associated with this product. Web cases are assigned based on this field.</inlineHelpText>
        <label>TRC Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TRC - AAH</fullName>
                </value>
                <value>
                    <fullName>TRC - ATS</fullName>
                </value>
                <value>
                    <fullName>TRC - Chillers</fullName>
                </value>
                <value>
                    <fullName>TRC - Controls</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor_Supplier_Long__c</fullName>
        <description>Full name of Vendor/Supplier.</description>
        <inlineHelpText>Full name of Vendor/Supplier.</inlineHelpText>
        <label>Vendor/Supplier Full Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Supplier__c</fullName>
        <label>Vendor/Supplier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ChillerWarrantyAuthorizationVFClassTest.cls
@isTest
public class ChillerWarrantyAuthorizationVFClassTest {
    
    @isTest
   static void cwac_Method()
        
    {
       
        AVA_SFCORE__TaxNowSetting__c ts1 = new AVA_SFCORE__TaxNowSetting__c(); 
        ts1.AVA_SFCORE__Active_Setting__c = true; 
        ts1.Name='Test Account';
        insert ts1;
        
        Account a = new Account(Name = 'Test'
                    , IE_Sync_Status__c = 'Pending'
                    , IE_ID__c = '123'
                    , IE_Account__c = true
                    );
        insert a;
        
        Account a2 = new Account(Name = 'Test'
                                , IE_Sync_Status__c = 'Pending'
                                , BillingStreet = '1234\n4567\n8910'
                                , BillingCity = 'Mlps'
                                , BIllingState = 'Minnesota'
                                , BillingCountry = 'United States'
                                , BillingPostalCode = '55441'
                                );
        insert a2;
        Contact con = new Contact();
        con.LastName = 'Solunus Test Contact';
        con.Email = 'solunus@test.com';
        con.phone = '08038290232';
        con.AccountId = a.id;
        insert con;
        
        Id RecordTypeIdCase = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Warranty Claim Authorization').getRecordTypeId();
        Id RecordTypeIdChildCase = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Warranty').getRecordTypeId();

        Product2 pd = new Product2();
        pd.Vendor_Supplier_Long__c = 'Daikin Applied Americas INC';
        pd.Vendor_Supplier__c = 'DA US';
        pd.Product_Category__c = 'Light Commercial';
        pd.Product_Sub_Category__c = 'Light Commercial';
        pd.Product_Group__c = 'DPS';
        pd.Name = 'Package System';
        pd.Description = 'Package System';
        pd.TRC_Group__c = 'TRC - AAH';
        pd.Apttus_Config2__ConfigurationType__c = 'Standalone';
        pd.DW_Product_Business_Unit__c = 'Applied Air Handler';
        pd.DW_Product_Family__c = 'Rooftop Systems';
        pd.DW_PCL_Description__c  = 'REBEL RT UNIT';
        pd.DW_Product_Class__c = '0425';
        pd.DW_Product_Line__c = 'Rebel [DPS]';
        insert pd;
        
        Asset ast = new Asset();
        ast.AccountId = a2.id;
        ast.ContactId = con.id;
        ast.Name = 'Test Asset';
        ast.SerialNumber = 'FB86J17878123';
        ast.Product2Id = pd.id;
        insert ast;
         Asset ast1 = new Asset();
        ast1.AccountId = a2.id;
        ast1.ContactId = con.id;
        ast1.Name = 'Test Asset';
        ast1.SerialNumber = 'FB86J17871458123';
        ast1.Product2Id = pd.id;
        insert ast1;
        
        Case pcase = new Case();
        pcase.Origin = 'Email';
        pcase.Subject = 'Test Soluns';
        pcase.AccountId = a2.id;
        pcase.Status = 'Warranty Review';
        pcase.Case_Category__c = 'Claim';
        pcase.RecordTypeId = RecordTypeIdCase;
        insert pcase;
        

        
        Case case1 = new Case();
        case1.RecordTypeId = RecordTypeIdChildCase;
        case1.ParentId = pcase.id;
        case1.Origin = 'Email';
        case1.Subject = 'Test Soluns';
        case1.AccountId = a2.id;
        case1.Status = 'Warranty Review';
        case1.Case_Category__c = 'Claim';
        case1.AssetId = ast.id;
        case1.Hours_Approved__c = 12.0;
        case1.Labor_Amount_Approved__c = 200;
        case1.Additional_Materials_Amount_Approved__c = 120;
        case1.X3rd_Party_Parts_Amount_Approved__c = 90;
        case1.Daikin_Parts_Amount_Approved__c = 92;
        insert case1;
        //CaseNumber,Hours_Approved__c,Labor_Amount_Approved__c,Additional_Materials_Amount_Approved__c,X3rd_Party_Parts_Amount_Approved__c,Daikin_Parts_Amount_Approved__c
        Case case2 = new Case();
        case2.RecordTypeId = RecordTypeIdChildCase;
        case2.ParentId = pcase.id;
        case2.Origin = 'Email';
        case2.Subject = 'Test Soluns';
        case2.AccountId = a2.id;
        case2.ContactId = con.id;
        case2.Status = 'Warranty Review';
        case2.Case_Category__c = 'Claim';
        case2.AssetId = ast1.id;
        case2.Hours_Approved__c = 12.0;
        case2.Labor_Amount_Approved__c = 200;
        case2.Additional_Materials_Amount_Approved__c = 120;
        case2.X3rd_Party_Parts_Amount_Approved__c = 90;
        case2.Daikin_Parts_Amount_Approved__c = 92;
        insert case2;
        
       /* Case_Service_Code__c cscode = new Case_Service_Code__c();
        cscode.Case__c = case1.id;
        cscode.Hours_Approved__c = 20.00;
        cscode.Labor_Amount_Approved__c = 2000;
        cscode.Additional_Materials_Amount_Approved__c = 120;
        cscode.X3rd_Party_Parts_Amount_Approved__c = 40;
        cscode.Daikin_Parts_Amount_Approved__c = 60;
        insert cscode;
        System.debug('Warranty class'+cscode.WarrantyClassCode__c);*/
      
        List<Case> caseToDisplay = new List<Case>();
      
        List<Case> cases = [SELECT Id,(SELECT Id,Serial_Number__c,CaseNumber,Hours_Approved__c,Labor_Amount_Approved__c,Additional_Materials_Amount_Approved__c,X3rd_Party_Parts_Amount_Approved__c,Daikin_Parts_Amount_Approved__c from Cases) FROM Case WHERE Case.Id=:pcase.id];
        Set<Id> csid = new Set<Id>();
        Map<String, List<Case_Service_Code__c>> cscodeList = new Map<String, List<Case_Service_Code__c>>();
        List<Case_Service_Code__c> csccodes = [SELECT Id, Name,Case__c,WarrantyClassCode__r.Name,Asset_PCL__c,WarrantyClassCode__r.Label__c FROM Case_Service_Code__c where Case__c IN :caseToDisplay];
        for(Case_Service_Code__c ccv :csccodes)
        {
            if(cscodeList.containsKey(ccv.Case__c)){
                cscodeList.get(ccv.Case__c).add(ccv);    
            }else{
                cscodeList.put(ccv.Case__c, new List<Case_Service_Code__c>{ccv});  
            }
        }
        
        
        test.startTest();
        ChillerWarrantyAuthorizationVFClass caseController = new ChillerWarrantyAuthorizationVFClass();
        caseController.caseIdValue=pcase.Id;
		List<case> caseList=caseController.casess;
        List<case> caseList1=caseController.warrantyChildcasess;
        case caseObj=caseController.caseValues;   
    	cscodeList = caseController.getservicecodes;
        caseController.csid = csid;
      
        test.stopTest();
        
    }

}