src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Account has been inactivated</description>
        <inlineHelpText>The Account/Company no longer exists (closed doors, bankruptcy, etc.)</inlineHelpText>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account_Address__c.object
<CustomObject>
    <description>Junction object to tie multiple address records to an account and multiple accounts to a single address record.</description>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Address Lookup</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Account_Addresses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Account Address</label>
    <nameField>
        <displayFormat>AA-{000000000}</displayFormat>
        <label>Account Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Bidder__c.object
<CustomObject>
    <description>DMNY</description>
    <fields>
        <fullName>Apparent_Winning_Bidder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Apparent Winning Bidder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bidder_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>DMNY</description>
        <label>Bidder Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bidders</relationshipLabel>
        <relationshipName>Bidders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates bidder not successful or no longer active.</description>
        <inlineHelpText>Indicates bidder not successful or no longer active.</inlineHelpText>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Bidders</relationshipLabel>
        <relationshipName>Bidders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bidder</label>
    <nameField>
        <label>Bidder Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bidders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Bid_Date__c</fullName>
        <description>Date of the Bid</description>
        <inlineHelpText>Date of the Bid</inlineHelpText>
        <label>Bid Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Bidder_Rollup__c</fullName>
        <label>Bidder Rollup</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact_Rollup__c</fullName>
        <description>It is a combination of Contact Name + “@” + Account Name + “(“Role”)”</description>
        <label>Contact Rollup</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Edited__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Edited</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Job_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Address Id for the Location of the Job Site</inlineHelpText>
        <label>Job Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Won_Lost_Against__c</fullName>
        <description>Specifies the competitor to whom the job was lost. This field is required for Lost opportunities.</description>
        <inlineHelpText>Specifies the competitor to whom the job was lost. This field is required for Lost opportunities.</inlineHelpText>
        <label>Won/Lost - Against</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AAF</fullName>
                </value>
                <value>
                    <fullName>AAON</fullName>
                </value>
                <value>
                    <fullName>ABB</fullName>
                </value>
                <value>
                    <fullName>AboveAir</fullName>
                </value>
                <value>
                    <fullName>Addison</fullName>
                </value>
                <value>
                    <fullName>Advantix</fullName>
                </value>
                <value>
                    <fullName>Aerco Boilers</fullName>
                </value>
                <value>
                    <fullName>AMANA</fullName>
                </value>
                <value>
                    <fullName>Annexair</fullName>
                </value>
                <value>
                    <fullName>ArchtiChill</fullName>
                </value>
                <value>
                    <fullName>Armstrong</fullName>
                </value>
                <value>
                    <fullName>Armstrong Pumps</fullName>
                </value>
                <value>
                    <fullName>Aurora Pump</fullName>
                </value>
                <value>
                    <fullName>Bard</fullName>
                </value>
                <value>
                    <fullName>Belimo</fullName>
                </value>
                <value>
                    <fullName>Bosch</fullName>
                </value>
                <value>
                    <fullName>Bry-Air</fullName>
                </value>
                <value>
                    <fullName>Buffalo</fullName>
                </value>
                <value>
                    <fullName>Camfill Farr</fullName>
                </value>
                <value>
                    <fullName>CaptiveAire</fullName>
                </value>
                <value>
                    <fullName>Carel USA</fullName>
                </value>
                <value>
                    <fullName>Carrier</fullName>
                </value>
                <value>
                    <fullName>Chigo</fullName>
                </value>
                <value>
                    <fullName>Chil-Pak</fullName>
                </value>
                <value>
                    <fullName>China Refrigeration</fullName>
                </value>
                <value>
                    <fullName>Cleaver Brooks</fullName>
                </value>
                <value>
                    <fullName>ClimaCool</fullName>
                </value>
                <value>
                    <fullName>Climatecraft</fullName>
                </value>
                <value>
                    <fullName>Climate Master</fullName>
                </value>
                <value>
                    <fullName>Climate Technologies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Rollup__c</fullName>
        <label>Product Rollup</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <description>created for the DSO&apos;s originally (DAAL - John Jeffcoat)</description>
        <inlineHelpText>Plan &amp; Spec: Projects that have a set of plans &amp; specifications released by an architect, an engineer, or an owner. 
Non–Plan &amp; Spec: All other projects including equipment replacements, design-build projects, etc.</inlineHelpText>
        <label>Project Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Non - Plan &amp; Spec</fullName>
                </value>
                <value>
                    <fullName>Plan &amp; Spec</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secured_Date__c</fullName>
        <description>Date the order was entered into the transactional system</description>
        <inlineHelpText>Date the order was entered into the transactional system</inlineHelpText>
        <label>Secure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vertical_Market__c</fullName>
        <description>Project Industry Types (versus account industry types).  If the Account is a Facilities Management Company the Vertical (Industry) for the opportunity could be different.</description>
        <inlineHelpText>Opportunity Industry type - may be different then Account</inlineHelpText>
        <label>Vertical Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Airports &amp; Transportation</fullName>
                </value>
                <value>
                    <fullName>Assembly, Arenas, and Recreation</fullName>
                </value>
                <value>
                    <fullName>Education K-12</fullName>
                </value>
                <value>
                    <fullName>Financial / Office Space</fullName>
                </value>
                <value>
                    <fullName>Government Buildings</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>Higher Education</fullName>
                </value>
                <value>
                    <fullName>Life Sciences, Pharm, Biotech</fullName>
                </value>
                <value>
                    <fullName>Lodging / Hotels</fullName>
                </value>
                <value>
                    <fullName>Manufacturing Facilities and Warehouses</fullName>
                </value>
                <value>
                    <fullName>Mining</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous Nonresidential Buildings</fullName>
                </value>
                <value>
                    <fullName>Multi-family Residential</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Religious Buildings</fullName>
                </value>
                <value>
                    <fullName>Stock Replenishment</fullName>
                </value>
                <value>
                    <fullName>Stores and Restaurants / Retail</fullName>
                </value>
                <value>
                    <fullName>Telecommunications and Data Centers</fullName>
                </value>
                <value>
                    <fullName>Warehouses (excl. Manufacturer Owned)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Won_Lost_Against_Other__c</fullName>
        <description>Please Specify Won/Lost Against</description>
        <inlineHelpText>Please Specify Won/Lost Against</inlineHelpText>
        <label>Won/Lost Against(Other)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Won_Lost_Reason__c</fullName>
        <description>A value indicating the main reason a job was won or lost.</description>
        <inlineHelpText>A value indicating the main reason a job was won or lost.</inlineHelpText>
        <label>Won/Lost Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Credit Terms</fullName>
                </value>
                <value>
                    <fullName>Daikin Contractor on the job</fullName>
                </value>
                <value>
                    <fullName>Delivery Time</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Lumped Out - Controls</fullName>
                </value>
                <value>
                    <fullName>Lumped Out - Equipment</fullName>
                </value>
                <value>
                    <fullName>Nat&apos;l Account Relationship</fullName>
                </value>
                <value>
                    <fullName>Negotiated</fullName>
                </value>
                <value>
                    <fullName>No Callback</fullName>
                </value>
                <value>
                    <fullName>Non-Daikin Contractor on the job</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Preference for stick-site built</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Project was canceled</fullName>
                </value>
                <value>
                    <fullName>Specs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/OpportunityRollupsBatchTest.cls
@isTest
public class OpportunityRollupsBatchTest {
    static Account acct;
    static Address__c addy;
    static Account_Address__c aAddy;
    
    static void setupData(){
        
        AVA_SFCORE__TaxNowSetting__c ts1 = new AVA_SFCORE__TaxNowSetting__c(); 
        ts1.AVA_SFCORE__Active_Setting__c = true; 
        ts1.Name='Test Account';
        insert ts1;
        
        acct = TestingUtils.createAccounts(1, 'TestAccount', false)[0];
        addy = TestingUtils.createAddresses(1, true)[0];
        
    }
    @isTest
    public static void OptyRollTest()
    {
        setupData();
        List<Opportunity> opps = new List<Opportunity>();
        User u = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
            LastName = 'last',
            Email = 'testinguser@daikinapplied.com',
            Username = 'testinguser@daikinapplied.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            //Department = 'IT',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US');
            insert u;
               
        acct.Name = 'Testing Opportunity';
        acct.Type = 'Competetor';
        acct.OwnerId = u.id;
        insert acct;
        Contact con = new Contact();
        con.AccountId = acct.id;
        con.LastName = 'Test Contact Name';
        con.Phone  ='99999999';
        insert con;
        
        Product2 pd = new Product2();
        pd.Name = 'Dell Crop';
        insert pd;
        Id RecordTypeIdContact = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('North America - DSO').getRecordTypeId();
        
        Opportunity Opty = new Opportunity();
        Opty.RecordTypeId =RecordTypeIdContact;
        Opty.Name        ='Test Oppty';
        Opty.CloseDate   = system.today()+20;
        Opty.AccountId = acct.id;
       /* Opty.Project_Type__c = '';
        OPty.Secured_Date__c=system.today();
        opty.Won_Lost_Against_Other__c ='';
        Opty.Job_Won_Lost_Against__c='';
       Opty.Contact_Rollup__c='test';
     Opty.Bidder_Rollup__c  = 'test bidder roll';
        Opty.Product_Rollup__c = 'test';
        Opty.Job_Address__c  = addy.id;
       Opty.Bid_Date__c = system.today()+20;
        Opty.Won_Lost_Reason__c='';*/
        Opty.Probability=50;
        Opty.StageName = 'Customer Validation';   
        Opty.Vertical_Market__c='Airports & Transportation';
        Opty.Edited__c = True;
        insert Opty;
        opps.add(Opty);
        
        
        //update opps;
        
        OpportunityContactRole opcr = new OpportunityContactRole();
        opcr.OpportunityId = Opty.id;
        opcr.ContactId = con.id;
        opcr.Role = 'Contract Engineer';
        insert opcr;
        
        /*OpportunityContactRole opcr1 = new OpportunityContactRole();
        opcr1.OpportunityId = Opty.id;
        opcr1.ContactId = con.id;
        opcr1.Role = 'Approver';
        insert opcr1;*/
        
        String pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry pbe = new PricebookEntry();
        pbe.Pricebook2Id = pricebookId;
        pbe.Product2Id = pd.id;
        pbe.UnitPrice = 50;
        //pbe.StandardPrice = 10000;
        pbe.IsActive = true;
        pbe.UseStandardPrice = false;
        insert pbe;

        OpportunityLineItem oplt = new OpportunityLineItem();
        oplt.Product2Id= pd.id;
        oplt.OpportunityId = Opty.id;
        oplt.Quantity = 2.0;
        oplt.TotalPrice = 1000;
        oplt.PricebookEntryId =pbe.id;
        insert oplt;
        
        OpportunityLineItem oplt1 = new OpportunityLineItem();
        oplt1.Product2Id= pd.id;
        oplt1.OpportunityId = Opty.id;
        oplt1.Quantity = 3.0;
        oplt1.TotalPrice = 600;
        oplt1.PricebookEntryId =pbe.id;
        insert oplt1;
        
        Bidder__c bdr = new Bidder__c();
        bdr.Apparent_Winning_Bidder__c = false;
        bdr.Opportunity__c = opty.id;
        bdr.OwnerId = u.id;
        bdr.Inactive__c = false;
       // insert bdr;
        
       /* Bidder__c bdr1 = new Bidder__c();
        bdr1.Apparent_Winning_Bidder__c = false;
        bdr1.Opportunity__c = opty.id;
       // bdr1.Bidder_Name__c = acct.id;
       // bdr1.OwnerId = u.id;
        bdr1.Inactive__c = false;
        insert bdr1;*/
        
        Test.startTest();
        OpportunityRollupsBatch orb = new OpportunityRollupsBatch();
        orb.execute(null, opps);
        Database.executeBatch(orb);
        Test.stopTest();
    }
    
}