src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Account has been inactivated</description>
        <inlineHelpText>The Account/Company no longer exists (closed doors, bankruptcy, etc.)</inlineHelpText>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>United States</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Åland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia, Plurinational State of</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <label>State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Acklins</fullName>
                </value>
                <value>
                    <fullName>Acre</fullName>
                </value>
                <value>
                    <fullName>Aguascalientes</fullName>
                </value>
                <value>
                    <fullName>Ahuachapán</fullName>
                </value>
                <value>
                    <fullName>Aisén del General Carlos Ibáñez del Campo</fullName>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alagoas</fullName>
                </value>
                <value>
                    <fullName>Alajuela</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Alberta</fullName>
                </value>
                <value>
                    <fullName>Alta Verapaz</fullName>
                </value>
                <value>
                    <fullName>Alto Paraguay</fullName>
                </value>
                <value>
                    <fullName>Alto Paraná</fullName>
                </value>
                <value>
                    <fullName>Amambay</fullName>
                </value>
                <value>
                    <fullName>Amapá</fullName>
                </value>
                <value>
                    <fullName>Amazonas</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Ancash</fullName>
                </value>
                <value>
                    <fullName>Andaman and Nicobar Islands</fullName>
                </value>
                <value>
                    <fullName>Andhra Pradesh</fullName>
                </value>
                <value>
                    <fullName>Anhui</fullName>
                </value>
                <value>
                    <fullName>Anse la Raye</fullName>
                </value>
                <value>
                    <fullName>Antioquia</fullName>
                </value>
                <value>
                    <fullName>Antofagasta</fullName>
                </value>
                <value>
                    <fullName>Anzoátegui</fullName>
                </value>
                <value>
                    <fullName>Apure</fullName>
                </value>
                <value>
                    <fullName>Apurímac</fullName>
                </value>
                <value>
                    <fullName>Aragua</fullName>
                </value>
                <value>
                    <fullName>Arauca</fullName>
                </value>
                <value>
                    <fullName>Araucanía</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <description>This record type if for all records created by SFDC Users.</description>
        <label>Address</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Bidder__c.object
<CustomObject>
    <description>DMNY</description>
    <fields>
        <fullName>Apparent_Winning_Bidder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Apparent Winning Bidder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bidder_Outcome_Feedback__c</fullName>
        <label>Bidder Outcome Feedback</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FSE hasn’t followed up yet</fullName>
                    <default>true</default>
                    <label>FSE hasn’t followed up yet</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Bidder is not the winning bidder.</fullName>
                </value>
                <value>
                    <fullName>Bidder is the apparent winning bidder.</fullName>
                </value>
                <value>
                    <fullName>A different bidder is the apparent winning bidder.</fullName>
                </value>
                <value>
                    <fullName>Bidder has abandoned this project.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates bidder not successful or no longer active.</description>
        <inlineHelpText>Indicates bidder not successful or no longer active.</inlineHelpText>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Bidders</relationshipLabel>
        <relationshipName>Bidders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>of_Follow_up_Attempts__c</fullName>
        <defaultValue>0</defaultValue>
        <label># of Follow-up Attempts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Bidder</label>
    <nameField>
        <label>Bidder Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bidders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Vertical_Market__c</fullName>
        <description>Project Industry Types (versus account industry types).  If the Account is a Facilities Management Company the Vertical (Industry) for the opportunity could be different.</description>
        <inlineHelpText>Opportunity Industry type - may be different then Account</inlineHelpText>
        <label>Vertical Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Airports &amp; Transportation</fullName>
                </value>
                <value>
                    <fullName>Assembly, Arenas, and Recreation</fullName>
                </value>
                <value>
                    <fullName>Education K-12</fullName>
                </value>
                <value>
                    <fullName>Financial / Office Space</fullName>
                </value>
                <value>
                    <fullName>Government Buildings</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>Higher Education</fullName>
                </value>
                <value>
                    <fullName>Life Sciences, Pharm, Biotech</fullName>
                </value>
                <value>
                    <fullName>Lodging / Hotels</fullName>
                </value>
                <value>
                    <fullName>Manufacturing Facilities and Warehouses</fullName>
                </value>
                <value>
                    <fullName>Mining</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous Nonresidential Buildings</fullName>
                </value>
                <value>
                    <fullName>Multi-family Residential</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Religious Buildings</fullName>
                </value>
                <value>
                    <fullName>Stock Replenishment</fullName>
                </value>
                <value>
                    <fullName>Stores and Restaurants / Retail</fullName>
                </value>
                <value>
                    <fullName>Telecommunications and Data Centers</fullName>
                </value>
                <value>
                    <fullName>Warehouses (excl. Manufacturer Owned)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Won_Lost_Reason__c</fullName>
        <description>A value indicating the main reason a job was won or lost.</description>
        <inlineHelpText>A value indicating the main reason a job was won or lost.</inlineHelpText>
        <label>Won/Lost Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Credit Terms</fullName>
                </value>
                <value>
                    <fullName>Daikin Contractor on the job</fullName>
                </value>
                <value>
                    <fullName>Delivery Time</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Lumped Out - Controls</fullName>
                </value>
                <value>
                    <fullName>Lumped Out - Equipment</fullName>
                </value>
                <value>
                    <fullName>Nat&apos;l Account Relationship</fullName>
                </value>
                <value>
                    <fullName>Negotiated</fullName>
                </value>
                <value>
                    <fullName>No Callback</fullName>
                </value>
                <value>
                    <fullName>Non-Daikin Contractor on the job</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Preference for stick-site built</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Project was canceled</fullName>
                </value>
                <value>
                    <fullName>Specs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/UpdateBidderTestClass.cls
@istest
public class UpdateBidderTestClass {
    
    static testMethod void updateBidderValues(){
        
       
        AVA_SFCORE__TaxNowSetting__c ts1 = new AVA_SFCORE__TaxNowSetting__c(); 
        ts1.AVA_SFCORE__Active_Setting__c = true; 
        ts1.Name='Test Account';
        insert ts1;
        Account a = new Account(Name = 'Test');
        a.BillingState = 'California';
        a.BillingPostalCode = '90210';
        a.BillingCountry = 'United States';
        insert a; 
  
        Opportunity opp = New Opportunity();
        opp.Name = 'test Bidder Opportunity';
        opp.StageName ='Closed Won';
        opp.Vertical_Market__c = 'Mining';
        opp.Probability = 75;
        opp.AccountId = a.Id;
        opp.Won_Lost_Reason__c='Credit Terms';
        opp.CloseDate=system.today();
        insert opp;
         Bidder__c Bi = New Bidder__c();
        bi.Note__c = 'Test Bidder Note';
        Bi.Apparent_Winning_Bidder__c =TRUE;
        Bi.of_Follow_up_Attempts__c=1;
        Bi.Bidder_Outcome_Feedback__c='';
        bi.Inactive__c=false;
        Bi.CurrencyIsoCode='';
        Bi.Opportunity__c = opp.id;
        insert Bi;
    }
    static testMethod void updatevalues(){
       
        AVA_SFCORE__TaxNowSetting__c ts2 = new AVA_SFCORE__TaxNowSetting__c(); 
        ts2.AVA_SFCORE__Active_Setting__c = true; 
        ts2.Name='Test Account2';
        upsert ts2;
        Account a = new Account(Name = 'Test');
        a.BillingState = 'Nevada';
        a.BillingCountry = 'United States';
        upsert a;
        Opportunity opp = New Opportunity();
        opp.Name = 'test1';
        opp.StageName ='Closed Won';
        opp.Vertical_Market__c = 'Mining';
        opp.Probability = 50;
        opp.AccountId = a.Id;
        opp.Won_Lost_Reason__c='Credit Terms';
        opp.CloseDate=system.today();
        upsert opp;
         Bidder__c B = New Bidder__c();
        B.Apparent_Winning_Bidder__c =TRUE;
        B.of_Follow_up_Attempts__c=1;
        B.Bidder_Outcome_Feedback__c='';
        B.CurrencyIsoCode='';
        B.Opportunity__c = opp.id;
        b.Inactive__c=false;
        insert B;
    }
   static testMethod void deleteValues()
   {   
      UpdateBidderTestClass.updateBidderValues();
     Opportunity delacc = [select id from Opportunity where Name = 'test Bidder Opportunity'];
     delete delacc; 
       Bidder__c delbid = [select id from Bidder__c where Note__c = 'Test Bidder Note'];
       delete delbid;
       
     
    }      
   /* void testdelete()
    {
          AVA_SFCORE__TaxNowSetting__c ts3 = new AVA_SFCORE__TaxNowSetting__c(); 
       ts3.AVA_SFCORE__Active_Setting__c = false; 
       ts3.Name='Test Account2';
       insert ts3;
       //delete ts3;
       Address__c address = new Address__C(Address_Line_1__c = 'line1',  City__c = 'City', Country__c = 'United States', State_Province__c = 'Minnesota');
       address.Postal_Code__c = '518000';
       insert address;
       //delete address;
       Account acct = new Account(Name = 'Test');
       acct.BillingState = 'Nevada';
       acct.BillingCountry = 'United States';
       insert acct;
       delete acct;
      
       Opportunity opp1 = New Opportunity();
       opp1.Name = 'test1';
       opp1.StageName ='Closed Won';
       opp1.Vertical_Market__c = 'Mining';
       opp1.Probability = 50;
       opp1.AccountId = acct.Id;
       opp1.Won_Lost_Reason__c='Credit Terms';
       opp1.CloseDate=system.today();
       insert opp1;
       delete opp1;
       Bidder__c Bidder = New Bidder__c();
       Bidder.Apparent_Winning_Bidder__c =TRUE;
       Bidder.of_Follow_up_Attempts__c=1;
       Bidder.Bidder_Outcome_Feedback__c='';
       Bidder.CurrencyIsoCode='';
       Bidder.Inactive__c=false;
       insert Bidder;
       delete Bidder;
       
    }*/
    
}