src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>Originally added for to capture Customer Bill To information from the Data Warehouse (Installed Base) for TRC Integration.</description>
        <label>Email</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Factory_Pricing_Authorization__c.object
<CustomObject>
    <fields>
        <fullName>Application_Engineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Engineer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>FPAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the appropriate Rep</inlineHelpText>
        <label>Sales Person</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Office__c</field>
                <operation>equals</operation>
                <valueField>FPA_Persona__c.Office__r.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>FPA_Persona__c</referenceTo>
        <relationshipLabel>FPAs</relationshipLabel>
        <relationshipName>FPAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FPA</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FPAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FPA_Link__c.object
<CustomObject>
    <fields>
        <fullName>FPA__c</fullName>
        <label>FPA</label>
        <referenceTo>Factory_Pricing_Authorization__c</referenceTo>
        <relationshipLabel>Unit Details</relationshipLabel>
        <relationshipName>Related_SFO</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SFO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFO</label>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipName>Related_SFO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Person__c</fullName>
        <formula>FPA__r.Sales_Person__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Person</label>
        <type>Text</type>
    </fields>
    <label>Unit Detail</label>
    <nameField>
        <label>Unit Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FPA_Persona__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Sales Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Persona</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Related_SFO__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Name__c</fullName>
        <formula>SFO__r.Option_Parent__r.Name</formula>
        <label>Parent Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFO</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Special_Feature_Option__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Read Only</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipLabel>Related SFO</relationshipLabel>
        <relationshipName>Related_SFO1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Detail</label>
        <referenceTo>FPA_Link__c</referenceTo>
        <relationshipLabel>Related SFO</relationshipLabel>
        <relationshipName>Related_SFO</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Related SFO</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Related SFO  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related SFO</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SendEmailFPARelatedAttachmentsController.cls
public class SendEmailFPARelatedAttachmentsController {
    
    public String fpaID {get; set;}
    public String zipFileName {get; set;}
    public List<string> ContentDocumentIds {get; set;}
    /**
*	Query for the Account using the parameter in the query string
*	Set the filename for the ZIP file
**/
    public SendEmailFPARelatedAttachmentsController(ApexPages.StandardController controller) {
        
        this.fpaID = ApexPages.currentPage().getParameters().get('id');
        Factory_Pricing_Authorization__c fpa = [Select 
                                                id, 
                                                Name, 
                                                Application_Engineer__c, 
                                                (Select id, 
                                                 SFO__c from Related_SFO__r)
                                                from 
                                                Factory_Pricing_Authorization__c 
                                                where Id=:fpaID];
        // Set the zip's filename to be formatted like "AccountName-2016-3-10.zip"
        this.zipFileName = fpa.Name + '-';
        Date d = Date.today();
        
        this.zipFileName += d.month() + '-' + d.day() +'-'+ d.year() + '.zip';
    }
    
    /**
*	Used for manually throwing errors back to the Visualforce page
*	Usage: throw new ApplicationException('This is the error message');
**/
    public class ApplicationException extends Exception {}
    
    /**
*	Primary function that initiates XML document creation.
*	Data is grouped by Opportunity into individual XML documents,
*	and within each file the Opportunity's data is displayed.
**/
    @RemoteAction
    public static Map<String, String> getXMLFiles(String fpaID) {
        
        List<String> parentIds = new List<String>();
        //List<String> UnitDetailIds = new List<String>();
        
        system.debug('test getXMLFiles');
        // Get the FPA and related SFOs Ids
        
        
        for(Factory_Pricing_Authorization__c fpa : [Select id, 
                                                    Name, 
                                                    (Select id, SFO__c from Related_SFO__r) 
                                                    from
                                                    Factory_Pricing_Authorization__c 
                                                    where Id=:fpaID])
        {            
            parentIds.add(fpa.Id);
            for(FPA_Link__c fpaLink : fpa.Related_SFO__r)
            {
                parentIds.add(fpaLink.SFO__c);
            }
        }
        system.debug('parentIds--'+parentIds);
        
        /*
for(Factory_Pricing_Authorization__c fpa : [Select Id, Name, (Select id, SFO__c from Related_SFO__r) from Factory_Pricing_Authorization__c 
where Id =: fpaID])
{            
parentIds.add(fpa.Id);
for(FPA_Link__c fpaLink : fpa.Related_SFO__r)
{
parentIds.add(fpaLink.SFO__c);
//UnitDetailIds.add(fpaLink.id);

}
//System.debug('UnitDetailIds :: '+UnitDetailIds);
//System.debug('UnitDetailIds Size:: '+UnitDetailIds.size());
/*for(Related_SFO__c	r: [SELECT Id, Name, SFO__c, Unit_Detail__c, Parent_Name__c FROM Related_SFO__c where Unit_Detail__c IN :UnitDetailIds]){
parentIds.add(r.SFO__c);
}
}*/
        system.debug('parentIds--'+parentIds);
        system.debug('parentIds-- size'+parentIds.size());
        
        // Query for all Attachments of FPA and related SFOs
        List<Attachment> listAtt = [Select id, Name, Body from Attachment where parentId IN: parentIds];
        List<String> ContentDocumentIds = new List<String>();
        for(ContentDocumentLink contentDocList : [SELECT Id, 
                                                  LinkedEntityId,
                                                  ContentDocumentId 
                                                  FROM ContentDocumentLink 
                                                  where LinkedEntityId IN: parentIds])
        {
            ContentDocumentIds.add(contentDocList.ContentDocumentId);
        }
        System.debug('ContentDocumentIds ::'+ContentDocumentIds);
        List<ContentVersion> contentList = new List<ContentVersion>();
        if(ContentDocumentIds.size() > 0)
        {
            for(ContentVersion contVersionList : [SELECT VersionData,Title,
                                                  filetype FROM ContentVersion WHERE 
                                                  ContentDocumentId IN : ContentDocumentIds 
                                                  AND IsLatest = true])
            {
                Attachment attObj = new Attachment();
                attObj.Name = contVersionList.Title+'.'+contVersionList.FileType;
                attObj.Body = contVersionList.VersionData;
                attObj.ContentType = contVersionList.FileType;
                listAtt.add(attObj);
                contentList.add(contVersionList);
            }
        }
        
        // Setup map to contain all results from this method. Will contain the generated XML files and a list of Opportunities that were used in the process.
        Map<String, String> resultsData = new Map<String, String>();
        
        // Create the XML body and filename for each Opportunity
        for(Attachment att : listAtt)
        {
            resultsData.put(att.Name, EncodingUtil.base64Encode(att.Body));
        }
        
        return resultsData;
    }
    
    /**
*	Remote Action method to save the ZIP file as an attachment
*	Set the ParentId to connect it to a specific record (the Account in this case)
**/
    @RemoteAction
    public static String saveData(String recordId, String filename, String data) {
        try {
            Attachment att = new Attachment(
                Name = filename,
                Body = EncodingUtil.base64Decode(data),
                ParentId = recordId
            );
            
            System.debug('data :: '+data);
            System.debug('Body :: '+EncodingUtil.base64Decode(data));
            String yourFiles = 'Lets assume this is your binary string of the files';
            
            if(data == null || data == ''){sendEmailMethod(null, recordId); return 'SUCCESS-';
            }
            else{
                ContentVersion conVer = new ContentVersion();
                conVer.ContentLocation = 'S'; // S specify this document is in SF, use E for external files
                conVer.PathOnClient = 'myZip.zip'; // The files name, extension is very important here which will help the file in preview.
                conVer.Title = filename; // Display name of the files
                conVer.VersionData = EncodingUtil.base64Decode(data); // converting your binary string to Blog
                insert conVer;
                
                sendEmailMethod(conVer.Id, recordId);
                
                System.debug('conVer :: '+conVer);
                return 'SUCCESS-'+conVer.Id;
            }
        } 
        catch(Exception e) {return e.getMessage();}
    }
    
    public static void sendEmailMethod(String conId, String fpaID){
        
        User u = [Select Id, Name, CompanyName From User WHERE Id =: UserInfo.getUserId()];
        EmailTemplate template = [Select Id, Name, Body From EmailTemplate WHERE DeveloperName =: 'FPA_External_Summary_Template'];
        Factory_Pricing_Authorization__c targetObjId = [SELECT Name, Id, OwnerId, Sales_Person__r.Email__c, 
                                                        Sales_Person__r.Name FROM Factory_Pricing_Authorization__c WHERE Id =: fpaID];
        List<Factory_Pricing_Authorization__c> fpaRecList = [SELECT Name, Id, Sales_Person__r.Email__c,
                                                             Application_Engineer__r.Email FROM Factory_Pricing_Authorization__c WHERE Id =: fpaID];
        
        List<String> toEmailAddresses = new List<String>();
        for(Factory_Pricing_Authorization__c fpaRec : fpaRecList)
        {
            toEmailAddresses.add(fpaRec.Application_Engineer__r.Email);
            System.debug('fpaRec.Application_Engineer__r.Email ::: '+fpaRec.Application_Engineer__r.Email);
        }
        System.debug('fpaID is :: '+fpaID);
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(toEmailAddresses);
        mail.setWhatId(targetObjId.Id);
        mail.setTemplateId(template.Id);
        mail.setTargetObjectId(u.Id);
        mail.setSaveAsActivity(false);
        List<Messaging.Emailfileattachment> fileAttachments = new List<Messaging.Emailfileattachment>();
        for (ContentVersion cversion : [SELECT Title, PathOnClient, 
                                        FileType, versiondata 
                                        FROM contentversion 
                                        WHERE Id =: conId]) 
        {
            blob WOCFbody = cversion.versiondata; 
            system.debug('body : '+WOCFbody+'-----------'+cversion.title); 
            Messaging.Emailfileattachment efa = new Messaging.Emailfileattachment();
            efa.setFileName(cversion.title+'.'+cversion.FileType);
            efa.setBody(WOCFbody); 
            fileAttachments.add(efa);
            System.debug('fileAttachments :: '+fileAttachments);
            mail.setFileAttachments(fileAttachments);
            System.debug('fileAttachments ::'+fileAttachments);
            System.debug('fileAttachments Size::'+fileAttachments.size());
            
        }
        System.debug('mail :: '+mail);
        //Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        Messaging.sendEmailResult[] results = Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        System.debug('Email Result :: '+results);
        
        if(results[0].success == true){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.CONFIRM,'Your Mail has been sent successsfully');
            ApexPages.addMessage(myMsg);
            System.debug('myMsg :: '+myMsg);
        }
    } 
    @RemoteAction
    public static String delData(String attId) {
        try {
            delete [Select id from Attachment where id =:attId];
            system.debug('Deleted');
            return 'SUCCESS';
        }
        
        catch(Exception e) {return e.getMessage();}
    }
}