src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>dcw_DistChannels.dc_active_flag</description>
        <inlineHelpText>dcw_DistChannels.dc_active_flag</inlineHelpText>
        <label>Active (DCW)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IE_ID__c</fullName>
        <externalId>true</externalId>
        <label>IE ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IE_Sync_Status__c</fullName>
        <label>IE Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IE_Updated_Date__c</fullName>
        <label>IE Updated Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Record_Usage__c</fullName>
        <description>Designed to show other systems that use the information in this record and for the purpose of preventing record deletion.</description>
        <label>Record Usage</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DCW</fullName>
                </value>
                <value>
                    <fullName>DW</fullName>
                </value>
                <value>
                    <fullName>IE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Warehouse_ID__c</fullName>
        <description>Originally added to capture Unique Keys from the Data Warehouse (Installed Base, McQuaySales, OrderHistory) or the SFDCIntegration staging DBA for the TRC Integration.</description>
        <externalId>true</externalId>
        <label>Warehouse ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>GWotGo__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Gateway on the Go 
Checked if the IE Gateway is a Gateway on the Go asset</description>
        <inlineHelpText>Gateway on the Go 
Checked if the IE Gateway is a Gateway on the Go asset</inlineHelpText>
        <label>GWotGo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IE_Asset__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate the record pertains to the IE integration. This is set on import of record from Daikin IE Back Office database.</description>
        <inlineHelpText>Flag to indicate the record pertains to the IE integration. This is set on import of record from Daikin IE Back Office database.</inlineHelpText>
        <label>IE Asset</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IE_ID__c</fullName>
        <externalId>true</externalId>
        <label>IE ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IE_Sync_Status__c</fullName>
        <description>Status that gets set when attributes on the record are updated and therefore needs to be sent to the IE system.</description>
        <inlineHelpText>Pending = Record needs to be sent to the IE system. 
Processed = Record was successfully received by IE system. 
Error = Record was not successfully received by IE system.</inlineHelpText>
        <label>IE Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IE_Updated_Date__c</fullName>
        <description>IE system date for when the record was last updated in the IE database.</description>
        <inlineHelpText>IE system date for when the record was last updated in the IE database.</inlineHelpText>
        <label>IE Updated Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Parent_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Equipment that this Asset is controlling or tied to.</inlineHelpText>
        <label>Parent Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Related Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Record_Usage__c</fullName>
        <description>Designed to show other systems that use the information in this record and for the purpose of preventing record deletion.</description>
        <label>Record Usage</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DW</fullName>
                </value>
                <value>
                    <fullName>IE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SIM_Card_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to determine if the SIM card is active or not.</description>
        <label>SIM Card Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SIM_Card_ICCID__c</fullName>
        <description>Only applicable for IE Assets. This is for the IE hardware on the asset.</description>
        <inlineHelpText>Only applicable for IE Assets. This is for the IE hardware on the asset.</inlineHelpText>
        <label>SIM Card ICCID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Startup_Date__c</fullName>
        <description>Startup Date</description>
        <inlineHelpText>Startup Date</inlineHelpText>
        <label>Startup Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Warehouse_ID__c</fullName>
        <description>src_dw_fact_shipment.dw_Shipments_Key</description>
        <externalId>true</externalId>
        <inlineHelpText>src_dw_fact_shipment.dw_Shipments_Key</inlineHelpText>
        <label>Warehouse ID</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Warranty_Items__c</fullName>
        <label>Warranty Items</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>IE_ID__c</fullName>
        <description>IE database unique record ID.</description>
        <externalId>true</externalId>
        <inlineHelpText>IE database unique record ID.</inlineHelpText>
        <label>IE ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IE_Sync_Status__c</fullName>
        <description>Status that gets set when attributes on the record are updated and therefore needs to be sent to the IE system.</description>
        <inlineHelpText>Pending =  Record needs to be sent to the IE system. 
Processed = Record was successfully received by IE system.
Error = Record was not successfully received by IE system.</inlineHelpText>
        <label>IE Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IE_Updated_Date__c</fullName>
        <description>IE system date for when the record was last updated in the IE database.</description>
        <inlineHelpText>IE system date for when the record was last updated in the IE database.</inlineHelpText>
        <label>IE Updated Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Record_Usage__c</fullName>
        <description>Designed to show other systems that use the information in this record and for the purpose of preventing record deletion.</description>
        <label>Record Usage</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DCW</fullName>
                </value>
                <value>
                    <fullName>DW</fullName>
                </value>
                <value>
                    <fullName>IE</fullName>
                </value>
                <value>
                    <fullName>MKTG Subscription</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Warehouse_ID__c</fullName>
        <description>Originally added to capture Unique Keys from the SFDCIntegration staging DBA for the TRC Integration.</description>
        <label>Warehouse ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact_Subscription__c.object
<CustomObject>
    <description>Junction object to tie a contact to an IE Subscription, the Unit for the Subscription and one IE role for the specific Unit &amp; Subscription.  If the contact has more than one IE role for a given Unit/Subscription, then another Contact Subscription record will be created for that Role/Unit combination.</description>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Intelligent Equipment Contacts</relationshipLabel>
        <relationshipName>Contact_Subscriptions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Contact Subscription</label>
    <nameField>
        <displayFormat>CS-{000000000}</displayFormat>
        <label>Contact Subscription ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>IE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Must check if Intelligent Equipment Gateway and Energy Management Model products so that resulting Assets are set as Record Usage = IE which prevents the Asset from being deleted. ADMIN ONLY field.</description>
        <inlineHelpText>Must check if Intelligent Equipment Gateway or Energy Management Model product so that resulting Gateway and EMM Assets are set as Record Usage = IE which prevents the Asset from being deleted.</inlineHelpText>
        <label>IE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Warehouse_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>External ID. DW_McQuayDataWarehouse.dbo.DW_DIM_EQUIPMENT_PRODUCT.DEP_EQUIPMENT_PRODUCT_KEY</inlineHelpText>
        <label>Warehouse ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Object to identify and tie IE Subscriptions, to their appropriate Unit (Asset), Buyer (Account), and Users (Contacts).</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Pass this attribute to IE as part of 1.2 release.  Removes need to change the Subscription End Date from the contract term end date if it&apos;s necessary to remove access to Unit in IE prior to End Date.</description>
        <inlineHelpText>If checked, Subscription has started and is currently in effect.  Uncheck if Subscription should be made inactive for any reason. (e.g. Contract Expired, Non-payment, Legal)</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Intelligent Equipment Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IE_ID__c</fullName>
        <description>IE database unique record ID.</description>
        <externalId>true</externalId>
        <inlineHelpText>IE database unique record ID.</inlineHelpText>
        <label>IE ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IE_Sync_Status__c</fullName>
        <description>Status that gets set when attributes on the record are updated and therefore needs to be sent to the IE system.</description>
        <inlineHelpText>Pending = Record needs to be sent to the IE system. 
Processed = Record was successfully received by IE system. 
Error = Record was not successfully received by IE system.</inlineHelpText>
        <label>IE Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IE_Updated_Date__c</fullName>
        <description>IE system date for when the record was last updated in the IE database.</description>
        <inlineHelpText>IE system date for when the record was last updated in the IE database.</inlineHelpText>
        <label>IE Updated Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Record_Usage__c</fullName>
        <description>Designed to show other systems that use the information in this record and for the purpose of preventing record deletion.</description>
        <label>Record Usage</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>S-{000000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/AssetTriggerHandler.cls
public without sharing class AssetTriggerHandler {
  /*********************************************************************
  * NOTE: The following set of Test Classes will test this trigger code.
  * These would all need to be run to get > 75% code coverage.
  * 
  * AssetTriggerHandler_Test
  * Batch_IE_DeactPrevMonthExpSubAndSta_Test
  * ResetGWotGoAsset_Test
  * WarrantyOracleHandlerTest
  **********************************************************************/
    
    public static void onBeforeUpdate(list<Asset> newList, map<Id, Asset> oldMap)
    {
        setIeSyncStatus(newList, oldMap);
    }
    
    public static void onAfterUpdate(map<Id, Asset> newMap, map<Id, Asset> oldMap)
    {
        processGatewayAsset(newMap, oldMap);
        //processSubscriptions(newMap,oldMap);
        //doIntelSync(newMap, oldMap);

        //Synching Oracle Startup Dates
        sendStartupDates(newMap, oldMap);
    }
    
    public static void onBeforeInsert(list<Asset> newList)
    {
        setIeSyncStatus(newList, null);
    }
    
    public static void onAfterInsert(map<Id, Asset> newMap)
    {
        processGatewayAsset(newMap, null);
        //processSubscriptions(newMap, null);
        sendStartupDates(newMap, null);
    } 
    
    public static void onBeforeDelete(map<Id, Asset> oldMap)
    {
        for(Asset a : oldMap.values())
        {
            if( a.Record_Usage__c != null)
                a.addError('This record cannot be deleted because it is integrated with other systems or tied to other critical information within Salesforce.');
                
        }
        
    }
    
    private static void sendStartupDates(map<Id, Asset> newMap, map<Id, Asset> oldMap){
        //Synching Oracle Startup Dates
        Set<Id> l = new Set<Id>();
        for(Asset a : newMap.values()){
            if(WarrantyOracleHandler.settingWarrantyInfo || a.Warehouse_ID__c == null || a.Warehouse_ID__c == ''){
                //Do Nothing...
            } else if(a.Startup_Date__c == null && (a.Warranty_Items__c==null || (oldMap != null && a.Startup_Date__c != oldMap.get(a.Id).Startup_Date__c))){
                if(!System.isFuture() && !System.isBatch())
                    WarrantyOracleHandler.getWarrantyInfo(a.Id);
            } else if(a.Startup_Date__c != null && oldMap != null && a.Startup_Date__c != oldMap.get(a.Id).Startup_Date__c){
                l.add(a.Id);
            }
        }
        if(l.size()>0 && !System.isFuture() && !System.isBatch())
            WarrantyOracleHandler.sendStartupDateList(l);
    }

    
    public static void setIeSyncStatus(list<Asset> newList, map<Id, Asset> oldMap)
    {
        system.debug(':::::::setIeSyncStatus newList:::::: ' + newList);
        system.debug(':::::::setIeSyncStatus oldMap:::::: ' + oldMap);

        set<Id> productIds = new set<Id>();
        map<Id, Boolean> productIsIeMap = new map<Id, Boolean>();
        for(Asset a : newList)
        {
            if(oldMap != null && oldMap.get(a.Id).IE_Updated_Date__c != a.IE_Updated_Date__c
               && a.IE_Updated_Date__c != null
               && oldMap.get(a.Id).IE_Updated_Date__c < oldMap.get(a.Id).LastModifiedDate){a.AddError('Salesforce Last Modified Date is more Recent then IE Updates');
            }
            
            productIds.add(a.Product2Id);
        }
        
        for(Product2 p : [Select Id, IE__c from Product2 where Id in :productIds])
        {
            productIsIeMap.put(p.Id, p.IE__c);
        }
        
        if(TriggerUtility.limitIeServiceIntegration || TriggerUtility.limitIntegrationBatch){return;
        } 
        
        for(Asset a : newList)
        {
            system.debug(':::::::setIeSyncStatus asset:::::: ' + a);

            if(a.IE_Asset__c && a.IE_Sync_Status__c != 'Pending' && ((oldMap == null || oldMap.get(A.Id).IE_Sync_Status__c != 'Pending')|| productIsIeMap.get(a.Product2Id)) )
            {
                if ((a.Name != 'Dummy GWotGo Unit Asset') && (a.Name != 'Holding GWotGo Unit Asset')) {
                    system.debug(':::::::setIeSyncStatus set status to Pending::::::');

                    a.IE_Sync_Status__c = 'Pending';
                }
            }
            
            if(a.IE_Asset__c && (oldMap==null || oldMap.get(a.Id).IE_Asset__c != true))
            {
                if(a.Record_Usage__c != null && !a.Record_Usage__c.contains('IE')){a.Record_Usage__c +=  ';IE';
				} else if(a.Record_Usage__c == null) {a.Record_Usage__c =  'IE';
                }
            }
        }
        
    }
    

    public static void processGatewayAsset(map<Id, Asset> newMap, map<Id, Asset> oldMap)
    {
        /*
          - Check for existing gateway asset on current gateway asset's parent equipment asset.
		  - If an existing one is found, set its status to obsolete.
          - ** Flag the Unit Asset as an IE Asset.

		  (A "set" cannot have duplicates, this is handled automatically)
        */
        
        system.debug(':::::::processGatewayAsset newMap:::::: ' + newMap);
        system.debug(':::::::processGatewayAsset oldMap:::::: ' + oldMap);

        if(TriggerUtility.limitIeServiceIntegration || TriggerUtility.limitIntegrationBatch){return;
        } 
        
        set<Id> newIdSet = new set<Id>();
        set<Id> newObsGWIdSet = new set<Id>();
        for(Asset a : newMap.values())
        {
            if(a.Status != 'Obsolete')
                newIdSet.add(a.Id);
            else if (a.Status == 'Obsolete' && (a.Name == 'Intelligent Equipment Gateway' || String.isNotEmpty(a.SIM_Card_ICCID__c))){newObsGWIdSet.add(a.Id);
			}
        }
        system.debug(':::::::processGatewayAsset newIdSet :::::: ' + newIdSet);
        system.debug(':::::::processGatewayAsset newObsGWIdSet :::::: ' + newObsGWIdSet);


        set<Id> parentAssetIdsForNewObsGW = new set<Id>();
        // collect parent assets for new obsolete GWs
        for(Asset a : [Select Id, Parent_Asset__c 
                         from Asset 
                        where Id in :newObsGWIdSet 
                          and GWotGo__c != true])  // ignore GWotGo assets
        {
            if(a.Parent_Asset__c != null)
                parentAssetIdsForNewObsGW.add(a.Parent_Asset__c);
        }


        set<Id> parentAssetIds = new set<Id>();
		set<Id> parentAssetIdsForReplacedGW = new set<Id>();
        list<Asset> obsoleteAssets = new list<Asset>();
        list<Asset> parentAssets = new list<Asset>();
        
        //collect the IE Gateway Assets
        for(Asset a : [Select Id, Parent_Asset__c 
                         from Asset 
                        where Id in :newIdSet 
                          and Product2.Product_Group__c = 'IE Gateway' 
                          and GWotGo__c != true  // ignore GWotGo assets
                          and Status != 'Obsolete'])
        {
            if(a.Parent_Asset__c != null)
                parentAssetIds.add(a.Parent_Asset__c);
        }

            
        //pull the parent Assets' existing gateway assets that are not the current gateway assets and mark them as Obsolete
        if(parentAssetIds.size() > 0)
        {
            for(Asset a : [Select Id, Parent_Asset__c
                             from Asset 
                            where Parent_Asset__c in :parentAssetIds 
                              and Parent_Asset__c != null
                              and (NOT( Id in :newIdSet) )
                              and Status != 'Obsolete'
                              and GWotGo__c != true  // never set GWotGo assets to Obsolete
                              and Product2.Product_Group__c = 'IE Gateway'])    
            {
                    a.Status = 'Obsolete';
                    obsoleteAssets.add(a);
					parentAssetIdsForReplacedGW.add(a.Parent_Asset__c);
					system.debug('processGatewayAsset: Setting obsolete GW, Id=' + a.Id + ', Parent Asset Id=' + a.Parent_Asset__c);
            }
        }
        
        
        set<Id> EMMparentAssetIds = new set<Id>();
        //collect the IE EMM Assets
        for(Asset a : [Select Id, Parent_Asset__c 
                         from Asset 
                        where Id in :newIdSet 
                          and Product2.Product_Group__c = 'IE EMM' 
                          and Status != 'Obsolete'])
        {
            EMMparentAssetIds.add(a.Parent_Asset__c);
        }
            
        //pull the parent Assets' existing IE EMM assets that are not the current IE EMM assets and mark them as Obsolete
        if(EMMparentAssetIds.size() > 0)
        {
            for(Asset a : [Select Id,  Parent_Asset__c
                             from Asset 
                            where Parent_Asset__c in :EMMparentAssetIds 
                              and Parent_Asset__c != null
                              and (NOT( Id in :newIdSet) )
                              and Status != 'Obsolete'
                              and Product2.Product_Group__c = 'IE EMM'])    
            {
                    a.Status = 'Obsolete';
                    obsoleteAssets.add(a);
                    parentAssetIds.add(a.Parent_Asset__c);
            }
        }
        
		system.debug(':::::::processGatewayAsset parentAssetIds :::::: ' + parentAssetIds);

        
        //pull the parent Assets so their IE flag can be set
        if(parentAssetIds.size() > 0)
        {
            for(Asset a : [Select Id 
                             from Asset 
                            where Id in :parentAssetIds 
                              and (IE_Asset__c = false or IE_Sync_Status__c != 'Pending')]) 
            {
                    system.debug(':::::::processGatewayAsset set status to Pending for asset :::::: ' + a);

                    a.IE_Asset__c = true;
                    a.IE_Sync_Status__c = 'Pending';
                    parentAssets.add(a);
            }
        }


        //Update fields for the parent Assets who have a new obsolete GW.
        //Only do the update if there is no other GW associated with the asset that is not obsolete.
        //Set the IE_Asset__c field to false since it is not an ie asset anymore on the ie side
        //Clear out the IE_ID__c field since it is not an ie asset anymore on the ie side
        if(parentAssetIdsForNewObsGW.size() > 0)
        {
            for(Asset a : [Select Id, IE_Asset__c, IE_ID__c,
                            (Select Id, Name, SerialNumber, SIM_Card_Active__c, Product2.Name, SIM_Card_ICCID__c, Device_ID__c, MAC_Address__c, GWotGo__c From Assets__r where  Product2.Product_Group__c = 'IE Gateway' and Status != 'Obsolete' and (NOT( Id in :newObsGWIdSet)))
                            from Asset 
                            where Id in :parentAssetIdsForNewObsGW]) 
            {
                    List<Asset> relatedAssets = a.Assets__r;
                    if (relatedAssets.isEmpty())
                    {
                        // Only perform the update if the unit asset doesn't have any other valid GW associated with it
                        system.debug(':::::::processGatewayAsset update parent asset for new obsolete GW :::::: ' + a);

                        a.IE_Asset__c = false;
                        a.IE_ID__c = null;
                        a.IE_Sync_Status__c = 'Processed';
                        parentAssets.add(a);
                    }
            }
        }


        //*** Collect the IE GWotGo Assets and their Parent unit and process them ***
        list<Asset> parentAssetsForGWotGo = new list<Asset>();
        for(Asset a : [Select Id, Parent_Asset__c 
                         from Asset 
                        where Id in :newIdSet 
                          //and Product2.Product_Group__c = 'IE Gateway' 
                          and GWotGo__c = true 
                          and Status != 'Obsolete'])
        {
            if (a.Parent_Asset__c != null) {
                Asset unitAsset = [SELECT Id, Name, IE_Sync_Status__c from Asset Where Id = :a.Parent_Asset__c];

                if ((unitAsset.Name != 'Dummy GWotGo Unit Asset') && (unitAsset.Name != 'Holding GWotGo Unit Asset')) {
                    if (oldMap == null || (a.Parent_Asset__c != oldMap.get(a.Id).Parent_Asset__c)) {
                        // This unit asset is associated with a GWotGo asset that just moved to it from another unit from a Reset operation
                        // Set status to 'Processed' so the hourly IE batch job ignores it
                        system.debug(':::::::processGatewayAsset set status to Processed for unit asset for GWotGo :::::: ' + unitAsset);
                        unitAsset.IE_Sync_Status__c = 'Processed';
                    }
                    else {
                        system.debug(':::::::processGatewayAsset set status to Pending for unit asset for GWotGo :::::: ' + unitAsset);
                        unitAsset.IE_Sync_Status__c = 'Pending';
                    }
                }
                else {
                    system.debug(':::::::processGatewayAsset set status to Processed for Dummy/Holding unit asset for GWotGo :::::: ' + unitAsset);
                    unitAsset.IE_Sync_Status__c = 'Processed';
                }

                parentAssetsForGWotGo.add(unitAsset);
            }
        }



		// Reprocess the subscriptions for the GW replacement
		system.debug(':::::::processGatewayAsset parentAssetIdsForReplacedGW :::::: ' + parentAssetIdsForReplacedGW);
		if(parentAssetIdsForReplacedGW.size() > 0)
		reprocessSubscriptionsForGWReplacement(parentAssetIdsForReplacedGW);

        //update the obsolete assets
		system.debug(':::::::processGatewayAsset obsoleteAssets :::::: ' + obsoleteAssets);
        if(obsoleteAssets.size() > 0)
            update obsoleteAssets;
            
        //update the parent assets for non-GWotGo
		system.debug(':::::::processGatewayAsset parentAssets :::::: ' + parentAssets);
        if(parentAssets.size() > 0)
            update parentAssets;
        
        //update the parent assets for GWotGo
		system.debug(':::::::processGatewayAsset parentAssetsForGWotGo :::::: ' + parentAssetsForGWotGo);
        if(parentAssetsForGWotGo.size() > 0)
            update parentAssetsForGWotGo;

    }


	private static void reprocessSubscriptionsForGWReplacement(set<Id> unitAssetIdSet)
	{
		list<Subscription__c> existingSubscriptionList = new list<Subscription__c>();

		for(Subscription__c s : [Select Id, TriggerInvokedByAPI__c
                                 from Subscription__c
                                 where Asset__c in :unitAssetIdSet])
        {
            s.TriggerInvokedByAPI__c = true;
            existingSubscriptionList.add(s);
        }
         
         
        if(existingSubscriptionList.size() > 0)
           update existingSubscriptionList;

	}


/*
    public static void processSubscriptions(map<Id, Asset> newMap, map<Id, Asset> oldMap)
    {
         
         set<Id> assetIdSet = new set<Id>();
         set<Id> commissionedAssetIdSet = new set<Id>();
         
         for(Asset a : newMap.values())
         {
            if(a.Commissioned__c == true && (oldMap != null && oldMap.get(a.Id).Commissioned__c == false) )
                commissionedAssetIdSet.add(a.Id);
                
            if(a.IE_Asset__c == true && (oldMap == null || oldMap.get(a.Id).IE_Asset__c == false))
                assetIdSet.add(a.Id);
         }
         list<Subscription__c> subscriptionList = new list<Subscription__c>();
         list<Subscription__c> existingSubscriptionList = new list<Subscription__c>();
         list<Contact_Subscription__c> contactSubscriptions = new list<Contact_Subscription__c>();
         list<Contact> daiknContacts = new list<Contact>();
         
         for(Subscription__c s : [Select Id, Term_Years__c, Type__c
                                    from Subscription__c
                                   where Asset__c in :commissionedAssetIdSet 
                                     and Asset__c != null
                                     and Type__c  != 'Daikin']) 
         {
            s.Start_Date__c = System.today();
            s.End_Date__c = System.today().addDays((Integer.valueOf(365 * (s.Term_Years__c==null?0:s.Term_Years__c)) ));
            existingSubscriptionList.add(s);
         }
         
         
         if(existingSubscriptionList.size() > 0)
            update existingSubscriptionList;
         

        // - ** NON GATEWAY ASSETS ** Create Daikin Subscription Record using "Daikin" Account and Contacts flagged as to be included(contacts flagged, 
        //      contact custom setting)
        //  -- When there are no existing Daikin Subscriotions and the IE_Asset__c flag is true and was previously false
        

         map<Id, Id> ExistingDaikinSubscriptionMap = new map<Id,Id>();
         
         for(Subscription__c s : [Select Id, Asset__c from Subscription__c where Asset__c in :assetIdSet and Type__c  = 'Daikin'])
            ExistingDaikinSubscriptionMap.put(s.Asset__c, s.Id);
            
         for(Id assetId : assetIdSet)   
         {
            if(!ExistingDaikinSubscriptionMap.containsKey(assetId))
            {
                subscriptionList.add(new Subscription__c(Asset__c = assetId
                                                        ,Buyer_Id__c = IE_Service_Configuration__c.getInstance().DaikinAccountId__c
                                                        ,Type__c  = 'Daikin'
                                                        ,Active__c = true));
            }
         }
            
         if(subscriptionList.size() > 0)
            insert subscriptionList;
            
         //create contact subscriptions
         
         //retrieve the "Daikin" account and then the flagged contacts
         for(Contact c : [Select Id, IE_Daikin_Subscription_Role__c
                            from Contact
                           where IE_Daikin_Subscription_Role__c != null
                             and AccountId = :IE_Service_Configuration__c.getInstance().DaikinAccountId__c ])
         {
             list<String> roleList = c.IE_Daikin_Subscription_Role__c.split(';');
             for(Subscription__c s : subscriptionList)
             {
                
                    contactSubscriptions.add(new Contact_Subscription__c(Contact__c = c.Id
                                                                        ,Subscription__c = s.Id
                                                                        ,Asset__c = s.Asset__c
                                                                        ,Role__c = c.IE_Daikin_Subscription_Role__c));
                                                                        
                                                                        
             }
         }
         
         if(contactSubscriptions.size() > 0)
            insert contactSubscriptions;
         
    }
*/


    /*
    public static void doIntelSync(map<Id, Asset> newMap, map<Id, Asset> oldMap) {
        List<Asset> assetsToSync = AssetIntegrationService.filterAssetsToSync(newMap.values(), oldMap, AssetIntegrationService.filterFields);
        System.debug('^^^ assetsToSync: ' + assetsToSync);
        for (Asset ast : assetsToSync) {
            ID jobID = System.enqueueJob(new SendAssetToIntel(ast.Id));
            System.debug('jobbbbb: ' + jobID);
        }
    }*/
 
}