src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <description>dcw_DistChannels.dc_location</description>
        <inlineHelpText>dcw_DistChannels.dc_location</inlineHelpText>
        <label>Location (DCW)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>National_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to identify a National Account.</description>
        <inlineHelpText>Identifies North America National Account when checked.</inlineHelpText>
        <label>National Account</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>United States</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Åland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia, Plurinational State of</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Geographic_Location__c</fullName>
        <inlineHelpText>Latitude and Longitude values for this address.</inlineHelpText>
        <label>Geographic Location</label>
        <scale>4</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <label>State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Acklins</fullName>
                </value>
                <value>
                    <fullName>Acre</fullName>
                </value>
                <value>
                    <fullName>Aguascalientes</fullName>
                </value>
                <value>
                    <fullName>Ahuachapán</fullName>
                </value>
                <value>
                    <fullName>Aisén del General Carlos Ibáñez del Campo</fullName>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alagoas</fullName>
                </value>
                <value>
                    <fullName>Alajuela</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Alberta</fullName>
                </value>
                <value>
                    <fullName>Alta Verapaz</fullName>
                </value>
                <value>
                    <fullName>Alto Paraguay</fullName>
                </value>
                <value>
                    <fullName>Alto Paraná</fullName>
                </value>
                <value>
                    <fullName>Amambay</fullName>
                </value>
                <value>
                    <fullName>Amapá</fullName>
                </value>
                <value>
                    <fullName>Amazonas</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Ancash</fullName>
                </value>
                <value>
                    <fullName>Andaman and Nicobar Islands</fullName>
                </value>
                <value>
                    <fullName>Andhra Pradesh</fullName>
                </value>
                <value>
                    <fullName>Anhui</fullName>
                </value>
                <value>
                    <fullName>Anse la Raye</fullName>
                </value>
                <value>
                    <fullName>Antioquia</fullName>
                </value>
                <value>
                    <fullName>Antofagasta</fullName>
                </value>
                <value>
                    <fullName>Anzoátegui</fullName>
                </value>
                <value>
                    <fullName>Apure</fullName>
                </value>
                <value>
                    <fullName>Apurímac</fullName>
                </value>
                <value>
                    <fullName>Aragua</fullName>
                </value>
                <value>
                    <fullName>Arauca</fullName>
                </value>
                <value>
                    <fullName>Araucanía</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Asset_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Model_Type__c</fullName>
        <formula>Text(Product2.Model_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Model Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FindNearbyLeads.cls
global with sharing class FindNearbyLeads {

    public FindNearbyLeads(ApexPages.StandardController controller) {

    }


    public FindNearbyLeads(ApexPages.StandardSetController controller) { }

    @RemoteAction
    // Find leads nearest a geolocation
    global static List<Lead> getNearby(String lat, String lon) {

        // If geolocation isn't set, use San Francisco
        if(lat == null || lon == null || lat.equals('') || lon.equals('')) {
            lat = '37.77493';
            lon = '-122.419416';
        }
        
        // SOQL query to get the nearest leads
        String queryString =
            'SELECT Id, Name, Company, LeadSource, Street, Phone, City, PostalCode, Country, State, OwnerId ' +//, Location__Latitude__s, Location__Longitude__s, Location__c
            'FROM Lead ' +
            //'WHERE DISTANCE(Location__c, GEOLOCATION('+lat+','+lon+'), \'mi\') < 2000 ' +
            'WHERE (OwnerId = \'' + UserInfo.getUserId() + '\' ' +
            'OR OwnerId=\'005i0000001JySJAA0\') ' +
            'AND Status in (\'Open\', \'Contacted\') ' +
            //'ORDER BY DISTANCE(Location__c, GEOLOCATION('+lat+','+lon+'), \'mi\') ASC ' +            
            'LIMIT 20';

        // Run and return the query results
        return(database.Query(queryString));
    }

    @RemoteAction
    // Find accounts nearest a geolocation
    global static List<Account> getNearbyAccounts(String lat, String lon) {

        // If geolocation isn't set, use San Francisco
        if(lat == null || lon == null || lat.equals('') || lon.equals('')) {
            lat = '37.77493';
            lon = '-122.419416';
        }
        
        // SOQL query to get the nearest leads
        String queryString =
            'SELECT Id, Name, AccountNumber, BillingStreet, Phone, BillingCity, BillingPostalCode, BillingCountry, BillingState, OwnerId, BillingLatitude, BillingLongitude, National_Account__c ' +
            'FROM Account ' +
            'WHERE DISTANCE(BillingAddress, GEOLOCATION('+lat+','+lon+'), \'mi\') < 2000 ' +
            //'AND OwnerId = \'' + UserInfo.getUserId() + '\' ' +
            'ORDER BY DISTANCE(BillingAddress, GEOLOCATION('+lat+','+lon+'), \'mi\') ASC ' +            
            'LIMIT 20';

        // Run and return the query results
        return(database.Query(queryString));
    }

    @RemoteAction
    // Find accounts nearest a geolocation
    global static List<Asset> getNearbyAssets(String lat, String lon) {

        // If geolocation isn't set, use San Francisco
        if(lat == null || lon == null || lat.equals('') || lon.equals('')) {
            lat = '37.77493';
            lon = '-122.419416';
        }
        
        // SOQL query to get the nearest leads
        String queryString =
            'SELECT Id, Name, SerialNumber, Asset_Address__r.Address_Line_1__c, Asset_Address__r.City__c, Asset_Address__r.Postal_Code__c, Asset_Address__r.Country__c, Asset_Address__r.State_Province__c, Account.OwnerId, Asset_Address__r.Geographic_Location__latitude__s, Asset_Address__r.Geographic_Location__longitude__s ' +
            ', Model_Type__c '+
            'FROM Asset ' +
            'WHERE DISTANCE(Asset_Address__r.Geographic_Location__c, GEOLOCATION('+lat+','+lon+'), \'mi\') < 100 ' +
            //'AND Account.OwnerId = \'' + UserInfo.getUserId() + '\' ' +
            'ORDER BY DISTANCE(Asset_Address__r.Geographic_Location__c, GEOLOCATION('+lat+','+lon+'), \'mi\') ASC ' +            
            'LIMIT 100';

        // Run and return the query results
        return(database.Query(queryString));
    }
    
    webservice static String createLeadFromAsset(String assetId){
        Asset a = [select Id, Name from Asset where Id=:assetId];
        Lead l = new Lead();
        l.LastName=a.Name;
        l.Company = a.Name;
        l.LeadSource = 'Web';
        l.Email = 'test@test.com';
        insert l;
        
        return l.Id;
    }

}