src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Account has been inactivated</description>
        <inlineHelpText>The Account/Company no longer exists (closed doors, bankruptcy, etc.)</inlineHelpText>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Bidder__c.object
<CustomObject>
    <description>DMNY</description>
    <fields>
        <fullName>Bidder_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>DMNY</description>
        <label>Bidder Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bidders</relationshipLabel>
        <relationshipName>Bidders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates bidder not successful or no longer active.</description>
        <inlineHelpText>Indicates bidder not successful or no longer active.</inlineHelpText>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Bidders</relationshipLabel>
        <relationshipName>Bidders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bidder</label>
    <nameField>
        <label>Bidder Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bidders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Active_Bidder__c</fullName>
        <label>Active Bidder</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BidderHelper.cls
public class BidderHelper {
    
    public static void UpdateBiddervalues(set<String> oppIds){
        List<Opportunity> opptobeUpdated = new List<Opportunity>();
        Integer i = 0;
        for(Opportunity opp :[SELECT Id,Active_Bidder__c,(SELECT Bidder_Name__r.Owner.Name,Bidder_Name__r.Owner.User_Department__c,
                                                          Inactive__c,Opportunity__c FROM 
                                                          Bidders__r WHERE  Inactive__c=FALSE) FROM Opportunity WHERE Id IN :oppIds]){
            
            opp.Active_Bidder__c = ' ';
            for(Bidder__c b :opp.Bidders__r){
               
                i++;
                opp.Active_Bidder__c += 'Active Bider'+' '+i+':'+b.Bidder_Name__r.Owner.Name+' ('+b.Bidder_Name__r.Owner.User_Department__c+'), ';
                
            }
			
            opp.Active_Bidder__c = +opp.Active_Bidder__c.removeEnd(', ');
            
            opptobeUpdated.add(opp);
        }
        
        if(opptobeUpdated.size() > 0){
            update opptobeUpdated;    
        }  
    }
}