src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>High_Value__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created for the DSO side of the business</description>
        <inlineHelpText>Indicates this is a high value account. Only include the approximately 10-20% of accounts that produce approximately 80-90% of the results (or has the potential to do so).</inlineHelpText>
        <label>High Value</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Warranty</fullName>
        <active>true</active>
        <businessProcess>Warranty</businessProcess>
        <description>Used for Warranty case claims</description>
        <label>Warranty</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>High_Value__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created originally for the DSO side of the business</description>
        <inlineHelpText>Indicates this contact is a strategically important person with a high level of influence.</inlineHelpText>
        <label>High Value</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>DSO</fullName>
        <active>true</active>
        <description>DSO Sales Calls tracker</description>
        <label>DSO</label>
    </recordTypes>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Standard task View</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>User_Department__c</fullName>
        <label>User Department</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>User_Division__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AAH</fullName>
                </value>
                <value>
                    <fullName>Admin</fullName>
                </value>
                <value>
                    <fullName>ATS</fullName>
                </value>
                <value>
                    <fullName>Central Mexico</fullName>
                </value>
                <value>
                    <fullName>Central Mexico - Bajio</fullName>
                </value>
                <value>
                    <fullName>Central Mexico - Guadalajara</fullName>
                </value>
                <value>
                    <fullName>Central Mexico - Mexico City</fullName>
                </value>
                <value>
                    <fullName>Chiller Applications</fullName>
                </value>
                <value>
                    <fullName>Chillers</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Controls</fullName>
                </value>
                <value>
                    <fullName>DAAL</fullName>
                </value>
                <value>
                    <fullName>DAAL - Equipment Sales</fullName>
                </value>
                <value>
                    <fullName>DAFL</fullName>
                </value>
                <value>
                    <fullName>DAFL - Equipment Sales</fullName>
                </value>
                <value>
                    <fullName>DAGA</fullName>
                </value>
                <value>
                    <fullName>DAGA - Equipment Sales</fullName>
                </value>
                <value>
                    <fullName>Daikin Latin America</fullName>
                </value>
                <value>
                    <fullName>DALA</fullName>
                </value>
                <value>
                    <fullName>DALA - Andean Pact</fullName>
                </value>
                <value>
                    <fullName>DALA - Caribbean</fullName>
                </value>
                <value>
                    <fullName>DALA - Central America</fullName>
                </value>
                <value>
                    <fullName>DALA - Service</fullName>
                </value>
                <value>
                    <fullName>DANY</fullName>
                </value>
                <value>
                    <fullName>DANY - Consulting Sales</fullName>
                </value>
                <value>
                    <fullName>DANY - Equipment Sales</fullName>
                </value>
                <value>
                    <fullName>Field Service</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>MCP</fullName>
                </value>
                <value>
                    <fullName>Mexico</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Valid_Business_Reason_Factor__mdt.object
<CustomObject>
    <fields>
        <fullName>Valid_Business_Reason_Factor__c</fullName>
        <label>Valid Business Reason Factor</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Valid_Business_Reason__c</fullName>
        <label>Valid Business Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Valid Business Reason Factor</label>
    <pluralLabel>Valid Business Reason Factors</pluralLabel>
</CustomObject>

src/classes/DSO_Sales_Call_Task_Controller_Test.cls
@isTest
public class DSO_Sales_Call_Task_Controller_Test {
    
    @testSetup static void setup(){//Insert Test Data
        Id accountRecordTypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Daikin Applied').getRecordTypeId();
        Id warrantyRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Warranty').getRecordTypeId();   
        Id warrantyAuthClaimRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Warranty Claim Authorization').getRecordTypeId();
        
        AVA_SFCORE__TaxNowSetting__c ts1 = new AVA_SFCORE__TaxNowSetting__c(); 
        ts1.AVA_SFCORE__Active_Setting__c = true; 
        ts1.Name='Test Account';
        insert ts1;
        User u = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Direct Sales Office Standard User'].Id,
            LastName = 'last',
            Email = 'testemails@daikinapplied.com',
            Username = 'puser000@amamama.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            User_Department__c='DAAL - Equipment Sales'
        );
        insert u;
        
        System.runAs(u) {
            List<account> accountList = new List<account>(); 
        List<contact> contactlist = new List<contact>();
        Account testAccount = APTPS_DaikinTestDataUtility.getAccount('accName');
        testAccount.High_Value__c = true;
        testAccount.Description='DAAL';
        accountList.add(testAccount);
        
        Account testAccount1 = APTPS_DaikinTestDataUtility.getAccount('accName');
        testAccount1.High_Value__c = false;
        testAccount1.Description='DAAL Tracking List';
        accountList.add(testAccount1);
        insert accountList;
        
        Contact testContact1 = APTPS_DaikinTestDataUtility.getContact(testAccount);
        testContact1.High_Value__c = true;
        Contact testContact2 = APTPS_DaikinTestDataUtility.getContact(testAccount);
        testContact2.High_Value__c = true;
        Contact testContact3 = APTPS_DaikinTestDataUtility.getContact(testAccount);
        testContact3.High_Value__c = true;
        Contact testContact4 = APTPS_DaikinTestDataUtility.getContact(testAccount);
        testContact4.High_Value__c = true; 
        Contact testContact5 = APTPS_DaikinTestDataUtility.getContact(testAccount);
        testContact5.High_Value__c = true; 
        contactlist.add(testContact1);
        contactlist.add(testContact2);
        contactlist.add(testContact3);
        contactlist.add(testContact4);
        contactlist.add(testContact5);
        insert contactlist;
        }
    
        
        /*
        system.debug('User '+U);
        // Update Owner on Accounts
        List<Account> accUpdate=new List<Account>();
        for(Account acUpdate:accountList){
            acupdate.owner=u;
            accUpdate.add(acupdate);
        }
        update accUpdate; */
        
    }
    
    @isTest static void fetchLookupValues(){
        List<string> exludeList=new  List<string>();
        List <sObject> sObj = DSO_Sales_Call_Task_Controller.fetchLookUpValues('Test Account NA-1', 'Contact', exludeList,'Test Account NA-1');
        // System.assertEquals(null, result);
    }
    @isTest static void getRelatedTasks(){
        List<String> contactIds=new List<String>();
        List<String> Cont1 = new List<String>();
        List<String> Cont2 = new List<String>();
        List<String> Cont3 = new List<String>();
        List<String> Cont4 = new List<String>();
        List<String> Cont5 = new List<String>();
        
        for(contact c:[select id,name from contact limit 10]){
            contactIds.add(c.id);
            if(Cont1.size()<1){
                Cont1.add(c.id);
            }
            if(Cont2.size()<2){
                Cont2.add(c.id);
            }
            if(Cont3.size()<3){
                Cont3.add(c.id);
            }
            if(Cont4.size()<4){
                Cont4.add(c.id);
            }
            if(Cont5.size()<5){
                Cont5.add(c.id);
            }
            
        }
        System.debug('contactIds'+contactIds);
        Account acc=[select id,name from account where High_Value__c = true limit 1];
        User u=[select id,name from user limit 1];
        acc.OwnerId=u.id;
        update acc;
        Task tsk=new Task();
        tsk.Sales_Call_Date__c=system.Date.today();
        tsk.WhatId=acc.id;
        tsk.Valid_Business_Reason__c='Customer Meal';
        
        case cas=new case();        
        cas.status='Warranty Approved';     
        insert cas;     
        
        Task tsks=new Task();       
        tsks=tsk.clone();       
        tsks.WhatId=cas.id;     
        tsks.Status='Completed';        
        tsks.Subject='Email:DSO';       
        insert tsks;        
        delete tsks;
        
        List<TaskRelation> getRelatedTask=DSO_Sales_Call_Task_Controller.getRelatedTasks(tsk, contactIds);
        String relatedTasks=JSON.serialize(getRelatedTask);
        //Calcualte Sales Score 
        String salesScore=DSO_Sales_Call_Task_Controller.calculateSalesScorce(tsk,relatedTasks);
        
        //Create a Task for selected account and contact
        string result=DSO_Sales_Call_Task_Controller.saveTask(tsk, relatedTasks, '60', 'Test');
        
        //Query custom metadata here
        Valid_Business_Reason_Factor__mdt supportSetting = [ SELECT Valid_Business_Reason__c,Valid_Business_Reason_Factor__c 
                                                            FROM Valid_Business_Reason_Factor__mdt WHERE Valid_Business_Reason__c LIKE '%Customer Meal%'
                                                            limit 1];
        //Get Account records from search Keywork
        List <sObject> fetchAccount=lookUpController.fetchAccount('accName', 'Account');
        //system.assertEquals(2, fetchAccount.size());
        tsk.Valid_Business_Reason__c='Cliffnotes Daikin Education';
        update tsk;
        
        system.assertEquals(UserInfo.getUserId(), lookUpController.getUser().Id);
    }
}