src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>dcw_DistChannels.dc_active_flag</description>
        <inlineHelpText>dcw_DistChannels.dc_active_flag</inlineHelpText>
        <label>Active (DCW)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Physical_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Click to open and view/edit the Physical Address record for this Account.</inlineHelpText>
        <label>Physical Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Accounts (Physical)</relationshipLabel>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account_Address__c.object
<CustomObject>
    <description>Junction object to tie multiple address records to an account and multiple accounts to a single address record.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Addresses</relationshipLabel>
        <relationshipName>Account_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Address Lookup</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Account_Addresses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Physical__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Physical</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Address</label>
    <nameField>
        <displayFormat>AA-{000000000}</displayFormat>
        <label>Account Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>United States</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Åland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia, Plurinational State of</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <label>State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Acklins</fullName>
                </value>
                <value>
                    <fullName>Acre</fullName>
                </value>
                <value>
                    <fullName>Aguascalientes</fullName>
                </value>
                <value>
                    <fullName>Ahuachapán</fullName>
                </value>
                <value>
                    <fullName>Aisén del General Carlos Ibáñez del Campo</fullName>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alagoas</fullName>
                </value>
                <value>
                    <fullName>Alajuela</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Alberta</fullName>
                </value>
                <value>
                    <fullName>Alta Verapaz</fullName>
                </value>
                <value>
                    <fullName>Alto Paraguay</fullName>
                </value>
                <value>
                    <fullName>Alto Paraná</fullName>
                </value>
                <value>
                    <fullName>Amambay</fullName>
                </value>
                <value>
                    <fullName>Amapá</fullName>
                </value>
                <value>
                    <fullName>Amazonas</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Ancash</fullName>
                </value>
                <value>
                    <fullName>Andaman and Nicobar Islands</fullName>
                </value>
                <value>
                    <fullName>Andhra Pradesh</fullName>
                </value>
                <value>
                    <fullName>Anhui</fullName>
                </value>
                <value>
                    <fullName>Anse la Raye</fullName>
                </value>
                <value>
                    <fullName>Antioquia</fullName>
                </value>
                <value>
                    <fullName>Antofagasta</fullName>
                </value>
                <value>
                    <fullName>Anzoátegui</fullName>
                </value>
                <value>
                    <fullName>Apure</fullName>
                </value>
                <value>
                    <fullName>Apurímac</fullName>
                </value>
                <value>
                    <fullName>Aragua</fullName>
                </value>
                <value>
                    <fullName>Arauca</fullName>
                </value>
                <value>
                    <fullName>Araucanía</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <description>This record type if for all records created by SFDC Users.</description>
        <label>Address</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>SFDC Order record unique Id number. Auto-generated within SFDC.</inlineHelpText>
        <label>Order ID</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Plan__c.object
<CustomObject>
    <label>Case Plan</label>
    <nameField>
        <label>Case Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case_Plan_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Case Plan Assets</relationshipLabel>
        <relationshipName>Case_Plan_Assets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Plan__c</fullName>
        <label>Case Plan</label>
        <referenceTo>Case_Plan__c</referenceTo>
        <relationshipLabel>Case Plan Assets</relationshipLabel>
        <relationshipName>Case_Plan_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Case Plan Asset</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Plan Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Plan Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Physical_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Click to open and view/edit the Physical Address record for this Contact.</inlineHelpText>
        <label>Physical Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Contacts (Physical)</relationshipLabel>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <description>Order information for TRC</description>
    <label>Order</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>DW_Product_Business_Unit__c</fullName>
        <label>DW Product Business Unit</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CasePlanTestClass.cls
@isTest 
private class CasePlanTestClass {  
    @TestSetup
    private static void loadTestData(){
        AVA_SFCORE__TaxNowSetting__c ts1 = new AVA_SFCORE__TaxNowSetting__c();
        ts1.AVA_SFCORE__Active_Setting__c = true;
        ts1.Name='Test Account';
        insert ts1;
        
        Address__c address = new Address__c();
        address.Address_Line_1__c = 'TEST';
        address.City__c = 'Minneapolis';
        address.Postal_Code__c = '55421';
        address.Country__c = 'United States';
        address.State_Province__c = 'Minnesota';
        insert address;

        Account a = new Account();
        a.Name = 'TEST';
        a.Type = 'Developer';
        a.Physical_Address__c = address.Id;
        insert a;
        
        Account_Address__c aa = new Account_Address__c();
        aa.Account__c = a.Id;
        aa.Address__c = address.Id;
        aa.Active__c = true;
        aa.Physical__c = true;
        insert aa;
        
        Contact c = new Contact();
        c.AccountId = a.Id;
        c.LastName = 'TEST';
        c.Email = 'test@test.com';
        insert c;
        
        Product2 p = new Product2();
        p.Name = 'TEST';
        p.IsActive = true;
        p.ProductCode = 'TEST';
        p.DW_Product_Business_Unit__c = 'Applied Air Handler';
        insert p;
        
        Order__c order = new Order__c();
        insert order;
        
        Asset asset = new Asset();
        asset.Name = 'TEST';
        asset.SerialNumber = 'TEST';
        asset.Product2Id = p.Id;
        asset.AccountId = a.Id;
        asset.ContactId = c.Id;
        asset.Order__c = order.Id;
        insert asset;

        Case_Plan__c cp = new Case_Plan__c();
        cp.Name='TEST';
        insert cp;
        
        Case_Plan_Asset__c cpa = new Case_Plan_Asset__c();
        cpa.Case_Plan__c = cp.Id;
        cpa.Asset__c = asset.Id;
        insert cpa;
    }  
    static testMethod void CasePlanAssetTriggerTest(){
        System.assertEquals(1, [select Id from Case_Plan_Asset__c].size());
    }
}