src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>dcw_DistChannels.dc_active_flag</description>
        <inlineHelpText>dcw_DistChannels.dc_active_flag</inlineHelpText>
        <label>Active (DCW)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IE_Sync_Status__c</fullName>
        <label>IE Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Physical_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Click to open and view/edit the Physical Address record for this Account.</inlineHelpText>
        <label>Physical Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Accounts (Physical)</relationshipLabel>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account_Address__c.object
<CustomObject>
    <description>Junction object to tie multiple address records to an account and multiple accounts to a single address record.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Addresses</relationshipLabel>
        <relationshipName>Account_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Address Lookup</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Account_Addresses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Physical__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Physical</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Address</label>
    <nameField>
        <displayFormat>AA-{000000000}</displayFormat>
        <label>Account Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>United States</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Åland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia, Plurinational State of</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IE_Sync_Status__c</fullName>
        <description>Status that gets set when attributes on the record are updated and therefore needs to be sent to the IE system.</description>
        <inlineHelpText>Pending =  Record needs to be sent to the IE system. 
Processed = Record was successfully received by IE system.
Error = Record was not successfully received by IE system.</inlineHelpText>
        <label>IE Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <label>State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Acklins</fullName>
                </value>
                <value>
                    <fullName>Acre</fullName>
                </value>
                <value>
                    <fullName>Aguascalientes</fullName>
                </value>
                <value>
                    <fullName>Ahuachapán</fullName>
                </value>
                <value>
                    <fullName>Aisén del General Carlos Ibáñez del Campo</fullName>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alagoas</fullName>
                </value>
                <value>
                    <fullName>Alajuela</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Alberta</fullName>
                </value>
                <value>
                    <fullName>Alta Verapaz</fullName>
                </value>
                <value>
                    <fullName>Alto Paraguay</fullName>
                </value>
                <value>
                    <fullName>Alto Paraná</fullName>
                </value>
                <value>
                    <fullName>Amambay</fullName>
                </value>
                <value>
                    <fullName>Amapá</fullName>
                </value>
                <value>
                    <fullName>Amazonas</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Ancash</fullName>
                </value>
                <value>
                    <fullName>Andaman and Nicobar Islands</fullName>
                </value>
                <value>
                    <fullName>Andhra Pradesh</fullName>
                </value>
                <value>
                    <fullName>Anhui</fullName>
                </value>
                <value>
                    <fullName>Anse la Raye</fullName>
                </value>
                <value>
                    <fullName>Antioquia</fullName>
                </value>
                <value>
                    <fullName>Antofagasta</fullName>
                </value>
                <value>
                    <fullName>Anzoátegui</fullName>
                </value>
                <value>
                    <fullName>Apure</fullName>
                </value>
                <value>
                    <fullName>Apurímac</fullName>
                </value>
                <value>
                    <fullName>Aragua</fullName>
                </value>
                <value>
                    <fullName>Arauca</fullName>
                </value>
                <value>
                    <fullName>Araucanía</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <description>This record type if for all records created by SFDC Users.</description>
        <label>Address</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Eprise_Login_ID__c</fullName>
        <description>This is the Login ID that Reps and Employees use to log into the Sales Portal and Daikin Tools.</description>
        <label>Eprise Login ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IE_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate the record pertains to the IE integration.  This is set on import of record from Daikin IE Back Office database.</description>
        <inlineHelpText>Flag to indicate the record pertains to the IE integration.  This is set on import of record from Daikin IE Back Office database.</inlineHelpText>
        <label>IE Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IE_Sync_Status__c</fullName>
        <description>Status that gets set when attributes on the record are updated and therefore needs to be sent to the IE system.</description>
        <inlineHelpText>Pending =  Record needs to be sent to the IE system. 
Processed = Record was successfully received by IE system.
Error = Record was not successfully received by IE system.</inlineHelpText>
        <label>IE Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Physical_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Click to open and view/edit the Physical Address record for this Contact.</inlineHelpText>
        <label>Physical Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Contacts (Physical)</relationshipLabel>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CountryCodes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Mapping of Countries to abbreviated codes</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CountryCodes</label>
</CustomObject>

src/objects/StateCodes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Mapping of States to their Abriviations</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>StateCodes</label>
</CustomObject>

src/classes/TestContactTrigger.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestContactTrigger {

// NOTE: Need to use the @isTest(SeeAllData=true) annotation because the test needs access the Custom Settings: CountryCodes__c, StateCodes__c

    @isTest(SeeAllData=true) static void unitTest1() {
        // Create an Address, Account and Contact objects to test the Insert and Update triggers on the Contact

		//!!!!!!!!!!! Need to add this code snippet for AvaTax- AccountAddressTrigger to run successfully on Before Insert into the Account table !!!!!!!!!!!!!!!!!
    	AVA_SFCORE__TaxNowSetting__c ts1 = new AVA_SFCORE__TaxNowSetting__c();
        ts1.AVA_SFCORE__Active_Setting__c = true;
        ts1.Name='Test Account';
        insert ts1;

		// ---------------------------------CREATE TEST DATA----------------------------
        // Create Address__c, Account, Account_Address__c records
        Account acctTemp = null;
        Address__c addrTemp = null;
        Account_Address__c acctAddrJunctionObj = null;
        
        addrTemp = new Address__c();
        addrTemp.Address_Line_1__c = 'Test Address Line 1';
        addrTemp.City__c = 'Minneapolis';
        addrTemp.Postal_Code__c = '55421';
        addrTemp.Country__c = 'United States';
        addrTemp.State_Province__c = 'Minnesota';
        insert addrTemp;
        
        acctTemp = new Account();
        acctTemp.Name = 'Account Test1';
        acctTemp.Type = 'Developer';
        acctTemp.Physical_Address__c = addrTemp.Id;
        acctTemp.IE_Sync_Status__c = 'Pending';
        insert acctTemp;
        
        acctAddrJunctionObj = new Account_Address__c();
        acctAddrJunctionObj.Account__c = acctTemp.Id;
        acctAddrJunctionObj.Address__c = addrTemp.Id;
        acctAddrJunctionObj.Active__c = true;
        acctAddrJunctionObj.Physical__c = true;
        insert acctAddrJunctionObj;

		//--------------------

		Account acctTemp4 = null;
        Address__c addrTemp4 = null;
        Account_Address__c acctAddrJunctionObj4 = null;
        
        addrTemp4 = new Address__c();
        addrTemp4.Address_Line_1__c = 'Test Address Line ZZZ';
        addrTemp4.City__c = 'Roseville';
        addrTemp4.Postal_Code__c = '55421';
        addrTemp4.Country__c = 'United States';
        addrTemp4.State_Province__c = 'Minnesota';
        insert addrTemp4;
        
        acctTemp4 = new Account();
        acctTemp4.Name = 'Account Test4';
        acctTemp4.Type = 'Developer';
        acctTemp4.Physical_Address__c = addrTemp4.Id;
        acctTemp4.IE_Sync_Status__c = 'Pending';
        insert acctTemp4;
        
        acctAddrJunctionObj4 = new Account_Address__c();
        acctAddrJunctionObj4.Account__c = acctTemp4.Id;
        acctAddrJunctionObj4.Address__c = addrTemp4.Id;
        acctAddrJunctionObj4.Active__c = true;
        acctAddrJunctionObj4.Physical__c = true;
        insert acctAddrJunctionObj4;

		//------------------

		RecordType recordTypeTemp = [SELECT Id FROM RecordType WHERE Name='Daikin Applied' AND SObjectType='Contact'];

        List<Contact> contactList = new List<Contact>();

		// Contact whose Account Address = its Primary Mailing Address
        Contact contactTemp1 = new Contact();
        contactTemp1.Eprise_Login_ID__c = 'RoesslKS1';
        contactTemp1.RecordTypeId = recordTypeTemp.Id;
        contactTemp1.AccountId = acctTemp.Id;
        contactTemp1.Status__c = 'Active';
        contactTemp1.Email = 'kent.roessler@daikinapplied.com';
        contactTemp1.FirstName = 'Kent1';
        contactTemp1.LastName = 'Roessler1';
        contactTemp1.IE_Sync_Status__c = 'Pending';
        contactTemp1.IE_Contact__c = true;
		contactTemp1.MailingStreet = 'Test Address Line 1';
		contactTemp1.MailingCity = 'Minneapolis';
		contactTemp1.MailingCountry = 'United States';
		contactTemp1.MailingState = 'Minnesota';
		contactTemp1.MailingPostalCode = '55421';
        // Create an address for this contact
        Address__c addrTemp1 = new Address__c();
        addrTemp1.Address_Line_1__c = 'Test Address Line 1';
        addrTemp1.City__c = 'Minneapolis';
        addrTemp1.Postal_Code__c = '55421';
        addrTemp1.Country__c = 'United States';
        addrTemp1.State_Province__c = 'Minnesota';
        insert addrTemp1;
        contactTemp1.Physical_Address__c = addrTemp1.Id;
		contactTemp1.Primary_Mailing_Address__c = addrTemp1.Id;
        contactList.add(contactTemp1);


		// Contact whose Account Address != its Primary Mailing Address
		Contact contactTemp2 = new Contact();
        contactTemp2.Eprise_Login_ID__c = 'RoesslKS2';
        contactTemp2.RecordTypeId = recordTypeTemp.Id;
        contactTemp2.AccountId = acctTemp.Id;
        contactTemp2.Status__c = 'Active';
        contactTemp2.Email = 'kent.roessler@daikinapplied.com';
        contactTemp2.FirstName = 'Kent2';
        contactTemp2.LastName = 'Roessler2';
        contactTemp2.IE_Sync_Status__c = 'Pending';
        contactTemp2.IE_Contact__c = true;
		contactTemp2.MailingStreet = 'Test Address Line 12';
		contactTemp2.MailingCity = 'Minneapolis';
		contactTemp2.MailingCountry = 'United States';
		contactTemp2.MailingState = 'Minnesota';
		contactTemp2.MailingPostalCode = '55418';
		contactTemp2.MailingCountryCode = 'US';
		contactTemp2.MailingStateCode = 'MN';
        // Create an address for this contact
        Address__c addrTemp2 = new Address__c();
        addrTemp2.Address_Line_1__c = 'Test Address Line 12';
        addrTemp2.City__c = 'Minneapolis';
        addrTemp2.Postal_Code__c = '55418';
        addrTemp2.Country__c = 'United States';
        addrTemp2.State_Province__c = 'Minnesota';
        insert addrTemp2;
        contactTemp2.Physical_Address__c = addrTemp2.Id;
		contactTemp2.Primary_Mailing_Address__c = addrTemp2.Id;
        contactList.add(contactTemp2);


		// Contact is NOT an IE Contact, set value for DTJobGUID__c field
        Contact contactTemp3 = new Contact();
		contactTemp3.Record_Usage__c = 'IE';
		contactTemp3.DTJobGUID__c = 'xxx';
        contactTemp3.Eprise_Login_ID__c = 'RoesslKS3';
        contactTemp3.RecordTypeId = recordTypeTemp.Id;
        contactTemp3.AccountId = acctTemp.Id;
        contactTemp3.Status__c = 'Active';
        contactTemp3.Email = 'kent.roessler@daikinapplied.com';
        contactTemp3.FirstName = 'Kent3';
        contactTemp3.LastName = 'Roessler3';
        contactTemp3.IE_Sync_Status__c = 'Pending';
        contactTemp3.IE_Contact__c = false;
		contactTemp3.MailingStreet = 'Test Address Line 1';
		contactTemp3.MailingCity = 'Minneapolis';
		contactTemp3.MailingCountry = 'United States';
		contactTemp3.MailingState = 'Minnesota';
		contactTemp3.MailingPostalCode = '55421';
        // Create an address for this contact
        Address__c addrTemp3 = new Address__c();
        addrTemp3.Address_Line_1__c = 'Test Address Line 1';
        addrTemp3.City__c = 'Minneapolis';
        addrTemp3.Postal_Code__c = '55421';
        addrTemp3.Country__c = 'United States';
        addrTemp3.State_Province__c = 'Minnesota';
        insert addrTemp3;
        contactTemp3.Physical_Address__c = addrTemp3.Id;
		contactTemp3.Primary_Mailing_Address__c = addrTemp3.Id;
        contactList.add(contactTemp3);


		insert contactList;

		// Update 3rd contact
		Contact ct3 = [SELECT Id, Type__c, Record_Usage__c, DTJobGUID__c  FROM Contact WHERE Id = :contactTemp3.Id];
		System.Debug('ct3.DTJobGUID__c='+ct3.DTJobGUID__c);
		ct3.Record_Usage__c = null;
		ct3.Type__c = 'Engineer';
		update ct3;


		// Update 2nd contact
		Contact ct2 = [SELECT Id, AccountId, Physical_Address__c, Primary_Mailing_Address__c  FROM Contact WHERE Id = :contactTemp2.Id];
		//set to a different account
		ct2.AccountId = acctTemp4.Id;
		ct2.MailingStreet = 'Test Address Line xx';
		ct2.MailingCity = 'Minneapolis';
		ct2.MailingCountry = 'United States';
		ct2.MailingState = 'Minnesota';
		ct2.MailingPostalCode = '55418';
		ct2.MailingCountryCode = 'US';
		ct2.MailingStateCode = 'MN';
		//create a new address for this contact
        Address__c addrTemp2_1 = new Address__c();
        addrTemp2_1.Address_Line_1__c = 'Test Address Line xx';
        addrTemp2_1.City__c = 'Minneapolis';
        addrTemp2_1.Postal_Code__c = '55418';
        addrTemp2_1.Country__c = 'United States';
        addrTemp2_1.State_Province__c = 'Minnesota';
        insert addrTemp2_1;
        ct2.Physical_Address__c = addrTemp2_1.Id;
		ct2.Primary_Mailing_Address__c = addrTemp2_1.Id;
		update ct2;


		// Assert Test Results
		Contact ct1 = [SELECT Id, IE_Sync_Status__c, Record_Usage__c from Contact Where Id = :contactTemp1.Id];
 		System.assertEquals('Pending', ct1.IE_Sync_Status__c);
		System.assertEquals('IE', ct1.Record_Usage__c);

		ct3 = [SELECT Id, DTJobGUID__c  FROM Contact WHERE Id = :contactTemp3.Id];
		System.Debug('ct3.DTJobGUID__c='+ct3.DTJobGUID__c);
		list<String> emptyList = new list<String>();
		System.assertEquals(''+emptyList, ct3.DTJobGUID__c);  // equivalent to System.assertEquals('()', ct3.DTJobGUID__c);

		ct2 = [SELECT Id, Physical_Address__c, Primary_Mailing_Address__c, MailingStreet  FROM Contact WHERE Id = :contactTemp2.Id];
		System.assertEquals('Test Address Line xx', ct2.MailingStreet);
    }
}