src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>dcw_DistChannels.dc_active_flag</description>
        <inlineHelpText>dcw_DistChannels.dc_active_flag</inlineHelpText>
        <label>Active (DCW)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IE_Sync_Status__c</fullName>
        <label>IE Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Code_String_Breakdown__c</fullName>
        <description>Display Breakdown of code string. Raw data pulled from Data Warehouse then transformed and compiled in the SFDC Integration dba prior to load here.</description>
        <label>Code String Breakdown</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IE_Sync_Status__c</fullName>
        <description>Status that gets set when attributes on the record are updated and therefore needs to be sent to the IE system.</description>
        <inlineHelpText>Pending = Record needs to be sent to the IE system. 
Processed = Record was successfully received by IE system. 
Error = Record was not successfully received by IE system.</inlineHelpText>
        <label>IE Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Equipment that this Asset is controlling or tied to.</inlineHelpText>
        <label>Parent Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Related Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SIM_Card_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to determine if the SIM card is active or not.</description>
        <label>SIM Card Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Eprise_Login_ID__c</fullName>
        <description>This is the Login ID that Reps and Employees use to log into the Sales Portal and Daikin Tools.</description>
        <label>Eprise Login ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IE_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate the record pertains to the IE integration.  This is set on import of record from Daikin IE Back Office database.</description>
        <inlineHelpText>Flag to indicate the record pertains to the IE integration.  This is set on import of record from Daikin IE Back Office database.</inlineHelpText>
        <label>IE Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IE_Sync_Status__c</fullName>
        <description>Status that gets set when attributes on the record are updated and therefore needs to be sent to the IE system.</description>
        <inlineHelpText>Pending =  Record needs to be sent to the IE system. 
Processed = Record was successfully received by IE system.
Error = Record was not successfully received by IE system.</inlineHelpText>
        <label>IE Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Account Manager</fullName>
                </value>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>Architect</fullName>
                </value>
                <value>
                    <fullName>Buyer</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>DA Factory Service Tech</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Engineer</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>Independent Sales Rep</fullName>
                </value>
                <value>
                    <fullName>Main</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Project Manager</fullName>
                </value>
                <value>
                    <fullName>Service Tech</fullName>
                </value>
                <value>
                    <fullName>Team Member</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact_Subscription__c.object
<CustomObject>
    <description>Junction object to tie a contact to an IE Subscription, the Unit for the Subscription and one IE role for the specific Unit &amp; Subscription.  If the contact has more than one IE role for a given Unit/Subscription, then another Contact Subscription record will be created for that Role/Unit combination.</description>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Intelligent Equipment Contacts</relationshipLabel>
        <relationshipName>Contact_Subscriptions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Intelligent Equipment Subscriptions</relationshipLabel>
        <relationshipName>Contact_Subscriptions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contact_Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Subscription</label>
    <nameField>
        <displayFormat>CS-{000000000}</displayFormat>
        <label>Contact Subscription ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Apttus_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Apttus Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DW_PCL_Description__c</fullName>
        <label>DW PCL Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <description>Product Category</description>
        <label>Product Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Supplier__c</fullName>
        <label>Vendor/Supplier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Object to identify and tie IE Subscriptions, to their appropriate Unit (Asset), Buyer (Account), and Users (Contacts).</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Pass this attribute to IE as part of 1.2 release.  Removes need to change the Subscription End Date from the contract term end date if it&apos;s necessary to remove access to Unit in IE prior to End Date.</description>
        <inlineHelpText>If checked, Subscription has started and is currently in effect.  Uncheck if Subscription should be made inactive for any reason. (e.g. Contract Expired, Non-payment, Legal)</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Intelligent Equipment Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Buyer_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Buyer ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Intelligent Equipment Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Connectivity_Type__c</fullName>
        <description>Subscription connectivity plan to either use AT&amp;T Cellular option with the SIM card active or customer&apos;s own WiFi/LAN option to send data to the Daikin IE cloud (MS Azure).</description>
        <label>Connectivity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cellular</fullName>
                </value>
                <value>
                    <fullName>WiFi/LAN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>IE_Sync_Status__c</fullName>
        <description>Status that gets set when attributes on the record are updated and therefore needs to be sent to the IE system.</description>
        <inlineHelpText>Pending = Record needs to be sent to the IE system. 
Processed = Record was successfully received by IE system. 
Error = Record was not successfully received by IE system.</inlineHelpText>
        <label>IE Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Counter__c</fullName>
        <description>Number of times the subscription has been renewed</description>
        <label>Renewal Counter</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Renewal_Notice_Current_Month__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean flag to keep track if an email was sent for a subscription renewal where the end date is in the current month.</description>
        <label>Renewal Notice Current Month</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Renewal_Notice_Last_Month__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean flag to keep track if an email was sent for a subscription renewal where the end date is in the last month.</description>
        <label>Renewal Notice Last Month</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Renewal_Notice_Next_Month__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean flag to keep track if an email was sent for a subscription renewal where the end date is in the next month.</description>
        <label>Renewal Notice Next Month</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Intelligent Equipment system subscription type.</description>
        <inlineHelpText>Intelligent Equipment system subscription type.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CustomRead</fullName>
                </value>
                <value>
                    <fullName>TechReadWrite</fullName>
                </value>
                <value>
                    <fullName>TechRead</fullName>
                </value>
                <value>
                    <fullName>Daikin</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>S-{000000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestRetrieveAssetService.cls
@isTest
private class TestRetrieveAssetService {

    static testmethod void testUnitSN()
    {
        //!!!!!!!!!!! Need to add this code snippet for AvaTax- AccountAddressTrigger to run successfully on Before Insert into the Account table !!!!!!!!!!!!!!!!!
        AVA_SFCORE__TaxNowSetting__c ts1 = new AVA_SFCORE__TaxNowSetting__c(); 
        ts1.AVA_SFCORE__Active_Setting__c = true; 
        ts1.Name='Test Account';
        insert ts1;
        

		// Create a Product for the Parent Asset
		Product2 prodTemp2 = null;
        prodTemp2 = new Product2();
        prodTemp2.Name = 'Test Prod2';
        prodTemp2.Vendor_Supplier__c = 'Test Vendor2';
        prodTemp2.IsActive = true;
        prodTemp2.Description = 'Test Description2';
        prodTemp2.DW_PCL_Description__c = 'Test DW PCL Description2';
        prodTemp2.Apttus_Product__c = true;
        prodTemp2.Product_Category__c = 'Test Category2';
        prodTemp2.ProductCode = 'RPS015A';
        insert prodTemp2;


        // Create an account for the assets
        Account acct = new Account(Name = 'Test');
        insert acct;
        

        // Create Parent Asset
        Asset parentAsset = new Asset(Name = 'test',
                             AccountId = acct.Id,
                             SerialNumber='123Test',
							 Product2Id = prodTemp2.Id
                             );
		parentAsset.Code_String_Breakdown__c = '[{"code_sequence":"1","code_value":"MPS","code_description":"UNIT TYPE; Unit Type"},{"code_sequence":"2","code_value":"003B","code_description":"UNIT SIZE; 3 ton, R410A"},{"code_sequence":"3","code_value":"Y","code_description":"HEAT; None"},{"code_sequence":"4","code_value":"D","code_description":"VOLTAGE/POWER CONNECTION; 460 V power"},{"code_sequence":"5","code_value":"M","code_description":"DRIVE PACKAGE; Belt drive - high static"},{"code_sequence":"6","code_value":"00D","code_description":"HEATING CAPACITY/CONTROLS; DDC controls"},{"code_sequence":"7","code_value":"CZ","code_description":"OPTIONS; HP,LP,LowAmb/Comfort Aler,FldPower GFI, Hail Guard"},{"code_sequence":"8","code_value":"D","code_description":"ECONOMIZER; Field Mounted 0-30% Outside air hood"}]';
        insert parentAsset;
        

        // Create Product2, and Related Asset
        Product2 prodTemp1 = null;
        prodTemp1 = new Product2();
        prodTemp1.Name = 'Intelligent Equipment Gateway';
		prodTemp1.ProductCode = 'IEGATE1';
        prodTemp1.Vendor_Supplier__c = 'Test Vendor1';
        prodTemp1.IsActive = true;
        prodTemp1.Description = 'Test Description1';
        prodTemp1.DW_PCL_Description__c = 'Test DW PCL Description1';
        prodTemp1.Apttus_Product__c = true;
        prodTemp1.Product_Category__c = 'Test Category1';
        insert prodTemp1;

        Asset relatedAsset = new Asset(Name = 'Intelligent Equipment Gateway', AccountId = acct.Id, SerialNumber = 'PO112711-2-075', Parent_Asset__c = parentAsset.Id);
        relatedAsset.Product2Id = prodTemp1.Id;
        relatedAsset.SIM_Card_Active__c = true;
        insert relatedAsset;


        // Create Contact, Subscription and Contact_Subscription
        Datetime currDateTime = Datetime.now();
        Contact contactTemp1 = new Contact();
        RecordType recordTypeTemp = [SELECT Id FROM RecordType WHERE Name='Daikin Applied' AND SObjectType='Contact'];
        contactTemp1.Eprise_Login_ID__c = 'RoesslKS1';
        contactTemp1.RecordTypeId = recordTypeTemp.Id;
        contactTemp1.AccountId = acct.Id;
        contactTemp1.Status__c = 'Active';
        contactTemp1.Email = 'kent.roessler@daikinapplied.com';
        contactTemp1.FirstName = 'Kent1';
        contactTemp1.LastName = 'Roessler1';
		contactTemp1.IE_Sync_Status__c = 'Processed'; 
        contactTemp1.IE_Contact__c = true;
		TriggerUtility.limitIntegrationBatch = true; // set this to true so contact trigger handler doesn't set status to Pending
        insert contactTemp1;
		TriggerUtility.limitIntegrationBatch = false; // reset back to false

        Subscription__c subTemp1 = new Subscription__c();
        subTemp1.Start_Date__c = currDateTime;
        subTemp1.End_Date__c = currDateTime.addMonths(12);
        subTemp1.Type__c = 'TechReadWrite';
        subTemp1.Active__c = true;
        subTemp1.Asset__c = parentAsset.Id;
        subTemp1.Buyer_ID__c = acct.Id;
        subTemp1.Renewal_Counter__c = 0;
        subTemp1.Connectivity_Type__c = 'Cellular';
        subTemp1.Renewal_Notice_Current_Month__c = false;
        subTemp1.Renewal_Notice_Next_Month__c = false;
        subTemp1.Renewal_Notice_Last_Month__c = false;
        subTemp1.Renewal_Notice_Next_Month_Plus_1__c = false;
        subTemp1.Renewal_Notice_Last_Month_Minus_1__c = false;
        insert subTemp1;
        
        Contact_Subscription__c contSubTemp1 = new Contact_Subscription__c();
        contSubTemp1.Role__c = 'RenewalAdministrator';
        contSubTemp1.Contact__c = contactTemp1.Id;
        contSubTemp1.Subscription__c = subTemp1.Id;
        contSubTemp1.Asset__c = parentAsset.Id;
        insert contSubTemp1;


        //call the service
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
 
        req.requestURI = 'https://cs8.salesforce.com/services/apexrest/RetrieveAsset?SerialNumber=123Test';  
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;
        RestContext.request.params.put('SerialNumber','123Test');
        RetrieveAssetService.ServiceAsset results = RetrieveAssetService.getAsset();
        System.debug(':::::results:::::'+results);
        
        //assert the results
        System.assertEquals('123Test',results.SerialNumber);

    }


	static testmethod void testGatewaySN()
    {
        //!!!!!!!!!!! Need to add this code snippet for AvaTax- AccountAddressTrigger to run successfully on Before Insert into the Account table !!!!!!!!!!!!!!!!!
        AVA_SFCORE__TaxNowSetting__c ts1 = new AVA_SFCORE__TaxNowSetting__c(); 
        ts1.AVA_SFCORE__Active_Setting__c = true; 
        ts1.Name='Test Account';
        insert ts1;
        

		// Create a Product for the Parent Asset
		Product2 prodTemp2 = null;
        prodTemp2 = new Product2();
        prodTemp2.Name = 'Test Prod2';
        prodTemp2.Vendor_Supplier__c = 'Test Vendor2';
        prodTemp2.IsActive = true;
        prodTemp2.Description = 'Test Description2';
        prodTemp2.DW_PCL_Description__c = 'Test DW PCL Description2';
        prodTemp2.Apttus_Product__c = true;
        prodTemp2.Product_Category__c = 'Test Category2';
        prodTemp2.ProductCode = 'RPS015A';
        insert prodTemp2;


        // Create an account for the assets
        Account acct = new Account(Name = 'Test');
        insert acct;
        

        // Create Parent Asset
        Asset parentAsset = new Asset(Name = 'test',
                             AccountId = acct.Id,
                             SerialNumber='123Test',
							 Product2Id = prodTemp2.Id,
							 GWotGo__c = false
                             );
        insert parentAsset;
        

        // Create Product2, and Related Asset
        Product2 prodTemp1 = null;
        prodTemp1 = new Product2();
        prodTemp1.Name = 'Intelligent Equipment Gateway';
		prodTemp1.ProductCode = 'IEGATE1';
        prodTemp1.Vendor_Supplier__c = 'Test Vendor1';
        prodTemp1.IsActive = true;
        prodTemp1.Description = 'Test Description1';
        prodTemp1.DW_PCL_Description__c = 'Test DW PCL Description1';
        prodTemp1.Apttus_Product__c = true;
        prodTemp1.Product_Category__c = 'Test Category1';
        insert prodTemp1;

        Asset relatedAsset = new Asset(Name = 'Intelligent Equipment Gateway', AccountId = acct.Id, SerialNumber = 'PO112711-2-075', Parent_Asset__c = parentAsset.Id);
        relatedAsset.Product2Id = prodTemp1.Id;
		relatedAsset.GWotGo__c = true;
		relatedAsset.Commissioned__c = true;
        relatedAsset.SIM_Card_Active__c = true;
		relatedAsset.SIM_Card_ICCID__c = '89011704258018735310';
		relatedAsset.MAC_Address__c = '00600c82c7c8';
        insert relatedAsset;


        // Create Contact, Subscription and Contact_Subscription
        Datetime currDateTime = Datetime.now();
        Contact contactTemp1 = new Contact();
        RecordType recordTypeTemp = [SELECT Id FROM RecordType WHERE Name='Daikin Applied' AND SObjectType='Contact'];
        contactTemp1.Eprise_Login_ID__c = 'RoesslKS1';
        contactTemp1.RecordTypeId = recordTypeTemp.Id;
        contactTemp1.AccountId = acct.Id;
        contactTemp1.Status__c = 'Active';
        contactTemp1.Email = 'kent.roessler@daikinapplied.com';
        contactTemp1.FirstName = 'Kent1';
        contactTemp1.LastName = 'Roessler1';
        insert contactTemp1;

        Subscription__c subTemp1 = new Subscription__c();
		subTemp1.GWotGoAsset__c = relatedAsset.Id;
        subTemp1.Start_Date__c = currDateTime;
        subTemp1.End_Date__c = currDateTime.addMonths(12);
        subTemp1.Type__c = 'TechReadWrite';
        subTemp1.Active__c = true;
        subTemp1.Asset__c = parentAsset.Id;
        subTemp1.Buyer_ID__c = acct.Id;
        subTemp1.Renewal_Counter__c = 0;
        subTemp1.Connectivity_Type__c = 'Cellular';
        subTemp1.Renewal_Notice_Current_Month__c = false;
        subTemp1.Renewal_Notice_Next_Month__c = false;
        subTemp1.Renewal_Notice_Last_Month__c = false;
        subTemp1.Renewal_Notice_Next_Month_Plus_1__c = false;
        subTemp1.Renewal_Notice_Last_Month_Minus_1__c = false;
        insert subTemp1;
        
        Contact_Subscription__c contSubTemp1 = new Contact_Subscription__c();
        contSubTemp1.Role__c = 'RenewalAdministrator';
        contSubTemp1.Contact__c = contactTemp1.Id;
        contSubTemp1.Subscription__c = subTemp1.Id;
        contSubTemp1.Asset__c = parentAsset.Id;
		contSubTemp1.GWotGoAsset__c = relatedAsset.Id;
		contSubTemp1.GWotGoPermAssoc__c = true;
        insert contSubTemp1;


        //call the service
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
 
        req.requestURI = 'https://cs8.salesforce.com/services/apexrest/RetrieveAsset?SerialNumber=PO112711-2-075';  
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;
        RestContext.request.params.put('SerialNumber','PO112711-2-075');
        RetrieveAssetService.ServiceAsset results = RetrieveAssetService.getAsset();
        System.debug(':::::results:::::'+results);
        
        //assert the results
        System.assertEquals('PO112711-2-075',results.SerialNumber);

    }


	static testmethod void testSupportedModels()
    {
        //call the isIESupportedModel() method with different models

        boolean results = RetrieveAssetService.isIESupportedModel('AGZ055D');
        
        //assert the results
        System.assertEquals(true, results);


		results = RetrieveAssetService.isIESupportedModel('AGZ190E');
		System.assertEquals(true, results);

		results = RetrieveAssetService.isIESupportedModel('WMC048DD');
		System.assertEquals(true, results);

		results = RetrieveAssetService.isIESupportedModel('WME0700SS');
		System.assertEquals(true, results);

		results = RetrieveAssetService.isIESupportedModel('WME1000DB');
		System.assertEquals(true, results);

		results = RetrieveAssetService.isIESupportedModel('WME092ADC');
		System.assertEquals(false, results);
    }
}