src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>United States</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Åland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia, Plurinational State of</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <label>State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Acklins</fullName>
                </value>
                <value>
                    <fullName>Acre</fullName>
                </value>
                <value>
                    <fullName>Aguascalientes</fullName>
                </value>
                <value>
                    <fullName>Ahuachapán</fullName>
                </value>
                <value>
                    <fullName>Aisén del General Carlos Ibáñez del Campo</fullName>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alagoas</fullName>
                </value>
                <value>
                    <fullName>Alajuela</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Alberta</fullName>
                </value>
                <value>
                    <fullName>Alta Verapaz</fullName>
                </value>
                <value>
                    <fullName>Alto Paraguay</fullName>
                </value>
                <value>
                    <fullName>Alto Paraná</fullName>
                </value>
                <value>
                    <fullName>Amambay</fullName>
                </value>
                <value>
                    <fullName>Amapá</fullName>
                </value>
                <value>
                    <fullName>Amazonas</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Ancash</fullName>
                </value>
                <value>
                    <fullName>Andaman and Nicobar Islands</fullName>
                </value>
                <value>
                    <fullName>Andhra Pradesh</fullName>
                </value>
                <value>
                    <fullName>Anhui</fullName>
                </value>
                <value>
                    <fullName>Anse la Raye</fullName>
                </value>
                <value>
                    <fullName>Antioquia</fullName>
                </value>
                <value>
                    <fullName>Antofagasta</fullName>
                </value>
                <value>
                    <fullName>Anzoátegui</fullName>
                </value>
                <value>
                    <fullName>Apure</fullName>
                </value>
                <value>
                    <fullName>Apurímac</fullName>
                </value>
                <value>
                    <fullName>Aragua</fullName>
                </value>
                <value>
                    <fullName>Arauca</fullName>
                </value>
                <value>
                    <fullName>Araucanía</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <description>This record type if for all records created by SFDC Users.</description>
        <label>Address</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/getGoogleMapsLocationAsync.cls
global with sharing class getGoogleMapsLocationAsync implements Schedulable {
  
  public static boolean isLocationUpdate = false;
  
  global void execute(SchedulableContext SC) {
      getGoogleMapsLocationAsync.batchUpdateLocations();
  }
    
  public static void batchUpdateLocations(){
      List<Address__c> adds = [select Id, Geographic_Location__latitude__s, Address_Line_1__c, City__c, Country__c, State_Province__c from Address__c where Geographic_Location__latitude__s = null and Address_Line_1__c != null and City__c != null and Country__c != null and State_Province__c != null LIMIT 100];
      if(adds.size()>0){
          Set<Id> ids = (new Map<Id,Address__c>(adds)).keySet();
          getLocation(ids);
          if(ids.size()==100){//more to process
              Datetime now = Datetime.now().addMinutes(3);
              System.schedule('AddressGeolocationUpdate_'+now.getTime(), now.second()+' ' + now.minute()+ ' '+now.hour()+' '+now.day()+' '+now.month()+' ? '+now.year(), new getGoogleMapsLocationAsync());
          }
      }
  }
  
  @future(callout=true)
  public static void getLocation(Set<Id> listObjectIds){
      //identify id's for object and then lookup up objects
      if(!listObjectIds.isEmpty()) {
            //Retrieve fields needed for the external call.
            List<Address__c> listJSONAddress = [select Id, Name, Address_Line_1__c, City__c, State_Province__c, Postal_Code__c, Country__c, Geographic_Location__latitude__s, Geographic_Location__longitude__s from Address__c where Id in :listObjectIds];
            List<Address__c> listToUpdate = new List<Address__c>();
            for(Address__c a : listJSONAddress){
                String address = '';
                //Only when lattitude and longitude is null and address is not null
                if(String.ISNOTBLANK(a.Address_Line_1__c)){
                    //Lookup address and update location with result
                    address += a.Address_Line_1__c +', ';
            
                    if (String.IsNotBlank(a.City__c))
                        address += a.City__c +', ';
            
                    if (String.IsNotBlank(a.State_Province__c))
                        address += a.State_Province__c +' ';
            
                    if (String.IsNotBlank(a.Postal_Code__c))
                        address += a.Postal_Code__c +', ';
            
                    if (String.IsNotBlank(a.Country__c))
                        address += a.Country__c;
                    address = EncodingUtil.urlEncode(address, 'UTF-8');
                    
                    double[] d = getCoordinates(address);
                    double lat = d[0];
                    double lon = d[1];
                    // update coordinates if we get back
                    if (true/*lat != null && lat != 0.0*/){
                        System.Debug('Updating Address: '+a.Name);
                        a.Geographic_Location__Latitude__s = lat;
                        a.Geographic_Location__Longitude__s = lon;
                        listToUpdate.add(a);
                        List<Address__c> otherAddresses = [select Id, Name, Address_Line_1__c, City__c, State_Province__c, Postal_Code__c, Country__c, Geographic_Location__latitude__s, Geographic_Location__longitude__s from Address__c where Id !=:a.Id and Geographic_Location__latitude__s !=:lat and Address_Line_1__c = :a.Address_Line_1__c and City__c = :a.City__c and State_Province__c = :a.State_Province__c and Postal_Code__c = :a.Postal_Code__c and Country__c = :a.Country__c and (Geographic_Location__latitude__s = null or Geographic_Location__latitude__s=0.0)];
                        for(Address__c oa :otherAddresses){
                            oa.Geographic_Location__Latitude__s = lat;
                            oa.Geographic_Location__Longitude__s = lon;
                            listToUpdate.add(oa);
                        }
                    }                    
                }
            }
            if(listToUpdate.size()>0){
                Set<Address__c> myset = new Set<Address__c>();
                List<Address__c> result = new List<Address__c>();
                myset.addAll(listToUpdate);
                result.addAll(myset);
                isLocationUpdate = true;
                System.debug('Trigger to be deactivated');
                update result;
                isLocationUpdate = false;
                System.debug('Trigger to be re-activated');
            }
        }   
     }
  
  @RemoteAction
  global static double[] getCoordinates(String address){
    double[] d = new double[]{0, 0};
  
    System.Debug('Address: '+address);
    // call webservice with address 
    // build callout
    Http h = new Http();
    HttpRequest req = new HttpRequest();
    req.setHeader('Accept','application/json');
    req.setEndpoint('https://maps.googleapis.com/maps/api/geocode/json?address='+address.replaceAll(' ', '+')+'&sensor=false&key=AIzaSyB2kMfdTgk--VRUVYLo4QrOJ7ImRvfibMQ');
    req.setMethod('GET');
    req.setTimeout(60000);

    try{
        // callout
        HttpResponse res = h.send(req);

        // parse coordinates from response
        JSONParser parser = JSON.createParser(res.getBody());

        while (parser.nextToken() != null) {
            //System.Debug('Token: '+parser.getText());
            if ((parser.getCurrentToken() == JSONToken.FIELD_NAME) &&
                (parser.getText() == 'location')){
                   parser.nextToken(); // object start

                   while (parser.nextToken() != JSONToken.END_OBJECT){
                       String txt = parser.getText();
                       //System.Debug('Location Token: '+txt);
                       parser.nextToken();
                       if (txt == 'lat'){
                           d[0] = parser.getDoubleValue();                           
                       } else if (txt == 'lng') {
                           d[1] = parser.getDoubleValue();
                       }
                   }
                   System.Debug ('Lat: '+ d[0] +' Lng: '+ d[1]);
                   break;
            }
        }

    } catch (Exception e) {
        System.Debug(Logginglevel.ERROR, 'EXCEPTION'+e.getMessage());
    }
    return d;
  }
  
    public getGoogleMapsLocationAsync() { }
    public getGoogleMapsLocationAsync(ApexPages.StandardController controller) { }
    public getGoogleMapsLocationAsync(ApexPages.StandardSetController controller) { }  
}