src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>IE_ID__c</fullName>
        <externalId>true</externalId>
        <label>IE ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Device_ID__c</fullName>
        <formula>IF (MAC_Address__c &lt;&gt; null, (&quot;00000000-00000000-&quot; &amp;  UPPER(LEFT( MAC_Address__c, 6)) &amp; &quot;FF-FF&quot; &amp;  UPPER(RIGHT(MAC_Address__c, 6))), &quot;&quot;)</formula>
        <inlineHelpText>Etherios Device ID passed to IE web service as MACAddress</inlineHelpText>
        <label>Device ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GWotGo__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Gateway on the Go 
Checked if the IE Gateway is a Gateway on the Go asset</description>
        <inlineHelpText>Gateway on the Go 
Checked if the IE Gateway is a Gateway on the Go asset</inlineHelpText>
        <label>GWotGo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IE_ID__c</fullName>
        <externalId>true</externalId>
        <label>IE ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MAC_Address__c</fullName>
        <description>Only applicable for IE Assets.  This is the MAC Address for the IE hardware on the asset.</description>
        <inlineHelpText>Only applicable for IE Assets.  This is the MAC Address for the IE hardware on the asset.</inlineHelpText>
        <label>MAC Address</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>SFDC Order record unique Id number. Auto-generated within SFDC.</inlineHelpText>
        <label>Order ID</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Equipment that this Asset is controlling or tied to.</inlineHelpText>
        <label>Parent Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Related Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SIM_Card_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to determine if the SIM card is active or not.</description>
        <label>SIM Card Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SIM_Card_ICCID__c</fullName>
        <description>Only applicable for IE Assets. This is for the IE hardware on the asset.</description>
        <inlineHelpText>Only applicable for IE Assets. This is for the IE hardware on the asset.</inlineHelpText>
        <label>SIM Card ICCID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tag__c</fullName>
        <inlineHelpText>Description entered by Sales Rep when selecting the product in Daikin Tools.</inlineHelpText>
        <label>Order Tag</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ATT_Jasper_API_REST_Services_Config__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>AT&amp;T Control Center Cisco Jasper API REST web services provides a set of REST APIs that allow you to perform essential device lifecycle and SMS functions.</description>
    <fields>
        <fullName>API_Key__c</fullName>
        <description>Jasper Control Center API Key</description>
        <label>API Key</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Base_URL__c</fullName>
        <description>The Control Center REST API is securely available over HTTPS. You can use the following base URL for all API calls.</description>
        <label>Base URL</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enterprise_Account_Id__c</fullName>
        <description>Unique identifier for the account that owns the devices you&apos;re searching for.</description>
        <label>Enterprise Account Id</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <description>Jasper Control Center User Name.</description>
        <label>User Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>ATT_Jasper_API_REST_Services_Config</label>
</CustomObject>

src/objects/Integration_Error__c.object
<CustomObject>
    <description>Object for logging integration errors.</description>
    <fields>
        <fullName>Direction__c</fullName>
        <label>Direction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Error_Description__c</fullName>
        <label>Error Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Integration_Object__c</fullName>
        <label>Integration Object</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Point__c</fullName>
        <label>Integration Point</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>IE</fullName>
                </value>
                <value>
                    <fullName>Intel TAS</fullName>
                </value>
                <value>
                    <fullName>PAR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Data__c</fullName>
        <label>Request Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Integration Error</label>
    <nameField>
        <displayFormat>EA-{00000000}</displayFormat>
        <label>Error ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Errors</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <description>Order information for TRC</description>
    <label>Order</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Object to identify and tie IE Subscriptions, to their appropriate Unit (Asset), Buyer (Account), and Users (Contacts).</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Pass this attribute to IE as part of 1.2 release.  Removes need to change the Subscription End Date from the contract term end date if it&apos;s necessary to remove access to Unit in IE prior to End Date.</description>
        <inlineHelpText>If checked, Subscription has started and is currently in effect.  Uncheck if Subscription should be made inactive for any reason. (e.g. Contract Expired, Non-payment, Legal)</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Intelligent Equipment Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Buyer_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Buyer ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Intelligent Equipment Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Connectivity_Type__c</fullName>
        <description>Subscription connectivity plan to either use AT&amp;T Cellular option with the SIM card active or customer&apos;s own WiFi/LAN option to send data to the Daikin IE cloud (MS Azure).</description>
        <label>Connectivity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cellular</fullName>
                </value>
                <value>
                    <fullName>WiFi/LAN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>IE_ID__c</fullName>
        <description>IE database unique record ID.</description>
        <externalId>true</externalId>
        <inlineHelpText>IE database unique record ID.</inlineHelpText>
        <label>IE ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IE_Subscription__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate the record pertains to the IE integration. This is set on import of record from Daikin IE Back Office database.</description>
        <inlineHelpText>Flag to indicate the record pertains to the IE integration. This is set on import of record from Daikin IE Back Office database.</inlineHelpText>
        <label>IE Subscription</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <formula>Asset__r.SerialNumber</formula>
        <label>Serial Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Term_Years__c</fullName>
        <label>Term (Years)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Intelligent Equipment system subscription type.</description>
        <inlineHelpText>Intelligent Equipment system subscription type.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CustomRead</fullName>
                </value>
                <value>
                    <fullName>TechReadWrite</fullName>
                </value>
                <value>
                    <fullName>TechRead</fullName>
                </value>
                <value>
                    <fullName>Daikin</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>S-{000000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Employee start date with company or date of employee&apos;s title/role change.  e.g. SSR becomes SCM.</description>
        <inlineHelpText>Employee start date with company or date of employee&apos;s title/role change.  e.g. SSR becomes SCM.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Batch_IE_DeactPrevMonthExpSubAndStartups.cls
/***********************************************************************
 Author       :   Kent Roessler
 Created Date :   Feb 16, 2017
 Modified     :   
 Description  :   Monthly batch job that deactivates the SIM card for previous
 month's expired subscriptions and any orders with startup access-only that 
 are past their expiration grace period and any WiFi/LAN subscriptions that
 are past their startup period.  Also, handles cases where user switches from
 Cellular to WiFi/LAN.

 Call the AT&T CC Web Service API to deactivate the SIM card.

 Call the IE API/Service Portal Web Service to update SIM Card Active 
 Status of the IE Unit (asset) in the MS Azure Cloud IE database.

 Set the Asset.SIM_Card_Active__c field to false.
************************************************************************/
global class Batch_IE_DeactPrevMonthExpSubAndStartups implements Database.Batchable<sObject>, Database.AllowsCallouts,  Database.Stateful {
	
	Datetime currDateTime = Datetime.now(); // current date and time in the GMT time zone

	// Create custom exception to throw if there are any errors
    public class Batch_IE_DeactPrevMonthExpSubAndStartupsException extends Exception {}

	
	global Batch_IE_DeactPrevMonthExpSubAndStartups() {

	}
	

	global Database.QueryLocator start(Database.BatchableContext BC) {
		// Since we are processing the gateway asset for a subscription and their are usually 2 Subscription records (TechReadWrite, CustomRead) 
		// or just one of type Standard for an order, just query the subscriptions whose type is TechReadWrite or Standard since all of them are 
		// associated with the gateway asset.
		return Database.getQueryLocator([select Id
                                         , Name
                                         , Start_Date__c
                                         , End_Date__c
                                         , Asset__c
                                         , Type__c
                                         , Active__c
                                         , Serial_Number__c
                                         , IE_Subscription__c
                                         , Buyer_ID__c
                                         , IE_ID__c
                                         , LastModifiedDate
                                         , Connectivity_Type__c
                                         , Term_Years__c
										 , Asset__r.Name
                                         from Subscription__c
                                         where IE_Subscription__c = true AND (Type__c = 'TechReadWrite' OR Type__c = 'Standard') AND 
										 ((End_Date__c = LAST_MONTH AND Active__c = false) OR (Connectivity_Type__c = 'WiFi/LAN' AND Start_Date__c < LAST_N_MONTHS:6))]);
	}


   	global void execute(Database.BatchableContext BC, List<Subscription__c> subscriptions) {
   		boolean hasErrors = false;

   		map<Id, Asset> assetMap = new map<Id, Asset>();
	    map<Id, Address__c> addressMap = new map<Id, Address__c>();
    	list<Integration_Error__c> integrationErrorList = new list<Integration_Error__c>();
    	

   		try {
   			// Error message string that is used to collect any errors/exceptions information
    		String errorMsg = 'Batch_IE_DeactPrevMonthExpSubAndStartups errors: ';
    		

	   		// Pull the AT&T credentials from a custom setting 
			ATT_Jasper_API_REST_Services_Config__c serviceConfig = ATT_Jasper_API_REST_Services_Config__c.getInstance();

			IERenewal_ATTJasperAPIServiceResponseObj putDeviceRespObj = new IERenewal_ATTJasperAPIServiceResponseObj();
			IERenewal_ATTJasperAPIServiceAccess restPutDevice = new IERenewal_ATTJasperAPIServiceAccess(serviceConfig.Base_URL__c, serviceConfig.API_Key__c, 'devices', serviceConfig.User_Name__c, serviceConfig.Enterprise_Account_Id__c);

			list<Asset> inactiveSIMCardAssets = new list<Asset>();


			// Bulkify Parent Asset SOQL query
			map<Id, Asset> parentAssetMap = new map<Id, Asset>();
	        set<Id> parentAssetIds = new set<Id>();
	        for (Subscription__c s : subscriptions)
	        {
	            if ((s.Asset__c != null) && (s.Asset__r.Name != 'Dummy GWotGo Unit Asset') && (s.Asset__r.Name != 'Holding GWotGo Unit Asset'))
	                parentAssetIds.add(s.Asset__c);
	        }
	        for (Asset a : [SELECT Id, Order__c, AccountId, Product2.ProductCode, Product2.Name, SerialNumber, Tag__c from Asset where Id in :parentAssetIds])
	        	parentAssetMap.put(a.Id, a);


	        // Bulkify Gateway Asset SOQL query
			map<Id, Asset> gatewayAssetMap = new map<Id, Asset>();
	        set<Id> gatewayParentAssetIds = new set<Id>();
	        for (Asset a : parentAssetMap.values())
	        {
	            if (a.Id != null)
	                gatewayParentAssetIds.add(a.Id);
	        }
	        for (Asset a : [SELECT Id, Parent_Asset__c, SIM_Card_Active__c, SIM_Card_ICCID__c, MAC_Address__c, Device_ID__c, Status, GWotGo__c from Asset Where (Name = 'Intelligent Equipment Gateway' OR Product2.Name = 'Intelligent Equipment Gateway') AND Status != 'Obsolete' AND Parent_Asset__c in :gatewayParentAssetIds])
	        	gatewayAssetMap.put(a.Parent_Asset__c, a);



			for (Subscription__c s : subscriptions)
			{
				Asset parentAsset=null;
				Asset gatewayAsset=null;
				String simCardICCID = null;

				parentAsset = parentAssetMap.get(s.Asset__c);

				if (parentAsset != null) {
					gatewayAsset = gatewayAssetMap.get(parentAsset.Id);

					if (gatewayAsset != null) {
						gatewayAsset.SIM_Card_Active__c = false;
	                	inactiveSIMCardAssets.add(gatewayAsset);

	                	if (String.isNotBlank(gatewayAsset.SIM_Card_ICCID__c)) {
	                		if (!gatewayAsset.SIM_Card_ICCID__c.trim().isNumeric()) {
				                // Sim Card ICCID should be a 20 digit number, remove any leading or trailing text
				                // ASCII code integer values for characters '0' to '9' are 48 to 57
				                Integer[] chars = gatewayAsset.SIM_Card_ICCID__c.trim().getChars();
				                list<Integer> charArray = new List<Integer>();
				                for (Integer i : chars) {
				                  if ((i >= 48) && (i <= 57))
				                    charArray.add(i);
				                }

				                simCardICCID = String.fromCharArray(charArray);
				            }
				            else {
				              	simCardICCID = gatewayAsset.SIM_Card_ICCID__c.trim();
				            }
	                	}
	                	
			              
			            if (simCardICCID != null) {
			                if (!Test.isRunningTest()) {
			                    // Test isn't running so call the service
			                    putDeviceRespObj = restPutDevice.updateDeviceByICCID(simCardICCID, 'DEACTIVATED', null, null, null, null, null, integrationErrorList);

			                    if (putDeviceRespObj.getResponseCode() != 200) {
	                      			hasErrors = true;
			            			errorMsg = errorMsg + ' | ' + 'SIM Card ICCID = ' + simCardICCID + ', Response code = ' + putDeviceRespObj.getResponseCode() + ', from call to deactivate the sim card!';
	                      		}
			                }
			                else {
			                    // Test is running so mock a response
			                    putDeviceRespObj.setResponseCode(200);
			                    putDeviceRespObj.setResponseData('{"iccid":"89011704258018735310"}');
			                }
			            }
					}
				}
			}


			if (!hasErrors) {
				//update the inactive SIM Card assets
	      		if (inactiveSIMCardAssets.size() > 0) {
	      			IERenewal_ExtWebServiceCallouts.syncIeCloudSIMCardActiveStatus(inactiveSIMCardAssets, assetMap, addressMap, integrationErrorList);
	          		update inactiveSIMCardAssets;
	      		}
			}

			if (hasErrors) {
				throw new Batch_IE_DeactPrevMonthExpSubAndStartupsException(errorMsg);
			}
			
   		}
   		catch (Exception e) {
   			System.debug(logginglevel.error, 'Batch_IE_DeactPrevMonthExpSubAndStartups Exception: ' + e);
   			hasErrors = true;
   			integrationErrorList.add(new Integration_Error__c(Direction__c = ''
       															, Error_Description__c = 'General Exception from Batch_IE_DeactPrevMonthExpSubAndStartups'
       															, Integration_Object__c = 'Asset'
       															, Integration_Point__c = 'IE'
       															, Request_Data__c = e.getMessage() ));
   		}
   		finally {
   			if (!hasErrors) {
   				if (assetMap.size() > 0)
   					update assetMap.values();

   				if (addressMap.size() > 0)
   					update addressMap.values();
   			}

   			if(integrationErrorList.size() > 0) {
   				System.debug(logginglevel.error, 'Batch_IE_DeactPrevMonthExpSubAndStartups integrationErrorList: ' + integrationErrorList);
       			insert integrationErrorList;
       		}
   		}

	}

	
	global void finish(Database.BatchableContext BC) {
		
	}
	
}