src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>United States</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Åland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia, Plurinational State of</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Entity_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address Entity Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <label>State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Acklins</fullName>
                </value>
                <value>
                    <fullName>Acre</fullName>
                </value>
                <value>
                    <fullName>Aguascalientes</fullName>
                </value>
                <value>
                    <fullName>Ahuachapán</fullName>
                </value>
                <value>
                    <fullName>Aisén del General Carlos Ibáñez del Campo</fullName>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alagoas</fullName>
                </value>
                <value>
                    <fullName>Alajuela</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Alberta</fullName>
                </value>
                <value>
                    <fullName>Alta Verapaz</fullName>
                </value>
                <value>
                    <fullName>Alto Paraguay</fullName>
                </value>
                <value>
                    <fullName>Alto Paraná</fullName>
                </value>
                <value>
                    <fullName>Amambay</fullName>
                </value>
                <value>
                    <fullName>Amapá</fullName>
                </value>
                <value>
                    <fullName>Amazonas</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Ancash</fullName>
                </value>
                <value>
                    <fullName>Andaman and Nicobar Islands</fullName>
                </value>
                <value>
                    <fullName>Andhra Pradesh</fullName>
                </value>
                <value>
                    <fullName>Anhui</fullName>
                </value>
                <value>
                    <fullName>Anse la Raye</fullName>
                </value>
                <value>
                    <fullName>Antioquia</fullName>
                </value>
                <value>
                    <fullName>Antofagasta</fullName>
                </value>
                <value>
                    <fullName>Anzoátegui</fullName>
                </value>
                <value>
                    <fullName>Apure</fullName>
                </value>
                <value>
                    <fullName>Apurímac</fullName>
                </value>
                <value>
                    <fullName>Aragua</fullName>
                </value>
                <value>
                    <fullName>Arauca</fullName>
                </value>
                <value>
                    <fullName>Araucanía</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <description>This record type if for all records created by SFDC Users.</description>
        <label>Address</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Asset_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Asset_Address__c.object
<CustomObject>
    <description>Object to tie multiple Assets to a single postal Address record while allowing Addresses and their related Assets to be broken down into more granular locations such as Building, Floor or Suite that are part of a single postal Address.</description>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Asset Addresses</relationshipLabel>
        <relationshipName>Asset_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Asset Address</label>
    <nameField>
        <displayFormat>EA-{000000000}</displayFormat>
        <label>Asset Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/getGoogleMapsLocationAsyncTest.cls
@isTest 
global class getGoogleMapsLocationAsyncTest implements HttpCalloutMock{

    public static String getBody(){
        String body = '';
        body += '{';
        body += '   "results" : [';
        body += '      {';
        body += '         "address_components" : [';
        body += '            {';
        body += '               "long_name" : "13600",';
        body += '               "short_name" : "13600",';
        body += '               "types" : [ "street_number" ]';
        body += '            },';
        body += '            {';
        body += '               "long_name" : "Industrial Park Boulevard",';
        body += '               "short_name" : "Industrial Park Blvd",';
        body += '               "types" : [ "route" ]';
        body += '            },';
        body += '            {';
        body += '               "long_name" : "Minneapolis",';
        body += '               "short_name" : "Minneapolis",';
        body += '               "types" : [ "locality", "political" ]';
        body += '            },';
        body += '            {';
        body += '               "long_name" : "Hennepin County",';
        body += '               "short_name" : "Hennepin County",';
        body += '               "types" : [ "administrative_area_level_2", "political" ]';
        body += '            },';
        body += '            {';
        body += '               "long_name" : "Minnesota",';
        body += '               "short_name" : "MN",';
        body += '               "types" : [ "administrative_area_level_1", "political" ]';
        body += '            },';
        body += '            {';
        body += '               "long_name" : "United States",';
        body += '               "short_name" : "US",';
        body += '               "types" : [ "country", "political" ]';
        body += '            },';
        body += '            {';
        body += '               "long_name" : "55441",';
        body += '               "short_name" : "55441",';
        body += '               "types" : [ "postal_code" ]';
        body += '            },';
        body += '            {';
        body += '               "long_name" : "3743",';
        body += '               "short_name" : "3743",';
        body += '               "types" : [ "postal_code_suffix" ]';
        body += '            }';
        body += '         ],';
        body += '         "formatted_address" : "13600 Industrial Park Blvd, Minneapolis, MN 55441, USA",';
        body += '         "geometry" : {';
        body += '            "location" : {';
        body += '               "lat" : 45.0039908,';
        body += '               "lng" : -93.4528457';
        body += '            },';
        body += '            "location_type" : "ROOFTOP",';
        body += '            "viewport" : {';
        body += '               "northeast" : {';
        body += '                  "lat" : 45.00533978029149,';
        body += '                  "lng" : -93.4514967197085';
        body += '               },';
        body += '               "southwest" : {';
        body += '                  "lat" : 45.0026418197085,';
        body += '                  "lng" : -93.45419468029151';
        body += '               }';
        body += '            }';
        body += '         },';
        body += '         "partial_match" : true,';
        body += '         "place_id" : "ChIJnXiWoDhKs1IRFEYzsG4s5mo",';
        body += '         "types" : [ "street_address" ]';
        body += '      }';
        body += '   ],';
        body += '   "status" : "OK"';
        body += '}';
        
        return body;
    }
    
    global HTTPResponse respond(HTTPRequest req) {
        HttpResponse res = new HttpResponse();
        res.setHeader('Content-Type', 'applicaton/json');
        res.setBody(getBody());        
        res.setStatusCode(200);
        return res;    
    }
     static testMethod void updateAddress() {
       Test.startTest();
       Test.setMock(HttpCalloutMock.class, new getGoogleMapsLocationAsyncTest());

       AVA_SFCORE__TaxNowSetting__c ts1 = new AVA_SFCORE__TaxNowSetting__c();
       ts1.AVA_SFCORE__Active_Setting__c = true;
       ts1.Name='Test Account';
       insert ts1;
     
       Account account = new Account();
       account.Name = 'TEST';
       account.Type = 'Other';
       account.BillingStreet = '13600 Industrial Park Blvd';
       account.BillingCity = 'Plymouth';
       account.BillingCountry = 'United States';
       account.BillingState = 'Minnesota';
       account.BillingPostalCode = '55441';
       insert account;
       
       Address__c address = new Address__c();
       address.Entity_Account__c=account.Id;
       address.Address_Line_1__c='13600 Industrial Park Blvd';
       address.City__c = 'Plymouth';
       address.Country__c = 'United States';
       address.State_Province__c = 'Minnesota';
       address.Postal_Code__c = '55441';
       insert address;

       Asset asset = new Asset();
       asset.Name = 'TEST';
       asset.AccountId = account.id;
       asset.Asset_Address__c = address.id;
       insert asset;
       
       getGoogleMapsLocationAsync.batchUpdateLocations();
       Test.stopTest();
       address = [select Id, Geographic_Location__Latitude__s, Geographic_Location__Longitude__s from Address__c where Id = :address.Id];

       System.assertEquals(45.0039908, address.Geographic_Location__Latitude__s);
       System.assertEquals(-93.4528457, address.Geographic_Location__Longitude__s);
    }
    static testMethod void FindNearbyLeads() {
        
        FindNearbyLeads.getNearby(null, null);
        FindNearbyLeads.getNearbyAccounts(null, null);
        FindNearbyLeads.getNearbyAssets(null, null);

       AVA_SFCORE__TaxNowSetting__c ts1 = new AVA_SFCORE__TaxNowSetting__c();
       ts1.AVA_SFCORE__Active_Setting__c = true;
       ts1.Name='Test Account';
       insert ts1;
     
       Account account = new Account();
       account.Name = 'TEST';
       account.Type = 'Other';
       account.BillingStreet = '13600 Industrial Park Blvd';
       account.BillingCity = 'Plymouth';
       account.BillingCountry = 'United States';
       account.BillingState = 'Minnesota';
       account.BillingPostalCode = '55441';
       insert account;
       
       Address__c address = new Address__c();
       address.Entity_Account__c=account.Id;
       address.Address_Line_1__c='13600 Industrial Park Blvd';
       address.City__c = 'Plymouth';
       address.Country__c = 'United States';
       address.State_Province__c = 'Minnesota';
       address.Postal_Code__c = '55441';
       insert address;

       Asset asset = new Asset();
       asset.Name = 'TEST';
       asset.AccountId = account.id;
       asset.Asset_Address__c = address.id;
       insert asset;

        System.assertNotEquals(null, FindNearByLeads.createLeadFromAsset(asset.Id));

        ApexPages.StandardController sc = new ApexPages.StandardController(asset);
        new FindNearbyLeads(sc);
        
        List<Asset> l = new List<Asset>();
        l.add(asset);
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(l);
        new FindNearbyLeads(ssc);
    }
}