src/objects/Approval_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>FPA_Total_Drafting_Hours__c</fullName>
        <label>FPA Total Drafting Hours</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FPA_Total_Engineering_Hours__c</fullName>
        <label>FPA Total Engineering Hours</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FPA_Total_Manufacturing_Hours__c</fullName>
        <label>FPA Total Manufacturing Hours</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_QTY_of_Units_On_Single_Line_Item__c</fullName>
        <label>Max QTY of Units On Single Line Item</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Total_Material_Cost_for_Single_Line__c</fullName>
        <label>Max Total Material Cost for Single Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QTY_of_line_Item_with_Specials__c</fullName>
        <label>QTY of line Item with Specials</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Approval Criteria</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Approval Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Factory_Pricing_Authorization__c.object
<CustomObject>
    <fields>
        <fullName>FPA_Number__c</fullName>
        <label>FPA Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_QTY_of_Units_On_Single_Line_Item__c</fullName>
        <label>Max QTY of Units On Single Line Item</label>
        <summarizedField>FPA_Link__c.Quantity__c</summarizedField>
        <summaryForeignKey>FPA_Link__c.FPA__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>QTY_of_line_Item_with_Specials__c</fullName>
        <label>QTY of line Item with Specials</label>
        <summarizedField>FPA_Link__c.Quantity__c</summarizedField>
        <summaryForeignKey>FPA_Link__c.FPA__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Non Bid Process</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <isActive>false</isActive>
                    <label>Pending</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FPA</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FPAs</pluralLabel>
    <recordTypes>
        <fullName>Read_only</fullName>
        <active>true</active>
        <label>Read only</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FPA_Approval__c.object
<CustomObject>
    <fields>
        <fullName>SFO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFO</label>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipLabel>Approvers</relationshipLabel>
        <relationshipName>FPA_Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approver</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FPA_Link__c.object
<CustomObject>
    <fields>
        <fullName>FPA_Total_Drafting_Hours__c</fullName>
        <label>FPA Total Drafting Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FPA_Total_Engineering_Hours__c</fullName>
        <label>FPA Total Engineering Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FPA_Total_Manufacturing_Hours__c</fullName>
        <label>FPA Total Manufacturing Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_QTY_of_Units_On_Single_Line_Item__c</fullName>
        <label>Max QTY of Units On Single Line Item</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Total_Material_Cost_for_Single_Line__c</fullName>
        <label>Max Total Material Cost for Single Line</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QTY_of_line_Item_with_Specials__c</fullName>
        <label>QTY of line Item with Specials</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SFO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFO</label>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipName>Related_SFO</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Unit Detail</label>
    <nameField>
        <label>Unit Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FPA_Persona__c.object
<CustomObject>
    <fields>
        <fullName>User_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <inlineHelpText>Uniquely identifies each user</inlineHelpText>
        <label>User Id</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Sales Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Persona</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Only Active Formats is available for FPA and SFO Selection</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Format</label>
    <nameField>
        <label>Format Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Related_SFO__c.object
<CustomObject>
    <fields>
        <fullName>SFO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFO</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Special_Feature_Option__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Read Only</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipLabel>Related SFO</relationshipLabel>
        <relationshipName>Related_SFO1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Detail</label>
        <referenceTo>FPA_Link__c</referenceTo>
        <relationshipLabel>Related SFO</relationshipLabel>
        <relationshipName>Related_SFO</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Related SFO</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Related SFO  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related SFO</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SFO_Dynamic_Fields__c.object
<CustomObject>
    <fields>
        <fullName>Field_Value__c</fullName>
        <label>Field Value</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFO_Field__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>SFO Field</label>
        <referenceTo>SFO_Fields__c</referenceTo>
        <relationshipName>SFO_Dynamic_Fields</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SFO__c</fullName>
        <label>SFO</label>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipName>SFO_Dynamic_Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>Text(SFO__r.Status__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Special Feature Dynamic Fields</label>
    <nameField>
        <label>Field Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Special Feature Dynamic Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SFO_Fields__c.object
<CustomObject>
    <fields>
        <fullName>Field_Data_Type__c</fullName>
        <label>Field Data Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>Formula</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                    <isActive>false</isActive>
                    <label>Checkbox</label>
                </value>
                <value>
                    <fullName>Date</fullName>
                    <isActive>false</isActive>
                    <label>Date</label>
                </value>
                <value>
                    <fullName>Date/Time</fullName>
                    <isActive>false</isActive>
                    <label>Date/Time</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Only Active Dynamic fields will be available for selection at Special Feature level (Level 4)</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Dynamic Field</label>
    <nameField>
        <label>Field Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dynamic Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Special_Feature_Option__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                    <isActive>false</isActive>
                    <label>Obsolete</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                    <isActive>false</isActive>
                    <label>Submitted for Approval</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Records</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Records</pluralLabel>
    <recordTypes>
        <fullName>Read_Only</fullName>
        <active>true</active>
        <description>Holds Locked Records</description>
        <label>Read Only</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/FPAApprovalDetailTest.cls
@isTest
public class FPAApprovalDetailTest{
   
    //Test Method for Approval Details and Approval Criteria Class
    
    
    public static testmethod void  FPAApprovalDetailMethod(){
        List<SFO_Dynamic_Fields__c> DynamicFields = new List<SFO_Dynamic_Fields__c>();
        List<Approval_Criteria__c>  ApprovalCriteria = new List<Approval_Criteria__c>();
        List<FPA_Link__c> UnitDetailObject = new List<FPA_Link__c>();
        Map<String, Factory_Pricing_Authorization__c> FPAMap = new Map<String, Factory_Pricing_Authorization__c>();
        Id recordTypeId =
            Schema.SObjectType.Special_Feature_Option__c.getRecordTypeInfosByDeveloperName()
            .get('Read_Only').getRecordTypeId();
        Special_Feature_Option__c TestSFO = new Special_Feature_Option__c();
        TestSFO.Status__c='Approved';
        TestSFO.RecordTypeId=recordTypeId;
        insert TestSFO;
        
        SFO_Fields__c SFOField = new SFO_Fields__c();
        SFOField.Name='Material Cost';
        SFOField.Field_Data_Type__c='Number';
        insert SFOField;
        
        //Creating the Dynamic Fields for the SFO
        
        SFO_Dynamic_Fields__c DynamicField1 = new SFO_Dynamic_Fields__c();
        DynamicField1.Field_Value__c='100';
        DynamicField1.SFO__c=TestSFO.Id;
        DynamicField1.Name='Material Cost';
        DynamicField1.SFO_Field__c=SFOField.Id;
        DynamicFields.add(DynamicField1);
        
        SFO_Dynamic_Fields__c DynamicField2 = new SFO_Dynamic_Fields__c();
        DynamicField2.Field_Value__c='101';
        DynamicField2.SFO__c=TestSFO.Id;
        DynamicField2.SFO_Field__c=SFOField.Id;
        DynamicField2.Name='Drafting Hours';
        DynamicFields.add(DynamicField2);
        
        SFO_Dynamic_Fields__c DynamicField3 = new SFO_Dynamic_Fields__c();
        DynamicField3.Field_Value__c='104';
        DynamicField3.SFO__c=TestSFO.Id;
        DynamicField3.SFO_Field__c=SFOField.Id;
        DynamicField3.Name='Manufacturing Hours';
        DynamicFields.add(DynamicField3);
        
        SFO_Dynamic_Fields__c DynamicField4 = new SFO_Dynamic_Fields__c();
        DynamicField4.Field_Value__c='106';
        DynamicField4.SFO__c=TestSFO.Id;
        DynamicField4.SFO_Field__c=SFOField.Id;
        DynamicField4.Name='Engineering Hours';
        DynamicFields.add(DynamicField4);
        
        insert DynamicFields;
        
        Product__c ProductObj=TestUtility.createProductFormat();
        ProductObj.IsActive__c=true;
        insert productObj;
        
        FPA_Persona__c FPAPersonRepObj=TestUtility.createFPAPersona('Rep',null);
        FPAPersonRepObj.User_Id__c='test 1234';
        insert FPAPersonRepObj;
       
        //Insert FPA(Factory_Pricing_Authorization)
        
        UtilityClass.getSObjectRelatedFields('FPA_Approval__c','FPA_Person__r.Name','',true);
        Factory_Pricing_Authorization__c FPAObj=TestUtility.createFPA(FPAPersonRepObj.Id,ProductObj.Id);
        insert FPAobj;
        FPAMap.put(FPAObj.Id,FPAObj);
  
        //Insert Approval Criteria Related to the product
        
        Approval_Criteria__c AppcriteriaA = TestUtility.ApprovalCriteria('A',ProductObj.Id,'1000','1000','1000','1000','1000','1000','1000','1000','1000');
        ApprovalCriteria.add(AppcriteriaA);
        Approval_Criteria__c AppcriteriaB = TestUtility.ApprovalCriteria('B',ProductObj.Id,'100','100','100','700','100','100','100','100','700');
        ApprovalCriteria.add(AppcriteriaB);
        Approval_Criteria__c AppcriteriaC = TestUtility.ApprovalCriteria('C',ProductObj.Id,'10','10','10','500','10','10','10','10','500');
        ApprovalCriteria.add(AppcriteriaC);
        Approval_Criteria__c AppcriteriaD = TestUtility.ApprovalCriteria('D',ProductObj.Id,Null,Null,Null,Null,Null,Null,Null,Null,Null);
        ApprovalCriteria.add(AppcriteriaD);
        insert ApprovalCriteria;
        
        //Unit Details Creation
        
        FPA_Link__c UnitDetailObj =TestUtility.CreatesfpaLink(FPAObj.Id);
        insert UnitDetailObj;
        
        
        List<Related_SFO__c> SFOList = new List<Related_SFO__c>();
        for(Integer i=0; i<50; i++){
            Related_SFO__c RelatedSFO = new Related_SFO__c();
            RelatedSFO.SFO__c=TestSFO.Id;
            RelatedSFO.Unit_Detail__c=UnitDetailObj.Id;
            SFOList.add(RelatedSFO);
        }
        insert SFOList;
        System.assertEquals(50, SFOList.size());
        FPAApprovalDetails.getFPADynamicFields(SFOList);
        FPAApprovalDetails.updateUnitTagOnDelete(SFOList);
        
        //updating the unitdetails with the Approver Criteria of the FPA
        
        UnitDetailObj.Max_QTY_of_Units_On_Single_Line_Item__c=800;
        UnitDetailObj.FPA_Total_Engineering_Hours__c=150;
        UnitDetailObj.FPA_Total_Manufacturing_Hours__c=150;
        UnitDetailObj.Max_Total_Material_Cost_for_Single_Line__c=150;
        UnitDetailObj.QTY_of_line_Item_with_Specials__c=800;
        UnitDetailObj.FPA_Total_Drafting_Hours__c=150;
        
        update UnitDetailObj;
     
        FPAobj.FPA_Number__c='998123456BC';  
        FPAobj.Approval_Level__c='A';
        update FPAobj;
        
        System.assertEquals(FPAobj.Approval_Level__c,'A');
    } 
}