src/objects/Approval_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Level__c</fullName>
        <inlineHelpText>Please select one level from the picklist and define the approval level</inlineHelpText>
        <label>Approval Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FPA_Total_Drafting_Hours__c</fullName>
        <label>FPA Total Drafting Hours</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FPA_Total_Engineering_Hours__c</fullName>
        <label>FPA Total Engineering Hours</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FPA_Total_Manufacturing_Hours__c</fullName>
        <label>FPA Total Manufacturing Hours</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Approval Criterias</relationshipLabel>
        <relationshipName>Approval_Criterias</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Max_QTY_of_Units_On_Single_Line_Item__c</fullName>
        <label>Max QTY of Units On Single Line Item</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Total_Drafting_Hours_per_Single_l__c</fullName>
        <label>Max Total Drafting Hours per Single l</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Total_Engineering_Hours_for_Single__c</fullName>
        <label>Max Total Engineering Hours for Single</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Total_Manufacturing_Hours_for_Single__c</fullName>
        <label>Max Total Manufacturing Hours for Single</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Total_Material_Cost_for_Single_Line__c</fullName>
        <label>Max Total Material Cost for Single Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Approval Criteria</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Approval Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <label>Format</label>
    <nameField>
        <label>Format Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ApprovalCriteriaTriggerTest.cls
@isTest
public class ApprovalCriteriaTriggerTest 
{
    
    @testSetup static void setup() {
        Product__c prod =new Product__c();
        prod.Name='Test Format'; 
        insert prod;
    }
    
    static testMethod void testApprovalLevelDupPreventer()
    {
        
        Product__c formatObj=[Select id from Product__c limit 1];
        
        list<Approval_Criteria__c> appList =new list<Approval_Criteria__c> (); 
        Approval_Criteria__c   appCriteriaRecord = new Approval_Criteria__c();
        {
            appCriteriaRecord.Approval_Level__c='A';
            appCriteriaRecord.Format__c =formatObj.id;
            appCriteriaRecord.FPA_Total_Drafting_Hours__c='10';
            appCriteriaRecord.FPA_Total_Engineering_Hours__c='30';
            appCriteriaRecord.FPA_Total_Manufacturing_Hours__c='20';
            appCriteriaRecord.Max_QTY_of_Units_On_Single_Line_Item__c='10';
            appCriteriaRecord.Max_Total_Drafting_Hours_per_Single_l__c='15';
            appCriteriaRecord.Max_Total_Engineering_Hours_for_Single__c='20';
            appCriteriaRecord.Max_Total_Material_Cost_for_Single_Line__c='30';
            appCriteriaRecord.Max_Total_Manufacturing_Hours_for_Single__c='20';
            appList.add(appCriteriaRecord);
        }
        insert appList;
        
        Approval_Criteria__c ac =[select id,name,Approval_Level__c from Approval_Criteria__c limit 1];
        system.assertEquals(ac.Approval_Level__c,'A');
    }
    
     static testMethod void testApprovalLevelDupUpdate()
    {
        Product__c formatObj=[Select id from Product__c limit 1];
        Approval_Criteria__c  appCriteriaRecordDup = new  Approval_Criteria__c();
        {
            appCriteriaRecordDup.Approval_Level__c='A';
            appCriteriaRecordDup.Format__c =formatObj.id;
            appCriteriaRecordDup.FPA_Total_Drafting_Hours__c='10';
            insert appCriteriaRecordDup;
            appCriteriaRecordDup.FPA_Total_Drafting_Hours__c='20';
            update appCriteriaRecordDup;
        }
        
    }
    
}