src/objects/APTPS_Configurable_Variables__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is supposed to hold configurable constants used in apex classes, pages.</description>
    <fields>
        <fullName>APTPS_RowCount__c</fullName>
        <label>RowCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>APTPS Configurable Variables</label>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Model__c</fullName>
        <formula>Asset.Product2.ProductCode</formula>
        <inlineHelpText>Serial Numbers Model</inlineHelpText>
        <label>Model</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MA_Model__c.object
<CustomObject>
    <fields>
        <fullName>Equipment_Group__c</fullName>
        <label>Equipment Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                    <default>true</default>
                    <label>A</label>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>F</fullName>
                </value>
                <value>
                    <fullName>G</fullName>
                </value>
                <value>
                    <fullName>H</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
                <value>
                    <fullName>J</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Equipment_Type__c</fullName>
        <label>Equipment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Absorption Chillers</fullName>
                </value>
                <value>
                    <fullName>AC Screw</fullName>
                </value>
                <value>
                    <fullName>Air Cleaners</fullName>
                </value>
                <value>
                    <fullName>Air Handlers &amp; Make-up Air Units</fullName>
                </value>
                <value>
                    <fullName>Airside Heat Recovery - Fixed Plate</fullName>
                </value>
                <value>
                    <fullName>Airside Heat Recovery Ventilator-Wheel</fullName>
                </value>
                <value>
                    <fullName>Back Flow Prevention</fullName>
                </value>
                <value>
                    <fullName>Blow Down Heat Recovery</fullName>
                </value>
                <value>
                    <fullName>Boilers - Electric Type</fullName>
                </value>
                <value>
                    <fullName>Boilers- Fossil Fuel Types</fullName>
                </value>
                <value>
                    <fullName>Centrifugal Chillers - Negative (low) Pressure</fullName>
                </value>
                <value>
                    <fullName>Centrifugal Chillers - Positive (high) Pressure</fullName>
                </value>
                <value>
                    <fullName>Computer Room Air Conditioning Units - (CRAC)</fullName>
                </value>
                <value>
                    <fullName>Cooling Towers</fullName>
                </value>
                <value>
                    <fullName>De-Humidifiers - Desiccant or Refrigerant Type</fullName>
                </value>
                <value>
                    <fullName>Domestic Water Heaters</fullName>
                </value>
                <value>
                    <fullName>Dry Coolers - Air cooled fluid cooler</fullName>
                </value>
                <value>
                    <fullName>Exhaust &amp; Return Fans</fullName>
                </value>
                <value>
                    <fullName>Fan Coil Units or Unit Ventilator</fullName>
                </value>
                <value>
                    <fullName>Flue Gas Heat Recovery (Stack economizer)</fullName>
                </value>
                <value>
                    <fullName>Furnaces</fullName>
                </value>
                <value>
                    <fullName>Heat Exchangers - Plate &amp; Frame / Shell &amp; Tube</fullName>
                </value>
                <value>
                    <fullName>Humidifier Units - Electric &amp; Steam</fullName>
                </value>
                <value>
                    <fullName>Magnetic Bearing Centrifugal Chillers</fullName>
                </value>
                <value>
                    <fullName>Pneumatic Air Compressor System</fullName>
                </value>
                <value>
                    <fullName>PTAC - Packaged Through the wall Air Conditioners</fullName>
                </value>
                <value>
                    <fullName>Reciprocating / Scroll Chillers - Air and Water Cooled</fullName>
                </value>
                <value>
                    <fullName>Refrigerant Monitor</fullName>
                </value>
                <value>
                    <fullName>Refrigerated Air Driers</fullName>
                </value>
                <value>
                    <fullName>Roof Top / Packaged or Split Systems (Unitary Equipment, Heating and cooling)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <label>Quote/Proposal</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>MA Models</relationshipLabel>
        <relationshipName>MA_Models</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Serial__c</fullName>
        <label>Serial #</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UniqueNumber__c</fullName>
        <label>UniqueNumber</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>MA Model</label>
    <nameField>
        <displayFormat>MAM-{000000000}</displayFormat>
        <label>MA Model Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MA Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/APTS_AddModelController.cls
/*************************************************************
@Name: APTS_AddModelController
@Author: Hardik Shah
@CreateDate: 18/01/2016
@Description: Controller to save MA Model Data Enter by User
@UsedBy: VF-Page/APTS_AddModel.page
@ModifiedBy: NA
@ModifiedDate: NA
@ChangeDescription: 
PS: @ModifiedBy and @ChangeDescription can be repeated multiple time, based on number of changes made to the original process.
******************************************************************/

public class APTS_AddModelController {
   
   // List of Original MA Models
   public List<MA_Model__c> listOriginalMAModels {get;set;}
   // List of Wrapper  MA Models
   public List<MA_Model__c> listMAModelsWrapper {get;set;}
   // Proposal-Id
   private String sProposalId = null;
   // Unique number associate with each MA-Model
   public String sUniqueNumber {get;set;}
   // Config-Request -id - This Parameter is use when a Page is Redirected
   private String sConfigRequestID = null;
   // Id - This Parameter is use when a Page is Redirected
   private String sID = null;
   
   private Integer iRowCount = 30;
   
    // Constructor 
    // Intializes variables after reterieving from URL
    public APTS_AddModelController(){
       sProposalId =  Apexpages.currentPage().getParameters().get('retId');
       sConfigRequestID =  Apexpages.currentPage().getParameters().get('configRequestId');
       sID =  Apexpages.currentPage().getParameters().get('id');
       iRowCount = getRowCount();
       system.debug('PS-->' + sProposalId + ' PS1--> ' +sConfigRequestID + ' PS2-->' + sID + 'Row-Count' + iRowCount );
       
    }
   
   // ApexPages.StandardSetController must be instantiated
   public ApexPages.StandardSetController setCon {
        get {
            List<MA_Model__c> listMAModel = new List<MA_Model__c>();
            MA_Model__c oMAModel = new MA_Model__c();
            oMAModel.UniqueNumber__c = 'Model' + getUniqueNumber();
            system.debug('HS--> ' + oMAModel.UniqueNumber__c);
            oMAModel.Proposal__c = sProposalId;
            listMAModel.add(oMAModel);
            setCon = new ApexPages.StandardSetController(listMAModel);
            return setCon;
        }
        set;
    }
   
    // getList of MA Models.
    public List<MA_Model__c> getMAModelsList() {
        if (listOriginalMAModels == null){ 
                listOriginalMAModels = setCon.getRecords(); 
                listMAModelsWrapper =  new List<MA_Model__c>();
                listMAModelsWrapper.addAll(listOriginalMAModels);
        }  
        
        return listMAModelsWrapper ;
    }
    
    // SAve the MA Models entered by User on VF page and Redirect 
    // the Page back to cart
    public Pagereference saveMAModles(){
       PageReference pageRef = null;
       
       for(MA_Model__c oModel : listMAModelsWrapper){
           if(String.isEmpty(oModel.Equipment_Group__c) || String.isEmpty(oModel.Equipment_Type__c)
                                                        || String.isEmpty(oModel.Serial__c) || String.isEmpty(oModel.Model__c)){
                Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, LABEL.APTS_Model_Validation_Message));
                return null;
            }
       }
       
       try{
            if(listMAModelsWrapper != null && listMAModelsWrapper.size() >= 1){
                upsert listMAModelsWrapper;
                system.debug('Upsert Successful');
            }
            pageRef = Page.Apttus_Config2__CartDetailView;  
            pageRef.getParameters().put('configRequestId',sConfigRequestID);
            pageRef.getParameters().put('id', sID);
            pageRef.setredirect(true);
                    
       }
       catch(Exception ex){
            system.debug('HS-->' + ex.getMessage());
            Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, ex.getMessage()));  
       }
       return pageRef;
    }
    
     // Add a row - Associate Proposal-Id,Unique-Number
     // Unique Number field is used to associate with MA Model Object.
     public PageReference AddRow(){
        
        if(listMAModelsWrapper != null && listMAModelsWrapper.size() >= iRowCount){
             Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.INFO, LABEL.APTPS_No_More_Rows));
             return null;
        }
        
        MA_Model__c oMAModel = new MA_Model__c();
        oMAModel.Proposal__c = sProposalId;
        oMAModel.UniqueNumber__c = 'Model' + getUniqueNumber();
        system.debug('HS--> ' + oMAModel.UniqueNumber__c);
        listMAModelsWrapper.add(oMAModel);
        return null;
        
     }
     
     // Delete a row - Associate Proposal-Id,Unique-Number
     // Unique Number field is used to associate with MA Model Object.
      public Pagereference removeRow(){
        
        system.debug('Inside Remove row' + sUniqueNumber);
        
        if(listMAModelsWrapper.size() == 1){
            listMAModelsWrapper.remove(listMAModelsWrapper.size() - 1);
            return null;
        }
        Integer iCount = 0;
        for(Integer i = 0;i<listMAModelsWrapper.size(); i++){
             MA_Model__c oModel = listMAModelsWrapper.get(i);
             if(oModel.UniqueNumber__c.equals(sUniqueNumber)) {
                 iCount = i;
                 system.debug('HS-->' + oModel);
             } 
        }
        listMAModelsWrapper.remove(iCount);
        return null;
        
     }
     
     // Generate q Unique Number
     private Long getUniqueNumber(){
         Long x =  System.currentTimeMillis() / 1000;
         return x;
     }
     
     // Get the Maximum row count - Maximum-Number of rows that needs to be Displayed in VF Page
     private Integer getRowCount(){
         
         try{
            APTPS_Configurable_Variables__c code = APTPS_Configurable_Variables__c.getInstance('North_America_Quote_Price_List');
            system.debug(code.APTPS_RowCount__c);
            Decimal dValue =  code.APTPS_RowCount__c;
            iRowCount = dValue.intValue();
         // In-Case of Exception,Default Row-Count will be used.
         }catch(Exception ex){
             system.debug('Exception while fetching row-count from custom-setting' + ex.getMessage());
         }
         return IRowCount;
     }
    
}