src/objects/APTPS_Configurable_Variables__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is supposed to hold configurable constants used in apex classes, pages.</description>
    <label>APTPS Configurable Variables</label>
</CustomObject>

src/objects/Clause__c.object
<CustomObject>
    <fields>
        <fullName>Clause__c</fullName>
        <label>Quote/Proposal</label>
        <referenceTo>Apttus_Proposal__Proposal__c</referenceTo>
        <relationshipLabel>Clauses</relationshipLabel>
        <relationshipName>Clauses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Clause</label>
    <nameField>
        <label>Clause Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clauses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>Line of business</description>
        <inlineHelpText>Type of Service/Product</inlineHelpText>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>CTK - Complex Turnkey</fullName>
                    <label>Contracting</label>
                </value>
                <value>
                    <fullName>Equipment Only</fullName>
                </value>
                <value>
                    <fullName>MA - Maintenance Agreement</fullName>
                </value>
                <value>
                    <fullName>MA - Renewal</fullName>
                </value>
                <value>
                    <fullName>MCP</fullName>
                </value>
                <value>
                    <fullName>Parts Only</fullName>
                </value>
                <value>
                    <fullName>Rental Chillers</fullName>
                </value>
                <value>
                    <fullName>Retrofit/Upgrades</fullName>
                </value>
                <value>
                    <fullName>Retrofit/Upgrades/CAP</fullName>
                </value>
                <value>
                    <fullName>Service &amp; Repair - Quoted</fullName>
                </value>
                <value>
                    <fullName>Service &amp; Repair - T&amp;M</fullName>
                </value>
                <value>
                    <fullName>Start-Up</fullName>
                </value>
                <value>
                    <fullName>TK - Turnkey Contracting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Quote_LOB_To_Clause_Record_Type__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Clause_RecordType__c</fullName>
        <label>Clause RecordType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_LOB__c</fullName>
        <label>Quote LOB</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Quote LOB To Clause Record Type</label>
</CustomObject>

src/classes/QuoteTriggerTest.cls
@isTest
private class QuoteTriggerTest {
    public static final string LOB ='Lob';
    private static testMethod void testClauseCreationOnQuoteInsert() {
/*        AVA_SFCORE__TaxNowSetting__c ts1 = new AVA_SFCORE__TaxNowSetting__c(); 
        ts1.AVA_SFCORE__Active_Setting__c = true; 
        ts1.Name='Test Account';
        insert ts1;

        PreventDeleteHandler.bypassTrigger = true;
        RecordType rtLAQuote = [Select Id from RecordType where sObjectType = 'Apttus_Proposal__Proposal__c' AND Name = 'Latin America Proposal'];
        
        Apttus_Config2__PriceList__c testPL = APTPS_DaikinTestDataUtility.getPriceList('USD Price List');
        insert testPL;
        
        APTPS_Configurable_Variables__c northAmericaQuoteCS = APTPS_DaikinTestDataUtility.getNorthAmericaQuoteCS();
        insert northAmericaQuoteCS;
        
        Account testAccount = APTPS_DaikinTestDataUtility.getAccount('Test Account NA - 1');
        insert testAccount;
        Contact testContact = APTPS_DaikinTestDataUtility.getContact(testAccount);
        insert testContact;
        Id stndrdPBId = APTPS_DaikinTestDataUtility.getStandardPricebookId();
        
        Opportunity testOpp = APTPS_DaikinTestDataUtility.getOpp(testAccount);
        testOpp.Name = 'Test Opp - LA';
        testOpp.Pricebook2Id = stndrdPBId;
        insert testOpp;
        
        Id clauseRT = [Select Id from RecordType where sObjectType = 'Clause__c' Limit 1].id;
        
        insert new Quote_LOB_To_Clause_Record_Type__c(name = LOB,Clause_RecordType__c = clauseRT,Quote_LOB__c = LOB);
        Apttus_Proposal__Proposal__c testQuoteLA1 = APTPS_DaikinTestDataUtility.getQuote(testAccount, testContact, testOpp, testPL);
        testQuoteLA1.Apttus_Proposal__Proposal_Name__c = 'Test Quote 1 - LA';
        testQuoteLA1.RecordTypeId = rtLAQuote.Id;
        testQuoteLA1.Primary__c = true;
        
        Test.startTest();
        testQuoteLA1.Line_of_Business__c =LOB;
        insert testQuoteLA1;
        Test.stopTest();
        List<Clause__c> insertedClauses = [Select Id, recordtypeId, clause__c from Clause__c];
        System.assertEquals(1, insertedClauses.size(), 'On insert of quote a clause shhould be insered wih corresponding recordtype');
        System.assertEquals(clauseRT, insertedClauses[0].recordtypeId, 'On insert of quote a clause shhould be insered wih corresponding recordtype');
        System.assertEquals(testQuoteLA1.id, insertedClauses[0].clause__c, 'On insert of quote a clause shhould be insered wih corresponding recordtype');        
*/    }
}