src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>SFDC Order record unique Id number. Auto-generated within SFDC.</inlineHelpText>
        <label>Order ID</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Additional_Materials_Amount_Approved__c</fullName>
        <inlineHelpText>What Additional Materials Dollar Amounts were approved?</inlineHelpText>
        <label>Additional Materials Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Additional_Materials_Amount_Requested__c</fullName>
        <inlineHelpText>What Additional Materials Dollar Amounts were requested?</inlineHelpText>
        <label>Additional Materials Amount Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Case_Category__c</fullName>
        <inlineHelpText>Please specify the category for this Case</inlineHelpText>
        <label>Case Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Accounts</fullName>
                </value>
                <value>
                    <fullName>Addresses</fullName>
                </value>
                <value>
                    <fullName>Approvals</fullName>
                </value>
                <value>
                    <fullName>Assets</fullName>
                </value>
                <value>
                    <fullName>Batch Jobs</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Campaigns</fullName>
                </value>
                <value>
                    <fullName>Cases</fullName>
                </value>
                <value>
                    <fullName>Change of Driver</fullName>
                </value>
                <value>
                    <fullName>Chatter</fullName>
                </value>
                <value>
                    <fullName>Claim</fullName>
                </value>
                <value>
                    <fullName>Contacts</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Credit Application</fullName>
                </value>
                <value>
                    <fullName>CRM</fullName>
                </value>
                <value>
                    <fullName>Dashboards</fullName>
                </value>
                <value>
                    <fullName>Documents</fullName>
                </value>
                <value>
                    <fullName>DST Assistance</fullName>
                </value>
                <value>
                    <fullName>Equipment Issue</fullName>
                </value>
                <value>
                    <fullName>Expedite</fullName>
                </value>
                <value>
                    <fullName>Extended</fullName>
                </value>
                <value>
                    <fullName>Fleet</fullName>
                </value>
                <value>
                    <fullName>Force.com Sites</fullName>
                </value>
                <value>
                    <fullName>FPA Special Request</fullName>
                </value>
                <value>
                    <fullName>General Questions</fullName>
                </value>
                <value>
                    <fullName>GEOTAB</fullName>
                </value>
                <value>
                    <fullName>Integration</fullName>
                </value>
                <value>
                    <fullName>Invoices</fullName>
                </value>
                <value>
                    <fullName>Known Issue (Fix on fail)</fullName>
                </value>
                <value>
                    <fullName>Leads</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Daikin_Parts_Amount_Approved__c</fullName>
        <inlineHelpText>What Daikin Parts Dollar Amounts were approved?</inlineHelpText>
        <label>Daikin Parts Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Daikin_Parts_Amount_Requested__c</fullName>
        <inlineHelpText>How much of the warranty request is for Daikin Parts?</inlineHelpText>
        <label>Daikin Parts Amount Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date_Received__c</fullName>
        <inlineHelpText>When was the Warranty Claim Authorization received?</inlineHelpText>
        <label>Date Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_Failure__c</fullName>
        <inlineHelpText>When did the Failure occur or was the issue discovered?</inlineHelpText>
        <label>Date of Failure</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hours_Approved__c</fullName>
        <description>The hours amount of labor Daikin will reimburse for Warranty that have been approved. Compare with Hours Requested</description>
        <inlineHelpText>The labor hours that will be reimbursed and have been approved. Compare to Hours Requested on the case ticket</inlineHelpText>
        <label>Hours Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hours_Requested__c</fullName>
        <description>The hours amount of labor that have been requested for Warranty claims. Compare with Hours Approved</description>
        <inlineHelpText>The requested labor hours to fix asset under warranty</inlineHelpText>
        <label>Hours Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Labor_Amount_Approved__c</fullName>
        <inlineHelpText>What Labor Dollar Amounts were approved?</inlineHelpText>
        <label>Labor Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Labor_Amount_Requested__c</fullName>
        <inlineHelpText>How much of the warranty request is for Labor?</inlineHelpText>
        <label>Labor Amount Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Looks up to Sales Order for Warranty. Populated via Process Builder when an asset is specified on the case</description>
        <inlineHelpText>The order of the asset specified on this case that is automatically populated when an asset is defined</inlineHelpText>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_for_Authorization_Request__c</fullName>
        <inlineHelpText>Detailed Reason for Authorization Request</inlineHelpText>
        <label>Reason for Authorization Request</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>X3rd_Party_Parts_Amount_Approved__c</fullName>
        <inlineHelpText>What 3rd Party Parts Dollar Amounts were approved?</inlineHelpText>
        <label>3rd-Party Parts Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X3rd_Party_Parts_Amount_Requested__c</fullName>
        <inlineHelpText>How much of the warranty request is for 3rd-Party Parts?</inlineHelpText>
        <label>3rd-Party Parts Amount Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Warranty</fullName>
        <active>true</active>
        <businessProcess>Warranty</businessProcess>
        <description>Used for Warranty case claims</description>
        <label>Warranty</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Service_Code__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Materials_Amount_Approved__c</fullName>
        <label>Additional Materials Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Additional_Materials_Amount_Requested__c</fullName>
        <label>Additional Materials Amount Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Service Codes</relationshipLabel>
        <relationshipName>Case_Service_Codes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Daikin_Parts_Amount_Approved__c</fullName>
        <label>Daikin Parts Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Daikin_Parts_Amount_Requested__c</fullName>
        <label>Daikin Parts Amount Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hours_Approved__c</fullName>
        <label>Hours Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hours_Requested__c</fullName>
        <label>Hours Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Labor_Amount_Approved__c</fullName>
        <label>Labor Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Labor_Amount_Requested__c</fullName>
        <label>Labor Amount Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MajorCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Major</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Case Service Codes (Major)</relationshipLabel>
        <relationshipName>Case_Service_Codes4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ModeCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mode</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Case Service Codes (Mode)</relationshipLabel>
        <relationshipName>Case_Service_Codes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Responsibility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsibility</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Case Service Codes (Responsibility)</relationshipLabel>
        <relationshipName>Case_Service_Codes6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Special_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Special Type</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Case Service Codes (Special Type)</relationshipLabel>
        <relationshipName>Case_Service_Codes7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SpecificCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Specific</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Case Service Codes (Specific)</relationshipLabel>
        <relationshipName>Case_Service_Codes5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TypeCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Type</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Case Service Codes (Type)</relationshipLabel>
        <relationshipName>Case_Service_Codes3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Case Service Codes (Unit)</relationshipLabel>
        <relationshipName>Case_Service_Codes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WarrantyClassCode__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Warranty Class</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Case Service Codes (Warranty Class)</relationshipLabel>
        <relationshipName>Case_Service_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X3rd_Party_Parts_Amount_Approved__c</fullName>
        <label>3rd-Party Parts Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X3rd_Party_Parts_Amount_Requested__c</fullName>
        <label>3rd-Party Parts Amount Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Case Service Code</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Case Service Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Service Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/WarrantyHelper.cls
global class WarrantyHelper implements Database.Batchable<sObject>  {

    private Boolean evenly = false;
    private Case_Service_Code__c csc;
    
    public WarrantyHelper(Case_Service_Code__c csc, Boolean evenly){
        this.csc = csc;
        this.evenly = evenly;
    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([select Id from Case where ParentId=:csc.Case__r.ParentId and Id!=:csc.Case__c]);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){
        List<Case> tcs = (List<Case>)scope;

        List<Case_Service_Code__c> cscs = new List<Case_Service_Code__c>();
        for(Case cs :tcs){
            Case_Service_Code__c c = csc.clone();
            c.Case__c = cs.Id;
            c.X3rd_Party_Parts_Amount_Approved__c=csc.X3rd_Party_Parts_Amount_Approved__c;
            c.Additional_Materials_Amount_Approved__c=csc.Additional_Materials_Amount_Approved__c;
            c.Daikin_Parts_Amount_Approved__c=csc.Daikin_Parts_Amount_Approved__c;
            c.Hours_Approved__c=csc.Hours_Approved__c;
            c.Labor_Amount_Approved__c=csc.Labor_Amount_Approved__c;
            
            c.X3rd_Party_Parts_Amount_Requested__c=csc.X3rd_Party_Parts_Amount_Requested__c;
            c.Additional_Materials_Amount_Requested__c=csc.Additional_Materials_Amount_Requested__c;
            c.Daikin_Parts_Amount_Requested__c=csc.Daikin_Parts_Amount_Requested__c;
            c.Hours_Requested__c=csc.Hours_Requested__c;
            c.Labor_Amount_Requested__c=csc.Labor_Amount_Requested__c;

            cscs.add(c);
        }
        insert cscs;
    }
    
    global void finish(Database.BatchableContext BC){
    }
    
    private static Decimal divideValue(Decimal val, Integer count){
        if(val == null)
            val = 0;
        if(val>0 && count>0){
            val /= count;
        }

        return val;
    }
    webservice static Integer associateCaseServiceCodes(String cscId, Boolean evenly){
        Case_Service_Code__c csc = [Select Id, Case__c, Case__r.ParentId
                                    ,X3rd_Party_Parts_Amount_Approved__c, Additional_Materials_Amount_Approved__c, Daikin_Parts_Amount_Approved__c, Hours_Approved__c, Labor_Amount_Approved__c
                                    ,X3rd_Party_Parts_Amount_Requested__c, Additional_Materials_Amount_Requested__c, Daikin_Parts_Amount_Requested__c, Hours_Requested__c, Labor_Amount_Requested__c
                                    , Description__c, MajorCode__c, ModeCode__c, SpecificCode__c, TypeCode__c, UnitCode__c, WarrantyClassCode__c, Responsibility__c, Special_Type__c 
                                    from Case_Service_Code__c where Id=:cscId];
        
        Integer origcount = Database.countQuery('select count() from Case where ParentId=\''+csc.Case__r.ParentId+'\' and Id!=\''+csc.Case__c+'\'');
        if(origcount>0){
            Integer count = origcount;
            if(evenly)
                count++;
            else
                count = 0;
            csc.X3rd_Party_Parts_Amount_Approved__c=divideValue(csc.X3rd_Party_Parts_Amount_Approved__c, count);
            csc.Additional_Materials_Amount_Approved__c=divideValue(csc.Additional_Materials_Amount_Approved__c, count);
            csc.Daikin_Parts_Amount_Approved__c=divideValue(csc.Daikin_Parts_Amount_Approved__c, count);
            csc.Hours_Approved__c=divideValue(csc.Hours_Approved__c, count);
            csc.Labor_Amount_Approved__c=divideValue(csc.Labor_Amount_Approved__c, count);
            
            csc.X3rd_Party_Parts_Amount_Requested__c=divideValue(csc.X3rd_Party_Parts_Amount_Requested__c, count);
            csc.Additional_Materials_Amount_Requested__c=divideValue(csc.Additional_Materials_Amount_Requested__c, count);
            csc.Daikin_Parts_Amount_Requested__c=divideValue(csc.Daikin_Parts_Amount_Requested__c, count);
            csc.Hours_Requested__c=divideValue(csc.Hours_Requested__c, count);
            csc.Labor_Amount_Requested__c=divideValue(csc.Labor_Amount_Requested__c, count);
                            
            update csc;
            Database.executeBatch(new WarrantyHelper(csc, evenly));
        }
        return origcount;        
    }

    webservice static Integer associateOrderAssets(String caseId){
        List<Case> cases = new List<Case>();
        
        List<Case> pcases = [Select Id, Order__r.Id, RecordTypeId, AccountId, ContactId, Origin, Priority, Date_of_Failure__c, Date_Received__c, Subject, Case_Category__c, Type, Status, Reason_For_Authorization_Request__c, Pay_To__c/*, Business_Unit_Multi__c*/ from Case where /*Case_Category__c='WAR' and*/ ParentId = null and Order__r.Id != null and Id=:caseId];
        if(pcases!=null && pcases.size()==1){
            Case pcase = pcases[0];
            if(pcase != null){
                List<Id> ids = new List<Id>();
                List<Case> tcs = [select AssetId from Case where AssetId != null and ParentId=:pcase.Id];
                if(tcs != null && tcs.size()>0){
                    for(Case cs :tcs){
                        ids.add(cs.AssetId);
                    }
                }
                //if(pcase.Business_Unit_Multi__c != null){
                    //String[] BUs = pcase.Business_Unit_Multi__c.split(';');
                    //if(BUs != null){
                        List<Asset> assets = [select Id, Order__r.Id from Asset where Order__r.Id=:pcase.Order__r.Id /*and (Product2.DW_Product_Business_Unit__c != null and Product2.DW_Product_Business_Unit__c in :BUs)*/ and Id not in :ids];
                        if(assets!=null && assets.size()>0){
                            for(Asset a :assets){
                                Case c = pcase.clone();
                                c.ParentId = pcase.Id;
                                c.AssetId = a.Id;
                                c.Status = pcase.Status;//'New';
                                c.Case_Category__c = 'Claim';
                                c.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Warranty').getRecordTypeId();//'0122F0000008acg';
                                cases.add(c);
                            }
                        }
                    //}    
                //}
            }
        }        
        Integer count = cases.size();
        if(count>0)
            insert cases;
        return count;
    }
    
}