src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Asset_Address_Line_1__c</fullName>
        <formula>Asset_Address__r.Address_Line_1__c</formula>
        <label>Address Line 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Asset_City__c</fullName>
        <formula>Asset_Address__r.City__c</formula>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Asset_Country__c</fullName>
        <formula>Text(Asset_Address__r.Country__c)</formula>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Asset_Postal_Code__c</fullName>
        <formula>Asset_Address__r.Postal_Code__c</formula>
        <label>Zip/Postal Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Asset_State_Province__c</fullName>
        <formula>Text(Asset_Address__r.State_Province__c)</formula>
        <label>State/Province</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code_String_Breakdown__c</fullName>
        <description>Display Breakdown of code string. Raw data pulled from Data Warehouse then transformed and compiled in the SFDC Integration dba prior to load here.</description>
        <label>Code String Breakdown</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Code_String__c</fullName>
        <label>Code String</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Current_Code_String_Breakdown__c</fullName>
        <description>Displays breakdown of code string with any modifications since Raw data was pulled from Data Warehouse (Code_String_Breakdown__c)</description>
        <label>Current Code String Breakdown</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Device_ID__c</fullName>
        <formula>IF (MAC_Address__c &lt;&gt; null, (&quot;00000000-00000000-&quot; &amp;  UPPER(LEFT( MAC_Address__c, 6)) &amp; &quot;FF-FF&quot; &amp;  UPPER(RIGHT(MAC_Address__c, 6))), &quot;&quot;)</formula>
        <inlineHelpText>Etherios Device ID passed to IE web service as MACAddress</inlineHelpText>
        <label>Device ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Format_Number__c</fullName>
        <description>DW_McQuayDataWarehouse.dbo.DW_DIM_CODE_STRING.DCST_FORMAT</description>
        <label>Format Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GWotGo__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Gateway on the Go 
Checked if the IE Gateway is a Gateway on the Go asset</description>
        <inlineHelpText>Gateway on the Go 
Checked if the IE Gateway is a Gateway on the Go asset</inlineHelpText>
        <label>GWotGo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IE_Asset__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate the record pertains to the IE integration. This is set on import of record from Daikin IE Back Office database.</description>
        <inlineHelpText>Flag to indicate the record pertains to the IE integration. This is set on import of record from Daikin IE Back Office database.</inlineHelpText>
        <label>IE Asset</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Job_Name__c</fullName>
        <formula>Order__r.Job_Name__c</formula>
        <label>Job Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MAC_Address__c</fullName>
        <description>Only applicable for IE Assets.  This is the MAC Address for the IE hardware on the asset.</description>
        <inlineHelpText>Only applicable for IE Assets.  This is the MAC Address for the IE hardware on the asset.</inlineHelpText>
        <label>MAC Address</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Equipment that this Asset is controlling or tied to.</inlineHelpText>
        <label>Parent Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Related Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ResetSuccessful__c</fullName>
        <description>Status field that gets set for a GWotGo Reset operation. 
None - Initialized state 
True - Reset operation was successful 
False - Reset Operation failed</description>
        <inlineHelpText>Status field that gets set for a GWotGo Reset operation. 
None - Initialized state 
True - Reset operation was successful 
False - Reset Operation failed</inlineHelpText>
        <label>ResetSuccessful</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>True</fullName>
                </value>
                <value>
                    <fullName>False</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SIM_Card_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to determine if the SIM card is active or not.</description>
        <label>SIM Card Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SIM_Card_ICCID__c</fullName>
        <description>Only applicable for IE Assets. This is for the IE hardware on the asset.</description>
        <inlineHelpText>Only applicable for IE Assets. This is for the IE hardware on the asset.</inlineHelpText>
        <label>SIM Card ICCID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tag__c</fullName>
        <inlineHelpText>Description entered by Sales Rep when selecting the product in Daikin Tools.</inlineHelpText>
        <label>Order Tag</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <description>dcw_Personnel.per_roletype</description>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>I</fullName>
                </value>
                <value>
                    <fullName>O</fullName>
                </value>
                <value>
                    <fullName>T</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Account Manager</fullName>
                </value>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>Architect</fullName>
                </value>
                <value>
                    <fullName>Buyer</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>DA Factory Service Tech</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Engineer</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>Independent Sales Rep</fullName>
                </value>
                <value>
                    <fullName>Main</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Project Manager</fullName>
                </value>
                <value>
                    <fullName>Service Tech</fullName>
                </value>
                <value>
                    <fullName>Team Member</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact_Subscription__c.object
<CustomObject>
    <description>Junction object to tie a contact to an IE Subscription, the Unit for the Subscription and one IE role for the specific Unit &amp; Subscription.  If the contact has more than one IE role for a given Unit/Subscription, then another Contact Subscription record will be created for that Role/Unit combination.</description>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Intelligent Equipment Contacts</relationshipLabel>
        <relationshipName>Contact_Subscriptions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CustomerAdministrator</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>TechnicianAdministrator</fullName>
                </value>
                <value>
                    <fullName>Technician</fullName>
                </value>
                <value>
                    <fullName>SalesRep</fullName>
                </value>
                <value>
                    <fullName>EquipmentAdministrator</fullName>
                </value>
                <value>
                    <fullName>Engineer</fullName>
                </value>
                <value>
                    <fullName>RenewalAdministrator</fullName>
                </value>
                <value>
                    <fullName>Administrator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <formula>Asset__r.SerialNumber</formula>
        <label>Serial Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contact_Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Subscription</label>
    <nameField>
        <displayFormat>CS-{000000000}</displayFormat>
        <label>Contact Subscription ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Object to identify and tie IE Subscriptions, to their appropriate Unit (Asset), Buyer (Account), and Users (Contacts).</description>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Intelligent Equipment Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Connectivity_Type__c</fullName>
        <description>Subscription connectivity plan to either use AT&amp;T Cellular option with the SIM card active or customer&apos;s own WiFi/LAN option to send data to the Daikin IE cloud (MS Azure).</description>
        <label>Connectivity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cellular</fullName>
                </value>
                <value>
                    <fullName>WiFi/LAN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Last_Renewal_Date__c</fullName>
        <description>Previous renewal date for the subscription</description>
        <label>Last Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_Counter__c</fullName>
        <description>Number of times the subscription has been renewed</description>
        <label>Renewal Counter</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Date the subscription was renewed</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <formula>Asset__r.SerialNumber</formula>
        <label>Serial Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Term_Years__c</fullName>
        <label>Term (Years)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Intelligent Equipment system subscription type.</description>
        <inlineHelpText>Intelligent Equipment system subscription type.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CustomRead</fullName>
                </value>
                <value>
                    <fullName>TechReadWrite</fullName>
                </value>
                <value>
                    <fullName>TechRead</fullName>
                </value>
                <value>
                    <fullName>Daikin</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>S-{000000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/RetrieveAssetService.cls
@RestResource(urlMapping='/RetrieveAsset/*')
global with sharing class RetrieveAssetService {
 
 	global class SubscriptionInfo
 	{
 		public integer RenewalCounter{get;set;}
        public date EndDate{get;set;}
        public string ConnectivityType{get;set;}
        public decimal TermYears{get;set;}
 	}

 	global class ContactInfo
 	{
 		public string Name{get;set;}
 		public string Email{get;set;}
 	}

    global class ServiceAsset
    {
        public string   AssetId{get;set;}
        public string   SerialNumber{get;set;}
        public string   Model{get;set;}
        public string   ProductName{get;set;}
        public boolean  Valid{get;set;}
        public string CodeStringFormat{get;set;}
        public list<string> CodeValues{get;set;}

        public string CodeString{get;set;}
        public string JobName{get;set;}
        public string UnitTag{get;set;}
        public string JobAddressLine1{get;set;}
        public string JobAddressCity{get;set;}
        public string JobAddressState{get;set;}
        public string JobAddressCountry{get;set;}
        public string JobAddressPostalCode{get;set;}
        public string GWSerialNumber{get;set;}
		public boolean GWOnTheGo{get;set;}
        public string GWICCID{get;set;}
        public string GWDeviceID{get;set;}
        public string GWMACAddress{get;set;}
        public string EMMSerialNumber{get;set;}
		public string GWResetSuccessful{get;set;}

        // IE Renewal fields
        public boolean IEAsset{get;set;}
        public boolean SIMCardActive{get;set;}
        public List<SubscriptionInfo> Subscriptions{get;set;}
        public list<ContactInfo> SubscriptionRenewalOwnersEmail{get;set;}

		public boolean UnitIESupportedModel{get;set;}
		public list<ContactInfo> GWContacts{get;set;}
    }
    
    
    @HttpGet
    global Static ServiceAsset getAsset()
    {
		// Pass in SN of the unit asset or GWotGo asset
        string serialNum = RestContext.request.params.get('SerialNumber'); 
        ServiceAsset response = new ServiceAsset();
        response.SerialNumber = serialNum;
        response.Valid = false;
        response.SIMCardActive = false;
        response.Subscriptions = null;
        response.SubscriptionRenewalOwnersEmail = null;
		response.IEAsset = false;
		response.UnitIESupportedModel = false;
		response.GWContacts = null;
		response.GWOnTheGo = false;
        
        for(Asset a : [select SerialNumber
                            , Product2.ProductCode
                            , Product2.Name
                            , Id
							, Name
                            , Format_Number__c
                            , Current_Code_String_Breakdown__c
                            , Code_String_Breakdown__c
                            , IE_Asset__c
                            , Code_String__c
                            , Job_Name__c
                            , Tag__c
                            , Asset_Address_Line_1__c
                            , Asset_City__c
                            , Asset_State_Province__c
                            , Asset_Country__c
                            , Asset_Postal_Code__c
							, SIM_Card_Active__c
							, SIM_Card_ICCID__c
							, Device_ID__c
							, MAC_Address__c
							, GWotGo__c
							, ResetSuccessful__c
							, Status
                            , (Select Id, Name, SerialNumber, SIM_Card_Active__c, Product2.Name, SIM_Card_ICCID__c, Device_ID__c, MAC_Address__c, GWotGo__c From Assets__r where Status != 'Obsolete')
                            , (Select Id, Type__c, Name, Connectivity_Type__c, End_Date__c, Term_Years__c, Renewal_Counter__c, Renewal_Date__c, Serial_Number__c, Start_Date__c, Last_Renewal_Date__c From Subscriptions__r)
                            , (Select Name, Role__c, Subscription__c, Contact__r.Name, Contact__r.Email From Contact_Subscriptions__r)

							// Sub-queries used for when GWotGo SN is passed in
							, (Select Id, Type__c, Name, Connectivity_Type__c, End_Date__c, Term_Years__c, Renewal_Counter__c, Renewal_Date__c, Serial_Number__c, Start_Date__c, Last_Renewal_Date__c, GWotGoAsset__c From Subscriptions1__r)
                            , (Select Name, Role__c, Subscription__c, Contact__r.Name, Contact__r.Email, GWotGoAsset__c, GWotGoPermAssoc__c From Contact_Subscriptions1__r)
                        from Asset
                       where SerialNumber = :serialNum])    
        {
			if ((a.Product2.Name == 'Intelligent Equipment Gateway') || (a.Name == 'Intelligent Equipment Gateway')) {
				if (a.Status != 'Obsolete')  //((a.Status != 'Obsolete') && (a.SIM_Card_Active__c != false))
				{
					// Serial number passed in is a Gateway asset
					System.debug(logginglevel.error, 'Serial number passed in is a Gateway asset = ' + serialNum);

					response.SerialNumber = a.SerialNumber;  //just set to GW SN since there is no parent asset
					response.Model = a.Product2.ProductCode;
					response.ProductName = a.Product2.Name;
					response.AssetId = a.Id;
					response.Valid = true;
					response.SIMCardActive = a.SIM_Card_Active__c;
					response.GWSerialNumber = a.SerialNumber;
					response.GWICCID = a.SIM_Card_ICCID__c;
					response.GWDeviceID = a.Device_ID__c;
					response.GWMACAddress = a.MAC_Address__c;
					response.GWOnTheGo = a.GWotGo__c;
					response.GWResetSuccessful = a.ResetSuccessful__c;

					List<Contact_Subscription__c> subscriptionContacts = a.Contact_Subscriptions1__r;
					list<ContactInfo> contactList = new List<ContactInfo>();
					list<ContactInfo> contactList2 = new List<ContactInfo>();
					for (Contact_Subscription__c cs: subscriptionContacts) {
						// Get list of Permanent contacts
            			if (cs.GWotGoPermAssoc__c == true) {
            				ContactInfo ci = new ContactInfo();
            				ci.Name = cs.Contact__r.Name;
            				ci.Email = cs.Contact__r.Email;

							// Only add to the contactList if the contact with this email doesn't exist already
							boolean found = false;
							for (ContactInfo ciTemp: contactList) {
								if (String.isNotEmpty(ciTemp.Email) && ciTemp.Email.containsIgnoreCase(ci.Email)) {
									found = true;
								}
							}

            				if (!found) contactList.add(ci);
            			}

						// Get list of contacts that are RenewalAdministrator
						String roles = cs.Role__c;
            			if (String.isNotEmpty(roles) && roles.contains('RenewalAdministrator')) {
            				ContactInfo ci = new ContactInfo();
            				ci.Name = cs.Contact__r.Name;
            				ci.Email = cs.Contact__r.Email;

							// Only add to the contactList2 if the contact with this email doesn't exist already
							boolean found = false;
							for (ContactInfo ciTemp: contactList2) {
								if (String.isNotEmpty(ciTemp.Email) && ciTemp.Email.containsIgnoreCase(ci.Email)) {
									found = true;
								}
							}

            				if (!found) contactList2.add(ci);
            			}
					}
					response.GWContacts = contactList;
					response.SubscriptionRenewalOwnersEmail = contactList2;


					List<Subscription__c> subscriptionList = a.Subscriptions1__r;
					list<SubscriptionInfo> subscriptionInfoList = new List<SubscriptionInfo>();
					for (Subscription__c s: subscriptionList) {
            			if (s.Type__c == 'TechReadWrite' || s.Type__c == 'Standard') {
            				SubscriptionInfo si = new SubscriptionInfo();
							si.TermYears = s.Term_Years__c;

							if (s.Renewal_Counter__c != null)
            					si.RenewalCounter = s.Renewal_Counter__c.intValue();
							else
								si.RenewalCounter = 0;

            				si.EndDate = s.End_Date__c.date();
            				si.ConnectivityType = s.Connectivity_Type__c;
            				subscriptionInfoList.add(si);
            			}
					}
					response.Subscriptions = subscriptionInfoList;
				}
				else {
					// Serial number passed in is a Gateway asset but its status is Obsolete so skip it
					System.debug(logginglevel.error, 'Serial number passed in is a Gateway asset but its Obsolete so its skipped = ' + serialNum);
				}
			}
			else {
				// Serial number passed in is a unit (equipment) asset
				System.debug(logginglevel.error, 'Serial number passed in is a unit (equipment) asset = ' + serialNum);
				
				string codeStringBreakDown = '';
            
				if(a.Current_Code_String_Breakdown__c != null) 
					codeStringBreakDown = a.Current_Code_String_Breakdown__c;
				else  
					codeStringBreakDown = a.Code_String_Breakdown__c;
                
				response.SerialNumber   = a.SerialNumber;
				response.Model          = a.Product2.ProductCode;
				response.ProductName    = a.Product2.Name;
				response.AssetId        = a.Id;
				response.Valid          = true;
				response.CodeStringFormat = a.Format_Number__c;
				response.CodeValues = IERenewal_ExtWebServiceCallouts.getCodeStringValues(codeStringBreakDown); //Batch_Sync_IE_Unit.getCodeStringValues(codeStringBreakDown);
            
				response.CodeString = a.Code_String__c;
				response.JobName = a.Job_Name__c;
				response.UnitTag = a.Tag__c;
				response.JobAddressLine1 = a.Asset_Address_Line_1__c;
				response.JobAddressCity = a.Asset_City__c;
				response.JobAddressState = a.Asset_State_Province__c;
				response.JobAddressCountry = a.Asset_Country__c;
				response.JobAddressPostalCode = a.Asset_Postal_Code__c;

				response.IEAsset = a.IE_Asset__c;
				response.UnitIESupportedModel = isIESupportedModel(a.Code_String__c); //isIESupportedModel(a.Product2.ProductCode);

				List<Asset> relatedAssets = a.Assets__r;
				for (Asset ast: relatedAssets) {
            		if ((ast.Product2.Name == 'Intelligent Equipment Gateway') || (ast.Name == 'Intelligent Equipment Gateway')) {
            			response.SIMCardActive = ast.SIM_Card_Active__c;
						response.GWSerialNumber = ast.SerialNumber;
						response.GWICCID = ast.SIM_Card_ICCID__c;
						response.GWDeviceID = ast.Device_ID__c;
						response.GWMACAddress = ast.MAC_Address__c;
						response.GWOnTheGo = ast.GWotGo__c;
            		}
					else if ((ast.Product2.Name == 'Intelligent Equipment Energy Management Module') || (ast.Name == 'Intelligent Equipment Energy Management Module')) {
						response.EMMSerialNumber = ast.SerialNumber;
					}
				}

				List<Contact_Subscription__c> subscriptionContacts = a.Contact_Subscriptions__r;
				list<ContactInfo> contactList = new List<ContactInfo>();
				for (Contact_Subscription__c cs: subscriptionContacts) {
            		String roles = cs.Role__c;
            		if (String.isNotEmpty(roles) && roles.contains('RenewalAdministrator')) {
            			ContactInfo ci = new ContactInfo();
            			ci.Name = cs.Contact__r.Name;
            			ci.Email = cs.Contact__r.Email;

						// Only add to the contactList if the contact with this email doesn't exist already
						boolean found = false;
						for (ContactInfo ciTemp: contactList) {
							if (String.isNotEmpty(ciTemp.Email) && ciTemp.Email.containsIgnoreCase(ci.Email)) {
								found = true;
							}
						}

            			if (!found) contactList.add(ci);
            		}
				}
				response.SubscriptionRenewalOwnersEmail = contactList;

				List<Subscription__c> subscriptionList = a.Subscriptions__r;
				list<SubscriptionInfo> subscriptionInfoList = new List<SubscriptionInfo>();
				for (Subscription__c s: subscriptionList) {
            		if (s.Type__c == 'TechReadWrite' || s.Type__c == 'Standard') {
            			SubscriptionInfo si = new SubscriptionInfo();
						si.TermYears = s.Term_Years__c;

						if (s.Renewal_Counter__c != null)
            				si.RenewalCounter = s.Renewal_Counter__c.intValue();
						else
							si.RenewalCounter = 0;

            			si.EndDate = s.End_Date__c.date();
            			si.ConnectivityType = s.Connectivity_Type__c;
            			subscriptionInfoList.add(si);
            		}
				}
				response.Subscriptions = subscriptionInfoList;
			}

        } // for-loop

		System.debug(logginglevel.error, 'RetrieveAssetService Response object = ' + response);
        
        return response;
    }


	public static Boolean isIESupportedModel(String model)
    {
        Boolean supported = false;
		string prefix = null;
		string letter = '';

		if (String.isNotEmpty(model) && (model.length() >= 3))
		{
			prefix = model.substring(0, 3);

			//For AGZ model look at the 7th character in the string to get the corresponding letter for verification (D or E).
			//We will only see a 3 digit tonnage in the model, e.g., AGZ055D or AGZ190E

			//For WME models look at the 9th character in the string to get the vintage code letter for verification.
			//Accept all vintage code letters except (C), e.g., WME0700SS, WME1000DB

			if (prefix.trim().equalsIgnoreCase('AGZ') && (model.length() >= 7))
				letter = model.substring(6, 7);
			else if (prefix.trim().equalsIgnoreCase('WME') && (model.length() >= 9))
				letter = model.substring(8, 9);

			if (prefix.trim().equalsIgnoreCase('DPS')) {
				// Rebel
				supported = true;
			}
			else if (prefix.trim().equalsIgnoreCase('MPS')) {
				// Mav-II
				supported = true;
			}
			else if (prefix.trim().equalsIgnoreCase('RAH') || prefix.trim().equalsIgnoreCase('RDS') ||
					prefix.trim().equalsIgnoreCase('RDT') || prefix.trim().equalsIgnoreCase('RFS') ||
					prefix.trim().equalsIgnoreCase('RPR') || prefix.trim().equalsIgnoreCase('RPS')) {
				// Roofpak
				supported = true;
			}
			else if (prefix.trim().equalsIgnoreCase('AGZ') && (letter.equalsIgnoreCase('D') || letter.equalsIgnoreCase('E'))) {
				// Trailblazer
				supported = true;
			}
			else if (prefix.trim().equalsIgnoreCase('AWV') || prefix.trim().equalsIgnoreCase('AWS')) {
				// Pathfinder
				supported = true;
			}
			else if (prefix.trim().equalsIgnoreCase('AMZ')) {
				// Scroll Air Cooled Chiller
				supported = true;
			}
			else if (prefix.trim().equalsIgnoreCase('WMC')) {
				// Centrifugal Water Cooled Chiller
				supported = true;
			}
			else if (prefix.trim().equalsIgnoreCase('WME') && !letter.equalsIgnoreCase('C')) {
				// Water Cooled Magnetic Bearing Centrifugal Chiller
				supported = true;
			}
		}

        System.debug(logginglevel.error, 'Model = ' + model + ' prefix = ' + prefix + ' letter = ' + letter + ' IE supported model = ' + supported);
        return supported;
    }

}

/* ***Use this SOQL query in the Workbench to return desired records***
select SerialNumber
                            , Product2.ProductCode
                            , Product2.Name
                            , Id
							, Name
                            , Format_Number__c
                            , Current_Code_String_Breakdown__c
                            , Code_String_Breakdown__c
                            , IE_Asset__c
                            , Code_String__c
                            , Job_Name__c
                            , Tag__c
                            , Asset_Address_Line_1__c
                            , Asset_City__c
                            , Asset_State_Province__c
                            , Asset_Country__c
                            , Asset_Postal_Code__c
							, SIM_Card_Active__c
							, SIM_Card_ICCID__c
							, Device_ID__c
							, MAC_Address__c
							, GWotGo__c
                            , (Select Id, Name, SerialNumber, SIM_Card_Active__c, Product2.Name, SIM_Card_ICCID__c, Device_ID__c, MAC_Address__c, GWotGo__c From Assets__r where Status != 'Obsolete')
                            , (Select Id, Type__c, Name, Connectivity_Type__c, End_Date__c, Term_Years__c, Renewal_Counter__c, Renewal_Date__c, Serial_Number__c, Start_Date__c, Last_Renewal_Date__c From Subscriptions__r)
                            , (Select Name, Role__c, Subscription__c, Contact__r.Name, Contact__r.Email From Contact_Subscriptions__r)
							// Sub-queries used for when GWotGo SN is passed in
							, (Select Id, Type__c, Name, Serial_Number__c, GWotGoAsset__c From Subscriptions1__r)
                            , (Select Name, Role__c, Contact__r.Name, Contact__r.Email, GWotGoAsset__c, GWotGoPermAssoc__c From Contact_Subscriptions1__r)
                        from Asset
                       where SerialNumber = 'FBOU150900980'
*/

// ***Testing the webservice in Workbench REST Explorer***
// Use the Get HTTP method on the following REST API Service URI: /services/apexrest/RetrieveAsset?SerialNumber=FBOU150900980