src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Commissioned__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>IE Use Only. If checked, the initial Gateway for this asset has been commissioned.</inlineHelpText>
        <label>Gateway Commissioned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IE_Sync_Status__c</fullName>
        <description>Status that gets set when attributes on the record are updated and therefore needs to be sent to the IE system.</description>
        <inlineHelpText>Pending = Record needs to be sent to the IE system. 
Processed = Record was successfully received by IE system. 
Error = Record was not successfully received by IE system.</inlineHelpText>
        <label>IE Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Record_Usage__c</fullName>
        <description>Designed to show other systems that use the information in this record and for the purpose of preventing record deletion.</description>
        <label>Record Usage</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DW</fullName>
                </value>
                <value>
                    <fullName>IE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Object to identify and tie IE Subscriptions, to their appropriate Unit (Asset), Buyer (Account), and Users (Contacts).</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Pass this attribute to IE as part of 1.2 release.  Removes need to change the Subscription End Date from the contract term end date if it&apos;s necessary to remove access to Unit in IE prior to End Date.</description>
        <inlineHelpText>If checked, Subscription has started and is currently in effect.  Uncheck if Subscription should be made inactive for any reason. (e.g. Contract Expired, Non-payment, Legal)</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Intelligent Equipment Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>GWotGoAsset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Gateway on the Go Asset</description>
        <label>GWotGo Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>GW on the Go Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IE_Subscription__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate the record pertains to the IE integration. This is set on import of record from Daikin IE Back Office database.</description>
        <inlineHelpText>Flag to indicate the record pertains to the IE integration. This is set on import of record from Daikin IE Back Office database.</inlineHelpText>
        <label>IE Subscription</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IE_Sync_Status__c</fullName>
        <description>Status that gets set when attributes on the record are updated and therefore needs to be sent to the IE system.</description>
        <inlineHelpText>Pending = Record needs to be sent to the IE system. 
Processed = Record was successfully received by IE system. 
Error = Record was not successfully received by IE system.</inlineHelpText>
        <label>IE Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Record_Usage__c</fullName>
        <description>Designed to show other systems that use the information in this record and for the purpose of preventing record deletion.</description>
        <label>Record Usage</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Notice_Current_Month__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean flag to keep track if an email was sent for a subscription renewal where the end date is in the current month.</description>
        <label>Renewal Notice Current Month</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Renewal_Notice_Last_Month_Minus_1__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean flag to keep track if an email was sent for a subscription renewal where the end date is in the last month minus 1.</description>
        <label>Renewal Notice Last Month Minus 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Renewal_Notice_Last_Month__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean flag to keep track if an email was sent for a subscription renewal where the end date is in the last month.</description>
        <label>Renewal Notice Last Month</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Renewal_Notice_Next_Month_Plus_1__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean flag to keep track if an email was sent for a subscription renewal where the end date is in the next month plus 1.</description>
        <label>Renewal Notice Next Month Plus 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Renewal_Notice_Next_Month__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean flag to keep track if an email was sent for a subscription renewal where the end date is in the next month.</description>
        <label>Renewal Notice Next Month</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Term_Years__c</fullName>
        <label>Term (Years)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TriggerInvokedByAPI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Hidden field used to determine if the Subscription trigger was invoked by the API and not the Salesforce UI. 
Temporarily gets set to true when a record is inserted via ETL or updated via IE Renewal Web Service and the Subscription triggers are fired. This is used to avoid some code paths in the trigger if the user inserted or updated a record via the Salesforce UI.</description>
        <label>TriggerInvokedByAPI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Intelligent Equipment system subscription type.</description>
        <inlineHelpText>Intelligent Equipment system subscription type.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CustomRead</fullName>
                </value>
                <value>
                    <fullName>TechReadWrite</fullName>
                </value>
                <value>
                    <fullName>TechRead</fullName>
                </value>
                <value>
                    <fullName>Daikin</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>S-{000000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Employee start date with company or date of employee&apos;s title/role change.  e.g. SSR becomes SCM.</description>
        <inlineHelpText>Employee start date with company or date of employee&apos;s title/role change.  e.g. SSR becomes SCM.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SubscriptionTriggerHandler.cls
public without sharing class SubscriptionTriggerHandler {
	/*********************************************************************
	* NOTE: The following set of Test Classes will test this trigger code.
	* These would all need to be run to get > 75% code coverage.
	* 
	* IERenewal_SubscriptionUpdateServiceTest
	* Batch_IE_Subscription_NotificationTest
	* Batch_IE_DeactivateExpiredSubscrip_Test
	* ResetGWotGoAsset_Test
	**********************************************************************/
	
	public static void onBeforeUpdate(map<Id, Subscription__c> newMap, map<Id, Subscription__c> oldMap)
	{
		resetEmailCriteriaBucketFlags(newMap.values(), oldMap);
		setIeSyncStatus(newMap.values(), oldMap);
	}
	
    
	public static void onBeforeInsert(list<Subscription__c> newList)
	{
		//setStartEndSubscriptionDates(newList); //Don't need to call since these fields will be set in the Renewal Service and ETL
		setIeSyncStatus(newList, null);
	}
	
    
	public static void onBeforeDelete(map<Id, Subscription__c> oldMap)
	{
		for(Subscription__c s : oldMap.values())
		{
			if( s.Record_Usage__c != null)
				s.addError('This record cannot be deleted because it is integrated with other systems or tied to other critical information within Salesforce.');
				
		}
	}


	public static void setIeSyncStatus(list<Subscription__c> newlist, map<Id, Subscription__c> oldMap)
	{
		for(Subscription__c a : newList)
		{
			if (a.IE_Subscription__c 
			   && (oldMap == null || oldMap.get(a.Id).TriggerInvokedByAPI__c == false)
			   && a.TriggerInvokedByAPI__c == false
			   && !(TriggerUtility.limitIeServiceIntegration || TriggerUtility.limitIntegrationBatch))
		    {
				if (a.GWotGoAsset__c != null) {
					// Processing a GWotGo asset
					Asset unitAsset = [SELECT Id, Name, IE_Sync_Status__c from Asset Where Id = :a.Asset__c];

					if ((unitAsset.Name != 'Dummy GWotGo Unit Asset') && (unitAsset.Name != 'Holding GWotGo Unit Asset')) {
						if ((a.GWotGoAsset__c != null) && (oldMap == null || (oldMap.get(a.Id).Asset__c != a.Asset__c)))
						{
							// This subscription is associated with a GWotGo asset that just moved from one unit to another from a Reset operation
							// Set status to 'Processed' so the IE batch job ignores it
							a.IE_Sync_Status__c = 'Processed';
						}
						else {
							a.IE_Sync_Status__c = 'Pending';
							a.TriggerInvokedByAPI__c = true;  // set to true so 15 min apex job processes it
						}
					}
					else {
						a.IE_Sync_Status__c = 'Processed';
					}
				}
				else {
					a.IE_Sync_Status__c = 'Pending';
					a.TriggerInvokedByAPI__c = true;  // set to true so 15 min apex job processes it
				}
		    }

			/*if (a.IE_Subscription__c 
			   && (oldMap == null || oldMap.get(a.Id).IE_Sync_Status__c != 'Pending')
			   && a.IE_Sync_Status__c != 'Pending'
			   && !(TriggerUtility.limitIeServiceIntegration || TriggerUtility.limitIntegrationBatch))
		    {
				if (a.GWotGoAsset__c != null) {
					// Processing a GWotGo asset
					Asset unitAsset = [SELECT Id, Name, IE_Sync_Status__c from Asset Where Id = :a.Asset__c];

					if ((unitAsset.Name != 'Dummy GWotGo Unit Asset') && (unitAsset.Name != 'Holding GWotGo Unit Asset')) {
						if ((a.GWotGoAsset__c != null) && (oldMap == null || (oldMap.get(a.Id).Asset__c != a.Asset__c)))
						{
							// This subscription is associated with a GWotGo asset that just moved from one unit to another from a Reset operation
							// Set status to 'Processed' so the hourly IE batch job ignores it
							a.IE_Sync_Status__c = 'Processed';
						}
						else {
							a.IE_Sync_Status__c = 'Pending';
							a.TriggerInvokedByAPI__c = true;  // set to true so 15 min apex job processes it
						}
					}
					else {
						a.IE_Sync_Status__c = 'Processed';
					}
				}
				else {
					a.IE_Sync_Status__c = 'Pending';
					a.TriggerInvokedByAPI__c = true;  // set to true so 15 min apex job processes it
				}
		    }*/
		    
		    if(a.IE_Subscription__c)
		    {
				if(a.Record_Usage__c != null && !a.Record_Usage__c.contains('IE'))
					a.Record_Usage__c +=  ';IE';
				else if(a.Record_Usage__c == null)
					a.Record_Usage__c =  'IE';
		    }
		}
	}


    
    
    public static void resetEmailCriteriaBucketFlags(list<Subscription__c> newlist, map<Id, Subscription__c> oldMap)
    {
		// Normally these fields will be reset in the Renewal Update Service and ETL inserts.
		// This is here for the case where a user updates the End Date manually causing the update trigger to fire.
        for(Subscription__c s : newList)
        {
            // if the subscription is being renewed (ie, new end_date) then reset all the email criteria bucket flags to false
            if (s.End_Date__c > oldMap.get(s.Id).End_Date__c)
            {
				System.debug(LoggingLevel.ERROR,'in subscription trigger handler: new end date = ' + s.End_Date__c + ', old end date = '+ oldMap.get(s.Id).End_Date__c);

                s.Renewal_Notice_Current_Month__c = false;
                s.Renewal_Notice_Next_Month__c = false;
                s.Renewal_Notice_Last_Month__c = false;
                s.Renewal_Notice_Next_Month_Plus_1__c = false;
                s.Renewal_Notice_Last_Month_Minus_1__c = false;
            }
        }
    }
	
    
    /*
	public static void setStartEndSubscriptionDates(list<Subscription__c> subscriptions)
	{
			//Asset.Commissioned__c = true
			//Asset.Commissioned__c was previously true
			//Asset.Subscription__c.StartDate__c = null
			//Asset.Subscription__c.Type__c  != 'Daikin'
			
		 map<Id, Asset> assetMap = new map<Id, Asset>(); 
		 set<Id> assetIds = new set<Id>();
		 for(Subscription__c s : subscriptions)
		 {
		 	if(s.Asset__c != null && s.Type__c  != 'Daikin' && s.Start_Date__c == null)
		 		assetIds.add(s.Asset__c);
		 }
		 
		 //retrieve the associated Assets
		 for(Asset a : [Select Id from Asset where Id in :assetIds and Commissioned__c = true])
		 	assetMap.put(a.Id, a);
		 
		 for(Subscription__c s : subscriptions)
		 {
		 	if(assetMap.containsKey(s.Asset__c))
		 	{
		 		s.Start_Date__c = system.today();
				s.End_Date__c = system.today().addDays( Integer.ValueOf(365 * (s.Term_Years__c==null ? 1 :s.Term_Years__c) ));
				s.Active__c = true;
		 	}
		 		
		 }
	}
	*/

}