src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>SFDC Order record unique Id number. Auto-generated within SFDC.</inlineHelpText>
        <label>Order ID</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SO_Line_Number__c</fullName>
        <description>Used to indicate the Sales Order Line number associated to the Asset</description>
        <label>SO Line Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Business_Unit_Multi__c</fullName>
        <label>Business Unit - RETIRE</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AAH</fullName>
                </value>
                <value>
                    <fullName>Applied Air Handler</fullName>
                </value>
                <value>
                    <fullName>Applied Terminal Systems</fullName>
                </value>
                <value>
                    <fullName>ATS</fullName>
                </value>
                <value>
                    <fullName>Chiller</fullName>
                </value>
                <value>
                    <fullName>Chillers</fullName>
                </value>
                <value>
                    <fullName>Controls</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Category__c</fullName>
        <inlineHelpText>Please specify the category for this Case</inlineHelpText>
        <label>Case Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Accounts</fullName>
                </value>
                <value>
                    <fullName>Addresses</fullName>
                </value>
                <value>
                    <fullName>Approvals</fullName>
                </value>
                <value>
                    <fullName>Assets</fullName>
                </value>
                <value>
                    <fullName>Batch Jobs</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Campaigns</fullName>
                </value>
                <value>
                    <fullName>Cases</fullName>
                </value>
                <value>
                    <fullName>Change of Driver</fullName>
                </value>
                <value>
                    <fullName>Chatter</fullName>
                </value>
                <value>
                    <fullName>Claim</fullName>
                </value>
                <value>
                    <fullName>Contacts</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Credit Application</fullName>
                </value>
                <value>
                    <fullName>CRM</fullName>
                </value>
                <value>
                    <fullName>Dashboards</fullName>
                </value>
                <value>
                    <fullName>Documents</fullName>
                </value>
                <value>
                    <fullName>DST Assistance</fullName>
                </value>
                <value>
                    <fullName>Equipment Issue</fullName>
                </value>
                <value>
                    <fullName>Expedite</fullName>
                </value>
                <value>
                    <fullName>Extended</fullName>
                </value>
                <value>
                    <fullName>Fleet</fullName>
                </value>
                <value>
                    <fullName>Force.com Sites</fullName>
                </value>
                <value>
                    <fullName>FPA Special Request</fullName>
                </value>
                <value>
                    <fullName>General Questions</fullName>
                </value>
                <value>
                    <fullName>GEOTAB</fullName>
                </value>
                <value>
                    <fullName>Integration</fullName>
                </value>
                <value>
                    <fullName>Invoices</fullName>
                </value>
                <value>
                    <fullName>Known Issue (Fix on fail)</fullName>
                </value>
                <value>
                    <fullName>Leads</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_Received__c</fullName>
        <inlineHelpText>When was the Warranty Claim Authorization received?</inlineHelpText>
        <label>Date Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_Failure__c</fullName>
        <inlineHelpText>When did the Failure occur or was the issue discovered?</inlineHelpText>
        <label>Date of Failure</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Looks up to Sales Order for Warranty. Populated via Process Builder when an asset is specified on the case</description>
        <inlineHelpText>The order of the asset specified on this case that is automatically populated when an asset is defined</inlineHelpText>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pay_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Amount or hours approved payed to Account lookup for Warranty cases. Populated Asset__r.Order__r.Bill_To__c account through Process Builder but can be overwritten if Pay To account is different than account that was billed on the order.</description>
        <inlineHelpText>The account that amount and/or hours approved will be credited to. Populated with order billed to Account but can be overwritten if applicable.</inlineHelpText>
        <label>Pay To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_for_Authorization_Request__c</fullName>
        <inlineHelpText>Detailed Reason for Authorization Request</inlineHelpText>
        <label>Reason for Authorization Request</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SO_Line_Number__c</fullName>
        <formula>Asset.SO_Line_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SO Line Number</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Warranty</fullName>
        <active>true</active>
        <businessProcess>Warranty</businessProcess>
        <description>Used for Warranty case claims</description>
        <label>Warranty</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <description>Order information for TRC</description>
    <label>Order</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>DW_Product_Business_Unit__c</fullName>
        <label>DW Product Business Unit</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WarrantyOrderAssetControllerExtension.cls
global class WarrantyOrderAssetControllerExtension implements Database.Batchable<sObject>{

    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([select Id, Order__r.Id from Asset where Id in :lst]);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){
        List<Asset> assets = (List<Asset>)scope;
        processAssets(assets, pcase);
    }
    
    global void finish(Database.BatchableContext BC){
    }    
    
    private void processAssets(List<Asset> assets, Case pcase){
        List<Case> cases = new List<Case>();
        for(Asset a :assets){
            Case c = pcase.clone();
            c.ParentId = pcase.Id;
            c.AssetId = a.Id;
            c.Case_Category__c = 'Claim';
            c.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Warranty').getRecordTypeId();//'0122F0000008acg';
            cases.add(c);
        }
        if(cases.size()>0)
            insert cases;
    
    }

    private Case pcase;
    private List<String> lst;
    
    public WarrantyOrderAssetControllerExtension () {
        String pcaseId = ApexPages.currentPage().getParameters().get('id');
        if(pcaseId != null)
            pcase = [select Id, Order__c from Case where Id=:pcaseId];        
        else
            pcase = null;
    }
    public WarrantyOrderAssetControllerExtension (List<String> lst, Case pcase) {
        this.pcase = pcase;
        this.lst = lst;
    }

    public Id getId(){
        if(pcase != null)
            return pcase.Id;
        return null;
    }
    
    public List<Asset> getOrderAssets() {
        if(pcase==null)
            return null;
        if(pcase.Order__c==null){return new List<Asset>();
        }
        return [select Id, Name, SerialNumber, SO_Line_Number__c, Product2.DW_Product_Business_Unit__c, Product2.ProductCode from Asset where Order__c=:pcase.Order__c and Id not in (select AssetId from Case where Parent.Id=:pcase.Id) order by Product2.DW_Product_Business_Unit__c, SO_Line_Number__c, SerialNumber LIMIT 1000];
    }
    
    @RemoteAction
    public static Integer createOrderAssets(String pId, List<String> lst) {
        Case pcase = [select Id, Order__r.Id, RecordTypeId, AccountId, ContactId, Origin, Priority, Date_of_Failure__c, Date_Received__c, Subject, Case_Category__c, Type, Status, Reason_For_Authorization_Request__c, Pay_To__c/*, Business_Unit_Multi__c*/, OwnerId from Case where Id=:pId];        
        String l = '(';
        for(String ls : lst){l+='\''+ls+'\', ';
        }
        if(l.endsWith(', ')){l = l.substring(0, l.length()-2);
        }
        l+=')';
        System.debug(l);
        Integer origcount = 0;
        if(l!='()'){
            origcount = Database.countQuery('select count() from Asset where Id in '+l);
            if(origcount>50)
                Database.executeBatch(new WarrantyOrderAssetControllerExtension(lst, pcase));
            else
                new WarrantyOrderAssetControllerExtension(lst, pcase).execute(null, [select Id, Order__r.Id from Asset where Id in :lst]);
        }
        return origcount;
    }
    
    public PageReference save() {
        PageReference redirectSuccess = new ApexPages.StandardController(pcase).view();
        return (redirectSuccess);
    }
    public PageReference cancel() {
        PageReference redirectSuccess = new ApexPages.StandardController(pcase).view();
        return (redirectSuccess);
    }
    public PageReference close() {
        PageReference redirectSuccess = new ApexPages.StandardController(pcase).view();
        return (redirectSuccess);
    }
}