src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>IE_ID__c</fullName>
        <externalId>true</externalId>
        <label>IE ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Object to identify and tie IE Subscriptions, to their appropriate Unit (Asset), Buyer (Account), and Users (Contacts).</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Pass this attribute to IE as part of 1.2 release.  Removes need to change the Subscription End Date from the contract term end date if it&apos;s necessary to remove access to Unit in IE prior to End Date.</description>
        <inlineHelpText>If checked, Subscription has started and is currently in effect.  Uncheck if Subscription should be made inactive for any reason. (e.g. Contract Expired, Non-payment, Legal)</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Intelligent Equipment Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Buyer_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Buyer ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Intelligent Equipment Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>IE_ID__c</fullName>
        <description>IE database unique record ID.</description>
        <externalId>true</externalId>
        <inlineHelpText>IE database unique record ID.</inlineHelpText>
        <label>IE ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IE_Subscription__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate the record pertains to the IE integration. This is set on import of record from Daikin IE Back Office database.</description>
        <inlineHelpText>Flag to indicate the record pertains to the IE integration. This is set on import of record from Daikin IE Back Office database.</inlineHelpText>
        <label>IE Subscription</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <formula>Asset__r.SerialNumber</formula>
        <label>Serial Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TriggerInvokedByAPI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Hidden field used to determine if the Subscription trigger was invoked by the API and not the Salesforce UI. 
Temporarily gets set to true when a record is inserted via ETL or updated via IE Renewal Web Service and the Subscription triggers are fired. This is used to avoid some code paths in the trigger if the user inserted or updated a record via the Salesforce UI.</description>
        <label>TriggerInvokedByAPI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Intelligent Equipment system subscription type.</description>
        <inlineHelpText>Intelligent Equipment system subscription type.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CustomRead</fullName>
                </value>
                <value>
                    <fullName>TechReadWrite</fullName>
                </value>
                <value>
                    <fullName>TechRead</fullName>
                </value>
                <value>
                    <fullName>Daikin</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>S-{000000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Batch_IE_DeactivateExpiredSubscriptions.cls
/********************************************************************************************
 Author       :   Kent Roessler
 Created Date :   Feb 14, 2017
 Modified     :   
 Description  :   Nightly batch job that checks all subscriptions whose End Date has expired.

 For expired subscriptions the Active__c field is set to false.

 The batch job, "Batch_IE_CallExtWebServices" will process these expired/deactivated 
 subscriptions by making a call to the IE API/Service Portal Web Services 
 to update the subscription active status in the MS Azure Cloud IE database.
**********************************************************************************************/
global class Batch_IE_DeactivateExpiredSubscriptions implements Database.Batchable<sObject>, Database.AllowsCallouts,  Database.Stateful{
	
	Datetime currDateTime = Datetime.now(); // current date and time in the GMT time zone

	
	global Batch_IE_DeactivateExpiredSubscriptions() {
		
	}
	

	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator([select Id
                                         , Name
                                         , Start_Date__c
                                         , End_Date__c
                                         , Asset__c
                                         , Type__c
                                         , Active__c
                                         , Serial_Number__c
                                         , IE_Subscription__c
                                         , Buyer_ID__c
                                         , IE_ID__c
										 , TriggerInvokedByAPI__c
                                         , LastModifiedDate
                                         from Subscription__c
                                         where IE_Subscription__c = true AND Active__c = true AND End_Date__c < :currDateTime]);
	}


   	global void execute(Database.BatchableContext BC, List<Subscription__c> subscriptions) {

		List<Subscription__c> updatedSubscriptions = new list<Subscription__c>();

		try {
			for (Subscription__c s : subscriptions)
	        {
				Asset parentAsset = [SELECT Id, Name from Asset Where Id = :s.Asset__c];

	        	s.Active__c = false;

				// Only set the trigger field on the subscription if its asset is not the Dummy Unit and Holding Unit.
				if ((parentAsset.Name != 'Dummy GWotGo Unit Asset') && (parentAsset.Name != 'Holding GWotGo Unit Asset'))
	        		s.TriggerInvokedByAPI__c = true;

	        	updatedSubscriptions.add(s);

	        }

	        if (!updatedSubscriptions.isEmpty()) {
	            update updatedSubscriptions;
	        }
		}
		catch (Exception e) {
   			System.debug(logginglevel.error, 'Batch_IE_DeactivateExpiredSubscriptions Exception: ' + e);
   		}
   		finally {

   		}

	}

	
	global void finish(Database.BatchableContext BC) {
		
	}
	
}