src/objects/Bidder__c.object
<CustomObject>
    <description>DMNY</description>
    <fields>
        <fullName>Apparent_Winning_Bidder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Apparent Winning Bidder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bidder_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>DMNY</description>
        <label>Bidder Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bidders</relationshipLabel>
        <relationshipName>Bidders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Bidders</relationshipLabel>
        <relationshipName>Bidders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bidder</label>
    <nameField>
        <label>Bidder Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bidders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Bidder_Rollup__c</fullName>
        <label>Bidder Rollup</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact_Rollup__c</fullName>
        <description>It is a combination of Contact Name + “@” + Account Name + “(“Role”)”</description>
        <label>Contact Rollup</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Edited__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Edited</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Rollup__c</fullName>
        <label>Product Rollup</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>User_Department__c</fullName>
        <label>User Department</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>User_Division__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AAH</fullName>
                </value>
                <value>
                    <fullName>Admin</fullName>
                </value>
                <value>
                    <fullName>ATS</fullName>
                </value>
                <value>
                    <fullName>Central Mexico</fullName>
                </value>
                <value>
                    <fullName>Central Mexico - Bajio</fullName>
                </value>
                <value>
                    <fullName>Central Mexico - Guadalajara</fullName>
                </value>
                <value>
                    <fullName>Central Mexico - Mexico City</fullName>
                </value>
                <value>
                    <fullName>Chiller Applications</fullName>
                </value>
                <value>
                    <fullName>Chillers</fullName>
                </value>
                <value>
                    <fullName>Colombia</fullName>
                </value>
                <value>
                    <fullName>Controls</fullName>
                </value>
                <value>
                    <fullName>DAAL</fullName>
                </value>
                <value>
                    <fullName>DAAL - Equipment Sales</fullName>
                </value>
                <value>
                    <fullName>DAFL</fullName>
                </value>
                <value>
                    <fullName>DAFL - Equipment Sales</fullName>
                </value>
                <value>
                    <fullName>DAGA</fullName>
                </value>
                <value>
                    <fullName>DAGA - Equipment Sales</fullName>
                </value>
                <value>
                    <fullName>Daikin Latin America</fullName>
                </value>
                <value>
                    <fullName>DALA</fullName>
                </value>
                <value>
                    <fullName>DALA - Andean Pact</fullName>
                </value>
                <value>
                    <fullName>DALA - Caribbean</fullName>
                </value>
                <value>
                    <fullName>DALA - Central America</fullName>
                </value>
                <value>
                    <fullName>DALA - Service</fullName>
                </value>
                <value>
                    <fullName>DANY</fullName>
                </value>
                <value>
                    <fullName>DANY - Consulting Sales</fullName>
                </value>
                <value>
                    <fullName>DANY - Equipment Sales</fullName>
                </value>
                <value>
                    <fullName>Field Service</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>MCP</fullName>
                </value>
                <value>
                    <fullName>Mexico</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/opportunityRollupsBatchHelper.cls
public class opportunityRollupsBatchHelper {
   
    public static list<opportunity> opportunityRollupsUpdate(List<Opportunity> oppList)
    {
        set<id> userIds = new set<id>();
        set<String> contactIds = new set<String>();
        List<Opportunity> oppToBeUpdated = new List<Opportunity>();
        System.debug('Oppoty List::::::::'+oppList);
        for(Opportunity opp :oppList)
        {
            for(OpportunityContactRole r : opp.OpportunityContactRoles)
            {
                contactIds.add(r.contactId);
            }  
            for(Bidder__c b: opp.Bidders__r)
            {
                userIds.add(b.ownerId);
            }
        }
        
        Map<Id, Contact> contactMap = new Map<Id, Contact>([SELECT Name, Account.Name FROM Contact WHERE Id IN :contactIds Order By Name]);
        Map<Id, User> userMap = new Map<Id, User>([SELECT id, Name, User_Department__c from User WHERE id IN : userIds]);
        for(Opportunity opp :oppList){
            Integer childCount = 0;
            opp.Contact_Rollup__c = '';
            for(OpportunityContactRole r : opp.OpportunityContactRoles){
                childCount++;
                if(childCount != opp.OpportunityContactRoles.size()){
                    opp.Contact_Rollup__c += contactMap.get(r.contactId).Name+
                        ' @ '+contactMap.get(r.contactId).Account.Name+' ('+r.Role+')'+'; ';
                }
                else{
                    opp.Contact_Rollup__c += contactMap.get(r.contactId).Name+
                        ' @ '+contactMap.get(r.contactId).Account.Name+' ('+r.Role+')';    
                }
            }
            opp.Product_Rollup__c = '';
            childCount = 0;
            for(OpportunityLineItem opli : opp.OpportunityLineItems){
                childCount++;
                if(childCount != opp.OpportunityLineItems.size()){
                    opp.Product_Rollup__c += opli.Product2.Name  +', '; 
                }else{
                    opp.Product_Rollup__c += opli.Product2.Name; 
                }
                
            }
            
            opp.Bidder_Rollup__c = '';
            childCount = 0;
            for(Bidder__c b : opp.Bidders__r){
                childCount++;
                String department = userMap.get(b.ownerId).User_Department__c;
                System.debug('Department::'+department);
               
                if(department == null){
                  department = '-';    
                }
                if(childCount != opp.Bidders__r.size()){
                    opp.Bidder_Rollup__c += b.Bidder_Name__r.Name+'-'+b.owner.Name+' ('+department+'), AWB='+b.Apparent_Winning_Bidder__c+'; ';
                }else{
                    opp.Bidder_Rollup__c += b.Bidder_Name__r.Name+'-'+b.owner.Name+' ('+department+'), AWB='+b.Apparent_Winning_Bidder__c;         
                }
                
            }
            if(opp.OpportunityContactRoles.size() > 0 || opp.Bidders__r.size() > 0 || opp.OpportunityLineItems.size() >0){
                opp.Edited__c = false;
                oppToBeUpdated.add(opp);     
            }
            
        }
        try{
            if(!oppToBeUpdated.isEmpty()){
                update oppToBeUpdated;   
            }
        }
        catch(Exception e){
            System.debug('Line Number::'+e.getLineNumber()+'\n StackTrace::'+e.getStackTraceString());
            System.debug('Error ::'+e.getMessage());
        } 
        return oppToBeUpdated;
    }
}