src/objects/Bidder__c.object
<CustomObject>
    <description>DMNY</description>
    <fields>
        <fullName>Apparent_Winning_Bidder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Apparent Winning Bidder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bidder_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>DMNY</description>
        <label>Bidder Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bidders</relationshipLabel>
        <relationshipName>Bidders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates bidder not successful or no longer active.</description>
        <inlineHelpText>Indicates bidder not successful or no longer active.</inlineHelpText>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Bidders</relationshipLabel>
        <relationshipName>Bidders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bidder</label>
    <nameField>
        <label>Bidder Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bidders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Bidder_Rollup__c</fullName>
        <label>Bidder Rollup</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact_Rollup__c</fullName>
        <description>It is a combination of Contact Name + “@” + Account Name + “(“Role”)”</description>
        <label>Contact Rollup</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Edited__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Edited</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Rollup__c</fullName>
        <label>Product Rollup</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/OpportunityRollupsBatch.cls
global class OpportunityRollupsBatch implements Database.Batchable<sObject> {
  
    global Database.QueryLocator start(Database.BatchableContext BC) {
        // collect the batches of records or objects to be passed to execute
       
        String North_America_DSO_RecordTypeId  = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('North America - DSO').getRecordTypeId(); 
        String query = 'SELECT Id, Contact_Rollup__c,Bidder_Rollup__c,Product_Rollup__c, '+
            '(SELECT Id,ContactId,Role FROM OpportunityContactRoles),'+
            ' (SELECT Product2.Name FROM OpportunityLineItems Order By Product2.Name),'+
            ' (SELECT Bidder_Name__r.Name,ownerId, Owner.Name, Apparent_Winning_Bidder__c FROM Bidders__r WHERE Inactive__c=False Order By Bidder_Name__r.Name) '+
            ' FROM Opportunity '+
            ' WHERE RecordTypeId = :North_America_DSO_RecordTypeId AND Edited__c =true ';
        System.debug('query'+query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Opportunity> oppList) {
        opportunityRollupsBatchHelper.opportunityRollupsUpdate(oppList);
        
    } 
    global void finish(Database.BatchableContext BC) {
        // execute any post-processing operations
                
    }
}