src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Additional_Materials_Amount_Approved__c</fullName>
        <inlineHelpText>What Additional Materials Dollar Amounts were approved?</inlineHelpText>
        <label>Additional Materials Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Additional_Materials_Amount_Requested__c</fullName>
        <inlineHelpText>What Additional Materials Dollar Amounts were requested?</inlineHelpText>
        <label>Additional Materials Amount Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>The Assets DW Business Unit</description>
        <formula>IF(Asset.Product2.DW_Product_Business_Unit__c = &quot;Applied Air Handler&quot;,&apos;AAH&apos;, 
IF(Asset.Product2.DW_Product_Business_Unit__c = &quot;Applied Terminal Systems&quot;, &apos;ATS&apos;,
IF(Asset.Product2.DW_Product_Business_Unit__c = &quot;Chiller&quot;, &apos;Chillers&apos;,
IF(Asset.Product2.DW_Product_Business_Unit__c = &quot;Controls&quot;, &apos;Controls&apos;,
IF(Asset.Product2.DW_Product_Business_Unit__c !=&quot;&quot;, &apos;VAV&apos;,&apos;Unknown&apos;)
)
)
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Assets DW Business Unit</inlineHelpText>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Daikin_Parts_Amount_Approved__c</fullName>
        <inlineHelpText>What Daikin Parts Dollar Amounts were approved?</inlineHelpText>
        <label>Daikin Parts Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Daikin_Parts_Amount_Requested__c</fullName>
        <inlineHelpText>How much of the warranty request is for Daikin Parts?</inlineHelpText>
        <label>Daikin Parts Amount Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hours_Approved__c</fullName>
        <description>The hours amount of labor Daikin will reimburse for Warranty that have been approved. Compare with Hours Requested</description>
        <inlineHelpText>The labor hours that will be reimbursed and have been approved. Compare to Hours Requested on the case ticket</inlineHelpText>
        <label>Hours Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hours_Requested__c</fullName>
        <description>The hours amount of labor that have been requested for Warranty claims. Compare with Hours Approved</description>
        <inlineHelpText>The requested labor hours to fix asset under warranty</inlineHelpText>
        <label>Hours Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Labor_Amount_Approved__c</fullName>
        <inlineHelpText>What Labor Dollar Amounts were approved?</inlineHelpText>
        <label>Labor Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Labor_Amount_Requested__c</fullName>
        <inlineHelpText>How much of the warranty request is for Labor?</inlineHelpText>
        <label>Labor Amount Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X3rd_Party_Parts_Amount_Approved__c</fullName>
        <inlineHelpText>What 3rd Party Parts Dollar Amounts were approved?</inlineHelpText>
        <label>3rd-Party Parts Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X3rd_Party_Parts_Amount_Requested__c</fullName>
        <inlineHelpText>How much of the warranty request is for 3rd-Party Parts?</inlineHelpText>
        <label>3rd-Party Parts Amount Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Warranty</fullName>
        <active>true</active>
        <businessProcess>Warranty</businessProcess>
        <description>Used for Warranty case claims</description>
        <label>Warranty</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Service_Code__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Materials_Amount_Approved__c</fullName>
        <label>Additional Materials Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Additional_Materials_Amount_Requested__c</fullName>
        <label>Additional Materials Amount Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Business_Unit_Calc__c</fullName>
        <formula>Case__r.Business_Unit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Service Codes</relationshipLabel>
        <relationshipName>Case_Service_Codes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Daikin_Parts_Amount_Approved__c</fullName>
        <label>Daikin Parts Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Daikin_Parts_Amount_Requested__c</fullName>
        <label>Daikin Parts Amount Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hours_Approved__c</fullName>
        <label>Hours Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hours_Requested__c</fullName>
        <label>Hours Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Labor_Amount_Approved__c</fullName>
        <label>Labor Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Labor_Amount_Requested__c</fullName>
        <label>Labor Amount Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MajorCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Major</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Case Service Codes (Major)</relationshipLabel>
        <relationshipName>Case_Service_Codes4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ModeCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mode</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Case Service Codes (Mode)</relationshipLabel>
        <relationshipName>Case_Service_Codes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Responsibility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsibility</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Case Service Codes (Responsibility)</relationshipLabel>
        <relationshipName>Case_Service_Codes6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SpecificCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Specific</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Case Service Codes (Specific)</relationshipLabel>
        <relationshipName>Case_Service_Codes5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TypeCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Type</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Case Service Codes (Type)</relationshipLabel>
        <relationshipName>Case_Service_Codes3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Case Service Codes (Unit)</relationshipLabel>
        <relationshipName>Case_Service_Codes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WarrantyClassCode__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Warranty Class</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Case Service Codes (Warranty Class)</relationshipLabel>
        <relationshipName>Case_Service_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X3rd_Party_Parts_Amount_Approved__c</fullName>
        <label>3rd-Party Parts Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X3rd_Party_Parts_Amount_Requested__c</fullName>
        <label>3rd-Party Parts Amount Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Case Service Code</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Case Service Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Service Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Code__c.object
<CustomObject>
    <description>Captures failure codes for Warranty parts and equipment claims</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Service Codes</relationshipLabel>
        <relationshipName>Service_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Business Unit</fullName>
                </value>
                <value>
                    <fullName>Unit</fullName>
                </value>
                <value>
                    <fullName>Mode</fullName>
                </value>
                <value>
                    <fullName>Type</fullName>
                </value>
                <value>
                    <fullName>Major</fullName>
                </value>
                <value>
                    <fullName>Specific</fullName>
                </value>
                <value>
                    <fullName>Warranty Class</fullName>
                </value>
                <value>
                    <fullName>Responsibility</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Code</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Service_Code__c.Type__c</field>
                <operation>equals</operation>
                <value>Unit</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Service Codes (Service Code)</relationshipLabel>
        <relationshipName>Unit_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Code</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service_Code_Junction__c.object
<CustomObject>
    <description>Used with service codes object</description>
    <fields>
        <fullName>Child__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Child</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Service Code Junctions (Service Code)</relationshipLabel>
        <relationshipName>Service_Code_Junctions1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Service Code Junctions (Parent)</relationshipLabel>
        <relationshipName>Service_Code_Junctions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>Text(Child__r.Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Unit</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Service_Code__c.Type__c</field>
                <operation>equals</operation>
                <value>Unit</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Service Code Junctions (Unit)</relationshipLabel>
        <relationshipName>Service_Code_Junctions2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Code Junction</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Code Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InlineEditServiceCodeExt.cls
public with sharing class InlineEditServiceCodeExt {
    public Id caseId {get; set;}
    public Id deletedCodeId {get; set;}
    public Id cloneCodeId {get; set;}
    public String newCodeUrl {get; set;}
    public List<Case_Service_Code__c> codesToBeDeleted = new List<Case_Service_Code__c>();
    public List<CaseServiceModel> serviceCodes {get; set;}
    public final String NEW_CODE_PAGE = '/apex/CaseServiceCodeEdit2?Id=';
    public final String SERVICE_CODE_TYPE = 'Business Unit';
    public Map<String, ServiceCodeModel> typeToModel;
    public static final String BUSINESS_UNIT = 'Business Unit';
    public static final Set<String> BUSINESS_TYPES = new Set<String>{
        'Business Unit',
        'Unit',
        'Mode',
        'Type',
        'Major',
        'Specific',
        'Warranty Class',
        'Responsibility'
    };
    public Map<Id, Case_Service_Code__c> idToCode = new Map<Id, Case_Service_Code__c>();
    public InlineEditServiceCodeExt(ApexPages.StandardController controller) {
        Case currentCase = [SELECT Business_Unit__c FROM Case WHERE Id =:controller.getRecord().Id LIMIT 1];

        this.caseId = currentCase.Id;
        List<Service_Code__c> businessCodeForCase = [SELECT Id FROM Service_Code__c WHERE Name =: currentCase.Business_Unit__c AND Type__c =: BUSINESS_UNIT LIMIT 1];
        String templateQuery = 'SELECT Business_Unit_Calc__c, UnitCode__c, TypeCode__c, MajorCode__c,ModeCode__c, SpecificCode__c, WarrantyClassCode__c, Responsibility__c, {0} FROM Case_Service_Code__c WHERE Case__c = {1}';
        List<String> fillers = new List<String>{serviceCodeFields(), '\'' + caseId + '\''};
        String query = String.format(templateQuery, fillers);
        this.typeToModel = ServiceCodeModel.generateModelsPerType(BUSINESS_TYPES);
        //for (Service_Code__c code : [SELECT Name, Label__c, Parent__c, Type__c, Unit_Code__c FROM Service_Code__c WHERE Type__c IN: BUSINESS_TYPES AND Active__c = true]) {
        //    typeToModel.get(code.Type__c).add(code);
        //}
        
        this.serviceCodes = new List<CaseServiceModel>();
        for(Case_Service_Code__c cs : Database.query(query)) {
            serviceCodes.add(new CaseServiceModel(cs, typeToModel, businessCodeForCase[0].Id));
        }

    }
    private String serviceCodeFields() {
        List<String> fieldNames = new List<String>{'Name'};
        Schema.FieldSet fieldSet = Schema.SObjectType.Case_Service_Code__c.fieldSets.getMap().get('In_Line_Edit');
        for (Schema.FieldSetMember field : fieldSet.getFields()) {
            fieldNames.add(field.getFieldPath());
        }
        return String.join(fieldNames, ',');
    }

    public void handleDelete() {
        for (Integer i = 0; i < serviceCodes.size(); i++ ) {
            if (serviceCodes[i].caseServiceCode.Id == deletedCodeId) {
                codesToBeDeleted.add(serviceCodes[i].caseServiceCode);
                serviceCodes.remove(i);
                break;
            }
        }
    }

    public void handleNew() {
        Case parentCase = [
            SELECT Business_Unit__c 
            FROM Case
            WHERE Id =: this.caseId
            LIMIT 1
        ];
        Case_Service_Code__c newCaseServiceCode = new Case_Service_Code__c(
            Case__c=parentCase.Id
        );
        try {
            insert newCaseServiceCode;
            newCodeUrl = NEW_CODE_PAGE + newCaseServiceCode.Id;
        } catch(DmlException e) {
            ApexPages.addmessage(
                new ApexPages.message(
                    ApexPages.severity.ERROR,
                    'There was an error contructing shell record for the new code page: ' + e.getMessage())
            );
            newCodeUrl = null;  
        }
    }

    public PageReference handleClone() {
        Case_Service_Code__c csc = [SELECT Id, Case__c, Description__c, 
            X3rd_Party_Parts_Amount_Approved__c, X3rd_Party_Parts_Amount_Requested__c, 
            Additional_Materials_Amount_Approved__c, Additional_Materials_Amount_Requested__c,  
            Daikin_Parts_Amount_Approved__c, Daikin_Parts_Amount_Requested__c, 
            Hours_Approved__c, Hours_Requested__c, 
            Labor_Amount_Approved__c, Labor_Amount_Requested__c, 
            MajorCode__c, ModeCode__c, 
            Responsibility__c, SpecificCode__c, 
            TypeCode__c, UnitCode__c, WarrantyClassCode__c
            FROM Case_Service_code__c
            WHERE Id =: cloneCodeId
            LIMIT 1
        ];
        Case_Service_Code__c newCaseServiceCode = csc.clone();
        try {
            insert newCaseServiceCode;
        } catch(DmlException e) {
            ApexPages.addmessage(
                new ApexPages.message(
                    ApexPages.severity.ERROR,
                    'There was an error contructing shell record for the new code page: ' + e.getMessage())
            );
        }
        PageReference pageRef = new PageReference('/apex/InlineEditServiceCode?Id='+csc.Case__c);
        pageRef.setRedirect(true);
        return pageRef;
    }

    public PageReference save() {
        Savepoint sp = Database.setSavepoint();
        List<Case_Service_Code__c> updatedCaseServiceCodes = new List<Case_Service_Code__c>();
        for(CaseServiceModel csm : serviceCodes) {
            updatedCaseServiceCodes.add(csm.caseServiceCode);
        }
        try {
            update updatedCaseServiceCodes;
            delete codesToBeDeleted;
        } catch(Exception e) {
            ApexPages.addmessage(
                new ApexPages.message(ApexPages.severity.ERROR,'There was an error saving records: ' + e.getMessage())
            );
            Database.rollback(sp);
            return null;
        }
        PageReference pr = new PageReference('/apex/InlineEditServiceCode?Id=' + caseId);
        pr.setRedirect(true);
        return pr;
    }

   public class CaseServiceModel{
        String businessUnitId;
        public Case_Service_Code__c caseServiceCode {get;set;}
        Map<String, ServiceCodeModel> scModel;
        public List<SelectOption> unitOptions {
            get{
                String type = 'Unit';
                this.scModel.get(type).removeAll();
                //for (Service_Code__c code : [SELECT Name, Label__c, Parent__c, Type__c, Unit_Code__c FROM Service_Code__c WHERE Type__c =:type AND Parent__c=:businessUnitId AND Active__c = true order by Label__c]) {
                //    this.scModel.get(type).add(code);
                //}
                for(Service_Code_Junction__c sc :[select Child__r.Id, Child__r.Name, Child__r.Label__c from Service_Code_Junction__c where Child__r.Type__c='Unit' and Child__r.Active__c=true and Parent__c=:businessUnitId order by Child__r.Label__c])
                    this.scModel.get(type).add(sc.Child__r);
                //return formatOptions(this.scModel.get(type).serviceCodesWithParent.get(businessUnitId));
                return formatOptions(this.scModel.get(type).all());
            }set;}
        public List<SelectOption> modeOptions{
            get{
                String type = 'Mode';
                this.scModel.get(type).removeAll();
                for (Service_Code__c code : [SELECT Name, Label__c, Parent__c, Type__c, Unit_Code__c FROM Service_Code__c WHERE Type__c =:type AND Active__c = true order by Label__c]) {
                    this.scModel.get(type).add(code);
                }
                return formatOptions(this.scModel.get(type).all());
            }set;}
        public List<SelectOption> typeOptions{
            get {
                String type = 'Type';
                this.scModel.get(type).removeAll();
                //for (Service_Code__c code : [SELECT Name, Label__c, Parent__c, Type__c, Unit_Code__c FROM Service_Code__c WHERE Type__c =:type AND Parent__c=:this.caseServiceCode.ModeCode__c AND Unit_Code__c=:this.caseServiceCode.UnitCode__c AND Active__c = true order by Label__c]) {
                //    this.scModel.get(type).add(code);
                //}
                for(Service_Code_Junction__c sc :[select Child__r.Id, Child__r.Name, Child__r.Label__c from Service_Code_Junction__c where Child__r.Type__c='Type' and Child__r.Active__c=true and Parent__c=:this.caseServiceCode.ModeCode__c and Unit__c=:this.caseServiceCode.UnitCode__c order by Child__r.Label__c])
                    this.scModel.get(type).add(sc.Child__r);
                //return formatOptions(this.scModel.get(type).fromParentAndUnit(this.caseServiceCode.ModeCode__c, this.caseServiceCode.UnitCode__c));
                return formatOptions(this.scModel.get(type).all());
            }set;}
        public List<SelectOption> majorOptions{
            get{
                String type = 'Major';
                this.scModel.get(type).removeAll();
                //for (Service_Code__c code : [SELECT Name, Label__c, Parent__c, Type__c, Unit_Code__c FROM Service_Code__c WHERE Type__c =:type AND Parent__c=:businessUnitId AND Unit_Code__c=:this.caseServiceCode.UnitCode__c AND Active__c = true order by Label__c]) {
                //    this.scModel.get(type).add(code);
                //}
                for(Service_Code_Junction__c sc :[select Child__r.Id, Child__r.Name, Child__r.Label__c from Service_Code_Junction__c where Child__r.Type__c='Major' and Child__r.Active__c=true and Parent__c=:businessUnitId and Unit__c=:this.caseServiceCode.UnitCode__c order by Child__r.Label__c])
                    this.scModel.get(type).add(sc.Child__r);
                //return formatOptions(this.scModel.get(type).fromParentAndUnit(businessUnitId, this.caseServiceCode.UnitCode__c));
                return formatOptions(this.scModel.get(type).all());
            }set;}
        public List<SelectOption> specificOptions{
            get{
                String type = 'Specific';
                this.scModel.get(type).removeAll();
                //for (Service_Code__c code : [SELECT Name, Label__c, Parent__c, Type__c, Unit_Code__c FROM Service_Code__c WHERE Type__c =:type AND Parent__c=:this.caseServiceCode.MajorCode__c AND Unit_Code__c=:this.caseServiceCode.UnitCode__c AND Active__c = true order by Label__c]) {
                //    this.scModel.get(type).add(code);
                //}
                for(Service_Code_Junction__c sc :[select Child__r.Id, Child__r.Name, Child__r.Label__c from Service_Code_Junction__c where Child__r.Type__c='Specific' and Child__r.Active__c=true and Parent__c=:this.caseServiceCode.MajorCode__c and Unit__c=:this.caseServiceCode.UnitCode__c order by Child__r.Name])
                    this.scModel.get(type).add(sc.Child__r);
                //return formatOptions(this.scModel.get(type).fromParentAndUnit(this.caseServiceCode.MajorCode__c, this.caseServiceCode.UnitCode__c));
                return formatOptions(this.scModel.get(type).all());
            }set;}
        public List<SelectOption> warrantyOptions{
            get{
                String type = 'Warranty Class';
                this.scModel.get(type).removeAll();
                //for (Service_Code__c code : [SELECT Name, Label__c, Parent__c, Type__c, Unit_Code__c FROM Service_Code__c WHERE Type__c =:type AND Parent__c=:businessUnitId AND Active__c = true order by Label__c]) {
                //    this.scModel.get(type).add(code);
                //}
                for(Service_Code_Junction__c sc :[select Child__r.Id, Child__r.Name, Child__r.Label__c from Service_Code_Junction__c where Child__r.Type__c='Warranty Class' and Child__r.Active__c=true and Parent__c=:businessUnitId order by Child__r.Label__c])
                    this.scModel.get(type).add(sc.Child__r);
                //return formatOptions(this.scModel.get(type).serviceCodesWithParent.get(businessUnitId));
                return formatOptions(this.scModel.get(type).all());
            }set;}
        public List<SelectOption> respOptions{
            get{
                String type = 'Responsibility';
                this.scModel.get(type).removeAll();
                //for (Service_Code__c code : [SELECT Name, Label__c, Parent__c, Type__c, Unit_Code__c FROM Service_Code__c WHERE Type__c =:type AND Parent__c=:businessUnitId AND Active__c = true order by Label__c]) {
                //    this.scModel.get(type).add(code);
                //}
                for(Service_Code_Junction__c sc :[select Child__r.Id, Child__r.Name, Child__r.Label__c from Service_Code_Junction__c where Child__r.Type__c='Responsibility' and Child__r.Active__c=true and Parent__c=:businessUnitId order by Child__r.Name])
                    this.scModel.get(type).add(sc.Child__r);
                //return formatOptions(this.scModel.get(type).serviceCodesWithParent.get(businessUnitId));
                return formatOptions(this.scModel.get(type).all());
            }set;}
        public CaseServiceModel(Case_Service_Code__c caseServiceCode, Map<String, ServiceCodeModel> typeToModel, String businessUnitId) {
            this.caseServiceCode = caseServiceCode;
            this.scModel = typeToModel;
            this.businessUnitId = businessUnitId;
        }
        private List<SelectOption> formatOptions(List<Service_Code__c> serviceCodes) {
            if (serviceCodes == null) {
                return null;
            }
            List<SelectOption> options = new List<SelectOption>{new SelectOption('', '')};
            for(Service_Code__c code :(List<Service_Code__c>)serviceCodes) {
                String optionLabel = '';
                if (code.Name != null) {
                    optionLabel = code.Name;
                }
                if (code.Label__c != null) {
                    optionLabel = code.Label__c;
                }

                options.add(new SelectOption(code.Id, optionLabel));
            }
            return options;
        }
   }
}