src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Monitoring__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>&quot;Monitoring&quot; should be used when a customer has said they are going to keep an eye on the issue, but we have no further action. This can only be edited on the Close Case Page Layout.</inlineHelpText>
        <label>Monitoring</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Events__c</fullName>
        <label>Number of Events</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Tasks__c</fullName>
        <label>Number of Tasks</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Original_Inquiry_Date_Time__c</fullName>
        <description>Date/Time of the original inquiry.  If the case was received via voicemail or email that date/time should be entered here.  Otherwise update with what the date/time is upon creation.</description>
        <inlineHelpText>Date/Time of the original inquiry. (e.g. - Voicemail or Email Date/Time)</inlineHelpText>
        <label>Original Inquiry Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Resolution_Description__c</fullName>
        <label>Resolution Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Resolution_Type__c</fullName>
        <label>Resolution Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Answered Question</fullName>
                </value>
                <value>
                    <fullName>Dispatch Daikin Applied Service Technician</fullName>
                </value>
                <value>
                    <fullName>Duplicate Call</fullName>
                </value>
                <value>
                    <fullName>Issued FPA to Rep</fullName>
                </value>
                <value>
                    <fullName>Moved to Change Request</fullName>
                </value>
                <value>
                    <fullName>Multiple requests</fullName>
                </value>
                <value>
                    <fullName>New Part Required</fullName>
                </value>
                <value>
                    <fullName>No action needed</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Performed Requested Task</fullName>
                </value>
                <value>
                    <fullName>SLP Rapid Response</fullName>
                </value>
                <value>
                    <fullName>Transferred to Customer Service</fullName>
                </value>
                <value>
                    <fullName>Transferred to Parts</fullName>
                </value>
                <value>
                    <fullName>Transferred to TRC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Asset__c.object
<CustomObject>
    <description>Junction object to allow association of more than one Asset record on a Case.</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Assets</relationshipLabel>
        <relationshipName>Case_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Case Asset</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Case Asset ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CaseAssetFields__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>API__c</fullName>
        <label>API</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Asset Fields</label>
</CustomObject>

src/classes/CloneCaseWithCaseAssetController.cls
public class CloneCaseWithCaseAssetController {
   
    private Id caseId;
    public  Case c;
    private ApexPages.StandardController sc;
    public CloneCaseWithCaseAssetController(ApexPages.StandardController stdController) {
        caseId = ApexPages.currentPage().getParameters().get('id');
        c = (case)stdController.getRecord();
        c.status = 'New';
        c.Resolution_Type__c = null;
        c.Resolution_Description__c = null;
        c.Monitoring__c = null;
		c.Original_Inquiry_Date_Time__c = null;
        this.sc = stdController;
    }
    
    public String save(){
        try{
            PageReference pageRef = sc.save();
        }catch(Exception e){
            System.debug('Error: '+e);
        }
        
        String newCaseId = sc.getId();
        
        //create dynamic query and get all the fields of Case Asset Object from Custom setting
        String query = 'Select ';        
        for(CaseAssetFields__c str : CaseAssetFields__c.getAll().values()){  
            query += str.API__c + ', ' ;
        }
        query +=  'Id from Case_Asset__C where Case__c =: caseId';
        
        List<Case_Asset__c> caseAssetList = Database.query(query);
        
        if(!caseAssetList.isEmpty()){
            List<Case_Asset__c> newCaseAssetList = new List<Case_Asset__c>();
            for(Case_Asset__c caseAsset : caseAssetList){
                Case_Asset__c caseAssetObj = new Case_Asset__C();
                caseAssetObj.Case__c = newCaseId;
                for(CaseAssetFields__c str : CaseAssetFields__c.getAll().values()){      
                    caseAssetObj.put(str.API__c,caseAsset.get(str.API__c));          
                }
                newCaseAssetList.add(caseAssetObj);
            }
            
            if(!newCaseAssetList.isEmpty()){
                Database.SaveResult[] result = Database.insert(newCaseAssetList,false);
                for (Database.SaveResult sr : result) {
                    if (sr.isSuccess()) {
                        System.debug('Successfully inserted Case Asset. Case Asset ID: ' + sr.getId());
                    }
                    else {
                        for(Database.Error err : sr.getErrors()) {
                            System.debug(err.getStatusCode() + ': ' + err.getMessage());
                            System.debug('Case Asset fields that affected this error: ' + err.getFields());
                        }
                    }
                }
            }           
        }
        return newCaseId;
    }
    
    public PageReference saveCase(){
        String newCaseId = save();
        if(newCaseId!=null){
            Case c = [select id,status from case where id = :newCaseId limit 1];
            c.status = 'New';
            c.Number_of_Tasks__c = 0;
            c.Number_of_Events__c = 0;
            update c;
        }
        PageReference pageRef ;
        if(newCaseId != null){
            pageRef = new PageReference('/'+newCaseId);
        }
        return pageRef;
    }
    
    public PageReference saveAndNewCase(){
        String newCaseId = save();
        PageReference pageRef ;
        if(caseId != null){
            pageRef = new PageReference('/setup/ui/recordtypeselect.jsp?ent=Case&retURL=/500/o&save_new_url=/500/e?retURL=/500/o');
        }
        return pageRef;
    }
    
    public PageReference saveAndClose(){
        String newCaseId = save();
        PageReference pageRef ;
        if(newCaseId != null){
            pageRef = new PageReference('/'+newCaseId+'/s?retURL=/'+newCaseId);
        }
        return pageRef;    
    }
}