src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Additional_Materials_Amount_Approved__c</fullName>
        <inlineHelpText>What Additional Materials Dollar Amounts were approved?</inlineHelpText>
        <label>Additional Materials Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>The Assets DW Business Unit</description>
        <formula>IF(Asset.Product2.DW_Product_Business_Unit__c = &quot;Applied Air Handler&quot;,&apos;AAH&apos;, 
IF(Asset.Product2.DW_Product_Business_Unit__c = &quot;Applied Terminal Systems&quot;, &apos;ATS&apos;,
IF(Asset.Product2.DW_Product_Business_Unit__c = &quot;Chiller&quot;, &apos;Chillers&apos;,
IF(Asset.Product2.DW_Product_Business_Unit__c = &quot;Controls&quot;, &apos;Controls&apos;,
IF(Asset.Product2.DW_Product_Business_Unit__c !=&quot;&quot;, &apos;VAV&apos;,&apos;Unknown&apos;)
)
)
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Assets DW Business Unit</inlineHelpText>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Daikin_Parts_Amount_Approved__c</fullName>
        <inlineHelpText>What Daikin Parts Dollar Amounts were approved?</inlineHelpText>
        <label>Daikin Parts Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hours_Approved__c</fullName>
        <description>The hours amount of labor Daikin will reimburse for Warranty that have been approved. Compare with Hours Requested</description>
        <inlineHelpText>The labor hours that will be reimbursed and have been approved. Compare to Hours Requested on the case ticket</inlineHelpText>
        <label>Hours Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Labor_Amount_Approved__c</fullName>
        <inlineHelpText>What Labor Dollar Amounts were approved?</inlineHelpText>
        <label>Labor Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <formula>Asset.Product2.ProductCode</formula>
        <inlineHelpText>Serial Numbers Model</inlineHelpText>
        <label>Model</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <formula>Asset.SerialNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Serial Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Summed_Amount_Approved__c</fullName>
        <formula>IF( 
Labor_Amount_Approved__c  + Daikin_Parts_Amount_Approved__c + Additional_Materials_Amount_Approved__c +  X3rd_Party_Parts_Amount_Approved__c&gt;0, 

Labor_Amount_Approved__c + Daikin_Parts_Amount_Approved__c + Additional_Materials_Amount_Approved__c + X3rd_Party_Parts_Amount_Approved__c, NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Sum of Labor, Daikin Parts, 3rd-Party Parts &amp; Additional Materials Amount Approved</inlineHelpText>
        <label>Total Summed Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X3rd_Party_Parts_Amount_Approved__c</fullName>
        <inlineHelpText>What 3rd Party Parts Dollar Amounts were approved?</inlineHelpText>
        <label>3rd-Party Parts Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Service_Code__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Materials_Amount_Approved__c</fullName>
        <label>Additional Materials Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Asset_PCL__c</fullName>
        <formula>Case__r.Asset.Product_Class__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Asset PCL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Service Codes</relationshipLabel>
        <relationshipName>Case_Service_Codes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Daikin_Parts_Amount_Approved__c</fullName>
        <label>Daikin Parts Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hours_Approved__c</fullName>
        <label>Hours Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Labor_Amount_Approved__c</fullName>
        <label>Labor Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MajorCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Major</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Case Service Codes (Major)</relationshipLabel>
        <relationshipName>Case_Service_Codes4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ModeCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mode</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Case Service Codes (Mode)</relationshipLabel>
        <relationshipName>Case_Service_Codes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Responsibility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsibility</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Case Service Codes (Responsibility)</relationshipLabel>
        <relationshipName>Case_Service_Codes6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Special_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Special Type</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Case Service Codes (Special Type)</relationshipLabel>
        <relationshipName>Case_Service_Codes7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SpecificCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Specific</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Case Service Codes (Specific)</relationshipLabel>
        <relationshipName>Case_Service_Codes5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Amount_Approved__c</fullName>
        <formula>Labor_Amount_Approved__c + Additional_Materials_Amount_Approved__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TypeCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Type</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Case Service Codes (Type)</relationshipLabel>
        <relationshipName>Case_Service_Codes3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WarrantyClassCode__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Warranty Class</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Case Service Codes (Warranty Class)</relationshipLabel>
        <relationshipName>Case_Service_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X3rd_Party_Parts_Amount_Approved__c</fullName>
        <label>3rd-Party Parts Amount Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Case Service Code</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Case Service Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Service Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Code__c.object
<CustomObject>
    <description>Captures failure codes for Warranty parts and equipment claims</description>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Service Code</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WarrantyAuthorizationRelatedChildCases.cls
public class WarrantyAuthorizationRelatedChildCases {
    public Id CaseIdvalue {Set;get;}
    public List<Case> caseToDisplay;
    public Map<String, List<Case_Service_Code__c>> caseServiceCodesList;
    public  WarrantyAuthorizationRelatedChildCases(ApexPages.StandardController acon)
    {
          CaseIdvalue = ApexPages.currentPage().getParameters().get('id');
    }
    public List<Case> casess{
        get{        
            
            caseToDisplay = new List<Case>();
            system.debug('CaseIdvalue::'+CaseIdvalue);
            List<Case> caseList = [SELECT Id,(SELECT Id,Serial_Number__c,Model__c,Total_Summed_Amount_Approved__c,CaseNumber,Hours_Approved__c,Labor_Amount_Approved__c,Additional_Materials_Amount_Approved__c,X3rd_Party_Parts_Amount_Approved__c,Daikin_Parts_Amount_Approved__c from Cases LIMIT 1000) FROM Case WHERE Case.Id=:CaseIdvalue LIMIT 1000];
            for(Case cc:caseList){
                {
                    for(Case cs : cc.Cases)
                    {
                        system.debug('cs--'+cs);
                        if(cs.Hours_Approved__c != null && cs.Hours_Approved__c>0)
                            cs.Hours_Approved__c = cs.Hours_Approved__c.setScale(2);
                        system.debug('cs--'+cs);
                        caseToDisplay.add(cs);
                        System.debug('Child Cases Ids::::::::'+cs.id);
                    }
                }
              
            }
          
            return caseToDisplay;
        }
        set;
    }
    
    public Map<String, List<Case_Service_Code__c>> getservicecodes{
        get{
            caseServiceCodesList = new Map<String, List<Case_Service_Code__c>>();
            System.debug(caseToDisplay);
            List<Case> caseList = [select (SELECT Id,Name, Case__c,WarrantyClassCode__r.Name,Asset_PCL__c,WarrantyClassCode__r.Label__c,Hours_Approved__c,
                                           Labor_Amount_Approved__c,Additional_Materials_Amount_Approved__c,X3rd_Party_Parts_Amount_Approved__c,ModeCode__r.Name,ModeCode__r.Label__c,
                                           Case__r.Business_Unit__c,TypeCode__r.Name,TypeCode__r.Label__c,MajorCode__r.Name,MajorCode__r.Label__c,SpecificCode__r.Name,SpecificCode__r.Label__c, Special_Type__r.Name,
                                           Daikin_Parts_Amount_Approved__c,Total_Amount_Approved__c,Responsibility__c,Responsibility__r.Name FROM Case_Service_Codes__r ) from Case WHERE ID IN:  caseToDisplay LIMIT 1000];
            // List<Case_Service_Code__c> csccodes = [SELECT Id, Name, Case__c,WarrantyClassCode__r.Name,Asset_PCL__c,WarrantyClassCode__r.Label__c FROM Case_Service_Code__c where caseToDisplay];
            //System.debug(csccodes);
            
            for(Case ccsc : caseList)
            {
                caseServiceCodesList.put(ccsc.id, new List<Case_Service_Code__c>());
                
                for(Case_Service_Code__c cscode : ccsc.Case_Service_Codes__r)
                {
                    caseServiceCodesList.get(ccsc.id).add(cscode); 
                    
                    
                }
            }
            system.debug('Map ::'+caseServiceCodesList.keySet());
            return caseServiceCodesList;
        } 
        
        set;
    }
}