src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Plan</label>
        <referenceTo>Case_Plan__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <default>true</default>
                    <label>Completed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>QA Program</fullName>
                    <default>true</default>
                    <label>QA Program</label>
                </value>
                <value>
                    <fullName>Fix on Fail</fullName>
                </value>
                <value>
                    <fullName>Known Issue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Plan</label>
    <nameField>
        <label>Case Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case_Plan_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Case Plan Assets</relationshipLabel>
        <relationshipName>Case_Plan_Assets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Plan__c</fullName>
        <label>Case Plan</label>
        <referenceTo>Case_Plan__c</referenceTo>
        <relationshipLabel>Case Plan Assets</relationshipLabel>
        <relationshipName>Case_Plan_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Case Plan Asset</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Case Plan Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Plan Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Account Manager</fullName>
                </value>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>Architect</fullName>
                </value>
                <value>
                    <fullName>Buyer</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>DA Factory Service Tech</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Engineer</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>Independent Sales Rep</fullName>
                </value>
                <value>
                    <fullName>Main</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Project Manager</fullName>
                </value>
                <value>
                    <fullName>Service Tech</fullName>
                </value>
                <value>
                    <fullName>Team Member</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/importCasePlanAssetsFromCSVCntrlTest.cls
@isTest
public class importCasePlanAssetsFromCSVCntrlTest {
    
    public static  String[] csvFileLines;
    public  static Blob csvFileBody;
    static String str = 'Serial Number,Contact Email \n 1234,test@gmail.com\n 5678,info@gmail.com\n 9632,psevak@apttus.com'; 
    
    @testSetup
    static void testSetUp(){
        
        Case_Plan__c cp =new Case_Plan__c();
        cp.name ='Test Case Plan';
        cp.Type__c='QA Program';
        cp.CurrencyIsoCode='USD';
        cp.Status__c='Completed';
        
        insert cp;
        
        
        AVA_SFCORE__TaxNowSetting__c ts1 = new AVA_SFCORE__TaxNowSetting__c(); 
        ts1.AVA_SFCORE__Active_Setting__c = true; 
        ts1.Name='Test Account';
        insert ts1;
        
        Account testAccount = APTPS_DaikinTestDataUtility.getAccount('accName');
        insert testAccount;
        
        Contact testContact = APTPS_DaikinTestDataUtility.getContact(testAccount);
        insert testContact;
        
        Asset asset = new Asset();
        asset.Name = 'TEST';
        asset.SerialNumber = '1234';
        asset.AccountId = testAccount.Id;

        insert asset;
        
        Case_Plan_Asset__c casePlanAsset =new Case_Plan_Asset__c();
        casePlanAsset.Case_Plan__c=cp.id;
        casePlanAsset.Asset__c=asset.id;
        
        insert casePlanAsset;
        
        Asset asset1 = new Asset();
        asset1.Name = 'TEST1';
        asset1.SerialNumber = '5678';
        asset1.AccountId = testAccount.Id;
        
        insert asset1;
    }
    
    static testMethod void ImportCsvFile()
    {
        
        Test.startTest();     
        Case_Plan__c cp=[select id ,name from Case_Plan__c limit 1];
        list<contact> contacts =[select id ,lastname,Email from contact where Email ='test@gmail.com'];
        csvFileBody = Blob.valueOf(str);
        String csvAsString = csvFileBody.toString();
        csvFileLines = csvAsString.split('\n'); 
        
        //Positive Scenario
        ApexPages.StandardController sd = new ApexPages.StandardController(cp);
        importCasePlanAssetsFromCSVController importData =new importCasePlanAssetsFromCSVController(sd);
        importData.csvFileBody = csvFileBody;
        importData.importCSVFile();
        list<contact> con =[select id ,lastname,Email from contact where Email ='test@gmail.com'];
        
        system.assertNotEquals(contacts.size(), con.size());
        
        //Negative scenario
        Case_Plan__c cp1 =new Case_Plan__c();
        
        ApexPages.StandardController sd1 = new ApexPages.StandardController(cp1);
        importCasePlanAssetsFromCSVController importData1 =new importCasePlanAssetsFromCSVController(sd1);
        importData1.csvFileBody = null;
        importData1.importCSVFile();
        
        
        Test.stopTest();
    }
    
}