src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>The Assets DW Business Unit</description>
        <formula>IF(Asset.Product2.DW_Product_Business_Unit__c = &quot;Applied Air Handler&quot;,&apos;AAH&apos;, 
IF(Asset.Product2.DW_Product_Business_Unit__c = &quot;Applied Terminal Systems&quot;, &apos;ATS&apos;,
IF(Asset.Product2.DW_Product_Business_Unit__c = &quot;Chiller&quot;, &apos;Chillers&apos;,
IF(Asset.Product2.DW_Product_Business_Unit__c = &quot;Controls&quot;, &apos;Controls&apos;,
IF(Asset.Product2.DW_Product_Business_Unit__c !=&quot;&quot;, &apos;VAV&apos;,&apos;Unknown&apos;)
)
)
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Assets DW Business Unit</inlineHelpText>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <formula>Asset.Product2.ProductCode</formula>
        <inlineHelpText>Serial Numbers Model</inlineHelpText>
        <label>Model</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Class__c</fullName>
        <description>Product Class of the Asset</description>
        <formula>Asset.Product_Class__c</formula>
        <inlineHelpText>Product Class of the Asset</inlineHelpText>
        <label>Product Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <formula>Asset.SerialNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Serial Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_Date__c</fullName>
        <formula>Asset.Ship_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ship Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Startup_Date__c</fullName>
        <description>Startup Date field on the asset. If blank, assume none defined or delayed, etc. Used for Warranty definitions</description>
        <formula>Asset.Startup_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Populated from Asset. If blank, assume none defined or has been delayed</inlineHelpText>
        <label>Startup Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Warranty</fullName>
        <active>true</active>
        <businessProcess>Warranty</businessProcess>
        <description>Used for Warranty case claims</description>
        <label>Warranty</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Service_Code__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Service Codes</relationshipLabel>
        <relationshipName>Case_Service_Codes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Case Service Code</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Case Service Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Service Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Code__c.object
<CustomObject>
    <description>Captures failure codes for Warranty parts and equipment claims</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Service Codes</relationshipLabel>
        <relationshipName>Service_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Business Unit</fullName>
                </value>
                <value>
                    <fullName>Unit</fullName>
                </value>
                <value>
                    <fullName>Mode</fullName>
                </value>
                <value>
                    <fullName>Type</fullName>
                </value>
                <value>
                    <fullName>Major</fullName>
                </value>
                <value>
                    <fullName>Specific</fullName>
                </value>
                <value>
                    <fullName>Warranty Class</fullName>
                </value>
                <value>
                    <fullName>Responsibility</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Code</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Service_Code__c.Type__c</field>
                <operation>equals</operation>
                <value>Unit</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Service_Code__c</referenceTo>
        <relationshipLabel>Service Codes (Service Code)</relationshipLabel>
        <relationshipName>Unit_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Code</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CaseServiceCodeControllerExtension.cls
public class CaseServiceCodeControllerExtension {

    private final Case_Service_Code__c csc;
    private final Case c;
    private String buId;
    
    public CaseServiceCodeControllerExtension (ApexPages.StandardController stdController) {
        this.csc = (Case_Service_Code__c)stdController.getRecord();
        c = [select Id, Serial_Number__c, Model__c, Product_Class__c, Startup_Date__c, Ship_Date__c, Business_Unit__c from Case where Id=:csc.Case__c limit 1];
        Service_Code__c sc = [select Id, Name, Type__c, Active__c from Service_Code__c where Type__c='Business Unit' and Active__c=true and Name=:c.Business_Unit__c limit 1];
        buId = sc.Id;        
    }

    public String getSerialNumber(){
        return c.Serial_Number__c;
    }

    public String getStartupDate(){
        Datetime dte = (Datetime)c.Startup_Date__c;
        if(dte==null)
            return '';
        return dte.format('yyyy-MM-dd');
    }

    public String getShipDate(){
        Datetime dte = (Datetime)c.Ship_Date__c;
        if(dte==null)
            return '';
        return dte.format('yyyy-MM-dd');
    }

    public String getPCL(){
        return c.Product_Class__c;
    }

    public String getModel(){
        return c.Model__c;
    }

    public String getCaseBusinessUnit() {
        return c.Business_Unit__c;
    }

    public String getCaseBusinessUnitId() {
        return buId;
    }

    public List<SelectOption> getBusinessUnits() {
        List<SelectOption> lst = new List<SelectOption>();

        List<Service_Code__c> scs = [select Id, Name, Label__c from Service_Code__c where Type__c='Business Unit' and Active__c=true order by Label__c];
        for(Service_Code__c sc :scs)
            lst.add(new SelectOption(sc.Id, sc.Label__c));

        //lst.sort();
        return lst;
    }

    @RemoteAction
    public static List<String[]> getUnits(String buId) {
        List<String[]> lst = new List<String[]>();

        List<Service_Code__c> scs = [select Id, Name, Label__c from Service_Code__c where Type__c='Unit' and Active__c=true and Parent__c=:buId order by Label__c];
        for(Service_Code__c sc :scs)
            lst.add(new String[]{sc.Id, sc.Name, sc.Label__c});
            
        //lst.sort();
        return lst;
    }

    public List<SelectOption> getModes() {
        List<SelectOption> lst = new List<SelectOption>();

        List<Service_Code__c> scs = [select Id, Name, Label__c from Service_Code__c where Type__c='Mode' and Active__c=true order by Label__c];
        for(Service_Code__c sc :scs)
            lst.add(new SelectOption(sc.Id, sc.Label__c));
            
        //lst.sort();
        return lst;
    }

    @RemoteAction
    public static List<String[]> getTypes(String modeId, String unitId) {
        List<String[]> lst = new List<String[]>();

        List<Service_Code__c> scs = [select Id, Name, Label__c from Service_Code__c where Type__c='Type' and Active__c=true and Parent__c=:modeId and Unit_Code__c=:unitId order by Label__c];
        for(Service_Code__c sc :scs)
            lst.add(new String[]{sc.Id, sc.Name, sc.Label__c});
            
        //lst.sort();
        return lst;
    }

    @RemoteAction
    public static List<String[]> getMajors(String buId, String unitId) {
        List<String[]> lst = new List<String[]>();

        List<Service_Code__c> scs = [select Id, Name, Label__c from Service_Code__c where Type__c='Major' and Active__c=true and Parent__c=:buId and Unit_Code__c=:unitId order by Label__c];
        for(Service_Code__c sc :scs)
            lst.add(new String[]{sc.Id, sc.Name, sc.Label__c});
            
        //lst.sort();
        return lst;
    }

    @RemoteAction
    public static List<String[]> getSpecifics(String majorId, String unitId) {
        List<String[]> lst = new List<String[]>();

        List<Service_Code__c> scs = [select Id, Name, Label__c from Service_Code__c where Type__c='Specific' and Active__c=true and Parent__c=:majorId and Unit_Code__c=:unitId order by Name];
        for(Service_Code__c sc :scs)
            lst.add(new String[]{sc.Id, sc.Name, sc.Label__c});
            
        //lst.sort();
        return lst;
    }

    @RemoteAction
    public static List<String[]> getClassifications(String buId) {
        List<String[]> lst = new List<String[]>();

        List<Service_Code__c> scs = [select Id, Name, Label__c from Service_Code__c where Type__c='Warranty Class' and Active__c=true and Parent__c=:buId order by Label__c];
        for(Service_Code__c sc :scs)
            lst.add(new String[]{sc.Id, sc.Name, sc.Label__c});
           
        //lst.sort();
        return lst;
   }

    @RemoteAction
    public static List<String[]> getResponsibility(String buId) {
        List<String[]> lst = new List<String[]>();

        List<Service_Code__c> scs = [select Id, Name, Label__c from Service_Code__c where Type__c='Responsibility' and Active__c=true and Parent__c=:buId order by Name];
        for(Service_Code__c sc :scs)
            lst.add(new String[]{sc.Id, sc.Name, sc.Label__c});
           
        //lst.sort();
        return lst;
   }
}