src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Business_Unit_Picklist__c</fullName>
        <description>Captures Business Unit for Warranty approval drivers and processes. Leveraged for the Warranty Header (parent) case</description>
        <inlineHelpText>Value will drive PGM approvers and approval threshold limits.</inlineHelpText>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AAH</fullName>
                </value>
                <value>
                    <fullName>ATS</fullName>
                </value>
                <value>
                    <fullName>Chillers</fullName>
                </value>
                <value>
                    <fullName>Controls</fullName>
                </value>
                <value>
                    <fullName>VAV</fullName>
                </value>
                <value>
                    <fullName>MCP</fullName>
                </value>
                <value>
                    <fullName>Applied Air Handler</fullName>
                    <isActive>false</isActive>
                    <label>Applied Air Handler</label>
                </value>
                <value>
                    <fullName>Applied Terminal Systems</fullName>
                    <isActive>false</isActive>
                    <label>Applied Terminal Systems</label>
                </value>
                <value>
                    <fullName>Chiller</fullName>
                    <isActive>false</isActive>
                    <label>Chiller</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Category__c</fullName>
        <inlineHelpText>Please specify the category for this Case</inlineHelpText>
        <label>Case Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Accounts</fullName>
                </value>
                <value>
                    <fullName>Addresses</fullName>
                </value>
                <value>
                    <fullName>Approvals</fullName>
                </value>
                <value>
                    <fullName>Assets</fullName>
                </value>
                <value>
                    <fullName>Batch Jobs</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Campaigns</fullName>
                </value>
                <value>
                    <fullName>Cases</fullName>
                </value>
                <value>
                    <fullName>Change of Driver</fullName>
                </value>
                <value>
                    <fullName>Chatter</fullName>
                </value>
                <value>
                    <fullName>Claim</fullName>
                </value>
                <value>
                    <fullName>Contacts</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Credit Application</fullName>
                </value>
                <value>
                    <fullName>CRM</fullName>
                </value>
                <value>
                    <fullName>Dashboards</fullName>
                </value>
                <value>
                    <fullName>Documents</fullName>
                </value>
                <value>
                    <fullName>DST Assistance</fullName>
                </value>
                <value>
                    <fullName>Equipment Issue</fullName>
                </value>
                <value>
                    <fullName>Expedite</fullName>
                </value>
                <value>
                    <fullName>Extended</fullName>
                </value>
                <value>
                    <fullName>Fleet</fullName>
                </value>
                <value>
                    <fullName>Force.com Sites</fullName>
                </value>
                <value>
                    <fullName>FPA Special Request</fullName>
                </value>
                <value>
                    <fullName>General Questions</fullName>
                </value>
                <value>
                    <fullName>GEOTAB</fullName>
                </value>
                <value>
                    <fullName>Integration</fullName>
                </value>
                <value>
                    <fullName>Invoices</fullName>
                </value>
                <value>
                    <fullName>Known Issue (Fix on fail)</fullName>
                </value>
                <value>
                    <fullName>Leads</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_Received__c</fullName>
        <inlineHelpText>When was the Warranty Claim Authorization received?</inlineHelpText>
        <label>Date Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_Failure__c</fullName>
        <inlineHelpText>When did the Failure occur or was the issue discovered?</inlineHelpText>
        <label>Date of Failure</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reason_for_Authorization_Request__c</fullName>
        <inlineHelpText>Detailed Reason for Authorization Request</inlineHelpText>
        <label>Reason for Authorization Request</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Warranty</fullName>
        <active>true</active>
        <businessProcess>Warranty</businessProcess>
        <description>Used for Warranty case claims</description>
        <label>Warranty</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CustomCloneWarrantyClaimControllerTest.cls
@isTest
public class CustomCloneWarrantyClaimControllerTest {

    @testsetup
    public static void testsetup()
    {
        Id warrantyAuthClaimRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Warranty Claim Authorization').getRecordTypeId();
        AVA_SFCORE__TaxNowSetting__c ts1 = new AVA_SFCORE__TaxNowSetting__c(); 
        ts1.AVA_SFCORE__Active_Setting__c = true; 
        ts1.Name='Test Account';
        insert ts1;
        
        Account testAccount = APTPS_DaikinTestDataUtility.getAccount('accName');
        insert testAccount;
        Contact testContact = APTPS_DaikinTestDataUtility.getContact(testAccount);
        insert testContact; 
        
        Case c = new Case(
            AccountId = testAccount.Id,
            ContactId = testContact.Id,
            Subject = 'Test',
            Date_of_Failure__c = system.today(),
            Date_Received__c = system.today().addDays(10),
            Reason_for_Authorization_Request__c ='reason for authorization',
            Origin = 'Email',
            Priority ='Urgent',
            Case_Category__c = 'Claim',
            
            Business_Unit_Picklist__c ='AAH',
            //Status = UserInfo.getUserId(),
            RecordTypeId  = warrantyAuthClaimRecordType);    
        
        insert c;
        
    }
    
    @isTest
    public static void insertTest()
    {
        testsetup();
        List<Case> c = [select id,Subject,Status,Business_Unit_Picklist__c,RecordTypeId from Case where Case_Category__c='claim' limit 1];
        ApexPages.StandardController sc = new ApexPages.StandardController(c[0]);

		Test.startTest();
       		CustomCloneWarrantyClaimController customeCloneCase = new CustomCloneWarrantyClaimController(sc);
            customeCloneCase.saveCase();
            customeCloneCase.saveAndClose();
        customeCloneCase.saveAndNewCase();
        //customeCloneCase.cancel();
       	Test.stopTest();
    }
    
}