src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Date_Time_Re_Opened__c</fullName>
        <description>Date/Time that case was re-opened (status changed from Closed to Working)</description>
        <inlineHelpText>Date/Time that case was Re-opened (Status changed from Closed to Working)</inlineHelpText>
        <label>Date/Time Re-Opened</label>
        <type>DateTime</type>
    </fields>
    <recordTypes>
        <fullName>TRC</fullName>
        <active>true</active>
        <businessProcess>TRC - North America</businessProcess>
        <description>Default Record Type for TRC web cases when the TRC Group is unknown for the Product.</description>
        <label>TRC</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Snapshot__c.object
<CustomObject>
    <description>Populated by the Apex Class - TRC Dashboard Data
https://na28.salesforce.com/01pC0000000R5QD</description>
    <fields>
        <fullName>Closed_Cases__c</fullName>
        <label>Closed Cases</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Created_Cases__c</fullName>
        <label>Created Cases</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open_Cases__c</fullName>
        <label>Open Cases</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reopened_Cases__c</fullName>
        <inlineHelpText>Cases that are Re-Opened</inlineHelpText>
        <label>Reopened Cases</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SnapShot_Date__c</fullName>
        <label>SnapShot Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TRC_Group__c</fullName>
        <description>It is a Group on a case.</description>
        <label>Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TRC</fullName>
                </value>
                <value>
                    <fullName>TRC - AAH</fullName>
                </value>
                <value>
                    <fullName>TRC - Chillers</fullName>
                </value>
                <value>
                    <fullName>TRC - ATS</fullName>
                </value>
                <value>
                    <fullName>TRC - Controls</fullName>
                </value>
                <value>
                    <fullName>Rep Help Desk</fullName>
                </value>
                <value>
                    <fullName>Salesforce Help</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Case_Snapshots</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Snapshot</label>
    <nameField>
        <displayFormat>CS - {000000}</displayFormat>
        <label>Case Snapshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TRC_Dashboard_Data.cls
public class TRC_Dashboard_Data {
        
    //Data holding class
    class TRCDashboardData {
        public Integer openCaseCount = 0;
        public Integer createdCaseCount = 0;
        public Integer closedCaseCount = 0;
        public Integer reopenedCaseCount = 0;
    }
    
    public void getTRCResults() {
        map<string,TRCDashboardData> resultsMap = new map<string,TRCDashboardData>();
        List<Case_Snapshot__c> cs = new List<Case_Snapshot__c>();        
       
        for(AggregateResult openCases : [SELECT RecordType.Name Name,OwnerId Id, count(Id) Result, Status FROM Case WHERE Status != 'Closed' AND RecordType.Name IN('TRC', 'TRC - AAH', 'TRC - Chillers','TRC - ATS','TRC - Controls',  'Rep Help Desk', 'Salesforce Help', 'TRC - PQR') AND OwnerID NOT IN('00GC0000002VcJx', '00GC0000002VcK2', '00GC0000002VcK7', '00GC0000002VcKC', '00G1A000002bqRe', '00GC0000002YF2m')  group by RecordType.Name, OwnerId, Status]) {
            resultsMap.put(openCases.get('Name') + ',' + openCases.get('Id') , new TRCDashboardData());
            resultsMap.get(openCases.get('Name') + ',' + openCases.get('Id')).openCaseCount = (Integer)openCases.get('Result');
			System.debug(openCases);
        }        
		System.debug(resultsMap);

        //need to update query criteria
        for(AggregateResult createdCases : [SELECT RecordType.Name Name, OwnerId Id, count(Id) Result FROM Case WHERE RecordType.Name IN('TRC', 'TRC - AAH', 'TRC - Chillers','TRC - ATS','TRC - Controls', 'Rep Help Desk', 'Salesforce Help', 'TRC - PQR') AND OwnerID NOT IN('00GC0000002VcJx', '00GC0000002VcK2', '00GC0000002VcK7', '00GC0000002VcKC', '00G1A000002bqRe', '00GC0000002YF2m') AND CreatedDate = YESTERDAY group by RecordType.Name, OwnerId]) {
            if(resultsMap.get(createdCases.get('Name') + ',' + createdCases.get('Id')) == NULL) {
                resultsMap.put(createdCases.get('Name') + ',' + createdCases.get('Id'), new TRCDashboardData());
                resultsMap.get(createdCases.get('Name') + ',' + createdCases.get('Id')).createdCaseCount = (Integer)createdCases.get('Result');
                
            } 
			else resultsMap.get(createdCases.get('Name') + ',' + createdCases.get('Id')).createdCaseCount = (Integer)createdCases.get('Result');     

        }
        
        //need to update query criteria
        for(AggregateResult closedCases : [SELECT RecordType.Name Name,OwnerId Id, count(Id) Result FROM Case WHERE RecordType.Name IN('TRC', 'TRC - AAH', 'TRC - Chillers','TRC - ATS','TRC - Controls', 'Rep Help Desk', 'Salesforce Help', 'TRC - PQR') AND OwnerID NOT IN('00GC0000002VcJx', '00GC0000002VcK2', '00GC0000002VcK7', '00GC0000002VcKC', '00G1A000002bqRe', '00GC0000002YF2m') AND ClosedDate = YESTERDAY group by RecordType.Name, OwnerId]) {
            if(resultsMap.get(closedCases.get('Name') + ',' + closedCases.get('Id')) == NULL) {
                resultsMap.put(closedCases.get('Name') + ',' + closedCases.get('Id'), new TRCDashboardData());
                resultsMap.get(closedCases.get('Name') + ',' + closedCases.get('Id')).closedCaseCount = (Integer)closedCases.get('Result');
                
            }
			else resultsMap.get(closedCases.get('Name') + ',' + closedCases.get('Id')).closedCaseCount = (Integer)closedCases.get('Result');     

        }
                
        //need to update query criteria
        for(AggregateResult reopenedCases : [SELECT RecordType.Name Name, OwnerId Id, count(Id) Result FROM Case WHERE RecordType.Name IN('TRC', 'TRC - AAH', 'TRC - Chillers','TRC - ATS','TRC - Controls', 'Rep Help Desk', 'Salesforce Help', 'TRC - PQR') AND OwnerID NOT IN('00GC0000002VcJx', '00GC0000002VcK2', '00GC0000002VcK7', '00GC0000002VcKC', '00G1A000002bqRe', '00GC0000002YF2m') AND Date_Time_Re_Opened__c = YESTERDAY group by RecordType.Name, OwnerId]) {
			System.debug(reopenedCases);
            if(resultsMap.get(reopenedCases.get('Name') + ',' + reopenedCases.get('Id')) == NULL) 
			{
                resultsMap.put(reopenedCases.get('Name') + ',' + reopenedCases.get('Id'), new TRCDashboardData());
                resultsMap.get(reopenedCases.get('Name') + ',' + reopenedCases.get('Id')).reopenedCaseCount = (Integer)reopenedCases.get('Result');
                
            }
			else resultsMap.get(reopenedCases.get('Name') + ',' + reopenedCases.get('Id')).reopenedCaseCount = (Integer)reopenedCases.get('Result');
        }
		System.debug(resultsMap);
        
  
        for(String keys : resultsMap.keySet()) {
            String [] arry;
            Case_Snapshot__c c = new Case_Snapshot__c();
            c.SnapShot_Date__c = Date.Today() - 1;
            c.Open_Cases__c = resultsMap.get(keys).openCaseCount;
            c.Created_Cases__c = resultsMap.get(keys).createdCaseCount;
            c.Closed_Cases__c = resultsMap.get(keys).closedCaseCount;
            c.Reopened_Cases__c = resultsMap.get(keys).reopenedCaseCount;
            
            arry = keys.split(',');
            system.debug('Group key is:' + arry[0]);
            c.TRC_Group__c = arry[0];
            //c.TRC_Group__c = getTRCGroupNameFromRecordTypeId(arry[0]);
            
            system.debug('Userkey is:' + arry[1]);
            c.User__c = (Id)arry[1];
            
            cs.add(c);
            system.debug('create case snapshot');
        }
        
        
        if(cs.size()>0) {
            system.debug('insert case records:' +cs);
            insert cs;
		}
    }
    
    
    
    /*string getTRCGroupNameFromRecordTypeId(String recordTypeId){
        string result = '';
            
        if (recordTypeId == '012C0000000Hqlk'){
            result = 'TRC';
        } else if (recordTypeId == '012C0000000HoMR'){
            result = 'TRC - AAH';
        } else if (recordTypeId == '012C0000000HoMS'){
            result = 'TRC - ATS';
        } else if (recordTypeId == '012C0000000HoMT'){
            result = 'TRC - Chillers';
        } else {
            result = 'TRC - Controls';
        }
        
        return result;
    }*/
}