src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Category__c</fullName>
        <inlineHelpText>Please specify the category for this Case</inlineHelpText>
        <label>Case Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Accounts</fullName>
                </value>
                <value>
                    <fullName>Addresses</fullName>
                </value>
                <value>
                    <fullName>Approvals</fullName>
                </value>
                <value>
                    <fullName>Assets</fullName>
                </value>
                <value>
                    <fullName>Batch Jobs</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Campaigns</fullName>
                </value>
                <value>
                    <fullName>Cases</fullName>
                </value>
                <value>
                    <fullName>Change of Driver</fullName>
                </value>
                <value>
                    <fullName>Chatter</fullName>
                </value>
                <value>
                    <fullName>Claim</fullName>
                </value>
                <value>
                    <fullName>Contacts</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Credit Application</fullName>
                </value>
                <value>
                    <fullName>CRM</fullName>
                </value>
                <value>
                    <fullName>Dashboards</fullName>
                </value>
                <value>
                    <fullName>Documents</fullName>
                </value>
                <value>
                    <fullName>DST Assistance</fullName>
                </value>
                <value>
                    <fullName>Equipment Issue</fullName>
                </value>
                <value>
                    <fullName>Expedite</fullName>
                </value>
                <value>
                    <fullName>Extended</fullName>
                </value>
                <value>
                    <fullName>Fleet</fullName>
                </value>
                <value>
                    <fullName>Force.com Sites</fullName>
                </value>
                <value>
                    <fullName>FPA Special Request</fullName>
                </value>
                <value>
                    <fullName>General Questions</fullName>
                </value>
                <value>
                    <fullName>GEOTAB</fullName>
                </value>
                <value>
                    <fullName>Integration</fullName>
                </value>
                <value>
                    <fullName>Invoices</fullName>
                </value>
                <value>
                    <fullName>Known Issue (Fix on fail)</fullName>
                </value>
                <value>
                    <fullName>Leads</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>QA Program</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Plan</label>
        <referenceTo>Case_Plan__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Email_Templates__c</fullName>
        <inlineHelpText>The template used to send email to contacts. Please note that name entered in this field should exactly match the Email template</inlineHelpText>
        <label>Email Template</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <default>true</default>
                    <label>Completed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>QA Program</fullName>
                    <default>true</default>
                    <label>QA Program</label>
                </value>
                <value>
                    <fullName>Fix on Fail</fullName>
                </value>
                <value>
                    <fullName>Known Issue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Plan</label>
    <nameField>
        <label>Case Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Account Manager</fullName>
                </value>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>Architect</fullName>
                </value>
                <value>
                    <fullName>Buyer</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>DA Factory Service Tech</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Engineer</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>Independent Sales Rep</fullName>
                </value>
                <value>
                    <fullName>Main</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Project Manager</fullName>
                </value>
                <value>
                    <fullName>Service Tech</fullName>
                </value>
                <value>
                    <fullName>Team Member</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CaseplansSendEmialNotificationTest.cls
@isTest
public class CaseplansSendEmialNotificationTest {
    
    @future
    static void testSetUp(){    
        //Insert Email Template
        EmailTemplate validEmailTemplate = new EmailTemplate();
        validEmailTemplate.isActive = true;
        validEmailTemplate.Name = 'Test';
        validEmailTemplate.DeveloperName = 'AAH-Wty Auth for Serv Office';
        validEmailTemplate.TemplateType = 'text';
        validEmailTemplate.FolderId = UserInfo.getUserId();        
        insert validEmailTemplate;
    } 
    
    @testSetup
    static void testSetUp2()
    {
        Case_Plan__c cp =new Case_Plan__c();
        cp.name ='Test Case Plan';
        cp.Type__c='QA Program';
        cp.CurrencyIsoCode='USD';
        cp.Status__c='Completed';
        cp.Email_Templates__c='AAH-Wty Auth for Serv Office';
        insert cp;
        
        Case_Plan__c cp1=cp.clone();
        cp1.CurrencyIsoCode='CAD';
        cp1.Email_Templates__c='';
        insert cp1;
        
        AVA_SFCORE__TaxNowSetting__c ts1 = new AVA_SFCORE__TaxNowSetting__c(); 
        ts1.AVA_SFCORE__Active_Setting__c = true; 
        ts1.Name='Test Account';
        insert ts1;
        
        Account testAccount = APTPS_DaikinTestDataUtility.getAccount('accName');
        insert testAccount;
        
        Contact testContact = APTPS_DaikinTestDataUtility.getContact(testAccount);
        insert testContact;
        
        case c =new case();      
        c.AccountId = testAccount.Id;
        c.ContactId = testContact.id;
        c.Subject='Test';
        c.Origin='Mail';
        c.Priority='Low';
        c.Status='New';
        c.Case_Plan__c=cp.id;
        c.Case_Category__c='Claim';
        insert c;          
    }
    
    static testMethod void sendEmailNotification()
    {
        Test.startTest();     
        Case_Plan__c cp = [select id ,name from Case_Plan__c where CurrencyIsoCode='USD' limit 1]; 
        case c = [select id,Case_Plan__c,ContactId from case limit 1];
        EmailTemplate e =[select id ,DeveloperName from EmailTemplate limit 1];
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setTargetObjectId(c.ContactId);
        //mail.whatid(c.id);
        mail.setTemplateId(e.Id);
        
        // Test.StartTest(); 
        PageReference pageRef = Page.CaseplansSendEmialNotification; // Initiate VF Page Action
        pageRef.getParameters().put('id', cp.Id); //Pass the recordID
        Test.setCurrentPage(pageRef); 
        ApexPages.StandardController sd = new ApexPages.StandardController(cp);
        CaseplansSendEmialNotification cs =new CaseplansSendEmialNotification(sd);
        cs.emialAlert(); //Send emails
        cs.getEmailResult(); //Get email result
        cs.cancel(); //Get redirected to Case plan detail page
        //Test.stopTest();
        
        //To display alert when the Case Plan donot have EMail template
        Case_Plan__c cp1 = [select id ,name from Case_Plan__c where CurrencyIsoCode='CAD' limit 1]; 
        PageReference pageRef1 = Page.CaseplansSendEmialNotification; // Initiate VF Page Action
        pageRef1.getParameters().put('id', cp1.Id); //Pass the recordID
        Test.setCurrentPage(pageRef1); 
        ApexPages.StandardController sd1 = new ApexPages.StandardController(cp1);
        CaseplansSendEmialNotification cs1 =new CaseplansSendEmialNotification(sd1);
        
    }
}