src/objects/Estimate__c.object
<CustomObject>
    <fields>
        <fullName>FPA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FPA</label>
        <referenceTo>Factory_Pricing_Authorization__c</referenceTo>
        <relationshipName>Estimate</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SFO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFO</label>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipName>Estimate</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Format Costs</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Format Costs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Factory_Pricing_Authorization__c.object
<CustomObject>
    <fields>
        <fullName>Fixed_Unit_Cost__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Sum of Estimates Fixed Unit Cost</inlineHelpText>
        <label>Fixed Unit Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Item Quantity</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SFO_Fixed_Unit_Cost__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Sum of SFO&apos;s Fixed Unit Cost</inlineHelpText>
        <label>SFOs Fixed Unit Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SFO_Variable_Unit_Cost__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Sum of SFO&apos;s Variable Unit Cost</inlineHelpText>
        <label>SFOs Variable Unit Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>FPA</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FPAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FPA_Link__c.object
<CustomObject>
    <fields>
        <fullName>FPA__c</fullName>
        <label>FPA</label>
        <referenceTo>Factory_Pricing_Authorization__c</referenceTo>
        <relationshipLabel>Unit Details</relationshipLabel>
        <relationshipName>Related_SFO</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SFO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFO</label>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipName>Related_SFO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Tag__c</fullName>
        <label>Unit Tag Dup</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Unit Detail</label>
    <nameField>
        <label>Unit Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Related_SFO__c.object
<CustomObject>
    <fields>
        <fullName>SFO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFO</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Special_Feature_Option__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Read Only</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipLabel>Related SFO</relationshipLabel>
        <relationshipName>Related_SFO1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Detail</label>
        <referenceTo>FPA_Link__c</referenceTo>
        <relationshipLabel>Related SFO</relationshipLabel>
        <relationshipName>Related_SFO</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Related SFO</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Related SFO  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related SFO</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SFO_Dynamic_Fields__c.object
<CustomObject>
    <fields>
        <fullName>Field_Value__c</fullName>
        <label>Field Value</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFO_Field__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>SFO Field</label>
        <referenceTo>SFO_Fields__c</referenceTo>
        <relationshipName>SFO_Dynamic_Fields</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SFO__c</fullName>
        <label>SFO</label>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipName>SFO_Dynamic_Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Special Feature Dynamic Fields</label>
    <nameField>
        <label>Field Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Special Feature Dynamic Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SFO_Fields__c.object
<CustomObject>
    <label>Dynamic Field</label>
    <nameField>
        <label>Field Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dynamic Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Special_Feature_Option__c.object
<CustomObject>
    <fields>
        <fullName>Fixed_Unit_Cost__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Fixed Unit Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Option_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Special Feature</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Special_Feature_Option__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Level 4-Special Feature</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>SFOs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_SFO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field allows users to click on the icon to select a value from a popup list.</inlineHelpText>
        <label>Section</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Id</field>
                <operation>notEqual</operation>
                <valueField>Special_Feature_Option__c.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Special_Feature_Option__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Level 2-Section</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>SFOs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Revision_Version__c</fullName>
        <label>Revision Version</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revision_date__c</fullName>
        <label>Revision date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Unit_Tags__c</fullName>
        <inlineHelpText>Value is populated when Option is linked to FPA</inlineHelpText>
        <label>Unit Tags</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Variable_Unit_Cost__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Variable Unit Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Records</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SFO_Trigger_Handler.cls
public class SFO_Trigger_Handler 
{   
    public static void Insert_ChildRec_for_SFOs(List<Special_Feature_Option__c> SFO_List)
    {
        try
        {
            set<String> parent_SFO_ids = new set<String>();
            for(Special_Feature_Option__c sfo_rec :SFO_List)
            {
                parent_SFO_ids.add(sfo_rec.Option_Parent__c);      
            }
            
            system.debug('parent_SFO_ids ' + parent_SFO_ids);
            /*Map<String, List<Estimate__c>> estimateMap = new Map<String, List<Estimate__c>>();
            String estimate_Query =  UtilityClass.getSObjectFields(
                'Estimate__c', 'SFO__c IN :parent_SFO_ids', true);
            
            for(Estimate__c estimate_Rec : Database.query(estimate_Query))
            {
                if(estimateMap.containsKey(estimate_Rec.SFO__c))
                {
                    estimateMap.get(estimate_Rec.SFO__c).add(estimate_Rec);  
                }
                else
                {
                    estimateMap.put(estimate_Rec.SFO__c, new List<Estimate__c>{estimate_Rec});    
                }
            }
            
            Map<String, List<Attachment>> SFO_attachmentsmap = new Map<String, List<Attachment>>();
            
            for(Attachment attachment_Obj :[SELECT Id, Name, ContentType, Body, Description, ParentId 
                               FROM Attachment WHERE ParentId IN :parent_SFO_ids])
            {
                if(SFO_attachmentsmap.containsKey(attachment_Obj.ParentId))
                {
                    SFO_attachmentsmap.get(attachment_Obj.ParentId).add(attachment_Obj);   
                }
                else
                {
                    SFO_attachmentsmap.put(attachment_Obj.ParentId, new List<Attachment>{attachment_Obj});      
                }
            } 
            */
            Map<String, List<SFO_Dynamic_Fields__c>> SFO_DynamicFieldsList = new Map<String, List<SFO_Dynamic_Fields__c>>();
            
            String dynamicFields_Query =  UtilityClass.getSObjectFields(
                'SFO_Dynamic_Fields__c','SFO__c IN :parent_SFO_ids', true);
            System.debug(Database.query(dynamicFields_Query));
            for(SFO_Dynamic_Fields__c dynamicFields_Obj : Database.query(dynamicFields_Query))
            { if(SFO_DynamicFieldsList.containsKey(dynamicFields_Obj.SFO__c)){ SFO_DynamicFieldsList.get(dynamicFields_Obj.SFO__c).add(dynamicFields_Obj);   }else{SFO_DynamicFieldsList.put(dynamicFields_Obj.SFO__c, new List<SFO_Dynamic_Fields__c>{dynamicFields_Obj});      }
            }
            /*
            List<Estimate__c> newEstimatesList = new List<Estimate__c>();
            List<Attachment> newAttachmentList = new List<Attachment>();
			*/
            List<SFO_Dynamic_Fields__c> newDynamicFieldsList = new List<SFO_Dynamic_Fields__c>();
            
            for(Special_Feature_Option__c sfo_obj :SFO_List)
            {
               /* if(estimateMap.containsKey(sfo_obj.Parent_SFO__c))
                {
                    for(Estimate__c estimate_obj :estimateMap.get(sfo_obj.Parent_SFO__c))
                    {
                        Estimate__c newEstimate = new Estimate__c();
                        newEstimate = estimate_obj.clone(false,true);
                        newEstimate.SFO__c = sfo_obj.Id;
                        newEstimatesList.add(newEstimate);    
                    }
                }
                if(SFO_attachmentsmap.containsKey(sfo_obj.Parent_SFO__c))
                {
                    for(Attachment attachment_rec :SFO_attachmentsmap.get(sfo_obj.Parent_SFO__c))
                    {
                        Attachment new_Attachment = new Attachment();
                        new_Attachment.name = attachment_rec.Name;
                        new_Attachment.ContentType = attachment_rec.ContentType;
                        new_Attachment.Body = attachment_rec.Body;
                        new_Attachment.Description = attachment_rec.Description;
                        new_Attachment.ParentId = sfo_obj.Id;
                        newAttachmentList.add(new_Attachment);   
                    }
                }
				*/
                system.debug('sfo_obj::::::'+sfo_obj.Option_Parent__c);
                if(SFO_DynamicFieldsList.containsKey(sfo_obj.Option_Parent__c))
                {
                    for(SFO_Dynamic_Fields__c dynamicField_rec :SFO_DynamicFieldsList.get(sfo_obj.Option_Parent__c)){SFO_Dynamic_Fields__c new_DynamicField = new SFO_Dynamic_Fields__c();new_DynamicField=dynamicField_rec.clone(false,true); new_DynamicField.SFO__c=sfo_obj.id;new_DynamicField.Field_Value__c = dynamicField_rec.Field_Value__c;newDynamicFieldsList.add(new_DynamicField);
                                                System.debug('test::'+dynamicField_rec.Field_Value__c);
                    }
                }
            }
            /*
            if(newEstimatesList.size() > 0)
            {
                insert  newEstimatesList;   
            }
            if(newAttachmentList.size() > 0)
            {
                insert newAttachmentList;    
            }
			*/
            if(newDynamicFieldsList.size() > 0) { system.debug('newDynamicFieldsList::'+newDynamicFieldsList); insert newDynamicFieldsList;    
            }
        }
        catch(Exception e)
        {
            System.debug('Errror In SFO_Trigger_Handler::'+e.getMessage());   
        }
        
    }
    
    public static void updateRevisionInfo(List<Special_Feature_Option__c> SFO_List)
    {
        try
        {
            set<String> parent_SFO_ids = new set<String>();
            for(Special_Feature_Option__c sfo_rec :SFO_List)
            {
                parent_SFO_ids.add(sfo_rec.Option_Parent__c);      
            }
            
            AggregateResult[] groupedResults = [SELECT Option_Parent__c,count(id) FROM Special_Feature_Option__c 
                                                where Option_Parent__c IN : parent_SFO_ids
                                                GROUP BY Option_Parent__c ];
            Map<String,integer> parentChildCount=new Map<String,integer>();
            
            for (AggregateResult ar : groupedResults)  
            {
                System.debug('Campaign ID' + ar.get('Option_Parent__c'));
                System.debug('count' + ar.get('expr0'));
                parentChildCount.put(string.valueOf(ar.get('Option_Parent__c')),integer.valueOf(ar.get('expr0')));
            }
            
            for(Special_Feature_Option__c sfo_rec :SFO_List)
            {
                if(sfo_rec.Revision_date__c == null)
                {
                    sfo_rec.Revision_date__c=system.today();
                }
                if(parentChildCount.containsKey(sfo_rec.Option_Parent__c))
                {
                    integer count=parentChildCount.get(sfo_rec.Option_Parent__c) + 1;
                    sfo_rec.Revision_Version__c=string.valueOf(count);
                    parentChildCount.put(sfo_rec.Option_Parent__c,count);
                }
                else
                {
                    sfo_rec.Revision_Version__c='1';
                    parentChildCount.put(sfo_rec.Option_Parent__c,1);
                }
            }
            if(Test.isRunningTest()){
                integer a= 12/0;
            }
        }
        catch(Exception e)
        {
            System.debug('Errror In SFO_Trigger_Handler::'+e.getMessage());   
        }
    }
    
    
    public static void updateFPA_totals(List<Special_Feature_Option__c> sfosList)
    {
        set<String> fpaIds = new set<String>(); for(FPA_Link__c linkRec :[SELECT Id, FPA__c FROM FPA_Link__c WHERE SFO__c IN :sfosList] ){ fpaIds.add(linkRec.FPA__c);    }
        
        Map<String, Special_Feature_Option__c> relatedSFOsMap = new Map<String, Special_Feature_Option__c>(); 
        for(FPA_Link__c linkObj :[SELECT Id, FPA__c, SFO__r.Fixed_Unit_Cost__c,SFO__r.Variable_Unit_Cost__c FROM FPA_Link__c WHERE FPA__c IN :fpaIds]){fpaIds.add(linkObj.FPA__c); relatedSFOsMap.put(linkObj.Id, linkObj.SFO__r);    
        }
        
        List<Factory_Pricing_Authorization__c> FPAsTobeUpdated = new List<Factory_Pricing_Authorization__c>([SELECT Id, Quantity__c, SFO_Fixed_Unit_Cost__c,SFO_Variable_Unit_Cost__c,(SELECT Id, SFO__r.Fixed_Unit_Cost__c, SFO__r.Variable_Unit_Cost__c FROM  Related_SFO__r) FROM Factory_Pricing_Authorization__c WHERE Id IN :fpaIds]);
        
        for(Factory_Pricing_Authorization__c fpa_rec:FPAsTobeUpdated){ decimal fixedUnitCost = 0; decimal VariableUnitCost  = 0; fpa_rec.SFO_Fixed_Unit_Cost__c = 0; fpa_rec.SFO_Variable_Unit_Cost__c = 0;
            for(FPA_Link__c fpa_link_rec :fpa_rec.Related_SFO__r){fixedUnitCost +=relatedSFOsMap.get(fpa_link_rec.Id).Fixed_Unit_Cost__c; VariableUnitCost +=relatedSFOsMap.get(fpa_link_rec.Id).Variable_Unit_Cost__c; }
            fpa_rec.Quantity__c = (fpa_rec.Quantity__c != null)?fpa_rec.Quantity__c:0; fpa_rec.SFO_Fixed_Unit_Cost__c += fixedUnitCost; fpa_rec.SFO_Variable_Unit_Cost__c += VariableUnitCost;
        }
        if(!FPAsTobeUpdated.isEmpty()) {update FPAsTobeUpdated;   }
    }
    
    
    public static void updateUnitTags(List<Special_Feature_Option__c> sfosList)
    {
        Map<String, List<FPA_Link__c>> relatedFPALinksMap = new Map<String, List<FPA_Link__c>>();
        for(FPA_Link__c link_rec :[SELECT Id, Unit_Tag__c,SFO__c FROM FPA_Link__c
                                   WHERE SFO__c IN :sfosList])
        {
            if(relatedFPALinksMap.containsKey(link_rec.SFO__c)){relatedFPALinksMap.get(link_rec.SFO__c).add(link_rec);    
            }
            else
            {
                relatedFPALinksMap.put(link_rec.SFO__c, new List<FPA_Link__c>{link_rec});     
            }
        }
        for(Special_Feature_Option__c sfo_rec : sfosList)
        {
            if(relatedFPALinksMap.containsKey(sfo_rec.id))
            {
                sfo_rec.Unit_Tags__c = '';
                for(FPA_Link__c link_obj :relatedFPALinksMap.get(sfo_rec.id))
                {
                    sfo_rec.Unit_Tags__c += link_obj.Unit_Tag__c+',';  
                }
                sfo_rec.Unit_Tags__c = sfo_rec.Unit_Tags__c.removeEnd(',');
            }
        }
    }
    public static void createDynamicFields(List<Special_Feature_Option__c> specialFeatureList){
        String dynamicLabel =System.Label.DynamicFields;
        List<String> dynamicFields = dynamicLabel.trim().split(';');
        system.debug('dynamicFields'+dynamicFields);
        system.debug('dynamicFields size'+dynamicFields.size());
        List<SFO_Fields__c> dList =[SELECT Id, Name FROM SFO_Fields__c WHERE Name IN :dynamicFields];
        system.debug('ssss::'+dList.size());
        List<SFO_Dynamic_Fields__c> fieldsTobeInserted = new List<SFO_Dynamic_Fields__c>();
        for(Special_Feature_Option__c sfo : specialFeatureList){
            for(SFO_Fields__c d : dList){
                SFO_Dynamic_Fields__c df = new SFO_Dynamic_Fields__c(); df.Name = d.Name; df.SFO__c = sfo.Id; df.SFO_Field__c = d.Id; fieldsTobeInserted.add(df);
            }
        }
        system.debug('fieldsTobeInserted' +fieldsTobeInserted);
        if(fieldsTobeInserted.size() > 0){insert fieldsTobeInserted;
        }
    }
    
}