src/objects/Estimate__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Cost__c</fullName>
        <label>Actual Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Est_Hours__c</fullName>
        <label>Est. Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hour__c</fullName>
        <label>$/Hour</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FPA Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Estimate</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SFO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFO</label>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipName>Estimate</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Cost__c</fullName>
        <label>Unit Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Format Costs</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Format Costs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Product Brand Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Only Active Formats is available for FPA and SFO Selection</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PCL__c</fullName>
        <inlineHelpText>Please contact saleforcehelp@daikinapplied.com  to add PCL Numbers</inlineHelpText>
        <label>PCL Number(s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0001</fullName>
                </value>
                <value>
                    <fullName>0002</fullName>
                </value>
                <value>
                    <fullName>0003</fullName>
                </value>
                <value>
                    <fullName>0004</fullName>
                </value>
                <value>
                    <fullName>0005</fullName>
                </value>
                <value>
                    <fullName>0006</fullName>
                </value>
                <value>
                    <fullName>0007</fullName>
                </value>
                <value>
                    <fullName>0008</fullName>
                </value>
                <value>
                    <fullName>0009</fullName>
                </value>
                <value>
                    <fullName>0010</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Format</label>
    <nameField>
        <label>Format Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SFO_Dynamic_Fields__c.object
<CustomObject>
    <fields>
        <fullName>Field_Value__c</fullName>
        <label>Field Value</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picklist_Entries__c</fullName>
        <label>Picklist Entries</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SFO_Field__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>SFO Field</label>
        <referenceTo>SFO_Fields__c</referenceTo>
        <relationshipName>SFO_Dynamic_Fields</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SFO__c</fullName>
        <label>SFO</label>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipName>SFO_Dynamic_Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Special Feature Dynamic Fields</label>
    <nameField>
        <label>Field Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Special Feature Dynamic Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SFO_Fields__c.object
<CustomObject>
    <fields>
        <fullName>Field_Data_Type__c</fullName>
        <label>Field Data Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>Formula</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                    <isActive>false</isActive>
                    <label>Checkbox</label>
                </value>
                <value>
                    <fullName>Date</fullName>
                    <isActive>false</isActive>
                    <label>Date</label>
                </value>
                <value>
                    <fullName>Date/Time</fullName>
                    <isActive>false</isActive>
                    <label>Date/Time</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field_Length__c</fullName>
        <inlineHelpText>Enter the maximum length for a text field</inlineHelpText>
        <label>Field Length</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Formula_Editor__c</fullName>
        <inlineHelpText>Shows the formula that is defined by the user while creating a dynamic field. Accepts simple formula i.e. single parentheses and Order of calculation followed is BOD MAS</inlineHelpText>
        <label>Formula Editor</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Only Active Dynamic fields will be available for selection at Special Feature level (Level 4)</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Picklist_Entries__c</fullName>
        <inlineHelpText>Allow users to select a value from a predefined list</inlineHelpText>
        <label>Picklist Entries</label>
        <type>TextArea</type>
    </fields>
    <label>Dynamic Field</label>
    <nameField>
        <label>Field Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dynamic Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Special_Feature_Option__c.object
<CustomObject>
    <fields>
        <fullName>Base_Unit_to_be_Modified__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Select formats by search/lookup as defined in the Format creation screen</inlineHelpText>
        <label>Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Records</relationshipLabel>
        <relationshipName>SFOs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_SFO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field allows users to click on the icon to select a value from a popup list.</inlineHelpText>
        <label>Section</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Id</field>
                <operation>notEqual</operation>
                <valueField>Special_Feature_Option__c.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Special_Feature_Option__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Level 2-Section</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>SFOs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Special_Feature_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Component</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Special_Feature_Option__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Level 3-Component</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipLabel>Special Features</relationshipLabel>
        <relationshipName>SFOs2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <formula>Fixed_Unit_Cost__c  +  Variable_Unit_Cost__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Records</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Records</pluralLabel>
    <recordTypes>
        <fullName>Component</fullName>
        <active>true</active>
        <description>Holds Component Records</description>
        <label>Level 3-Component</label>
    </recordTypes>
    <recordTypes>
        <fullName>Section</fullName>
        <active>true</active>
        <description>Holds Section Records</description>
        <label>Level 2-Section</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SFODynamicFields_Test.cls
@isTest
public class SFODynamicFields_Test {
    @TestSetup
    public static void setup()
    { 
        
        Product2 Product2Obj=TestUtility.createProduct();
        insert product2Obj;
        
        // Product__c productObj=[Select id from Product__c limit 1];
        Product__c productObj= new Product__c();
        productObj.Name = '997';
        productObj.IsActive__c=true;
        productObj.Description__c ='Vision/Skyline';
        productObj.PCL__c='0002';
        insert productObj;
        
        //get record type of Special_Feature_Option__c
        Id RecordTypeIdSFO = Schema.SObjectType.Special_Feature_Option__c.getRecordTypeInfosByName().get('Level 2-Section').getRecordTypeId();    
        //Create SFO record
        Special_Feature_Option__c SFO_Obj1 = TestUtility.createSFO(productObj.id);
        SFO_Obj1.Name__c = 'test';
        SFO_Obj1.RecordTypeId = RecordTypeIdSFO;
        SFO_Obj1.Base_Unit_to_be_Modified__c =productObj.id;
        insert SFO_Obj1;
        
        //get record type of Component
        Id RecordTypeIdSFO1 = Schema.SObjectType.Special_Feature_Option__c.getRecordTypeInfosByName().get('Level 3-Component').getRecordTypeId();    
        
        //Create SFO(Section) record
        Special_Feature_Option__c SFO_Obj2 = TestUtility.createSFO(productObj.id);
        SFO_Obj2.Name__c = 'test';
        SFO_Obj2.RecordTypeId = RecordTypeIdSFO1;
        SFO_Obj2.Parent_SFO__c = SFO_Obj1.id;
        insert SFO_Obj2;
        
        //get record type of Special Feature
        Id RecordTypeIdSFO2 = Schema.SObjectType.Special_Feature_Option__c.getRecordTypeInfosByName().get('Level 4-Special Feature').getRecordTypeId();    
        
        //Create SFO(Special feature) record
        Special_Feature_Option__c SFO_Obj3 = TestUtility.createSFO(productObj.id);
        SFO_Obj3.Name__c ='Sample Special feature';
        SFO_Obj3.RecordTypeId = RecordTypeIdSFO2;
        SFO_Obj3.Special_Feature_Parent__c = SFO_Obj2.id;
        insert SFO_Obj3;
        
        System.assertEquals(SFO_Obj3.Base_Unit_to_be_Modified__c, productObj.id);
        
        Estimate__c est = new Estimate__c();
        est.Name = 'Test Estimate';
        est.Est_Hours__c = 5.00;
        est.Hour__c = 12;
        est.Total_Cost__c = 300;
        est.Unit_Cost__c = 40;
        est.Actual_Cost__c = 300;
        est.SFO__c = SFO_Obj3.id;
        insert est;
        
        System.assertEquals(est.SFO__c, SFO_Obj3.id);
        
        list<SFO_Fields__c> SFOFieldsList = new list<SFO_Fields__c>();
        
        SFO_Fields__c sfo_Fields =  TestUtility.createSFOFields('Manufacturing Communication','Number');
        //sfo_Fields.Picklist_Entries__c = 'four five six one two three'; 
        sfo_Fields.IsActive__c =true;  
        sfo_Fields.Field_Data_Type__c ='Number';
        sfo_Fields.Field_Length__c = 10000;
        SFOFieldsList.add(sfo_Fields);
        
        SFO_Fields__c sfo_Fields2 =  TestUtility.createSFOFields('Drafting Cost','Text');
        //sfo_Fields.Picklist_Entries__c = 'four five six one two three'; 
        sfo_Fields2.IsActive__c =true;  
        sfo_Fields2.Field_Length__c = 5000;
        SFOFieldsList.add(sfo_Fields2);
        
        SFO_Fields__c sfo_Fields3 =  TestUtility.createSFOFields('Drafting Cost','Formula');
        sfo_Fields3.IsActive__c =true; 
        sfo_Fields3.Formula_Editor__c = 'MFG*Manufacturing Hours';
        sfo_Fields3.Field_Length__c = 5000;
        SFOFieldsList.add(sfo_Fields3);
        
        insert SFOFieldsList;
        
        list<SFO_Dynamic_Fields__c> SFODynamicFieldsList = new list<SFO_Dynamic_Fields__c>();
        
        SFO_Dynamic_Fields__c SFODynamicFields = TestUtility.createSFODynamicFields(sfo_Fields.id, SFO_Obj3.id);
        SFODynamicFieldsList.add(SFODynamicFields);
        
        SFO_Dynamic_Fields__c SFODynamicFields2 = TestUtility.createSFODynamicFields(sfo_Fields2.id, SFO_Obj3.id);
        SFODynamicFields2.Field_Value__c ='20000';
        SFODynamicFieldsList.add(SFODynamicFields2);
        
        insert SFODynamicFieldsList;
    }
    @isTest
    public static void sfo_FieldsMethodTest()
    {
        Special_Feature_Option__c sfObject = [select id,Name__c from Special_Feature_Option__c where Name__c ='Sample Special feature' limit 1 ];
        List<SFO_Fields__c> sf = [select id,Picklist_Entries__c,Field_Data_Type__c,Name from SFO_Fields__c];
        test.startTest();
        ApexPages.StandardController controller = new ApexPages.StandardController(sfObject);
        SFODynamicFields dynamicsfo = new SFODynamicFields(controller);
        dynamicsfo.getDynamicFields();
        dynamicsfo.saveSFODynamicFields();
        //List<SelectOption> selOpts=dynamicsfo.getdynamiclistEntries();
        test.stopTest();
        //SFODynamicFields.dynamicWrapper dynamincWrap = new SFODynamicFields.dynamicWrapper(sf);
        // dynamincWrap.dynamicWrapper(sf);
        //dynamincWrap.getdynamiclistEntries();
    }
    
        @isTest
    public static void sfo_FieldsMethodTest2()
    {
        Special_Feature_Option__c sfObject = [select id,Name__c from Special_Feature_Option__c where Name__c ='Sample Special feature' limit 1 ];
        List<SFO_Fields__c> sf = [select id,Picklist_Entries__c,Field_Data_Type__c,Formula_Editor__c,Name from SFO_Fields__c];

    //Created SFO Formula Field
        SFO_Fields__c sfoFields = new SFO_Fields__c();
        sfoFields.Name='Test Field';
        sfoFields.Field_Data_Type__c='Formula';
        sfoFields.Formula_Editor__c='c=1+2';
        sfoFields.IsActive__c=true;
        insert sfoFields;
        
        // Creating Dynamic Field
         SFO_Dynamic_Fields__c SFODynamicFields = TestUtility.createSFODynamicFields(sfoFields.id, sfObject.id);
        SFODynamicFields.Name='Test Dynamic Field';
        SFODynamicFields.Field_Value__c='10';
        SFODynamicFields.SFO__c=sfObject.id;
        SFODynamicFields.SFO_Field__c=sfoFields.id;
        insert SFODynamicFields;
        
        test.startTest();
        ApexPages.StandardController controller = new ApexPages.StandardController(sfObject);
        SFODynamicFields dynamicsfo = new SFODynamicFields(controller);
        dynamicsfo.getDynamicFields();
        dynamicsfo.saveSFODynamicFields();
        //List<SelectOption> selOpts=dynamicsfo.getdynamiclistEntries();
        test.stopTest();
        //SFODynamicFields.dynamicWrapper dynamincWrap = new SFODynamicFields.dynamicWrapper(sf);
        // dynamincWrap.dynamicWrapper(sf);
        //dynamincWrap.getdynamiclistEntries();
    }
    
}