src/objects/Estimate__c.object
<CustomObject>
    <fields>
        <fullName>Estimate_Lable__c</fullName>
        <label>Estimate Label</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AGENCY</fullName>
                </value>
                <value>
                    <fullName>DRAFTING</fullName>
                </value>
                <value>
                    <fullName>ENGINEERING</fullName>
                </value>
                <value>
                    <fullName>LAB TEST</fullName>
                </value>
                <value>
                    <fullName>MFG</fullName>
                </value>
                <value>
                    <fullName>MODEL SHOP</fullName>
                </value>
                <value>
                    <fullName>OTHER</fullName>
                </value>
                <value>
                    <fullName>SET UP</fullName>
                </value>
                <value>
                    <fullName>TOOLING;FIXTURES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hour__c</fullName>
        <label>$/Hour</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FPA Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Estimate</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hours</fullName>
                </value>
                <value>
                    <fullName>Dollars</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Format Costs</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Format Costs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Only Active Formats is available for FPA and SFO Selection</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Format</label>
    <nameField>
        <label>Format Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductEstimatesTest.cls
@istest
public class ProductEstimatesTest 
{
	@isTest static void ProductEstimatesTestMethod() 
    {
        Product2 Product2Obj=TestUtility.createProduct();
        insert product2Obj;
        
        Product__c productObj=TestUtility.createProductFormat();
       // productObj.IsActive__c=true;
        insert productObj;
        
        pageReference pageRef=new pageReference('/apex/ProductEstimatesPage?id='+productObj.Id);
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(productObj);
        ProductEstimates ProductEstimatesObj = new ProductEstimates(sc);
        
        ProductEstimatesObj.addRow();
        ProductEstimatesObj.delRow();
        
        Map<Integer,Estimate__c> estWraper=ProductEstimatesObj.estimateMap;
        for(Estimate__c wrap: estWraper.values())
        {
            wrap.Estimate_Lable__c='AGENCY';
            wrap.Type__c='Hours';
            wrap.Hour__c=12;
            break;
        }
        ProductEstimatesObj.submitEstimates();
        
        ProductEstimatesObj = new ProductEstimates(sc);
    }
}