src/objects/Estimate__c.object
<CustomObject>
    <fields>
        <fullName>Estimate_Lable__c</fullName>
        <label>Estimate Label</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AGENCY</fullName>
                </value>
                <value>
                    <fullName>DRAFTING</fullName>
                </value>
                <value>
                    <fullName>ENGINEERING</fullName>
                </value>
                <value>
                    <fullName>LAB TEST</fullName>
                </value>
                <value>
                    <fullName>MFG</fullName>
                </value>
                <value>
                    <fullName>MODEL SHOP</fullName>
                </value>
                <value>
                    <fullName>OTHER</fullName>
                </value>
                <value>
                    <fullName>SET UP</fullName>
                </value>
                <value>
                    <fullName>TOOLING;FIXTURES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hour__c</fullName>
        <label>$/Hour</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FPA Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Estimate</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SFO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFO</label>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipName>Estimate</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Format Costs</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Format Costs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <label>Format</label>
    <nameField>
        <label>Format Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SFO_Dynamic_Fields__c.object
<CustomObject>
    <fields>
        <fullName>Field_Value__c</fullName>
        <label>Field Value</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picklist_Entries__c</fullName>
        <label>Picklist Entries</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SFO_Field__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>SFO Field</label>
        <referenceTo>SFO_Fields__c</referenceTo>
        <relationshipName>SFO_Dynamic_Fields</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SFO__c</fullName>
        <label>SFO</label>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipName>SFO_Dynamic_Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Special Feature Dynamic Fields</label>
    <nameField>
        <label>Field Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Special Feature Dynamic Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SFO_Fields__c.object
<CustomObject>
    <fields>
        <fullName>Field_Data_Type__c</fullName>
        <label>Field Data Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>Formula</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                    <isActive>false</isActive>
                    <label>Checkbox</label>
                </value>
                <value>
                    <fullName>Date</fullName>
                    <isActive>false</isActive>
                    <label>Date</label>
                </value>
                <value>
                    <fullName>Date/Time</fullName>
                    <isActive>false</isActive>
                    <label>Date/Time</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field_Length__c</fullName>
        <inlineHelpText>Enter the maximum length for a text field</inlineHelpText>
        <label>Field Length</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Formula_Editor__c</fullName>
        <inlineHelpText>Shows the formula that is defined by the user while creating a dynamic field. Accepts simple formula i.e. single parentheses and Order of calculation followed is BOD MAS</inlineHelpText>
        <label>Formula Editor</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Picklist_Entries__c</fullName>
        <inlineHelpText>Allow users to select a value from a predefined list</inlineHelpText>
        <label>Picklist Entries</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Always require a value in this field in order to save a record</inlineHelpText>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <label>Dynamic Field</label>
    <nameField>
        <label>Field Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dynamic Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Special_Feature_Option__c.object
<CustomObject>
    <fields>
        <fullName>Base_Unit_to_be_Modified__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Select formats by search/lookup as defined in the Format creation screen</inlineHelpText>
        <label>Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Records</relationshipLabel>
        <relationshipName>SFOs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Records</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Records</pluralLabel>
    <recordTypes>
        <fullName>Format</fullName>
        <active>false</active>
        <description>Holds Format Records</description>
        <label>Level 1-Format</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SFODynamicFields.cls
public class SFODynamicFields 
{
    public Special_Feature_Option__c sfo_Obj{get;set;}
    public List<dynamicWrapper> dynamicWrapperList{get;set;}
    public List<dynamicWrapper> dynamicWrapperList2{get;set;}
    private List<SFO_Dynamic_Fields__c> sfo_dynamic_fields_list = new List<SFO_Dynamic_Fields__c>();
    
    public SFODynamicFields(ApexPages.StandardController controller)
    {
        sfo_Obj = (Special_Feature_Option__c)controller.getRecord();
        if(sfo_Obj.Id != NULL)
        {
            string SFOId=sfo_Obj.Id;
            sfo_Obj = Database.query(UtilityClass.getSObjectFields('Special_Feature_Option__c', 'id=:SFOId', true)); 
            sfo_dynamic_fields_list = Database.query(UtilityClass.getSObjectRelatedFields('SFO_Dynamic_Fields__c',
                             'SFO_Field__r.Field_Data_Type__c,SFO_Field__r.Field_Length__c, SFO_Field__r.Formula_Editor__c,'+
                             'SFO_Field__r.Required__c, SFO_Field__r.Name',
                             'SFO__c = :SFOId',  true)); 
                
        }
        system.debug('sfo_dynamic_fields_list'+sfo_dynamic_fields_list);
        getDynamicFields();
    }
    
    public pagereference saveSFODynamicFields()
    {
        List<SFO_Dynamic_Fields__c> sfo_dynamic_list = new List<SFO_Dynamic_Fields__c>();
        Map<String, String> keyValueMap = new Map<String, String>();
        
        List<dynamicWrapper> cumulativeWrapperList = new List<dynamicWrapper>();
        cumulativeWrapperList.addAll(dynamicWrapperList);
        cumulativeWrapperList.addAll(dynamicWrapperList2);
        System.debug('cumulativeWrapperList::'+cumulativeWrapperList);
        List<Estimate__c> estimateList = new List<Estimate__c>();
        String format = sfo_Obj.Base_Unit_to_be_Modified__c;
        System.debug('format::'+format);
        estimateList = Database.query(UtilityClass.getSObjectFields('Estimate__c', 'Product__c =:format', true));
        for(Estimate__c e :estimateList){
            String key = e.Estimate_Lable__c.toLowerCase(); keyValueMap.put(key, String.valueOf(e.Hour__c));    
            
        } 
        for(dynamicWrapper wrap : cumulativeWrapperList)
        {
            SFO_Dynamic_Fields__c  SFO_Dynamic_Fields_Rec = wrap.sfo_dynamic_field_obj;
            System.debug('sfo_Obj.id '+sfo_Obj.id);
           	sfo_dynamic_list.add(SFO_Dynamic_Fields_Rec); 
            String key = SFO_Dynamic_Fields_Rec.Name.toLowerCase();
            
            if((SFO_Dynamic_Fields_Rec.Field_Value__c == null || SFO_Dynamic_Fields_Rec.Field_Value__c == '')
               && (wrap.sfo_dynamic_field_obj.SFO_Field__r.Field_Data_Type__c == 'Number'))
            {
                SFO_Dynamic_Fields_Rec.Field_Value__c = '0';        
            }
            
            keyValueMap.put(key, SFO_Dynamic_Fields_Rec.Field_Value__c);    
        }
        
        
        for(dynamicWrapper wrapVal : cumulativeWrapperList)
        {
            SFO_Dynamic_Fields__c  SFO_Dynamic_Fields_Rec = wrapVal.sfo_dynamic_field_obj;
            Integer dynamic_field_length = 0;
            System.debug(SFO_Dynamic_Fields_Rec.Name+'::Field Length::'+SFO_Dynamic_Fields_Rec.Field_Value__c);
            if(SFO_Dynamic_Fields_Rec.Field_Value__c != null && SFO_Dynamic_Fields_Rec.Field_Value__c== ''){dynamic_field_length =  SFO_Dynamic_Fields_Rec.Field_Value__c.length();  
            }
            Integer sfo_field_Length = Integer.valueOf(wrapVal.sfo_dynamic_field_obj.SFO_Field__r.Field_Length__c);
            
            if(dynamic_field_length > sfo_field_Length)
            {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, wrapVal.sfo_dynamic_field_obj.SFO_Field__r.Name +' length is exceeded')); return null;
            }
            System.debug('wrapVal.sfo_dynamic_field_obj.SFO_Field__r.Field_data_Type__c ::'+wrapVal.sfo_dynamic_field_obj.SFO_Field__r.Field_data_Type__c);
            if(wrapVal.sfo_dynamic_field_obj.SFO_Field__r.Field_data_Type__c == 'Formula')
            {
                String formula = wrapVal.sfo_dynamic_field_obj.SFO_Field__r.Formula_Editor__c;
                SFO_Dynamic_Fields_Rec.Field_Value__c = 
                    Evaluate_Expression.evaluateExpression(formula, keyValueMap);
                
            }
        }
        if(sfo_dynamic_list.size() > 0)
        {
            upsert sfo_dynamic_list;
            
        }
        
        return new pagereference('/'+sfo_Obj.Id);
    }
    
    public void getDynamicFields()
    {
       
        dynamicWrapperList = new List<dynamicWrapper>();
        dynamicWrapperList2 = new List<dynamicWrapper>();
        
        integer i=0;
        for(SFO_Dynamic_Fields__c sfo_Dynamic_fields_rec :sfo_dynamic_fields_list)
        {
            if(math.mod(i,2) == 0)
            {
                dynamicWrapperList.add(new dynamicWrapper(sfo_Dynamic_fields_rec)); 
            }
            else
            {
                dynamicWrapperList2.add(new dynamicWrapper(sfo_Dynamic_fields_rec));
            }
            if(sfo_Dynamic_fields_rec.SFO_Field__r.Field_Data_Type__c != 'Formula')
            {
               i++; 
            }
        }
        
        System.debug('dynamicWrapperList::'+dynamicWrapperList);
        
        Map<String, SFO_Dynamic_Fields__c> sfo_dynamic_fields_map = new 
            Map<String, SFO_Dynamic_Fields__c>();
        
        if(sfo_Obj.Id != null)
        {
            System.debug('sfo_Obj.Id:: '+sfo_Obj.Id);
            
            for(SFO_Dynamic_Fields__c dynamicField :sfo_dynamic_fields_list)
            {
                sfo_dynamic_fields_map.put(dynamicField.SFO_Field__c, dynamicField);    
            }
        }
        
        for(dynamicWrapper wrap : dynamicWrapperList)
        {
            if(sfo_dynamic_fields_map.containsKey(wrap.sfo_dynamic_field_obj.SFO_Field__c))
            {
                wrap.sfo_dynamic_field_obj =  sfo_dynamic_fields_map.get(wrap.sfo_dynamic_field_obj.SFO_Field__c);
                wrap.fieldValue = sfo_dynamic_fields_map.get(wrap.sfo_dynamic_field_obj.SFO_Field__c).Field_Value__c;
            }
        }
        for(dynamicWrapper wrap : dynamicWrapperList2)
        {
            if(sfo_dynamic_fields_map.containsKey(wrap.sfo_dynamic_field_obj.SFO_Field__c))
            {
                wrap.sfo_dynamic_field_obj =  sfo_dynamic_fields_map.get(wrap.sfo_dynamic_field_obj.SFO_Field__c);
                wrap.fieldValue = sfo_dynamic_fields_map.get(wrap.sfo_dynamic_field_obj.SFO_Field__c).Field_Value__c;
            }
        }
    }
    
    public class dynamicWrapper
    {
        public SFO_Dynamic_Fields__c sfo_dynamic_field_obj{get;set;} 
        public List<String> sfo_pick_list_entries{get;set;}
        public String fieldValue{get;set;}
        public dynamicWrapper(SFO_Dynamic_Fields__c sfo_dynamic_field_rec)
        {
            sfo_pick_list_entries = new List<String>();
            if(sfo_dynamic_field_rec.Picklist_Entries__c != null && sfo_dynamic_field_rec.Picklist_Entries__c != '')
            {
                sfo_pick_list_entries = sfo_dynamic_field_rec.Picklist_Entries__c.split('\n');
                
            }
            sfo_dynamic_field_obj = sfo_dynamic_field_rec;
            
        }
        public List<SelectOption> getdynamiclistEntries() 
        {
            List<SelectOption> options = new List<SelectOption>(); options.add(new SelectOption('','--None--'));
            for(String entry :sfo_pick_list_entries) {entry = entry.trim(); options.add(new SelectOption(entry,entry)); 
            }
            return options;
        }
    }
}