src/objects/Factory_Pricing_Authorization__c.object
<CustomObject>
    <label>FPA</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FPAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FPA_Persona__c.object
<CustomObject>
    <fields>
        <fullName>User_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <inlineHelpText>Uniquely identifies each user</inlineHelpText>
        <label>User Id</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Sales Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Persona</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Only Active Formats is available for FPA and SFO Selection</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Format</label>
    <nameField>
        <label>Format Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FPA_Email_Template_Test.cls
@isTest
public class FPA_Email_Template_Test {
    
    
    @testSetup static void setup() {
        Product2 Product2Obj=TestUtility.createProduct();
        insert product2Obj;
        
        Product__c ProductObj=TestUtility.createProductFormat();
        ProductObj.IsActive__c=false;
        insert productObj;
        
        ProductObj.IsActive__c=true;
        update productObj;
        
        FPA_Persona__c FPAPersonRepObj=TestUtility.createFPAPersona('Rep',null);
        FPAPersonRepObj.User_Id__c='test 1234';
        insert FPAPersonRepObj;
        
    }
    @isTest
    public static void fpa_EmailApproverMethod()
    {
        Factory_Pricing_Authorization__c FPAObj=TestUtility.createFPA([Select Id from FPA_Persona__c limit 1].Id,[Select Id from Product__c limit 1].Id);
        insert FPAObj;
        
        FPA_Email_Template_Controller fpa_EmailTempCon = new FPA_Email_Template_Controller();
        fpa_EmailTempCon.getFPA_Id();
        fpa_EmailTempCon.setFPA_Id(FPAObj.id);
        fpa_EmailTempCon.FPA_Email_Template_Controller();
    }
}