src/objects/Factory_Pricing_Authorization__c.object
<CustomObject>
    <fields>
        <fullName>Base_Unit_to_be_Modified__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>FPAs</relationshipLabel>
        <relationshipName>FPAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FPA_Number__c</fullName>
        <label>FPA Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Non Bid Process</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <isActive>false</isActive>
                    <label>Pending</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FPA</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FPAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FPA_Approvers__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FPA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FPA</label>
        <referenceTo>Factory_Pricing_Authorization__c</referenceTo>
        <relationshipName>FPA_Approvers2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FPA Approvers</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FPA Approvers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FPA_Persona__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>User_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <inlineHelpText>Uniquely identifies each user</inlineHelpText>
        <label>User Id</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Sales Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Persona</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <label>Format</label>
    <nameField>
        <label>Format Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Special_Feature_Option__c.object
<CustomObject>
    <fields>
        <fullName>Base_Unit_to_be_Modified__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Select formats by search/lookup as defined in the Format creation screen</inlineHelpText>
        <label>Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Records</relationshipLabel>
        <relationshipName>SFOs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                    <isActive>false</isActive>
                    <label>Obsolete</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                    <isActive>false</isActive>
                    <label>Submitted for Approval</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Records</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CreateTaskEmailTest.cls
@istest
public class CreateTaskEmailTest 
{
    @isTest
    static void createTaskEmailTestmethod()
    {
        // create a new email and envelope object
        Messaging.InboundEmail email = new Messaging.InboundEmail() ;
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
        
        Product2 Product2Obj=TestUtility.createProduct();
        insert product2Obj;
        
        Product__c productObj=TestUtility.createProductFormat();
        insert productObj;
        
        Special_Feature_Option__c SFOObj=TestUtility.createSFO(productObj.Id);
        
        insert SFOObj;
        
        FPA_Persona__c FPAPersonObj=TestUtility.createFPAPersona('Engineer','Product');
        FPAPersonObj.User_Id__c='test 12323';
        insert FPAPersonObj;
        
        Factory_Pricing_Authorization__c fpaObj = TestUtility.createFPA(FPAPersonObj.id, productObj.id);
        //fpaObj.Base_Unit_to_be_Modified__c = null;
        fpaObj.FPA_Number__c = 'ABCD1234';
        insert fpaObj;
        Factory_Pricing_Authorization__c fpaObj1 = TestUtility.createFPA(FPAPersonObj.id, productObj.id);
        //fpaObj.Base_Unit_to_be_Modified__c = null;
        fpaObj1.FPA_Number__c = 'ABCD1234';
        
        //Creating Approvers for FPA
        FPA_Approvers__c FpaApprover1 = new FPA_Approvers__c();
        FpaApprover1.FPA__c=fpaObj.id;
        FpaApprover1.Status__c='Sent';
        FpaApprover1.Email__c='Daikin@test.com';
        insert FpaApprover1;
        
        SFOObj=[Select id,name from Special_Feature_Option__c limit 1];
        
        // setup the data for the email
        email.subject = 'SFO Approval request for'+fpaObj.FPA_Number__c;
        email.fromAddress = 'Daikin@test.com';
        email.plainTextBody = 'email body\n2225256325\nTitle\n APPROVED';
        
        
        // call the email service class and test it with the data in the testMethod
        CreateTaskEmail  testInbound=new CreateTaskEmail ();
        testInbound.handleInboundEmail(email, env);
    }
    @isTest static void createTaskEmailTestmethod2()
    {
        // create a new email and envelope object
        Messaging.InboundEmail email = new Messaging.InboundEmail() ;
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
        
        Product2 Product2Obj=TestUtility.createProduct();
        insert product2Obj;
        
        Product__c productObj=TestUtility.createProductFormat();
        insert productObj;
        
        Special_Feature_Option__c SFOObj=TestUtility.createSFO(productObj.Id);
        
        insert SFOObj;
        
        FPA_Persona__c FPAPersonObj=TestUtility.createFPAPersona('Engineer','Product');
        FPAPersonObj.User_Id__c='test 12323';
        insert FPAPersonObj;
        
        Factory_Pricing_Authorization__c fpaObj = TestUtility.createFPA(FPAPersonObj.id, productObj.id);
        //fpaObj.Base_Unit_to_be_Modified__c = null;
        fpaObj.FPA_Number__c = 'AGFD1234';
        
        //Creating Approvers for FPA
        FPA_Approvers__c FpaApprover1 = new FPA_Approvers__c();
        FpaApprover1.FPA__c=fpaObj.id;
        FpaApprover1.Status__c='Sent';
        FpaApprover1.Email__c='Daikin@test.com';
        insert FpaApprover1;
        
        SFOObj=[Select id,name from Special_Feature_Option__c limit 1];
        
        // setup the data for the email
        email.subject = 'SFO Approval request for'+fpaObj.FPA_Number__c;
        email.fromAddress = 'Daikin@test.com';
        email.plainTextBody =  'email body\n2225256325\nTitle\n Dear';
        
        
        // call the email service class and test it with the data in the testMethod
        CreateTaskEmail  testInbound=new CreateTaskEmail ();
        testInbound.handleInboundEmail(email, env);
    }
        @isTest static void createTaskEmailTestmethod3()
    {
        // create a new email and envelope object
        Messaging.InboundEmail email = new Messaging.InboundEmail() ;
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
        
        Product2 Product2Obj=TestUtility.createProduct();
        insert product2Obj;
        
        Product__c productObj=TestUtility.createProductFormat();
        insert productObj;
        
        Special_Feature_Option__c SFOObj=TestUtility.createSFO(productObj.Id);
        
        insert SFOObj;
        
        FPA_Persona__c FPAPersonObj=TestUtility.createFPAPersona('Engineer','Product');
        FPAPersonObj.User_Id__c='test 12323';
        insert FPAPersonObj;
        
        Factory_Pricing_Authorization__c fpaObj = TestUtility.createFPA(FPAPersonObj.id, productObj.id);
        //fpaObj.Base_Unit_to_be_Modified__c = null;
        fpaObj.FPA_Number__c = 'AGFD1234';
        
        //Creating Approvers for FPA
        FPA_Approvers__c FpaApprover1 = new FPA_Approvers__c();
        FpaApprover1.FPA__c=fpaObj.id;
        FpaApprover1.Status__c='Sent';
        FpaApprover1.Email__c='Daikin@test.com';
        insert FpaApprover1;
        
        SFOObj=[Select id,name from Special_Feature_Option__c limit 1];
        
        // setup the data for the email
        email.subject = 'SFO Approval request for'+fpaObj.FPA_Number__c;
        email.fromAddress = 'Daikin@test.com';
        email.plainTextBody =  'email body\n2225256325\nTitle\n REJECTED';
        
        
        // call the email service class and test it with the data in the testMethod
        CreateTaskEmail  testInbound=new CreateTaskEmail ();
        testInbound.handleInboundEmail(email, env);
    }
}