src/objects/Factory_Pricing_Authorization__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Level__c</fullName>
        <label>Approval Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Base_Unit_to_be_Modified__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>FPAs</relationshipLabel>
        <relationshipName>FPAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Eng_Mfg_Effort__c</fullName>
        <label>Eng/Mfg Effort</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                    <default>true</default>
                    <label>Low</label>
                </value>
                <value>
                    <fullName>Very Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_FPA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent FPA</label>
        <referenceTo>Factory_Pricing_Authorization__c</referenceTo>
        <relationshipLabel>Related Versions</relationshipLabel>
        <relationshipName>FPAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Item Quantity</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <label>Revenue</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low to High</fullName>
                    <default>true</default>
                    <label>Low to High</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Risk__c</fullName>
        <label>Risk</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                    <default>true</default>
                    <label>Low</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>FPA</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FPAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FPA_Link__c.object
<CustomObject>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Unit Detail</label>
    <nameField>
        <label>Unit Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FPA_Persona__c.object
<CustomObject>
    <fields>
        <fullName>User_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <inlineHelpText>Uniquely identifies each user</inlineHelpText>
        <label>User Id</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Sales Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Persona</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Only Active Formats is available for FPA and SFO Selection</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Format</label>
    <nameField>
        <label>Format Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FPA_CreationControllerTest.cls
@isTest
public class FPA_CreationControllerTest {
    
    @testSetup static void setup() {
        Product2 Product2Obj=TestUtility.createProduct();
        insert product2Obj;
        
       /* Product__c productObj=[Select id from Product__c limit 1];
        productObj.IsActive__c=true;
        //productObj.Revenue__c = 'High';
        update productObj;*/
        
        Product__c productObj=TestUtility.createProductFormat();
        productObj.IsActive__c=false;
        insert productObj;
        productObj.IsActive__c=true;
        update productObj;
        
        FPA_Persona__c FPAPersonRepObj=TestUtility.createFPAPersona('Rep',null);
        FPAPersonRepObj.User_Id__c='test 1234';
        insert FPAPersonRepObj;
        
    }
    
    @isTest static void FPACreationTestMethod() 
    {
        
        Factory_Pricing_Authorization__c FPAObj=TestUtility.createFPA([Select Id from FPA_Persona__c limit 1].Id,[Select Id from Product__c limit 1].Id);        
        FPAObj.Risk__c = 'High';
        //FPAObj.CapX__c = 'Likely';
        FPAObj.Eng_Mfg_Effort__c = 'High';
       // FPAObj.Previous_FPA__c = 'No';
        FPAObj.Approval_Level__c='A';
        pageReference pageRef=new pageReference('/apex/FPA_Creation?&pageType=Creation&retUrl=/apex/FPASearchPage');
        Test.setCurrentPage(pageRef);
        
        //Below lines to cover New FPA Creation
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(FPAObj);
        FPA_CreationController fpaCreation = new FPA_CreationController(sc);
        fpaCreation.FPAObj = FPAObj;
        fpaCreation.saveFPA();
        fpaCreation.backtofpasearch();  
        Test.stopTest();
        
        System.assertEquals(FPAObj.Approval_Level__c, 'A');
        System.assertEquals(fpaCreation.vfTitle, 'FPA Creation Page');
    }
    
    @isTest static void FPACloneTestMethod() 
    {
        
         Factory_Pricing_Authorization__c FPAObj=TestUtility.createFPA([Select Id from FPA_Persona__c limit 1].Id,[Select Id from Product__c limit 1].Id);
        insert FPAObj;
        
        pageReference pageRef=new pageReference('/apex/FPA_Creation?&pageType=Creation&retUrl=/apex/FPASearchPage');
        Test.setCurrentPage(pageRef);
        
        //Below lines to cover Clone FPA
        Test.startTest();
        FPAObj = Database.query(UtilityClass.getSObjectFields('Factory_Pricing_Authorization__c', 'Id !=Null limit 1', true));
        pageRef=new pageReference('/apex/FPA_Creation?id='+FPAObj.Id+'&pageType=Clone&retUrl=/apex/FPASearchPage');
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(FPAObj);
        FPA_CreationController fpaCreation = new FPA_CreationController(sc);
        fpaCreation.saveFPA();
        fpaCreation.backtofpasearch();
        Test.stopTest();
        
        System.assertEquals(fpaCreation.vfTitle, 'FPA Clone Page');
    }
    // For FPA_Version_Controller  Class 
    @isTest static void FPAVersionTestMethod() 
    {
         Factory_Pricing_Authorization__c FPAObj=TestUtility.createFPA([Select Id from FPA_Persona__c limit 1].Id,[Select Id from Product__c limit 1].Id);
        FPAObj.Version__c = '';
        //FPAObj.Parent_FPA__c=FPAObjParent.id;
        insert FPAObj;
        
        //Creating FPA Link For FPA Object
        FPA_Link__c fpaLink = TestUtility.CreatesfpaLink(FPAObj.Id);
        insert fpaLink;
         // Creating Attachments for FPA Parent
        String data = 'test data for attacement';
        List<Attachment> ListAttachments = new List<Attachment>();
        for(Integer i=0; i<5; i++){
            Attachment att = new Attachment();
            att.Name = 'Test Name'+i;
            att.Body = EncodingUtil.base64Decode(data);
            att.ParentId = FPAObj.id;
            ListAttachments.add(att);
        } 
        insert ListAttachments;
        
        // Creating ContentDocumentLink
        
        ContentVersion contentVersion = new ContentVersion(
            Title = 'Penguins',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        insert contentVersion;    
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        
        //create ContentDocumentLink  record for the FPA 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = FPAObj.id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        insert cdl; 
        
        pageReference pageRef=new pageReference('/apex/FPA_Creation?&pageType=Creation');
        Test.setCurrentPage(pageRef);
        
        //Below lines to cover Version FPA
        Test.startTest();
        FPAObj = Database.query(UtilityClass.getSObjectFields('Factory_Pricing_Authorization__c', 'Id !=Null limit 1', true));
        pageRef=new pageReference('/apex/FPA_Creation?id='+FPAObj.Id+'&pageType=Version');
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(FPAObj);
        FPA_CreationController fpaCreation = new FPA_CreationController(sc);
        fpaCreation.saveFPA(); 
        Test.stopTest();
        
        System.assertEquals(fpaCreation.vfTitle, 'FPA Versioning Page');
    }
    
    @isTest static void FPAExceptionTestMethod1() 
    {
         Factory_Pricing_Authorization__c FPAObj=TestUtility.createFPA([Select Id from FPA_Persona__c limit 1].Id,[Select Id from Product__c limit 1].Id);
        FPAObj.Base_Unit_to_be_Modified__c=Null;
        
        pageReference pageRef=new pageReference('/apex/FPA_Creation');
        Test.setCurrentPage(pageRef);
        
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(FPAObj);
        FPA_CreationController fpaCreation = new FPA_CreationController(sc);
        fpaCreation.FPAObj = FPAObj;
        fpaCreation.saveFPA();
        Test.stopTest();
    }
    
     @isTest static void FPAExceptionTestMethod2() 
    {
         Factory_Pricing_Authorization__c FPAObj=TestUtility.createFPA([Select Id from FPA_Persona__c limit 1].Id,[Select Id from Product__c limit 1].Id);
        FPAObj.Quantity__c=0;
        
        pageReference pageRef=new pageReference('/apex/FPA_Creation');
        Test.setCurrentPage(pageRef);
        
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(FPAObj);
        FPA_CreationController fpaCreation = new FPA_CreationController(sc);
        fpaCreation.FPAObj = FPAObj;
        fpaCreation.fpaQuantityString='5';
        fpaCreation.addRow();
        fpaCreation.saveFPA();  
        fpaCreation.generateUnitDetails();
        fpaCreation.delRow();
        Test.stopTest();
    }
    
    // For FPA_Version_Controller class
         @isTest static void FPAExceptionTestMethod3() 
    {
         Factory_Pricing_Authorization__c FPAObjParent=TestUtility.createFPA([Select Id from FPA_Persona__c limit 1].Id,[Select Id from Product__c limit 1].Id);
        FPAObjParent.Quantity__c=0;
        id FPA_Id = FPAObjParent.id;
       
        pageReference pageRef=new pageReference('/apex/FPA_Creation?Id='+FPA_Id+'&version=1&retUrl=/'+FPA_Id);
        Test.setCurrentPage(pageRef);
        Test.startTest();
        FPA_Version_Controller fpaCreation = new FPA_Version_Controller();
        FPA_Version_Controller.redirectToFPACreation();
        Test.stopTest();
    }
}