src/objects/Factory_Pricing_Authorization__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Non Bid Process</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <isActive>false</isActive>
                    <label>Pending</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FPA</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FPAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FPA_Approvers__c.object
<CustomObject>
    <fields>
        <fullName>FPA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FPA</label>
        <referenceTo>Factory_Pricing_Authorization__c</referenceTo>
        <relationshipName>FPA_Approvers2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FPA Approvers</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FPA Approvers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FPA_Persona__c.object
<CustomObject>
    <fields>
        <fullName>User_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <inlineHelpText>Uniquely identifies each user</inlineHelpText>
        <label>User Id</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Sales Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Persona</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Only Active Formats is available for FPA and SFO Selection</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Format</label>
    <nameField>
        <label>Format Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FPA_ApprovalHelperTest.cls
@isTest
public class FPA_ApprovalHelperTest {
    
    public static testmethod void  FPAApprovalHelper(){
        
        Map<String, FPA_Approvers__c> approvals = new Map<String, FPA_Approvers__c>();
        List<FPA_Approvers__c> approverList = new List<FPA_Approvers__c>();
        List<FPA_Approvers__c> updatedapproverList = new List<FPA_Approvers__c>();
        
        Product__c ProductObj=TestUtility.createProductFormat();
        ProductObj.IsActive__c=true;
        insert productObj;
        
        FPA_Persona__c FPAPersonRepObj=TestUtility.createFPAPersona('Rep',null);
        FPAPersonRepObj.User_Id__c='test 1234';
        insert FPAPersonRepObj;
        
        UtilityClass.getSObjectRelatedFields('FPA_Approvers__c','FPA_Person__r.Name','',true);
        Factory_Pricing_Authorization__c FPAObj=TestUtility.createFPA(FPAPersonRepObj.Id,ProductObj.Id);
        insert FPAobj;
        
        FPA_Approvers__c FpaApprover1 = new FPA_Approvers__c();
        FpaApprover1.FPA__c=FPAObj.id;
        FpaApprover1.Status__c='Approved';
        approverList.add(FpaApprover1);
        
        FPA_Approvers__c FpaApprover2 = new FPA_Approvers__c();
        FpaApprover2.FPA__c=FPAObj.id;
        FpaApprover2.Status__c='Rejected';
        approverList.add(FpaApprover2);
        

        FPA_Approvers__c FpaApprover3 = new FPA_Approvers__c();
        FpaApprover3.FPA__c=FPAObj.id;
        FpaApprover3.Status__c='Rejected';
        approverList.add(FpaApprover3);

        FPA_Approvers__c FpaApprover4 = new FPA_Approvers__c();
        FpaApprover3.FPA__c=FPAObj.id;
        FpaApprover3.Status__c='Approved';
        approverList.add(FpaApprover4);
    
        insert approverList; 
        
        for(FPA_Approvers__c a: approverList){
            if(a.Status__c == 'Approved'){
                a.Status__c='Rejected';
            }
            else{
                a.Status__c='Approved';
            }
            updatedapproverList.add(a);
        }
        update updatedapproverList;
        
        for(FPA_Approvers__c aa: updatedapproverList){
            approvals.put(aa.Id,aa);
        }
        
        System.assertEquals('Approved', updatedapproverList[3].Status__c);
         System.assertEquals('Rejected', updatedapproverList[2].Status__c);

    }
}