src/objects/Factory_Pricing_Authorization__c.object
<CustomObject>
    <fields>
        <fullName>Base_Unit_to_be_Modified__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>FPAs</relationshipLabel>
        <relationshipName>FPAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FPA_Number__c</fullName>
        <label>FPA Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Non Bid Process</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <isActive>false</isActive>
                    <label>Pending</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FPA</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FPAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FPA_Approvers__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FPA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FPA</label>
        <referenceTo>Factory_Pricing_Authorization__c</referenceTo>
        <relationshipName>FPA_Approvers2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FPA Approvers</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FPA Approvers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreateTaskEmail.cls
global class CreateTaskEmail implements Messaging.InboundEmailHandler 
{
    
    global Messaging.InboundEmailResult  handleInboundEmail(Messaging.inboundEmail email, 
                                                            Messaging.InboundEnvelope env)
    {
        System.debug('inside method');
        // Create an InboundEmailResult object for returning the result of the 
        // Apex Email Service
        Messaging.InboundEmailResult result = new Messaging.InboundEmailResult();
       
        
        String myPlainText= ''; 
        
        // Store the email plain text into the local variable 
        myPlainText = email.plainTextBody;
            System.debug('myPlainText'+myPlainText);
        String subject = email.subject;
            System.debug('subject'+subject);
        String fromAddress = email.fromAddress;
            System.debug('fromAddress'+fromAddress);
        String FPA_number = subject.substringAfter('for').trim();
            System.debug('FPA_number@@@'+FPA_number);
        boolean Approvalstatus;
      //  boolean Approvalstatus = false;
        if(!myPlainText.startsWith('Dear'))
        {
            if(myPlainText.contains('Dear'))
                myPlainText=myPlainText.split('Dear')[0];            
            system.debug('myPlainText ' + myPlainText);
            
            if(myPlainText.containsIgnoreCase('APPROVED') || myPlainText.containsIgnoreCase('APPROVE'))
            {
                Approvalstatus = True;    
            }
            else if(myPlainText.containsIgnoreCase('REJECTED') || myPlainText.containsIgnoreCase('REJECT'))
            { 
                Approvalstatus = False;     
            }
        }
        list<Factory_Pricing_Authorization__c> fpaList = new list<Factory_Pricing_Authorization__c>(
            [select id,FPA_Number__c,Base_Unit_to_be_Modified__c from Factory_Pricing_Authorization__c where FPA_Number__c =: FPA_number]);
        Factory_Pricing_Authorization__c fpa = new Factory_Pricing_Authorization__c();
        system.debug('fpa'+fpaList); 
        if(fpaList.size()>0){
            fpa =  fpaList[0];                 
        }  
        
        list<FPA_Approvers__c> apprList = new list<FPA_Approvers__c>(
            [select id,Email__c,Status__c from FPA_Approvers__c where Email__c =: fromAddress AND  FPA__c =:fpa.id AND Status__c ='Sent']);
        FPA_Approvers__c appr = new FPA_Approvers__c();
        system.debug('appr'+apprList); 
        if(apprList.size()>0){
            appr =  apprList[0];   
            if(Approvalstatus == null){
             	return null;   
            }
			appr.Status__c = (Approvalstatus)?'Approved':'Rejected';
            update appr;
        }
            system.debug(appr);

        return result;
    }
}