src/objects/Factory_Pricing_Authorization__c.object
<CustomObject>
    <fields>
        <fullName>Application_Engineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Engineer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>FPAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Base_Unit_to_be_Modified__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>FPAs</relationshipLabel>
        <relationshipName>FPAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Non Bid Process</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <isActive>false</isActive>
                    <label>Pending</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FPA</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FPAs</pluralLabel>
    <recordTypes>
        <fullName>Read_only</fullName>
        <active>true</active>
        <label>Read only</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FPA_Approval__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SFO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFO</label>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipLabel>Approvers</relationshipLabel>
        <relationshipName>FPA_Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approver</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FPA_Link__c.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <formula>SFO__r.Notes__c</formula>
        <label>Notes</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFO</label>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipName>Related_SFO</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Unit Detail</label>
    <nameField>
        <label>Unit Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FPA_Persona__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>User_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <inlineHelpText>Uniquely identifies each user</inlineHelpText>
        <label>User Id</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Sales Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Persona</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Only Active Formats is available for FPA and SFO Selection</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Format</label>
    <nameField>
        <label>Format Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Related_SFO__c.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SFO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFO</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Special_Feature_Option__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Read Only</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipLabel>Related SFO</relationshipLabel>
        <relationshipName>Related_SFO1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Detail</label>
        <referenceTo>FPA_Link__c</referenceTo>
        <relationshipLabel>Related SFO</relationshipLabel>
        <relationshipName>Related_SFO</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Related SFO</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Related SFO  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related SFO</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Special_Feature_Option__c.object
<CustomObject>
    <fields>
        <fullName>Base_Unit_to_be_Modified__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Select formats by search/lookup as defined in the Format creation screen</inlineHelpText>
        <label>Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Records</relationshipLabel>
        <relationshipName>SFOs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Option_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Special Feature</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Special_Feature_Option__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Level 4-Special Feature</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>SFOs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_SFO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field allows users to click on the icon to select a value from a popup list.</inlineHelpText>
        <label>Section</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Id</field>
                <operation>notEqual</operation>
                <valueField>Special_Feature_Option__c.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Special_Feature_Option__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Level 2-Section</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>SFOs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Special_Feature_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Component</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Special_Feature_Option__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Level 3-Component</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipLabel>Special Features</relationshipLabel>
        <relationshipName>SFOs2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                    <isActive>false</isActive>
                    <label>Obsolete</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                    <isActive>false</isActive>
                    <label>Submitted for Approval</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Records</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Records</pluralLabel>
    <recordTypes>
        <fullName>Component</fullName>
        <active>true</active>
        <description>Holds Component Records</description>
        <label>Level 3-Component</label>
    </recordTypes>
    <recordTypes>
        <fullName>Format</fullName>
        <active>false</active>
        <description>Holds Format Records</description>
        <label>Level 1-Format</label>
    </recordTypes>
    <recordTypes>
        <fullName>Option</fullName>
        <active>true</active>
        <description>Holds Options Records</description>
        <label>Level 5-Option</label>
    </recordTypes>
    <recordTypes>
        <fullName>Read_Only</fullName>
        <active>true</active>
        <description>Holds Locked Records</description>
        <label>Read Only</label>
    </recordTypes>
    <recordTypes>
        <fullName>Section</fullName>
        <active>true</active>
        <description>Holds Section Records</description>
        <label>Level 2-Section</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>User_ID__c</fullName>
        <formula>Id = $User.Id</formula>
        <label>User ID</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SFOSearchControllerTest.cls
@isTest
public class SFOSearchControllerTest {
    @testSetup
    public Static void Setup(){
        // Setup test data
        // This code runs as the system user
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = [Select Id, Name, Email from User where Id =: userInfo.getUserId()];
        
        // Creating the Product 
        Product2 Product2Obj=TestUtility.createProduct();
        insert product2Obj;
        
        // Creating the Format i.e parent for the SFO Record Type Section
        Product__c productObj = TestUtility.createProductFormat();
        productObj.IsActive__c=true;
        insert productObj;
        
        //Creating User 
        // Creating the SalesPerson for FPA
        FPA_Persona__c FPAPersonRepObj=TestUtility.createFPAPersona('Engineer','Operations');
        FPAPersonRepObj.User_Id__c='DKN1113';
        FPAPersonRepObj.Email__c='deepika.a@solunuscorp.com';
        insert FPAPersonRepObj;
        
        //Creating FPA with parameters salesperson and projectid
        Factory_Pricing_Authorization__c FPAObj=TestUtility.createFPA(FPAPersonRepObj.Id,productObj.Id);
        FPAObj.Name = 'Test FPA';
        FPAObj.Application_Engineer__c = u.id;
        FPAObj.Status__c='Approved';
        insert FPAObj;
        
        //Creating Unitdetails for FPA object i.e FPA Link
        
        FPA_Link__c fpaLink = TestUtility.CreatesfpaLink(FPAObj.Id);
        insert fpaLink;   
        
        //get record type of Special_Feature_Option__c
        Id RecordTypeIdSFO = Schema.SObjectType.Special_Feature_Option__c.getRecordTypeInfosByName().get('Level 2-Section').getRecordTypeId();    
        //Create SFO record of record Type Section
        Special_Feature_Option__c SFO_Obj1 = TestUtility.createSFO(productObj.id);
        SFO_Obj1.Name__c = 'test';
        SFO_Obj1.RecordTypeId = RecordTypeIdSFO;
        SFO_Obj1.Base_Unit_to_be_Modified__c =productObj.id;
        insert SFO_Obj1;
        
        //get record type of Component
        Id RecordTypeIdSFO1 = Schema.SObjectType.Special_Feature_Option__c.getRecordTypeInfosByName().get('Level 3-Component').getRecordTypeId();    
        
        //Create SFO record of record type  Component
        Special_Feature_Option__c SFO_Obj2 = TestUtility.createSFO(productObj.id);
        SFO_Obj2.Name__c = 'test Component';
        SFO_Obj2.RecordTypeId = RecordTypeIdSFO1;
        SFO_Obj2.Parent_SFO__c = SFO_Obj1.id;
        insert SFO_Obj2;
        
        //get record type of Special Feature
        Id RecordTypeIdSFO2 = Schema.SObjectType.Special_Feature_Option__c.getRecordTypeInfosByName().get('Level 4-Special Feature').getRecordTypeId();    
        
        //Create SFO record of record type Level 4-Special Feature
        Special_Feature_Option__c SFO_Obj3 = TestUtility.createSFO(productObj.id);
        SFO_Obj3.Name__c ='Sample Special feature';
        SFO_Obj3.RecordTypeId = RecordTypeIdSFO2;
        SFO_Obj3.Special_Feature_Parent__c = SFO_Obj2.id;
        insert SFO_Obj3;
        
        
        
          //get record type of Option
        Id RecordTypeIdSFO3 = Schema.SObjectType.Special_Feature_Option__c.getRecordTypeInfosByName().get('Level 5-Option').getRecordTypeId(); 
        
        SFO_Obj3.RecordTypeId=RecordTypeIdSFO3;
        SFO_Obj3.Status__c='Approved';
        update SFO_Obj3;
        
               // Id ReadOnlyRecordTypeIdSFO = Schema.SObjectType.Special_Feature_Option__c.getRecordTypeInfosByName().get('Read Only').getRecordTypeId();    
        List<Related_SFO__c> SFOList = new List<Related_SFO__c>();
        for(Integer i=0; i<50; i++){
            Related_SFO__c RelatedSFO = new Related_SFO__c();
            RelatedSFO.SFO__c=SFO_Obj3.Id;
            RelatedSFO.Notes__c='Test'+i;
            //RelatedSFO.CurrencyIsoCode='CAD - Canadian Dollar';
            RelatedSFO.Unit_Detail__c=fpaLink.Id;
            SFOList.add(RelatedSFO);
        }
        insert SFOList;
    }
    @isTest static void   SendEmailFPARelatedAttachmentsMethod(){
        Factory_Pricing_Authorization__c   FPAObj =[Select id,Name,Application_Engineer__c,Status__c from Factory_Pricing_Authorization__c where Name=:'Test FPA'];
        Special_Feature_Option__c SFOObj= [Select id,Name__c,Status__c,RecordTypeId,Option_Parent__c from Special_Feature_Option__c where Name__c=:'Sample Special feature'];
        FPA_Link__c fpalink = [Select id, Name From FPA_Link__c limit 1];
        Id readOnlyRecordTypeId = Schema.SObjectType.Special_Feature_Option__c.getRecordTypeInfosByDeveloperName()
            .get('Read_Only').getRecordTypeId();
        SFOObj.RecordTypeId=readOnlyRecordTypeId;
        update SFOObj;
        Related_SFO__c RelatedSFo = [Select id,SFO__c,Notes__c,Unit_Detail__c from Related_SFO__c where Notes__c =:'Test1'];
        
        Test.startTest();
        PageReference pgref = new Pagereference('/apex/SFOSearchPage?id='+FPAObj.id);
        Test.setCurrentPage(pgref); 
        ApexPages.StandardController sc = new ApexPages.StandardController(FPAObj);
        SFOSearchController SFOApprovalControllerObj = new SFOSearchController(sc);
        SFOSearchController.SFOWrapper sfoWrap = new SFOSearchController.SFOWrapper(SFOObj);
        SFOSearchController.UnitTagWrapper sfoUnitTagWrap = new SFOSearchController.UnitTagWrapper(SFOObj,fpalink);
        SFOApprovalControllerObj.getUnitDetails();
        SFOApprovalControllerObj.searchVal='Approved';
        SFOApprovalControllerObj.isSearched = true;
        SFOApprovalControllerObj.getFields('Special_Feature_Option__c');
        SFOApprovalControllerObj.doSearch();
        SFOApprovalControllerObj.associateSFO();
        SFOApprovalControllerObj.closePopup();
        SFOApprovalControllerObj.showPopup();
        SFOApprovalControllerObj.createSFO();
        SFOApprovalControllerObj.backToFPA();
        SFOApprovalControllerObj.Beginning();
        SFOApprovalControllerObj.Next();
        SFOApprovalControllerObj.getDisableNext();
        SFOApprovalControllerObj.Previous();
        SFOApprovalControllerObj.getDisablePrevious();
        SFOApprovalControllerObj.relatedSFOID=RelatedSFo.id;
        SFOApprovalControllerObj.deleteRow();
        Test.stopTest();
        
    }
    @isTest static void   SendEmailFPARelatedAttachmentsMethod2(){
        Factory_Pricing_Authorization__c   FPAObj =[Select id,Name,Application_Engineer__c,Status__c from Factory_Pricing_Authorization__c where Name=:'Test FPA'];
        Special_Feature_Option__c SFOObj= [Select id,Name__c,Status__c,RecordTypeId,Option_Parent__c from Special_Feature_Option__c where Name__c=:'Sample Special feature'];
        FPA_Link__c fpalink = [Select id, Name From FPA_Link__c limit 1];
        
        Related_SFO__c RelatedSFo = [Select id,SFO__c,Notes__c,Unit_Detail__c from Related_SFO__c where Notes__c =:'Test1'];
        
        Test.startTest();
        PageReference pgref = new Pagereference('/apex/SFOSearchPage?id='+FPAObj.id);
        Test.setCurrentPage(pgref); 
        ApexPages.StandardController sc = new ApexPages.StandardController(FPAObj);
        SFOSearchController SFOApprovalControllerObj = new SFOSearchController(sc);
        SFOSearchController.SFOWrapper sfoWrap = new SFOSearchController.SFOWrapper(SFOObj);
        SFOSearchController.UnitTagWrapper sfoUnitTagWrap = new SFOSearchController.UnitTagWrapper(SFOObj,fpalink);
        SFOApprovalControllerObj.getUnitDetails();
        SFOApprovalControllerObj.searchVal='Approved';
        SFOApprovalControllerObj.searchsfoVal='';
        SFOApprovalControllerObj.isSearched = true;
        SFOApprovalControllerObj.getFields('Special_Feature_Option__c');
        SFOApprovalControllerObj.doSearch();
        SFOApprovalControllerObj.associateSFO();
        Test.stopTest();
        
    }
    
    // Test Method to cover the method in TestUtility Class
    @isTest static void TestUtilityMethod(){
        Factory_Pricing_Authorization__c   FPAObj =[Select id,Name,Application_Engineer__c,Status__c from Factory_Pricing_Authorization__c where Name=:'Test FPA'];
        Integer MaxQuantitySingleLineItem =2;
        Integer FpaTotalEngHours =3;
        Integer FpaTotalMagHours=4;
        Integer MaxMaterialCost=5;
        Integer QLineItemSpecial=6;
       Integer FpaTotalDrfHours=4;
        FPA_Link__c UnitDetailObject = TestUtility.CreatesfpaLink(FPAObj.id,MaxQuantitySingleLineItem,FpaTotalEngHours,FpaTotalMagHours,MaxMaterialCost,QLineItemSpecial,FpaTotalDrfHours);
      
        //Creating FpaApprover
        FPA_Approval__c FPAApprover = TestUtility.CreateFpaApprover(FPAObj.id,'Approved');
        
        // Creating the Format i.e parent for the SFO Record Type Section
        Product__c productObj = TestUtility.createProductFormat();
        productObj.IsActive__c=true;
        insert productObj;
        
        //Creating Format Approver
        FPA_Approval__c FormatApprover = TestUtility.CreateFormatApprover(productObj.id, 'Approved', true, true, true, false);
    }
    
    //Test Method To Cover For Updating the SFO with Different UnitDetails(Trigger Handler Class )
    
    @isTest static void SFOTriggerHandlerMethod(){
        Factory_Pricing_Authorization__c   FPAObj =[Select id,Name,Application_Engineer__c,Status__c from Factory_Pricing_Authorization__c where Name=:'Test FPA'];
        Special_Feature_Option__c SFOObj= [Select id,Name__c,Status__c,RecordTypeId,Option_Parent__c from Special_Feature_Option__c where Name__c=:'test Component'];
        
        // Creating Product
        
        Product__c productObj = TestUtility.createProductFormat();
        productObj.IsActive__c=true;
        insert productObj;
        
         //get record type of Special Feature
        Id RecordTypeIdSFO2 = Schema.SObjectType.Special_Feature_Option__c.getRecordTypeInfosByName().get('Level 4-Special Feature').getRecordTypeId();    
        //Create SFO record of record type Level 4-Special Feature
        Special_Feature_Option__c SFO_Obj3 = TestUtility.createSFO(productObj.id);
        SFO_Obj3.Name__c ='Sample Special feature test';
        SFO_Obj3.RecordTypeId =RecordTypeIdSFO2;
        SFO_Obj3.Special_Feature_Parent__c = SFOObj.id;
        insert SFO_Obj3;
        
        //get record type of Option
        Id RecordTypeIdSFO3 = Schema.SObjectType.Special_Feature_Option__c.getRecordTypeInfosByName().get('Level 5-Option').getRecordTypeId(); 
        Special_Feature_Option__c SFO_Obj4 = TestUtility.createSFO(productObj.id);
        SFO_Obj4.Name__c ='Option test';
        SFO_Obj4.RecordTypeId = RecordTypeIdSFO3;
        SFO_Obj4.Option_Parent__c = SFO_Obj3.id;
        insert SFO_Obj4;
        
        //Creating Unitdetails for FPA object i.e FPA Link
        
        FPA_Link__c fpaLink = TestUtility.CreatesfpaLink(FPAObj.Id);
        fpaLink.SFO__c=SFO_Obj4.id;
        insert fpaLink;  

        
        List<Special_Feature_Option__c> Sfolist = new List<Special_Feature_Option__c>();
        Sfolist.add(SFO_Obj3);
        SFO_Trigger_Handler SFOTriggerHandlerCls = new SFO_Trigger_Handler();
        SFO_Trigger_Handler.createDynamicFields(Sfolist);
        SFO_Trigger_Handler.Insert_ChildRec_for_SFOs(Sfolist);
        SFO_Trigger_Handler.updateRevisionInfo(Sfolist);
        SFO_Trigger_Handler.updateUnitTags(Sfolist);
    }
    
    // TestMethod For removeDraftRejectedSFO Class 
      @isTest static void   removeDraftRejectedSFOS(){
        Factory_Pricing_Authorization__c   FPAObj =[Select id,Name,Application_Engineer__c,Status__c from Factory_Pricing_Authorization__c where Name=:'Test FPA'];
          Special_Feature_Option__c SFOObj= [Select id,Name__c,Status__c,RecordTypeId,Option_Parent__c from Special_Feature_Option__c where Name__c=:'Sample Special feature'];
          FPA_Link__c fpalink = [Select id, Name From FPA_Link__c limit 1];
          Id readOnlyRecordTypeId = Schema.SObjectType.Special_Feature_Option__c.getRecordTypeInfosByDeveloperName()
              .get('Read_Only').getRecordTypeId();
          SFOObj.RecordTypeId=readOnlyRecordTypeId;
          update SFOObj;
          SFOObj.Status__c='Draft';
          update SFOObj;
          //Related_SFO__c RelatedSFo = [Select id,SFO__c,Notes__c,Unit_Detail__c from Related_SFO__c where Notes__c =:'Test1']; 
    }
}