src/objects/Factory_Pricing_Authorization__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Person_Name__c</fullName>
        <label>Sales Person Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Non Bid Process</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <isActive>false</isActive>
                    <label>Pending</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FPA</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FPAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FPA_Persona__c.object
<CustomObject>
    <fields>
        <fullName>User_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <inlineHelpText>Uniquely identifies each user</inlineHelpText>
        <label>User Id</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Sales Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Persona</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <label>Format</label>
    <nameField>
        <label>Format Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>User_ID__c</fullName>
        <formula>Id = $User.Id</formula>
        <label>User ID</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/FPASearchControllerTest.cls
@istest
public class FPASearchControllerTest 
{
    @testSetup static void fPASearchControllTestSetUp() {
        Product2 Product2Obj=TestUtility.createProduct();
        insert product2Obj;
        
        Product__c productObj=TestUtility.createProductFormat();
        insert productObj;
        
        FPA_Persona__c FPAPersonRepObj=TestUtility.createFPAPersona('Rep',null);
        FPAPersonRepObj.User_Id__c='test 1234';
        insert FPAPersonRepObj;
        
        Factory_Pricing_Authorization__c FPAObj=TestUtility.createFPA(FPAPersonRepObj.Id,productObj.Id);
        FPAObj.Status__c='Approved';
        FPAObj.Name='Test FPA';
        insert FPAObj;
    }
	@isTest static void FPASearchControllerTestMethod() 
    {
        
        Factory_Pricing_Authorization__c FPAObj=[Select id,Sales_Person_Name__c from Factory_Pricing_Authorization__c where Name=:'Test FPA'];
        
        system.debug('FPAObj '+ FPAObj);
        
        pageReference pageRef=new pageReference('/apex/FPASearchPage');
        Test.setCurrentPage(pageRef);
        
        Id [] fixedSearchResults= new Id[1];
        fixedSearchResults[0] = FPAObj.Id;
        Test.setFixedSearchResults(fixedSearchResults);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(FPAObj);
        FPASearchController FPASearchControllerObj=new FPASearchController(sc);
        FPASearchControllerObj.removeValues();
        FPASearchControllerObj.getFields();
        FPASearchControllerObj.resetFilters();
        FPASearchControllerObj.filter();
        FPASearchControllerObj.cloneFPA();
        FPASearchControllerObj.selectedFpa=null;
        FPASearchControllerObj.selectWrapper();
        FPASearchControllerObj.selectedFpa=FPAObj.id;
        FPASearchControllerObj.cloneFPA();
        FPASearchControllerObj.createFPA();
        FPASearchControllerObj.searchVal='Test';
        FPASearchControllerObj.salesPersonName='FPA User';
        /*FPASearchControllerObj.officeName='Test Office';
        FPASearchControllerObj.jobName='Test Job';
        FPASearchControllerObj.location='Test Location';
        FPASearchControllerObj.FPANumber='Test1234';*/
        FPASearchControllerObj.doSearch();
        FPASearchControllerObj.selectWrapper();
        FPASearchControllerObj.selectedFpa=FPAObj.Id;
        FPASearchControllerObj.selectWrapper();
    }
    
    @isTest static void TestMethod2(){
        Factory_Pricing_Authorization__c FPAObj=[Select id,Sales_Person_Name__c from Factory_Pricing_Authorization__c where Name=:'Test FPA'];
       
        pageReference pageRef=new pageReference('/apex/FPASearchPage');
        Test.setCurrentPage(pageRef);
        
        Id [] fixedSearchResults= new Id[1];
        fixedSearchResults[0] = FPAObj.Id;
        Test.setFixedSearchResults(fixedSearchResults);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(FPAObj);
        FPASearchController FPASearchControllerObj=new FPASearchController(sc);
        FPASearchControllerObj.officeName='Test Office';
         FPASearchControllerObj.removeValues();
        FPASearchControllerObj.getFields();
        FPASearchControllerObj.resetFilters();
        FPASearchControllerObj.filter();
        FPASearchControllerObj.cloneFPA();
        FPASearchControllerObj.selectedFpa=null;
        FPASearchControllerObj.selectWrapper();
        FPASearchControllerObj.selectedFpa=FPAObj.id;
        FPASearchControllerObj.cloneFPA();
        FPASearchControllerObj.createFPA();
        FPASearchControllerObj.searchVal='Test';
        FPASearchControllerObj.officeName='Test Office';
        FPASearchControllerObj.doSearch();
    }
        @isTest static void TestMethod3(){
        Factory_Pricing_Authorization__c FPAObj=[Select id,Sales_Person_Name__c from Factory_Pricing_Authorization__c where Name=:'Test FPA'];
       
        pageReference pageRef=new pageReference('/apex/FPASearchPage');
        Test.setCurrentPage(pageRef);
        
        Id [] fixedSearchResults= new Id[1];
        fixedSearchResults[0] = FPAObj.Id;
        Test.setFixedSearchResults(fixedSearchResults);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(FPAObj);
        FPASearchController FPASearchControllerObj=new FPASearchController(sc);
        
         FPASearchControllerObj.removeValues();
        FPASearchControllerObj.getFields();
        FPASearchControllerObj.resetFilters();
        FPASearchControllerObj.filter();
        FPASearchControllerObj.cloneFPA();
        FPASearchControllerObj.selectedFpa=null;
        FPASearchControllerObj.selectWrapper();
        FPASearchControllerObj.selectedFpa=FPAObj.id;
        FPASearchControllerObj.cloneFPA();
        FPASearchControllerObj.createFPA();
        FPASearchControllerObj.searchVal='Test';
         FPASearchControllerObj.jobName='Test Job';
        FPASearchControllerObj.doSearch();
    }
}