src/objects/Factory_Pricing_Authorization__c.object
<CustomObject>
    <fields>
        <fullName>Base_Unit_to_be_Modified__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>FPAs</relationshipLabel>
        <relationshipName>FPAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Discreet_Identifier__c</fullName>
        <label>Discrete Identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Eng_Mfg_Effort__c</fullName>
        <label>Eng/Mfg Effort</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                    <default>true</default>
                    <label>Low</label>
                </value>
                <value>
                    <fullName>Very Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Entry_Date__c</fullName>
        <label>Entry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Job_ID__c</fullName>
        <label>Job ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Modifier_location__c</fullName>
        <label>Modifier Name(s)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the sales rep office</inlineHelpText>
        <label>Rep Office</label>
        <referenceTo>Office__c</referenceTo>
        <relationshipLabel>FPAs</relationshipLabel>
        <relationshipName>FPAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Item Quantity</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Risk__c</fullName>
        <label>Risk</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                    <default>true</default>
                    <label>Low</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the appropriate Rep</inlineHelpText>
        <label>Sales Person</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Office__c</field>
                <operation>equals</operation>
                <valueField>FPA_Persona__c.Office__r.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>FPA_Persona__c</referenceTo>
        <relationshipLabel>FPAs</relationshipLabel>
        <relationshipName>FPAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submitted__c</fullName>
        <inlineHelpText>FPA Submitted date</inlineHelpText>
        <label>Submitted Date</label>
        <type>Date</type>
    </fields>
    <label>FPA</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FPAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FPA_Approval__c.object
<CustomObject>
    <fields>
        <fullName>A__c</fullName>
        <defaultValue>false</defaultValue>
        <label>A</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>D__c</fullName>
        <defaultValue>false</defaultValue>
        <label>D</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FPA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FPA</label>
        <referenceTo>Factory_Pricing_Authorization__c</referenceTo>
        <relationshipLabel>Approvers</relationshipLabel>
        <relationshipName>FPA_Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Approver</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FPA_Link__c.object
<CustomObject>
    <fields>
        <fullName>FPA__c</fullName>
        <label>FPA</label>
        <referenceTo>Factory_Pricing_Authorization__c</referenceTo>
        <relationshipLabel>Unit Details</relationshipLabel>
        <relationshipName>Related_SFO</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <formula>SFO__r.Notes__c</formula>
        <label>Notes</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Person__c</fullName>
        <formula>FPA__r.Sales_Person__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Person</label>
        <type>Text</type>
    </fields>
    <label>Unit Detail</label>
    <nameField>
        <label>Unit Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FPA_Persona__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <inlineHelpText>Select the department which user belongs to</inlineHelpText>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Operations</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the Primary Work Location</inlineHelpText>
        <label>Office</label>
        <referenceTo>Office__c</referenceTo>
        <relationshipLabel>Sales Persona</relationshipLabel>
        <relationshipName>Sales_Persons</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <inlineHelpText>Assign the user role</inlineHelpText>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Rep</fullName>
                </value>
                <value>
                    <fullName>Engineer</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Persona</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Product Brand Name</label>
        <type>TextArea</type>
    </fields>
    <label>Format</label>
    <nameField>
        <label>Format Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>3200</length>
        <type>LongTextArea</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SFO_Dynamic_Fields__c.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <formula>SFO__r.Notes__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Notes</label>
        <type>Text</type>
    </fields>
    <label>Special Feature Dynamic Fields</label>
    <nameField>
        <label>Field Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Special Feature Dynamic Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Special_Feature_Option__c.object
<CustomObject>
    <fields>
        <fullName>Base_Unit_to_be_Modified__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Select formats by search/lookup as defined in the Format creation screen</inlineHelpText>
        <label>Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Records</relationshipLabel>
        <relationshipName>SFOs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entry_Date__c</fullName>
        <label>Entry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Modifier_Location__c</fullName>
        <label>Modifier Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Unit_Tags__c</fullName>
        <inlineHelpText>Value is populated when Option is linked to FPA</inlineHelpText>
        <label>Unit Tags</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Records</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestUtility.cls
public class TestUtility 
{  
    public static Product2 createProduct()
    {
        Product2 product = new Product2();
        product.Name = 'Test Product';
        return product;
    }
    public static Office__c createOffice()
    {
        Office__c office = new Office__c();
        office.Name =  'Daikin Office';
        return office;
    }
    public static FPA_Persona__c createFPAPersona(String role, String department)
    {
        FPA_Persona__c person = new FPA_Persona__c();
        person.Name ='FPA User';
        person.Office__c = createOffice().Id;
        person.Role__c = role;
        person.Department__c = department;
        person.Email__c = 'Daikin@test.com';
        return person;
    }
    public static Factory_Pricing_Authorization__c createFPA(String salesPersonId, String productId)
    {
        Factory_Pricing_Authorization__c fpa = new Factory_Pricing_Authorization__c();
        fpa.Name = 'Test FPA';
        fpa.Job_ID__c = '1234';
        fpa.Discreet_Identifier__c ='FPA-1234';
        fpa.Sales_Person__c = salesPersonId;
        fpa.Entry_Date__c = System.today();
        fpa.Project__c = 'Daikin';
        fpa.Office__c = createOffice().Id;
        fpa.Risk__c = '';
        fpa.Eng_Mfg_Effort__c = '';
       // fpa.CapX__c = '';
        //fpa.Previous_FPA__c = '';
        fpa.Description__c = 'Test Description';
        fpa.Base_Unit_to_be_Modified__c = productId;
        //fpa.Base_Unit_to_be_Modified__c=TestUtility.createProductFormat().p.Id;
        fpa.Quantity__c = 10;
        fpa.Submitted__c = date.newInstance(2019, 01, 01);
        return fpa;
    }
    public static Special_Feature_Option__c createSFO(String ProductId)
    {
        Special_Feature_Option__c SFO_Obj = new Special_Feature_Option__c();
        SFO_Obj.Base_Unit_to_be_Modified__c = ProductId;
        SFO_Obj.Name__c = 'test Name';
        SFO_Obj.Notes__c = '5K Flat HX TEMPLATE';
        SFO_Obj.Entry_Date__c = system.today();
        SFO_Obj.Modifier_Location__c = 'Top, End';
        SFO_Obj.Unit_Tags__c = 'test units';
        return SFO_Obj;
    }
    public static SFO_Fields__c createSFOFields(String fieldLabel, String dataType)
    {
        SFO_Fields__c field = new SFO_Fields__c();
        field.Name   = fieldLabel;
        field.Field_Data_Type__c = dataType;
        return field;
    }
    public static SFO_Dynamic_Fields__c createSFODynamicFields(String SFOFieldId, String sfoId)
    {
        SFO_Dynamic_Fields__c field = new SFO_Dynamic_Fields__c();
        field.SFO_Field__c=SFOFieldId;
        field.SFO__c = sfoId;
        
        return field;
    }
    
    public static FPA_Link__c CreatesfpaLink(String fpaId)
    {
        FPA_Link__c fpaLink = new FPA_Link__c();
        fpaLink.Quantity__c = 12;
        fpaLink.Unit_Tag__c = 'MAY 1';
        fpaLink.Lead_Time__c = 16;
        fpaLink.FPA__c = fpaId;
        
        return fpaLink ;
    }
    
     public static Product__c createProductFormat(){
        Product__c p = new Product__c();
        p.Name='TestProduct';
        p.PCL__c='0001';
        p.Description__c='NewBrand';
        p.IsActive__c=true;
        return p;
}
    
    public static Approval_Criteria__c ApprovalCriteria(String ApprovelLevel,id Productid,String dh,String Eh,String Mh,
                                                        String Mqali,String MTDH,
                                                        String MTEH,String MTMH,String MTMC,String QLIS){
        Approval_Criteria__c Appcriteria = new Approval_Criteria__c();
        Appcriteria.Approval_Level__c=ApprovelLevel;
        Appcriteria.Format__c=Productid;
        Appcriteria.FPA_Total_Drafting_Hours__c=dh;
        Appcriteria.FPA_Total_Engineering_Hours__c=Eh;
        Appcriteria.FPA_Total_Manufacturing_Hours__c=Mh;
        Appcriteria.Max_QTY_of_Units_On_Single_Line_Item__c=Mqali;
        Appcriteria.Max_Total_Drafting_Hours_per_Single_l__c=MTDH;
        Appcriteria.Max_Total_Engineering_Hours_for_Single__c=MTEH;
        Appcriteria.Max_Total_Manufacturing_Hours_for_Single__c=MTMH;
        Appcriteria.Max_Total_Material_Cost_for_Single_Line__c=MTMC;
        Appcriteria.QTY_of_line_Item_with_Specials__c=QLIS;
        return Appcriteria;
    }
    public static FPA_Link__c CreatesfpaLink(id FPAObj,Integer MaxQuantitySingleLineItem,Integer FpaTotalEngHours,Integer FpaTotalMagHours,
                                                                  Integer MaxMaterialCost,Integer QLineItemSpecial,Integer FpaTotalDrfHours){
        FPA_Link__c UnitDetailObj =TestUtility.CreatesfpaLink(FPAObj);
        
        UnitDetailObj.Max_QTY_of_Units_On_Single_Line_Item__c=MaxQuantitySingleLineItem;
        UnitDetailObj.FPA_Total_Engineering_Hours__c=FpaTotalEngHours;
        UnitDetailObj.FPA_Total_Manufacturing_Hours__c=FpaTotalMagHours;
        UnitDetailObj.Max_Total_Material_Cost_for_Single_Line__c=MaxMaterialCost;
        UnitDetailObj.QTY_of_line_Item_with_Specials__c=QLineItemSpecial;
        UnitDetailObj.FPA_Total_Drafting_Hours__c=FpaTotalDrfHours;
        return  UnitDetailObj;                                                             
    } 
public static FPA_Approval__c CreateFpaApprover(String fpaId,String Status)
{
    FPA_Approval__c FpaApprover = new FPA_Approval__c();
    FpaApprover.FPA__c=fpaId;
    FpaApprover.Status__c=Status;
    return FpaApprover;
}
    public static FPA_Approval__c CreateFormatApprover(String formatId,String Status,boolean a, boolean b, boolean c, boolean d)
{
    FPA_Approval__c FormatApprover = new FPA_Approval__c();
    FormatApprover.Format__c=formatId;
    FormatApprover.A__c=a;
    FormatApprover.B__c=b;
    FormatApprover.C__c=c;
    FormatApprover.D__c=d;
    return FormatApprover;
}
}