src/objects/Factory_Pricing_Authorization__c.object
<CustomObject>
    <fields>
        <fullName>Application_Engineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Engineer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>FPAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Level__c</fullName>
        <label>Approval Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Average_List_Price_Markup__c</fullName>
        <label>Average List Price Markup</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Base_Unit_to_be_Modified__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>FPAs</relationshipLabel>
        <relationshipName>FPAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Costt__c</fullName>
        <label>Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Created_Date__c</fullName>
        <formula>DATEVALUE(CreatedDate)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Created Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FPA_Number__c</fullName>
        <label>FPA Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_ID__c</fullName>
        <label>Job ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <label>List Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Multiplier__c</fullName>
        <defaultValue>0.30</defaultValue>
        <label>Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the sales rep office</inlineHelpText>
        <label>Rep Office</label>
        <referenceTo>Office__c</referenceTo>
        <relationshipLabel>FPAs</relationshipLabel>
        <relationshipName>FPAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <formula>Sales_Person__r.Phone__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Item Quantity</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the appropriate Rep</inlineHelpText>
        <label>Sales Person</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Office__c</field>
                <operation>equals</operation>
                <valueField>FPA_Persona__c.Office__r.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>FPA_Persona__c</referenceTo>
        <relationshipLabel>FPAs</relationshipLabel>
        <relationshipName>FPAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <label>Total Cost</label>
        <summarizedField>FPA_Link__c.Total_Cost__c</summarizedField>
        <summaryForeignKey>FPA_Link__c.FPA__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Margin__c</fullName>
        <label>Total Margin</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>FPA</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FPAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FPA_Link__c.object
<CustomObject>
    <fields>
        <fullName>FPA__c</fullName>
        <label>FPA</label>
        <referenceTo>Factory_Pricing_Authorization__c</referenceTo>
        <relationshipLabel>Unit Details</relationshipLabel>
        <relationshipName>Related_SFO</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lead_Time__c</fullName>
        <label>Lead Time(wks)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SFO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFO</label>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipName>Related_SFO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Person__c</fullName>
        <formula>FPA__r.Sales_Person__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Person</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <formula>Item_Cost__c  *  Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Margin__c</fullName>
        <formula>Total_Net_Price__c  -  Total_Cost__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Margin $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Unit Detail</label>
    <nameField>
        <label>Unit Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FPA_Persona__c.object
<CustomObject>
    <fields>
        <fullName>Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the Primary Work Location</inlineHelpText>
        <label>Office</label>
        <referenceTo>Office__c</referenceTo>
        <relationshipLabel>Sales Persona</relationshipLabel>
        <relationshipName>Sales_Persons</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Sales Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Persona</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Product Brand Name</label>
        <type>TextArea</type>
    </fields>
    <label>Format</label>
    <nameField>
        <label>Format Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Related_SFO__c.object
<CustomObject>
    <fields>
        <fullName>Expected_Margin__c</fullName>
        <formula>IF(AND(NOT(ISNULL(Total_Cost__c)),Total_Cost__c !=0),(Assumed_Multiplier__c  *  List_Price__c  - Total_Cost__c ) /  Total_Cost__c,0)*100</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expected Margin</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <formula>Cost_Per_unit__c  *  List_Markup__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SFO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFO</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Special_Feature_Option__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Read Only</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipLabel>Related SFO</relationshipLabel>
        <relationshipName>Related_SFO1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <formula>SFO__r.Sum_of_Eng_Draft_Cost__c +( SFO__r.Sum_of_Mod_Material_Mfg_Cost__c * Unit_Detail__r.Quantity__c  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Detail</label>
        <referenceTo>FPA_Link__c</referenceTo>
        <relationshipLabel>Related SFO</relationshipLabel>
        <relationshipName>Related_SFO</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Related SFO</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Related SFO  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related SFO</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SFO_Dynamic_Fields__c.object
<CustomObject>
    <fields>
        <fullName>SFO__c</fullName>
        <label>SFO</label>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipName>SFO_Dynamic_Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Special Feature Dynamic Fields</label>
    <nameField>
        <label>Field Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Special Feature Dynamic Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Special_Feature_Option__c.object
<CustomObject>
    <fields>
        <fullName>Base_Unit_to_be_Modified__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Select formats by search/lookup as defined in the Format creation screen</inlineHelpText>
        <label>Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Records</relationshipLabel>
        <relationshipName>SFOs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Option_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Special Feature</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Special_Feature_Option__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Level 4-Special Feature</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>SFOs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <formula>Fixed_Unit_Cost__c  +  Variable_Unit_Cost__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Records</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Records</pluralLabel>
    <recordTypes>
        <fullName>Component</fullName>
        <active>true</active>
        <description>Holds Component Records</description>
        <label>Level 3-Component</label>
    </recordTypes>
    <recordTypes>
        <fullName>Section</fullName>
        <active>true</active>
        <description>Holds Section Records</description>
        <label>Level 2-Section</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/unitTagewithRelatedSFOExt_Controller.cls
public class unitTagewithRelatedSFOExt_Controller {
    public string fpa_ID;
    public string pdfcontent{set;get;}
    public Set<Id> RFOId = new Set<Id>();
    public Map<id,List<FPA_Link__c>> fpaMap {set;get;}
    public Factory_Pricing_Authorization__c FPA_rec{get;set;}
    public List<Attachment> attachmnt {get;set;}
    public Map<id,List<Related_SFO__c>> unitTagMap {get;set;}
    public Map<id,List<unitTagWrapper>> unitRelatedSFOWrap {set;get;}
    public Map<id,FPA_Link__c> fpaLinkMap {set;get;}
    public String getFPA_Id(){ return FPA_Id; }
    List<FPA_Link__c> fpaLinkList {get;set;}
    public void setFPA_Id(String s){
        FPA_Id = s;
        unitTagewithRelatedSFOExt_Controller();
    }
    
    public void unitTagewithRelatedSFOExt_Controller(){
        Set<id> fpaLinkIds = new set<id>();
        system.debug('fpaID '+fpa_ID);
        set<id> sfoIds = new set<id>();
        unitTagMap = new Map<id,List<Related_SFO__c>>();
        fpaMap = new Map<id,List<FPA_Link__c>>();
        fpaLinkMap = new Map<id,FPA_Link__c>();
        FPA_rec = new Factory_Pricing_Authorization__c();
        for(Factory_Pricing_Authorization__c fpa : [Select Id, Created_Date__c , Owner.Name, Application_Engineer__r.Name, Phone__c, Multiplier__c, Description__c , Average_List_Price_Markup__c, Total_Margin__c, Costt__c, List_Price__c, Name, Job_ID__c, FPA_Number__c, Office__r.Name, Sales_Person__r.Name, Approval_Level__c, Base_Unit_to_be_Modified__r.Description__c, (Select Id, Name,Quantity__c, Lead_Time__c from Related_SFO__r) from Factory_Pricing_Authorization__c where Id =:fpa_ID ])
        {
            FPA_rec = fpa;
            system.debug('fpa '+fpa);
            for(FPA_Link__c fpalink:fpa.Related_SFO__r){
                
                fpaLinkMap.put(fpalink.Id,fpalink);
                fpaLinkIds.add(fpalink.id);
                if(fpaMap.containsKey(fpa.id)) {   
                    fpaMap.get(fpa.id).add(fpalink);}
                else {
                    fpaMap.put(fpa.id,new list<FPA_Link__c>{fpalink});
                }
            }
        }
        
        system.debug('fpaLinkIds '+fpaLinkIds);
        Map<id,id> relatedSFOMap = new Map<id,id>();
        List<Related_SFO__c> relatedSFOList = new List<Related_SFO__c>();
        
        for(Related_SFO__c rfo : [Select Id, Name, Expected_Margin__c, Total_Cost__c, SFO__c, SFO__r.Option_Parent__r.Notes__c, List_Price__c, SFO__r.name, SFO__r.Option_Parent__r.name, SFO__r.Drafting_hours__c, Unit_Detail__c, SFO__r.Notes__c,SFO__r.Component_Name__c ,SFO__r.Revision_Version__c,SFO__r.Section_Name__c from Related_SFO__c where Unit_Detail__c =: fpaLinkIds ]){
            sfoIds.add(rfo.SFO__c);
            RFOId.add(rfo.Id);
            relatedSFOMap.put(rfo.id, rfo.SFO__c);
            relatedSFOList.add(rfo);
            if(unitTagMap.containsKey(rfo.Unit_Detail__c)) {   
                unitTagMap.get(rfo.Unit_Detail__c).add(rfo);}
            else {unitTagMap.put(rfo.Unit_Detail__c,new list<Related_SFO__c>{rfo}); }
        }
        
        attachmnt = new List<Attachment>();        
        attachmnt = [Select Id, Name, Body, Contenttype, ParentId,Parent.Name From Attachment where parentid IN: RFOId and contenttype='Application/PDF'];
        Map<Id,String> AtUnitTagMap = new Map<Id,String>();
        for(Attachment att : attachmnt){
            pdfcontent = EncodingUtil.Base64Encode(att.Body);
            
        }
        //pdfcontent = EncodingUtil.Base64Encode(attachmnt.Body);
        fpaLinkList = [Select Id, Name,(Select Id, Name From Related_SFO__r where Id IN : RFOId) From FPA_Link__c ];
        for(FPA_Link__c fpaLink : fpaLinkList){
           
            
        }
        set<string> dynamicFieldList = new set<string>{'Material Cost','Drafting Hours','Manufacturing Hours','Engineering Hours','Modifier Cost'};
            
            Map<Id,List<SFO_Dynamic_Fields__c>> sfoDynamicMap = new Map<Id,List<SFO_Dynamic_Fields__c>>();
        for(Special_Feature_Option__c sfos : [Select Id, Name, Total_Cost_value__c, Component_Name__c, Section_Name__c, Revision_Version__c, (Select Id, Name, Field_Value__c, Field_Value_Number__c from SFO_Dynamic_Fields__r where name =:dynamicFieldList ) from Special_Feature_Option__c where Id =:sfoIds ])
        {
            sfoDynamicMap.put(sfos.id,sfos.SFO_Dynamic_Fields__r);
            
        }
        unitRelatedSFOWrap=new Map<id,List<unitTagWrapper>>();
        system.debug('relatedSFOList '+relatedSFOList);
        system.debug('sfoDynamicMap '+sfoDynamicMap);
        for(Related_SFO__c rf:relatedSFOList){
            System.debug('rf notes'+rf.SFO__r.Notes__c);
            string notes = rf.SFO__r.Option_Parent__r.Notes__c;
            String components = rf.SFO__r.Component_Name__c ;
            String sections = rf.SFO__r.Section_Name__c;
            string revisions = rf.SFO__r.Revision_Version__c;
            decimal listPrices = rf.List_Price__c;
            
            system.debug('rf '+rf.Name +' DYN '+sfoDynamicMap.get(rf.SFO__c));
            if(unitRelatedSFOWrap.containskey(rf.Unit_Detail__c)){   
                unitRelatedSFOWrap.get(rf.Unit_Detail__c).add(new unitTagWrapper(rf.SFO__r.Name, rf.SFO__r.Option_Parent__r.name,notes, components, sections, revisions, listPrices));
            }
            else{
                unitRelatedSFOWrap.put(rf.Unit_Detail__c,new list<unitTagWrapper>{new unitTagWrapper(rf.SFO__r.Name, rf.SFO__r.Option_Parent__r.name, notes, components, sections, revisions, listPrices)}); 
            }
        }
        system.debug('unitRelatedSFOWrap '+unitRelatedSFOWrap);
        
    }
    public class unitTagWrapper{
        public string optionName {set;get;}
        public string specialFeature {set;get;}
        public String notes{set;get;}
        public String components{set;get;}
        public String sections{set;get;}
        public String revisions{set;get;}
        public decimal listPrices{set;get;}
        
        public unitTagWrapper(string optionNam,string specialFeatur,String note, String component, String section, String revision, decimal listPrice){
            optionName = optionNam;
            specialFeature = specialFeatur;
            notes = note;
            components = component;
            sections = section;
            revisions = revision;
            listPrices = listPrice;
        }
    }
}