src/objects/Factory_Pricing_Authorization__c.object
<CustomObject>
    <fields>
        <fullName>Base_Unit_to_be_Modified__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>FPAs</relationshipLabel>
        <relationshipName>FPAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Entry_Date__c</fullName>
        <label>Entry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fixed_Unit_Cost__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Sum of Estimates Fixed Unit Cost</inlineHelpText>
        <label>Fixed Unit Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Modifier_location__c</fullName>
        <label>Modifier Name(s)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PCL__c</fullName>
        <label>PCL</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Non Bid Process</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <isActive>false</isActive>
                    <label>Pending</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FPA</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FPAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FPA_Link__c.object
<CustomObject>
    <fields>
        <fullName>Group_Identifier__c</fullName>
        <formula>SFO__r.Parent_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Individual_Identifier__c</fullName>
        <formula>SFO__r.Name__c</formula>
        <label>SFO Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <formula>SFO__r.Notes__c</formula>
        <label>Notes</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFO</label>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipName>Related_SFO</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Unit Detail</label>
    <nameField>
        <label>Unit Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FPA_Persona__c.object
<CustomObject>
    <fields>
        <fullName>User_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <inlineHelpText>Uniquely identifies each user</inlineHelpText>
        <label>User Id</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Sales Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Persona</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Product Brand Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Only Active Formats is available for FPA and SFO Selection</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PCL__c</fullName>
        <inlineHelpText>Please contact saleforcehelp@daikinapplied.com  to add PCL Numbers</inlineHelpText>
        <label>PCL Number(s)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0001</fullName>
                </value>
                <value>
                    <fullName>0002</fullName>
                </value>
                <value>
                    <fullName>0003</fullName>
                </value>
                <value>
                    <fullName>0004</fullName>
                </value>
                <value>
                    <fullName>0005</fullName>
                </value>
                <value>
                    <fullName>0006</fullName>
                </value>
                <value>
                    <fullName>0007</fullName>
                </value>
                <value>
                    <fullName>0008</fullName>
                </value>
                <value>
                    <fullName>0009</fullName>
                </value>
                <value>
                    <fullName>0010</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Format</label>
    <nameField>
        <label>Format Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Special_Feature_Option__c.object
<CustomObject>
    <fields>
        <fullName>Base_Unit_to_be_Modified__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Select formats by search/lookup as defined in the Format creation screen</inlineHelpText>
        <label>Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Records</relationshipLabel>
        <relationshipName>SFOs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Approval Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Drafting_cost__c</fullName>
        <label>Drafting Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Drafting_hours__c</fullName>
        <label>Drafting hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Entry_Date__c</fullName>
        <label>Entry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fixed_Unit_Cost__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Fixed Unit Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Group_Identifier__c</fullName>
        <externalId>true</externalId>
        <label>Group Identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Individual_Identifier__c</fullName>
        <externalId>true</externalId>
        <label>Individual Identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Modifier_Location__c</fullName>
        <label>Modifier Location</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Option_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Special Feature</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Special_Feature_Option__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Level 4-Special Feature</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>SFOs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_SFO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field allows users to click on the icon to select a value from a popup list.</inlineHelpText>
        <label>Section</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Id</field>
                <operation>notEqual</operation>
                <valueField>Special_Feature_Option__c.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Special_Feature_Option__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Level 2-Section</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>SFOs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchased_material_cost__c</fullName>
        <label>Purchased Material Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Raw_material_cost__c</fullName>
        <label>Raw Material Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Revision_Version__c</fullName>
        <label>Revision Version</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revision_date__c</fullName>
        <label>Revision date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Special_Feature_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Component</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Special_Feature_Option__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Level 3-Component</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipLabel>Special Features</relationshipLabel>
        <relationshipName>SFOs2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                    <isActive>false</isActive>
                    <label>Obsolete</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                    <isActive>false</isActive>
                    <label>Submitted for Approval</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_Tags__c</fullName>
        <inlineHelpText>Value is populated when Option is linked to FPA</inlineHelpText>
        <label>Unit Tags</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Variable_Unit_Cost__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Variable Unit Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Records</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Records</pluralLabel>
    <recordTypes>
        <fullName>Component</fullName>
        <active>true</active>
        <description>Holds Component Records</description>
        <label>Level 3-Component</label>
    </recordTypes>
    <recordTypes>
        <fullName>Option</fullName>
        <active>true</active>
        <description>Holds Options Records</description>
        <label>Level 5-Option</label>
    </recordTypes>
    <recordTypes>
        <fullName>Section</fullName>
        <active>true</active>
        <description>Holds Section Records</description>
        <label>Level 2-Section</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SFOSearchTest.cls
@istest
public class SFOSearchTest 
{
    @isTest static void SFOSearchTestMethod() 
    {
        Product2 Product2Obj=TestUtility.createProduct();
        insert product2Obj;
        
        // Create Feature record
        Product__c productObj= new Product__c();
        productObj.Name = '997';
        productObj.IsActive__c=true;
        productObj.Description__c ='Vision/Skyline';
        productObj.PCL__c='0002';
        insert productObj;
        system.debug('productObj:: '+productObj);
        
        //get record type of Section
        Id RecordTypeIdSFO = Schema.SObjectType.Special_Feature_Option__c.getRecordTypeInfosByName().get('Level 2-Section').getRecordTypeId();    
        
        //Create SFO(Section) record
        Special_Feature_Option__c SFO_Obj1 = TestUtility.createSFO(productObj.id);
        SFO_Obj1.Name__c = 'test';
        SFO_Obj1.Base_Unit_to_be_Modified__c =productObj.id;
        SFO_Obj1.RecordTypeId = RecordTypeIdSFO;
        insert SFO_Obj1;
        
        FPA_Persona__c FPAPersonRepObj=TestUtility.createFPAPersona('Rep',null);
        FPAPersonRepObj.User_Id__c='test 1234';
        insert FPAPersonRepObj;
        
        //Creating FPA
        Factory_Pricing_Authorization__c FPAObj=TestUtility.createFPA(FPAPersonRepObj.Id,productObj.Id);
        insert FPAObj;
        
        //Creating Unit Detail For FPA
        FPA_Link__c fpaLink = TestUtility.CreatesfpaLink(FPAObj.id);
        insert fpaLink;
        
        //get record type of Component
        Id RecordTypeIdSFO1 = Schema.SObjectType.Special_Feature_Option__c.getRecordTypeInfosByName().get('Level 3-Component').getRecordTypeId();    
        
        //Create SFO(Section) record
        Special_Feature_Option__c SFO_Obj2 = TestUtility.createSFO(productObj.id);
        SFO_Obj2.Name__c = 'test';
        SFO_Obj2.RecordTypeId = RecordTypeIdSFO1;
        SFO_Obj2.Parent_SFO__c = SFO_Obj1.id;
        insert SFO_Obj2;
        
        //get record type of Special Feature
        Id RecordTypeIdSFO2 = Schema.SObjectType.Special_Feature_Option__c.getRecordTypeInfosByName().get('Level 4-Special Feature').getRecordTypeId(); 
       
        // Creating SFO of Special feature
        List<Special_Feature_Option__c> SFOObjList=new List<Special_Feature_Option__c>();
        Special_Feature_Option__c SFOObj;
        for(integer i=0;i<=20;i++)
        {
            SFOObj=TestUtility.createSFO(productObj.Id);
            SFOObj.Status__c='Draft';
            SFOObj.RecordTypeId = RecordTypeIdSFO2;
            SFOObj.Special_Feature_Parent__c = SFO_Obj2.id;
            SFOObj.Comments__c='test comment'+i;
            SFOObjList.add(SFOObj);
        }
        
        insert SFOObjList;
        
        //get record type of Option
        Id RecordTypeIdSFO3 = Schema.SObjectType.Special_Feature_Option__c.getRecordTypeInfosByName().get('Level 5-Option').getRecordTypeId(); 
        
        //creating SFO With Option Record Type
         Special_Feature_Option__c SFOOption;
        List<Special_Feature_Option__c> OptionSfoList = new List<Special_Feature_Option__c>();
        for(Integer i=0;i<10;i++){
        SFOOption=TestUtility.createSFO(productObj.Id);
        SFOOption.Status__c='Draft';
        SFOOption.RecordTypeId = RecordTypeIdSFO3;
        SFOObj.Option_Parent__c = SFOObjList[0].id;
        SFOOption.Comments__c='test comment'+i;
            OptionSfoList.add(SFOOption);
        }  
        insert OptionSfoList;
        
        for(Special_Feature_Option__c s: OptionSfoList){
        s.Status__c='Approved';
        }
        update OptionSfoList;
        
        
        // Add Option to Unit Detail i.e Related SFO To Unit Detail
        
         fpaLink.SFO__c=OptionSfoList[0].id;
         update fpaLink;
        /*SFOObj=TestUtility.createSFO(productObj.Id);
        SFOObj.Parent_SFO__c = SFO_Obj1.id;
        SFOObj.Status__c='Approved';
        SFOObj.Comments__c='test comment';
        insert SFOObj;*/
        
        string sFO_sosl_query ='FIND \'test commen\' IN ALL FIELDS  RETURNING Special_Feature_Option__c(Id,OwnerId,IsDeleted,Name,CurrencyIsoCode,RecordTypeId,CreatedDate,CreatedById,LastModifiedDate,LastModifiedById,SystemModstamp,LastActivityDate,LastViewedDate,LastReferencedDate,Revision_Version__c,Entry_Date__c,Comments__c,Unit_Tags__c,Status__c,Modifier_Location__c,Notes__c,Parent_SFO__c,Base_Unit_to_be_Modified__c,Group_Identifier__c,Individual_Identifier__c,Variable_Unit_Cost__c,Fixed_Unit_Cost__c,Purchased_material_cost__c,Raw_material_cost__c,Drafting_hours__c,Drafting_cost__c,Revision_date__c WHERE  Status__c = \'Approved\' limit 100)';
        List<List<SObject>> searchList = search.query(sFO_sosl_query);
        List<Special_Feature_Option__c> sfoList = (List<Special_Feature_Option__c>) searchList[0];
        System.debug('SFOList size::'+SFOList.size());
        
        pageReference pageRef=new pageReference('/apex/SFOSearchPage?id='+FPAObj.Id);
        Test.setCurrentPage(pageRef);
        
        List<Id> fixedSearchResults= new List<Id>();
        for(Special_Feature_Option__c SFOId : OptionSfoList)
        {
            fixedSearchResults.add(SFOId.Id);
        }
        //fixedSearchResults.add(SFOObjList[0].Id);
        Test.setFixedSearchResults(fixedSearchResults);
        
        /*ApexPages.StandardController sc = new ApexPages.StandardController(FPAObj);
        SFOSearchController SFOApprovalControllerObj = new SFOSearchController(sc);
        SFOApprovalControllerObj.removeValues();
        SFOApprovalControllerObj.getFields('Special_Feature_Option__c');
        SFOApprovalControllerObj.showPopup();
        SFOApprovalControllerObj.createSFO();
        SFOApprovalControllerObj.backToFPA();
        SFOApprovalControllerObj.closePopup();
        SFOApprovalControllerObj.searchVal='Approved';
        SFOApprovalControllerObj.doSearch();
        SFOApprovalControllerObj.NextPage();
        SFOApprovalControllerObj.Previous();
        SFOApprovalControllerObj.Beginning();
        SFOApprovalControllerObj.End();
        SFOApprovalControllerObj.getDisablePrevious();
        SFOApprovalControllerObj.getDisableNext();
        SFOApprovalControllerObj.parentSFOId=SFOObjList[0].Id;
        SFOApprovalControllerObj.refreshPopUp();
        SFOApprovalControllerObj.selectedSFo=SFOObj.Id;
        SFOApprovalControllerObj.selectWrapper();
        SFOApprovalControllerObj.getExistingFPALinks();
        SFOApprovalControllerObj.navigateToFPALinks();
        SFOApprovalControllerObj.backTosearchResults();
        SFOApprovalControllerObj.saveFPALinks();
        
        SFOApprovalControllerObj = new SFOSearchController(sc);
        SFOApprovalControllerObj.getExistingFPALinks();*/
        
        Test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(FPAObj);
        SFOSearchController SFOApprovalControllerObj = new SFOSearchController(sc);
        SFOApprovalControllerObj = new SFOSearchController(sc);
        SFOSearchController.SFOWrapper sfoWrap = new SFOSearchController.SFOWrapper(OptionSfoList[0]);
        SFOSearchController.UnitTagWrapper sfoUnitTagWrap = new SFOSearchController.UnitTagWrapper(OptionSfoList[0],fpaLink);
        SFOApprovalControllerObj.getUnitDetails();
        SFOApprovalControllerObj.searchVal='Approved';
        SFOApprovalControllerObj.isSearched = true;
        SFOApprovalControllerObj.getFields('Special_Feature_Option__c');
        SFOApprovalControllerObj.doSearch();
        SFOApprovalControllerObj.associateSFO();
        SFOApprovalControllerObj.closePopup();
        SFOApprovalControllerObj.showPopup();
        SFOApprovalControllerObj.createSFO();
        SFOApprovalControllerObj.backToFPA();
        SFOApprovalControllerObj.Beginning();
        //SFOApprovalControllerObj.counter=12;
        SFOApprovalControllerObj.Next();
        SFOApprovalControllerObj.getDisableNext();
        SFOApprovalControllerObj.Previous();
        SFOApprovalControllerObj.getDisablePrevious();
                // SFOApprovalControllerObj.End();
        //SFOApprovalControllerObj.deleteRow();
        Test.stopTest();
        
    }
}