src/objects/Factory_Pricing_Authorization__c.object
<CustomObject>
    <fields>
        <fullName>Base_Unit_to_be_Modified__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>FPAs</relationshipLabel>
        <relationshipName>FPAs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed Won</fullName>
                </value>
                <value>
                    <fullName>Non Bid Process</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <isActive>false</isActive>
                    <label>Pending</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FPA</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FPAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FPA_Link__c.object
<CustomObject>
    <fields>
        <fullName>FPA__c</fullName>
        <label>FPA</label>
        <referenceTo>Factory_Pricing_Authorization__c</referenceTo>
        <relationshipLabel>Unit Details</relationshipLabel>
        <relationshipName>Related_SFO</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SFO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFO</label>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipName>Related_SFO</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Unit Detail</label>
    <nameField>
        <label>Unit Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FPA_Persona__c.object
<CustomObject>
    <fields>
        <fullName>User_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <inlineHelpText>Uniquely identifies each user</inlineHelpText>
        <label>User Id</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Sales Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Persona</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Only Active Formats is available for FPA and SFO Selection</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Format</label>
    <nameField>
        <label>Format Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Related_SFO__c.object
<CustomObject>
    <fields>
        <fullName>SFO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFO</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Special_Feature_Option__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Read Only</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipLabel>Related SFO</relationshipLabel>
        <relationshipName>Related_SFO1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Detail</label>
        <referenceTo>FPA_Link__c</referenceTo>
        <relationshipLabel>Related SFO</relationshipLabel>
        <relationshipName>Related_SFO</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Related SFO</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Related SFO  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related SFO</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Special_Feature_Option__c.object
<CustomObject>
    <fields>
        <fullName>Base_Unit_to_be_Modified__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Select formats by search/lookup as defined in the Format creation screen</inlineHelpText>
        <label>Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Records</relationshipLabel>
        <relationshipName>SFOs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                    <isActive>false</isActive>
                    <label>Obsolete</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                    <isActive>false</isActive>
                    <label>Submitted for Approval</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Records</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/FPARelatedAttachmentsDownloadTest.cls
@isTest
public class FPARelatedAttachmentsDownloadTest {
    
    @isTest static void FPARelatedAttchmentControllerTestMethod() 
    {
        Product2 Product2Obj=TestUtility.createProduct();
        insert product2Obj;
        
        Product__c productObj = TestUtility.createProductFormat();
        productObj.IsActive__c=true;
        insert productObj;
        
        FPA_Persona__c FPAPersonRepObj=TestUtility.createFPAPersona('Engineer','Operations');
        FPAPersonRepObj.User_Id__c='DKN1113';
        insert FPAPersonRepObj;
        
        Factory_Pricing_Authorization__c FPAObj=TestUtility.createFPA(FPAPersonRepObj.Id,productObj.Id);
        FPAObj.Name = 'Test FPA';
        FPAObj.Status__c='Approved';
        insert FPAObj;
        System.assertEquals('Test FPA',  FPAObj.Name);
        System.assertEquals('Approved',  FPAObj.Status__c);
        
        
        String data = 'test data for attacement';
        List<Attachment> ListAttachments = new List<Attachment>();
        for(Integer i=0; i<5; i++){
        Attachment att = new Attachment();
        att.Name = 'Test Name'+i;
        att.Body = EncodingUtil.base64Decode(data);
        att.ParentId = FPAObj.id;
        ListAttachments.add(att);
        } 
        insert ListAttachments;
        
        // Creating ContentDocumentLink
        
        ContentVersion contentVersion = new ContentVersion(
            Title = 'Penguins',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        insert contentVersion;    
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        
        //create ContentDocumentLink  record for the FPA 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = FPAObj.id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        insert cdl;
        
         System.assertEquals('V', cdl.shareType);
        System.assertEquals(FPAObj.id, ListAttachments[0].ParentId);
        
        FPA_Link__c fpaLink = new FPA_Link__c();
        fpalink.FPA__c = FPAObj.id;
        insert fpaLink;
        System.assertEquals(fpalink.FPA__c, FPAObj.id);
        
        /*Special_Feature_Option__c sfo = testUtility.createSFO(productObj.Id);
        sfo.Base_Unit_to_be_Modified__c=null;
        insert sfo;
        sfo.Base_Unit_to_be_Modified__c=productObj.Id;
        update sfo;
        

        
        Related_SFO__c relatedSfo = new Related_SFO__c();
        relatedSfo.SFO__c=sfo.id;
        relatedSfo.CurrencyIsoCode='USD - U.S. Dollar';
        relatedSfo.Unit_Detail__c=fpaLink.id;
        
        
        String data = 'test data for attacement';
        
        Attachment att = new Attachment();
        att.Name = 'Test Name';
        att.Body = EncodingUtil.base64Decode(data);
        att.ParentId = sfo.id;
        insert att;
        
        System.assertEquals('Test Name', att.Name);
        System.assertEquals(sfo.id, att.ParentId);*/
        
        pageReference pageRef=new pageReference('/apex/FPARelatedAttachmentsDownload?id='+FPAObj.Id);
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(FPAObj);
        FPARelatedAttachmentsDownloadController dController = new FPARelatedAttachmentsDownloadController(sc);
        dController.fpaID=FPAObj.id;
        FPARelatedAttachmentsDownloadController.getXMLFiles(FPAObj.ID);
        FPARelatedAttachmentsDownloadController.saveData(FPAObj.id, 'test file name', data);
        FPARelatedAttachmentsDownloadController.saveData(FPAObj.id, 'test file name', data);
        FPARelatedAttachmentsDownloadController.delData(ListAttachments[0].Id);
          
    }
}