src/objects/MA_Model__c.object
<CustomObject>
    <fields>
        <fullName>Equipment_Type_Labor__c</fullName>
        <label>Equipment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Absorption Chiller</fullName>
                </value>
                <value>
                    <fullName>Air Cooled Screw Chiller</fullName>
                </value>
                <value>
                    <fullName>Air Cooled Scroll Chiller</fullName>
                </value>
                <value>
                    <fullName>Air Handler</fullName>
                </value>
                <value>
                    <fullName>Balancing Valves</fullName>
                </value>
                <value>
                    <fullName>Boiler -  Condensing</fullName>
                </value>
                <value>
                    <fullName>Boiler - Steam</fullName>
                </value>
                <value>
                    <fullName>Boiler - Water</fullName>
                </value>
                <value>
                    <fullName>Breaching or venting System</fullName>
                </value>
                <value>
                    <fullName>Condensing Unit</fullName>
                </value>
                <value>
                    <fullName>Controls</fullName>
                </value>
                <value>
                    <fullName>Cooling Tower</fullName>
                </value>
                <value>
                    <fullName>Duct System</fullName>
                </value>
                <value>
                    <fullName>Energy Recovery Wheels</fullName>
                </value>
                <value>
                    <fullName>Evaporative Cooler</fullName>
                </value>
                <value>
                    <fullName>Fan</fullName>
                </value>
                <value>
                    <fullName>Fan Coil</fullName>
                </value>
                <value>
                    <fullName>Fan Coil Unit</fullName>
                </value>
                <value>
                    <fullName>Fluid Cooler</fullName>
                </value>
                <value>
                    <fullName>Heat Exchanger - Air</fullName>
                </value>
                <value>
                    <fullName>Heat Exchange - Plate &amp; Frame</fullName>
                </value>
                <value>
                    <fullName>Heat Exchange -Shell &amp; Tube</fullName>
                </value>
                <value>
                    <fullName>Isolation Valve</fullName>
                </value>
                <value>
                    <fullName>Piping System</fullName>
                </value>
                <value>
                    <fullName>Pneumatic Controls</fullName>
                </value>
                <value>
                    <fullName>Pump</fullName>
                </value>
                <value>
                    <fullName>Pump Strainer</fullName>
                </value>
                <value>
                    <fullName>Refrigerant Air Dryer</fullName>
                </value>
                <value>
                    <fullName>Refrigerant Monitor</fullName>
                </value>
                <value>
                    <fullName>Rooftop Unit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Equipment_Type__c</fullName>
        <label>Equipment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Absorption Chillers</fullName>
                </value>
                <value>
                    <fullName>AC Screw</fullName>
                </value>
                <value>
                    <fullName>Air Cleaners</fullName>
                </value>
                <value>
                    <fullName>Air Handlers &amp; Make-up Air Units</fullName>
                </value>
                <value>
                    <fullName>Airside Heat Recovery - Fixed Plate</fullName>
                </value>
                <value>
                    <fullName>Airside Heat Recovery Ventilator-Wheel</fullName>
                </value>
                <value>
                    <fullName>Back Flow Prevention</fullName>
                </value>
                <value>
                    <fullName>Blow Down Heat Recovery</fullName>
                </value>
                <value>
                    <fullName>Boilers - Electric Type</fullName>
                </value>
                <value>
                    <fullName>Boilers- Fossil Fuel Types</fullName>
                </value>
                <value>
                    <fullName>Centrifugal Chillers - Negative (low) Pressure</fullName>
                </value>
                <value>
                    <fullName>Centrifugal Chillers - Positive (high) Pressure</fullName>
                </value>
                <value>
                    <fullName>Computer Room Air Conditioning Units - (CRAC)</fullName>
                </value>
                <value>
                    <fullName>Cooling Towers</fullName>
                </value>
                <value>
                    <fullName>De-Humidifiers - Desiccant or Refrigerant Type</fullName>
                </value>
                <value>
                    <fullName>Domestic Water Heaters</fullName>
                </value>
                <value>
                    <fullName>Dry Coolers - Air cooled fluid cooler</fullName>
                </value>
                <value>
                    <fullName>Exhaust &amp; Return Fans</fullName>
                </value>
                <value>
                    <fullName>Fan Coil Units or Unit Ventilator</fullName>
                </value>
                <value>
                    <fullName>Flue Gas Heat Recovery (Stack economizer)</fullName>
                </value>
                <value>
                    <fullName>Furnaces</fullName>
                </value>
                <value>
                    <fullName>Heat Exchangers - Plate &amp; Frame / Shell &amp; Tube</fullName>
                </value>
                <value>
                    <fullName>Humidifier Units - Electric &amp; Steam</fullName>
                </value>
                <value>
                    <fullName>Magnetic Bearing Centrifugal Chillers</fullName>
                </value>
                <value>
                    <fullName>Pneumatic Air Compressor System</fullName>
                </value>
                <value>
                    <fullName>PTAC - Packaged Through the wall Air Conditioners</fullName>
                </value>
                <value>
                    <fullName>Reciprocating / Scroll Chillers - Air and Water Cooled</fullName>
                </value>
                <value>
                    <fullName>Refrigerant Monitor</fullName>
                </value>
                <value>
                    <fullName>Refrigerated Air Driers</fullName>
                </value>
                <value>
                    <fullName>Roof Top / Packaged or Split Systems (Unitary Equipment, Heating and cooling)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MA Model</label>
    <nameField>
        <displayFormat>MAM-{000000000}</displayFormat>
        <label>MA Model Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MA Models</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ModelWrapper.cls
public class ModelWrapper {
    final public String SERVICE_TECH = '*Service Technician S&R/TK';
    public Integer rowNumber {get; set;}
    private Apttus_Config2__LineItem__c lineItem;
    public Ma_Model__c modelObj {get; set;}

    public ModelWrapper(Ma_Model__c model, Apttus_Config2__LineItem__c line, Integer rowCount, Boolean isLabor) {
        lineItem = line;
        if(isLabor) {
            model.Equipment_Type_Labor__c = model.Equipment_Type__c;
        }
        if(model != null && model.Equipment_Type__c == SERVICE_TECH) {
            model.Equipment_Type_Labor__c = '--None--';
        }
        modelObj = model;
        rowNumber = rowCount;
    }
}