src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Vertical_Market__c</fullName>
        <description>Project Industry Types (versus account industry types).  If the Account is a Facilities Management Company the Vertical (Industry) for the opportunity could be different.</description>
        <inlineHelpText>Opportunity Industry type - may be different then Account</inlineHelpText>
        <label>Vertical Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Airports &amp; Transportation</fullName>
                </value>
                <value>
                    <fullName>Assembly, Arenas, and Recreation</fullName>
                </value>
                <value>
                    <fullName>Education K-12</fullName>
                </value>
                <value>
                    <fullName>Financial / Office Space</fullName>
                </value>
                <value>
                    <fullName>Government Buildings</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>Higher Education</fullName>
                </value>
                <value>
                    <fullName>Life Sciences, Pharm, Biotech</fullName>
                </value>
                <value>
                    <fullName>Lodging / Hotels</fullName>
                </value>
                <value>
                    <fullName>Manufacturing Facilities and Warehouses</fullName>
                </value>
                <value>
                    <fullName>Mining</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous Nonresidential Buildings</fullName>
                </value>
                <value>
                    <fullName>Multi-family Residential</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Religious Buildings</fullName>
                </value>
                <value>
                    <fullName>Stock Replenishment</fullName>
                </value>
                <value>
                    <fullName>Stores and Restaurants / Retail</fullName>
                </value>
                <value>
                    <fullName>Telecommunications and Data Centers</fullName>
                </value>
                <value>
                    <fullName>Warehouses (excl. Manufacturer Owned)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Won_Lost_Reason__c</fullName>
        <description>A value indicating the main reason a job was won or lost.</description>
        <inlineHelpText>A value indicating the main reason a job was won or lost.</inlineHelpText>
        <label>Won/Lost Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Credit Terms</fullName>
                </value>
                <value>
                    <fullName>Daikin Contractor on the job</fullName>
                </value>
                <value>
                    <fullName>Delivery Time</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Lumped Out - Controls</fullName>
                </value>
                <value>
                    <fullName>Lumped Out - Equipment</fullName>
                </value>
                <value>
                    <fullName>Nat&apos;l Account Relationship</fullName>
                </value>
                <value>
                    <fullName>Negotiated</fullName>
                </value>
                <value>
                    <fullName>No Callback</fullName>
                </value>
                <value>
                    <fullName>Non-Daikin Contractor on the job</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Preference for stick-site built</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Project was canceled</fullName>
                </value>
                <value>
                    <fullName>Specs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/testCreateAssetonClosedWon.cls
@isTest 

private class testCreateAssetonClosedWon {
    
    static testMethod void testCreateAssetonClosedWon(){
        
        //Account a = [select Id from Account limit 1];
        
        
        Account a = new Account();
        a.Name = 'Test Account';
        a.Type = 'Architect';
        a.Industry = 'Healthcare';
        
        insert a;  
        
        PricebookEntry pbID = [select Id from PricebookEntry where Pricebook2.Name='Standard Price Book' and IsActive = true limit 1];
        Opportunity o = new Opportunity();
        OpportunityLineItem ol = new OpportunityLineItem();
        
        o.AccountId = a.Id;
        o.Name = 'test';
        o.StageName = 'Develop Customer Solution/In Design';
        o.Won_Lost_Reason__c = 'win';
        o.CloseDate = date.today();
        o.Vertical_Market__c = 'Healthcare';
        insert o;
        
        ol.OpportunityId = o.Id;
        ol.Quantity = 1;
        ol.UnitPrice = 2.00;
        ol.PricebookEntryId = pbId.Id;
        
        insert ol;
        
        o.StageName= 'Closed Won';
        o.Won_Lost_Reason__c = 'Price';
        update o;
        
        delete ol;
        delete o;
        
        
        
    }
    
    
}