src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>Line of business</description>
        <inlineHelpText>Type of Service/Product</inlineHelpText>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>CTK - Complex Turnkey</fullName>
                    <label>Contracting</label>
                </value>
                <value>
                    <fullName>Equipment Only</fullName>
                </value>
                <value>
                    <fullName>MA - Maintenance Agreement</fullName>
                </value>
                <value>
                    <fullName>MA - Renewal</fullName>
                </value>
                <value>
                    <fullName>MCP</fullName>
                </value>
                <value>
                    <fullName>Parts Only</fullName>
                </value>
                <value>
                    <fullName>Rental Chillers</fullName>
                </value>
                <value>
                    <fullName>Retrofit/Upgrades</fullName>
                </value>
                <value>
                    <fullName>Retrofit/Upgrades/CAP</fullName>
                </value>
                <value>
                    <fullName>Service &amp; Repair - Quoted</fullName>
                </value>
                <value>
                    <fullName>Service &amp; Repair - T&amp;M</fullName>
                </value>
                <value>
                    <fullName>Start-Up</fullName>
                </value>
                <value>
                    <fullName>TK - Turnkey Contracting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prevailing_Wage__c</fullName>
        <description>Prevailing Wage job</description>
        <inlineHelpText>Is this a prevailing wage (PW)  job?</inlineHelpText>
        <label>Prevailing Wage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NO</fullName>
                </value>
                <value>
                    <fullName>YES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vertical_Market__c</fullName>
        <description>Project Industry Types (versus account industry types).  If the Account is a Facilities Management Company the Vertical (Industry) for the opportunity could be different.</description>
        <inlineHelpText>Opportunity Industry type - may be different then Account</inlineHelpText>
        <label>Vertical Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Airports &amp; Transportation</fullName>
                </value>
                <value>
                    <fullName>Assembly, Arenas, and Recreation</fullName>
                </value>
                <value>
                    <fullName>Education K-12</fullName>
                </value>
                <value>
                    <fullName>Financial / Office Space</fullName>
                </value>
                <value>
                    <fullName>Government Buildings</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>Higher Education</fullName>
                </value>
                <value>
                    <fullName>Life Sciences, Pharm, Biotech</fullName>
                </value>
                <value>
                    <fullName>Lodging / Hotels</fullName>
                </value>
                <value>
                    <fullName>Manufacturing Facilities and Warehouses</fullName>
                </value>
                <value>
                    <fullName>Mining</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous Nonresidential Buildings</fullName>
                </value>
                <value>
                    <fullName>Multi-family Residential</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Religious Buildings</fullName>
                </value>
                <value>
                    <fullName>Stock Replenishment</fullName>
                </value>
                <value>
                    <fullName>Stores and Restaurants / Retail</fullName>
                </value>
                <value>
                    <fullName>Telecommunications and Data Centers</fullName>
                </value>
                <value>
                    <fullName>Warehouses (excl. Manufacturer Owned)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Won_Lost_Reason__c</fullName>
        <description>A value indicating the main reason a job was won or lost.</description>
        <inlineHelpText>A value indicating the main reason a job was won or lost.</inlineHelpText>
        <label>Won/Lost Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Credit Terms</fullName>
                </value>
                <value>
                    <fullName>Daikin Contractor on the job</fullName>
                </value>
                <value>
                    <fullName>Delivery Time</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Lumped Out - Controls</fullName>
                </value>
                <value>
                    <fullName>Lumped Out - Equipment</fullName>
                </value>
                <value>
                    <fullName>Nat&apos;l Account Relationship</fullName>
                </value>
                <value>
                    <fullName>Negotiated</fullName>
                </value>
                <value>
                    <fullName>No Callback</fullName>
                </value>
                <value>
                    <fullName>Non-Daikin Contractor on the job</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Preference for stick-site built</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Project was canceled</fullName>
                </value>
                <value>
                    <fullName>Specs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AccountHierarchyTestClass.cls
@isTest
public class AccountHierarchyTestClass {
    @testSetup public static void dataSetUp()
    {
        AVA_SFCORE__TaxNowSetting__c ts1 = new AVA_SFCORE__TaxNowSetting__c(); 
       ts1.AVA_SFCORE__Active_Setting__c = true; 
       ts1.Name='Test Account';
       insert ts1;
        Account accountRecord = new Account();
        accountRecord.Name ='Parent Account';
        accountRecord.type = 'Developer';
        insert accountRecord;
        
        Account childAccount = new Account();
        childAccount.Name='Child Account 1';
        childAccount.Type='Developer';
        childAccount.ParentId = accountRecord.Id;
        insert childAccount;
        
        Opportunity opportunityRecord = new Opportunity();
        opportunityRecord.Name = 'Parent Opportunity';
        opportunityRecord.StageName = 'Closed Won';
        opportunityRecord.Won_Lost_Reason__c='Credit Terms';
        opportunityRecord.AccountId = accountRecord.Id;
        opportunityRecord.Amount = 10000;
        opportunityRecord.CloseDate = system.today();
        opportunityRecord.Line_of_Business__c = 'MCP';
        opportunityRecord.Vertical_Market__c = 'Healthcare';
        opportunityRecord.Prevailing_Wage__c = 'No';
		insert opportunityRecord;  
        
        Opportunity childOpportunity = new Opportunity();
        childOpportunity.Name = 'Parent Opportunity';
        childOpportunity.StageName = 'Closed Won';
        childOpportunity.Won_Lost_Reason__c='Credit Terms';
        childOpportunity.AccountId = accountRecord.Id;
        childOpportunity.Amount = 10000;
        childOpportunity.CloseDate = system.today();
        childOpportunity.Line_of_Business__c = 'MCP';
        childOpportunity.Vertical_Market__c = 'Healthcare';
        childOpportunity.Prevailing_Wage__c = 'No';
		insert childOpportunity;  
        
         Opportunity childOpportunity2 = new Opportunity();
        childOpportunity2.Name = 'Parent Opportunity';
        childOpportunity2.StageName = 'Closed Won';
        childOpportunity2.Won_Lost_Reason__c='Credit Terms';
        childOpportunity2.AccountId = accountRecord.Id;
        childOpportunity2.Amount = 10000;
        childOpportunity2.CloseDate = system.today();
        childOpportunity2.Line_of_Business__c = 'MCP';
        childOpportunity2.Vertical_Market__c = 'Healthcare';
        childOpportunity2.Prevailing_Wage__c = 'No';
		insert childOpportunity2; 
    }
    
    public static testmethod void NationalAccountsHierarchy()
    {
        Account accountRec = [select id,name from Account where Name = 'Parent Account'];
        Apexpages.StandardController sc = new Apexpages.StandardController(accountRec);
        AccountHierarchy hierarchy = new AccountHierarchy(sc);
        hierarchy.getOpportunityList();
    }

}