src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Bid_Date__c</fullName>
        <description>Date of the Bid</description>
        <inlineHelpText>Date of the Bid</inlineHelpText>
        <label>Bid Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DM_District_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be populated by Cups DM &amp;ROSM Workflow rule and is used in Cups email notification.</description>
        <inlineHelpText>Opportunity Owner DM (District Manager)</inlineHelpText>
        <label>DM (District Manager)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DMOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>Line of business</description>
        <inlineHelpText>Type of Service/Product</inlineHelpText>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>CTK - Complex Turnkey</fullName>
                    <label>Contracting</label>
                </value>
                <value>
                    <fullName>Equipment Only</fullName>
                </value>
                <value>
                    <fullName>MA - Maintenance Agreement</fullName>
                </value>
                <value>
                    <fullName>MA - Renewal</fullName>
                </value>
                <value>
                    <fullName>MCP</fullName>
                </value>
                <value>
                    <fullName>Parts Only</fullName>
                </value>
                <value>
                    <fullName>Rental Chillers</fullName>
                </value>
                <value>
                    <fullName>Retrofit/Upgrades</fullName>
                </value>
                <value>
                    <fullName>Retrofit/Upgrades/CAP</fullName>
                </value>
                <value>
                    <fullName>Service &amp; Repair - Quoted</fullName>
                </value>
                <value>
                    <fullName>Service &amp; Repair - T&amp;M</fullName>
                </value>
                <value>
                    <fullName>Start-Up</fullName>
                </value>
                <value>
                    <fullName>TK - Turnkey Contracting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Local_Currency__c</fullName>
        <description>Indicate&apos;s the opportunity&apos;s local currency for Latin America.</description>
        <label>Local Currency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>CLP</fullName>
                </value>
                <value>
                    <fullName>COP</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>MXN</fullName>
                </value>
                <value>
                    <fullName>UF</fullName>
                </value>
                <value>
                    <fullName>USD</fullName>
                    <default>true</default>
                    <label>USD</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ROSM_Regional_Owner_Sales_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be populated by Cups DM &amp;ROSM Workflow rule and is used in Cups email notification.</description>
        <inlineHelpText>This field will be populated by Cups DM &amp;ROSM Workflow rule and is used in Cups email notification.</inlineHelpText>
        <label>ROSM (Regional Owner Sales Manager)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ROSMOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>DM_District_Manager__c</fullName>
        <label>DM (District Manager)</label>
        <relationshipName>DM_District_Manager</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>Legal_Approver__c</fullName>
        <description>Used to determine the Legal Approver for Service Quote/Proposals.</description>
        <label>Legal Approver</label>
        <relationshipName>Service_Region</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>RGM_Regional_General_Manager__c</fullName>
        <label>RGM (Regional General Manager)</label>
        <relationshipName>RGM_Regional_General_Manager</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>ROSM_Regional_Owner_Sales_Manager__c</fullName>
        <label>ROSM (Regional Owner Sales Manager)</label>
        <relationshipName>ROSM_Regional_Owner_Sales_Manager</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>RSM_Regional_Service_Manager__c</fullName>
        <label>RSM (Regional Service Manager)</label>
        <relationshipName>RSM_Regional_Service_Manager</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CreateNewServiceProposalController.cls
public with sharing class CreateNewServiceProposalController {
    public Apttus_Proposal__Proposal__c Proposal{get; set;}
    
    public User currentUser{get; set;}
    public String oppId{get; set;}
    public String oppId2{get;set;}
    
    public CreateNewServiceProposalController(ApexPages.StandardController controller) {
        this.Proposal = (Apttus_Proposal__Proposal__c)controller.getRecord();
        
        oppId = ApexPages.currentPage().getParameters().get('retURL');
        //oppId = this.Proposal.Apttus_Proposal__Opportunity__c;
        oppId2 = oppId.replace('/', '');

        system.debug('This is the OppId2:' + oppId2);
        currentUser = new User();
        currentUser = [SELECT Id, Name, Country, Legal_Approver__c, RGM_Regional_General_Manager__c, ROSM_Regional_Owner_Sales_Manager__c, RSM_Regional_Service_Manager__c, DM_District_Manager__c FROM User WHERE Id =: userinfo.getuserId()];
        
        if(currentUser.country == 'United States'){
            Proposal.T_C_Country__c  = 'USA';
            Proposal.Local_Currency__c  = 'USD';
        } else if(currentUser.country == 'Canada') {
            Proposal.T_C_Country__c  = 'Canada - English';
            Proposal.Local_Currency__c  = 'CAD';
        }
        
        Opportunity Opp = [SELECT Id, Name, AccountId, CloseDate, Line_of_Business__c, Bid_Date__c  FROM Opportunity WHERE Id = :oppId2];
        if(opp !=NULL) {
            Proposal.Apttus_Proposal__Proposal_Name__c = opp.Name;
            Proposal.Apttus_Proposal__Account__c = opp.AccountId;
            Proposal.Line_of_Business__c = opp.Line_of_Business__c;
            Proposal.Estimated_Close_Date__c = opp.CloseDate;
            Proposal.Opportunity_Bid_Date__c = opp.Bid_Date__c;
        }
        
    }
       

}