src/objects/Related_SFO__c.object
<CustomObject>
    <fields>
        <fullName>SFO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFO</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Special_Feature_Option__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Read Only</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipLabel>Related SFO</relationshipLabel>
        <relationshipName>Related_SFO1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Detail</label>
        <referenceTo>FPA_Link__c</referenceTo>
        <relationshipLabel>Related SFO</relationshipLabel>
        <relationshipName>Related_SFO</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Related SFO</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Related SFO  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related SFO</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Special_Feature_Option__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                    <isActive>false</isActive>
                    <label>Obsolete</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                    <isActive>false</isActive>
                    <label>Submitted for Approval</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Records</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Records</pluralLabel>
    <recordTypes>
        <fullName>Option</fullName>
        <active>true</active>
        <description>Holds Options Records</description>
        <label>Level 5-Option</label>
    </recordTypes>
    <recordTypes>
        <fullName>Read_Only</fullName>
        <active>true</active>
        <description>Holds Locked Records</description>
        <label>Read Only</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/removeDraftRejectedSFO.cls
public class removeDraftRejectedSFO {
    public static void removesfo(map<Id, Special_Feature_Option__c> oldmap, map<Id, Special_Feature_Option__c> newmap){
        list<Special_Feature_Option__c> SFOList = new list<Special_Feature_Option__c>();
        set<Id> sfoids = new set<Id>();
        RecordType readonlyrectype =  [select id, developerName, SObjectType from RecordType where developerName = 'Read_Only' and SObjectType='Special_Feature_Option__c'];
        RecordType optionrectype =  [select id, developerName, SObjectType from RecordType where developerName = 'Option' and SObjectType='Special_Feature_Option__c'];
        for(Id i : oldmap.keyset()){
            if(oldmap.get(i).RecordTypeId == readonlyrectype.Id && oldmap.get(i).Status__c == 'Approved' && 
               (newmap.get(i).Status__c == 'Draft' || newmap.get(i).Status__c == 'Rejected')){
                   Special_Feature_Option__c sfo = newmap.get(i);
                   //sfo.RecordTypeId = optionrectype.Id;
                   SFOList.add(sfo);
                   sfoids.add(i);
               }
        }
        list<Related_SFO__c> relatedSFOList = new list<Related_SFO__c>();
        for(Related_SFO__c r_sfo :[Select Id, Name, SFO__c from Related_SFO__c where SFO__c In :sfoids]){
            system.debug('name:'+r_sfo.Name);
            r_sfo.SFO__c = NULL;
            r_sfo.Unit_Detail__c = NULL;
            relatedSFOList.add(r_sfo);
        }
        database.delete(relatedSFOList);
        //update relatedSFOList;
    }
}