src/objects/SFO_Fields__c.object
<CustomObject>
    <fields>
        <fullName>Field_Data_Type__c</fullName>
        <label>Field Data Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>Formula</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                    <isActive>false</isActive>
                    <label>Checkbox</label>
                </value>
                <value>
                    <fullName>Date</fullName>
                    <isActive>false</isActive>
                    <label>Date</label>
                </value>
                <value>
                    <fullName>Date/Time</fullName>
                    <isActive>false</isActive>
                    <label>Date/Time</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field_Length__c</fullName>
        <inlineHelpText>Enter the maximum length for a text field</inlineHelpText>
        <label>Field Length</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Formula_Editor__c</fullName>
        <inlineHelpText>Shows the formula that is defined by the user while creating a dynamic field. Accepts simple formula i.e. single parentheses and Order of calculation followed is BOD MAS</inlineHelpText>
        <label>Formula Editor</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Only Active Dynamic fields will be available for selection at Special Feature level (Level 4)</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Picklist_Entries__c</fullName>
        <inlineHelpText>Allow users to select a value from a predefined list</inlineHelpText>
        <label>Picklist Entries</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Always require a value in this field in order to save a record</inlineHelpText>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <label>Dynamic Field</label>
    <nameField>
        <label>Field Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dynamic Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Special_Feature_Option__c.object
<CustomObject>
    <label>Records</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SFO_DynamicFields_Selection_Test.cls
@isTest
public class SFO_DynamicFields_Selection_Test {
    @isTest static void SFO_DynamicFields_Selection_Method () {
        List<SFO_Fields__c> selectedFeldsList = new List<SFO_Fields__c>();
        for(Integer i=0;i<5;i++){
        SFO_Fields__c Sfo = new SFO_Fields__c();
        Sfo.IsActive__c =true;
        Sfo.Field_Data_Type__c = 'Text';
        Sfo.Field_Length__c = 10;
        Sfo.Formula_Editor__c ='Abcd';
        Sfo.Picklist_Entries__c = 'Efgh';
        Sfo.Required__c = true;
           
            selectedFeldsList.add(Sfo);
        }
        Insert selectedFeldsList;
        
        
        Test.startTest();
        Special_Feature_Option__c Spfo = new Special_Feature_Option__c();
        SFO_DynamicFields_Selection sfc = new SFO_DynamicFields_Selection(new ApexPages.StandardController(Spfo));
        sfc.getDynamicFields();
        sfc.gotoNext();
        sfc.gotoPrevious();
        sfc.saveFields();
        sfc.Beginning();
        sfc.Previous();
        sfc.Next();
        sfc.End();
        sfc.getDisablePrevious();
        sfc.getDisableNext();
        sfc.closePopup();
        Sfc.saveSFOField();
        sfc.showPopup();
        
       /* List<Special_Feature_Option__c> SFOList = new List<Special_Feature_Option__c>();
        SFOList.add(Spfo);
        SFO_Trigger_Handler str = new SFO_Trigger_Handler();
        SFO_Trigger_Handler.Insert_ChildRec_for_SFOs(SFOList);*/
        Test.stopTest();
    }
    
}