src/objects/Special_Feature_Option__c.object
<CustomObject>
    <fields>
        <fullName>Option_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Special Feature</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Special_Feature_Option__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Level 4-Special Feature</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Special_Feature_Option__c</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>SFOs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Cost1__c</fullName>
        <label>Total Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Cost_value__c</fullName>
        <label>Option Total Cost</label>
        <summarizedField>SFO_Dynamic_Fields__c.Field_Value_Number__c</summarizedField>
        <summaryFilterItems>
            <field>SFO_Dynamic_Fields__c.Is_Rollup_Field__c</field>
            <operation>equals</operation>
            <value>TRUE</value>
        </summaryFilterItems>
        <summaryForeignKey>SFO_Dynamic_Fields__c.SFO__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Records</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Records</pluralLabel>
    <recordTypes>
        <fullName>Option</fullName>
        <active>true</active>
        <description>Holds Options Records</description>
        <label>Level 5-Option</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SFODynamicRollup.cls
public class SFODynamicRollup {
    public static boolean hasRollUp = true;
    public static void summarizeTotalCost(list<Special_Feature_Option__c> options){
        set<String> parentIds = new set<String>();
        for(Special_Feature_Option__c option :options){
        	parentIds.add(option.Option_Parent__c);    
        }
        List<Special_Feature_Option__c> parentSFOs = new  List<Special_Feature_Option__c>(
        [select id,Total_Cost1__c from Special_Feature_Option__c where id IN : parentIds]);
        Map<String, decimal> sfoParentToOptions 
            = new Map<String, decimal>();
        for(Special_Feature_Option__c optionRec : [SELECT Id, Total_Cost_value__c,Option_Parent__c FROM Special_Feature_Option__c
                                                  WHERE Option_Parent__c IN :parentIds]){
            decimal totalCost = (optionRec.Total_Cost_value__c == null)?0:optionRec.Total_Cost_value__c;
            if(sfoParentToOptions.containsKey(optionRec.Option_Parent__c)){
                decimal totCost = sfoParentToOptions.get(optionRec.Option_Parent__c)+totalCost;
                sfoParentToOptions.put(optionRec.Option_Parent__c, totCost);  
            }else{
                sfoParentToOptions.put(optionRec.Option_Parent__c, totalCost);   
            }          
        }
        for(Special_Feature_Option__c parentSFO :parentSFOs){
            
            if(sfoParentToOptions.containsKey(parentSFO.Id)){ parentSFO.Total_Cost1__c =  sfoParentToOptions.get(parentSFO.Id);
            }
        }
        
        if(parentSFOs.size() > 0){
            hasRollUp = false; update parentSFOs;    
        }
    }
}